// lib/cad/codes/code-library.ts
import type { PointCodeDefinition } from '../types';

export const MASTER_CODE_LIBRARY: PointCodeDefinition[] = [
  // ─── BOUNDARY CONTROL ───────────────────────────────────────────────────────

  // 3/8" Iron Rod
  {
    alphaCode: 'BC01', numericCode: '308', description: '3/8" Iron Rod Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_038_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '3/8" IRF',
    simplifiedCode: '308', simplifiedDescription: '3/8" Iron Rod Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: '3/8"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC33', numericCode: '315', description: '3/8" Iron Rod Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_038_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '3/8" IRS',
    simplifiedCode: '308', simplifiedDescription: '3/8" Iron Rod Found', collapses: true,
    monumentAction: 'SET', monumentSize: '3/8"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC09', numericCode: '327', description: '3/8" Iron Rod Calculated',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_038_CALC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '3/8" IRC',
    simplifiedCode: '308', simplifiedDescription: '3/8" Iron Rod Found', collapses: true,
    monumentAction: 'CALCULATED', monumentSize: '3/8"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // 1/2" Iron Rod
  {
    alphaCode: 'BC02', numericCode: '309', description: '1/2" Iron Rod Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_050_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '1/2" IRF',
    simplifiedCode: '309', simplifiedDescription: '1/2" Iron Rod Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: '1/2"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC06', numericCode: '317', description: '1/2" Iron Rod Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_050_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '1/2" IRS',
    simplifiedCode: '309', simplifiedDescription: '1/2" Iron Rod Found', collapses: true,
    monumentAction: 'SET', monumentSize: '1/2"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC10', numericCode: '328', description: '1/2" Iron Rod Calculated',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_050_CALC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '1/2" IRC',
    simplifiedCode: '309', simplifiedDescription: '1/2" Iron Rod Found', collapses: true,
    monumentAction: 'CALCULATED', monumentSize: '1/2"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // 5/8" Iron Rod
  {
    alphaCode: 'BC03', numericCode: '310', description: '5/8" Iron Rod Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_058_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '5/8" IRF',
    simplifiedCode: '310', simplifiedDescription: '5/8" Iron Rod Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: '5/8"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC07', numericCode: '318', description: '5/8" Iron Rod Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_058_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '5/8" IRS',
    simplifiedCode: '310', simplifiedDescription: '5/8" Iron Rod Found', collapses: true,
    monumentAction: 'SET', monumentSize: '5/8"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC11', numericCode: '329', description: '5/8" Iron Rod Calculated',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_058_CALC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '5/8" IRC',
    simplifiedCode: '310', simplifiedDescription: '5/8" Iron Rod Found', collapses: true,
    monumentAction: 'CALCULATED', monumentSize: '5/8"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // 3/4" Iron Rod
  {
    alphaCode: 'BC04', numericCode: '311', description: '3/4" Iron Rod Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_075_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '3/4" IRF',
    simplifiedCode: '311', simplifiedDescription: '3/4" Iron Rod Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: '3/4"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC08', numericCode: '319', description: '3/4" Iron Rod Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_075_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '3/4" IRS',
    simplifiedCode: '311', simplifiedDescription: '3/4" Iron Rod Found', collapses: true,
    monumentAction: 'SET', monumentSize: '3/4"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC12', numericCode: '330', description: '3/4" Iron Rod Calculated',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IR_075_CALC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '3/4" IRC',
    simplifiedCode: '311', simplifiedDescription: '3/4" Iron Rod Found', collapses: true,
    monumentAction: 'CALCULATED', monumentSize: '3/4"', monumentType: 'Iron Rod',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // Iron Pipe
  {
    alphaCode: 'BC13', numericCode: '312', description: 'Iron Pipe Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Pipe',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IP_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'IPF',
    simplifiedCode: '312', simplifiedDescription: 'Iron Pipe Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: null, monumentType: 'Iron Pipe',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC14', numericCode: '331', description: 'Iron Pipe Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Pipe',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IP_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'IPS',
    simplifiedCode: '312', simplifiedDescription: 'Iron Pipe Found', collapses: true,
    monumentAction: 'SET', monumentSize: null, monumentType: 'Iron Pipe',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC15', numericCode: '332', description: 'Iron Pipe Calculated',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Pipe',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IP_CALC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'IPC',
    simplifiedCode: '312', simplifiedDescription: 'Iron Pipe Found', collapses: true,
    monumentAction: 'CALCULATED', monumentSize: null, monumentType: 'Iron Pipe',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // Concrete Monument
  {
    alphaCode: 'BC16', numericCode: '313', description: 'Concrete Monument Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Concrete Monument',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_CONC_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'CMF',
    simplifiedCode: '313', simplifiedDescription: 'Concrete Monument Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: null, monumentType: 'Concrete Monument',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC17', numericCode: '333', description: 'Concrete Monument Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Concrete Monument',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_CONC_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'CMS',
    simplifiedCode: '313', simplifiedDescription: 'Concrete Monument Found', collapses: true,
    monumentAction: 'SET', monumentSize: null, monumentType: 'Concrete Monument',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC18', numericCode: '334', description: 'Concrete Monument Calculated',
    category: 'BOUNDARY_CONTROL', subcategory: 'Concrete Monument',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_CONC_CALC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'CMC',
    simplifiedCode: '313', simplifiedDescription: 'Concrete Monument Found', collapses: true,
    monumentAction: 'CALCULATED', monumentSize: null, monumentType: 'Concrete Monument',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // Cap/Disk
  {
    alphaCode: 'BC19', numericCode: '314', description: 'Cap/Disk Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Cap/Disk',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_CAP_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'CDF',
    simplifiedCode: '314', simplifiedDescription: 'Cap/Disk Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: null, monumentType: 'Cap/Disk',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC20', numericCode: '335', description: 'Cap/Disk Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Cap/Disk',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_CAP_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'CDS',
    simplifiedCode: '314', simplifiedDescription: 'Cap/Disk Found', collapses: true,
    monumentAction: 'SET', monumentSize: null, monumentType: 'Cap/Disk',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC21', numericCode: '336', description: 'Cap/Disk Calculated',
    category: 'BOUNDARY_CONTROL', subcategory: 'Cap/Disk',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_CAP_CALC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'CDC',
    simplifiedCode: '314', simplifiedDescription: 'Cap/Disk Found', collapses: true,
    monumentAction: 'CALCULATED', monumentSize: null, monumentType: 'Cap/Disk',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // PK Nail
  {
    alphaCode: 'BC22', numericCode: '338', description: 'PK Nail Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Nail',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_PKNAIL_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'PKNF',
    simplifiedCode: '338', simplifiedDescription: 'PK Nail Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: null, monumentType: 'PK Nail',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC23', numericCode: '339', description: 'PK Nail Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Nail',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_PKNAIL_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'PKNS',
    simplifiedCode: '338', simplifiedDescription: 'PK Nail Found', collapses: true,
    monumentAction: 'SET', monumentSize: null, monumentType: 'PK Nail',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // Mag Nail
  {
    alphaCode: 'BC24', numericCode: '340', description: 'Mag Nail Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Nail',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_MAGNAIL_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'MGNF',
    simplifiedCode: '340', simplifiedDescription: 'Mag Nail Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: null, monumentType: 'Mag Nail',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC25', numericCode: '345', description: 'Mag Nail Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Nail',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_MAGNAIL_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'MGNS',
    simplifiedCode: '340', simplifiedDescription: 'Mag Nail Found', collapses: true,
    monumentAction: 'SET', monumentSize: null, monumentType: 'Mag Nail',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // Railroad Spike / Witness Post
  {
    alphaCode: 'BC26', numericCode: '341', description: 'Railroad Spike Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Spike',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_RRSPIKE_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'RRSF',
    simplifiedCode: '341', simplifiedDescription: 'Railroad Spike Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: null, monumentType: 'Railroad Spike',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC27', numericCode: '342', description: 'Witness Post Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Witness Post',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_WPOST_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: 'WPF',
    simplifiedCode: '342', simplifiedDescription: 'Witness Post Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: null, monumentType: 'Witness Post',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // 1/2" Iron Rod w/ Cap
  {
    alphaCode: 'BC05', numericCode: '316', description: '1/2" Iron Rod w/ Cap Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod w/ Cap',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IRC_050_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '1/2" IRCF',
    simplifiedCode: '316', simplifiedDescription: '1/2" Iron Rod w/ Cap Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: '1/2"', monumentType: 'Iron Rod w/ Cap',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC28', numericCode: '343', description: '1/2" Iron Rod w/ Cap Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod w/ Cap',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IRC_050_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '1/2" IRCS',
    simplifiedCode: '316', simplifiedDescription: '1/2" Iron Rod w/ Cap Found', collapses: true,
    monumentAction: 'SET', monumentSize: '1/2"', monumentType: 'Iron Rod w/ Cap',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC29', numericCode: '344', description: '1/2" Iron Rod w/ Cap Calculated',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod w/ Cap',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IRC_050_CALC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '1/2" IRCC',
    simplifiedCode: '316', simplifiedDescription: '1/2" Iron Rod w/ Cap Found', collapses: true,
    monumentAction: 'CALCULATED', monumentSize: '1/2"', monumentType: 'Iron Rod w/ Cap',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // 5/8" Iron Rod w/ Cap
  {
    alphaCode: 'BC30', numericCode: '320', description: '5/8" Iron Rod w/ Cap Found',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod w/ Cap',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IRC_058_FOUND', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '5/8" IRCF',
    simplifiedCode: '320', simplifiedDescription: '5/8" Iron Rod w/ Cap Found', collapses: false,
    monumentAction: 'FOUND', monumentSize: '5/8"', monumentType: 'Iron Rod w/ Cap',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC31', numericCode: '346', description: '5/8" Iron Rod w/ Cap Set',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod w/ Cap',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IRC_058_SET', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '5/8" IRCS',
    simplifiedCode: '320', simplifiedDescription: '5/8" Iron Rod w/ Cap Found', collapses: true,
    monumentAction: 'SET', monumentSize: '5/8"', monumentType: 'Iron Rod w/ Cap',
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'BC32', numericCode: '347', description: '5/8" Iron Rod w/ Cap Calculated',
    category: 'BOUNDARY_CONTROL', subcategory: 'Iron Rod w/ Cap',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'MON_IRC_058_CALC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'BOUNDARY-MON', defaultLabelFormat: '5/8" IRCC',
    simplifiedCode: '320', simplifiedDescription: '5/8" Iron Rod w/ Cap Found', collapses: true,
    monumentAction: 'CALCULATED', monumentSize: '5/8"', monumentType: 'Iron Rod w/ Cap',
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── SURVEY CONTROL ─────────────────────────────────────────────────────────

  {
    alphaCode: 'SC01', numericCode: '301', description: 'Control Point',
    category: 'SURVEY_CONTROL', subcategory: 'Control',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_CTRL_PT', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'SURVEY-CTRL', defaultLabelFormat: 'CP',
    simplifiedCode: '301', simplifiedDescription: 'Control Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'SC02', numericCode: '302', description: 'Benchmark',
    category: 'SURVEY_CONTROL', subcategory: 'Control',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_BENCHMARK', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'SURVEY-CTRL', defaultLabelFormat: 'BM',
    simplifiedCode: '302', simplifiedDescription: 'Benchmark', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'SC03', numericCode: '303', description: 'GPS Control',
    category: 'SURVEY_CONTROL', subcategory: 'Control',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_GPS_CTRL', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'SURVEY-CTRL', defaultLabelFormat: 'GPS',
    simplifiedCode: '303', simplifiedDescription: 'GPS Control', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'SC04', numericCode: '304', description: 'Traverse Point',
    category: 'SURVEY_CONTROL', subcategory: 'Control',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_TRAV_PT', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'SURVEY-CTRL', defaultLabelFormat: 'TP',
    simplifiedCode: '304', simplifiedDescription: 'Traverse Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'SC05', numericCode: '305', description: 'Setup Point',
    category: 'SURVEY_CONTROL', subcategory: 'Control',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_SETUP_PT', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'SURVEY-CTRL', defaultLabelFormat: 'STP',
    simplifiedCode: '305', simplifiedDescription: 'Setup Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'SC06', numericCode: '306', description: 'Backsight Point',
    category: 'SURVEY_CONTROL', subcategory: 'Control',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_BS_PT', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'SURVEY-CTRL', defaultLabelFormat: 'BSP',
    simplifiedCode: '306', simplifiedDescription: 'Backsight Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── PROPERTY LINES ──────────────────────────────────────────────────────────

  {
    alphaCode: 'PL01', numericCode: '501', description: 'Boundary Line',
    category: 'PROPERTY_LINES', subcategory: 'Boundary',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_BOUNDARY', defaultColor: '#FF0000',
    defaultLineWeight: 2, defaultLayerId: 'BOUNDARY-LINE', defaultLabelFormat: 'BDYL',
    simplifiedCode: '501', simplifiedDescription: 'Boundary Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'PL02', numericCode: '502', description: 'Easement Line',
    category: 'PROPERTY_LINES', subcategory: 'Easement',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_EASEMENT', defaultColor: '#FF8000',
    defaultLineWeight: 1, defaultLayerId: 'EASEMENT', defaultLabelFormat: 'ESE',
    simplifiedCode: '502', simplifiedDescription: 'Easement Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'PL03', numericCode: '503', description: 'Building Line (BSL)',
    category: 'PROPERTY_LINES', subcategory: 'Building Line',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_BLDG_LINE', defaultColor: '#FFAA00',
    defaultLineWeight: 1, defaultLayerId: 'BLDG-LINE', defaultLabelFormat: 'BSL',
    simplifiedCode: '503', simplifiedDescription: 'Building Line (BSL)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'PL04', numericCode: '504', description: 'ROW Line',
    category: 'PROPERTY_LINES', subcategory: 'ROW',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_ROW', defaultColor: '#FF00FF',
    defaultLineWeight: 1, defaultLayerId: 'ROW', defaultLabelFormat: 'ROW',
    simplifiedCode: '504', simplifiedDescription: 'ROW Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'PL05', numericCode: '505', description: 'Flood Zone Line',
    category: 'PROPERTY_LINES', subcategory: 'Flood',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_FLOOD', defaultColor: '#0000FF',
    defaultLineWeight: 1, defaultLayerId: 'FLOOD', defaultLabelFormat: 'FLD',
    simplifiedCode: '505', simplifiedDescription: 'Flood Zone Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'PL06', numericCode: '506', description: 'City Limit Line',
    category: 'PROPERTY_LINES', subcategory: 'Jurisdiction',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_MISC', defaultColor: '#800080',
    defaultLineWeight: 1, defaultLayerId: 'MISC', defaultLabelFormat: 'CITY',
    simplifiedCode: '506', simplifiedDescription: 'City Limit Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'PL07', numericCode: '507', description: 'County Line',
    category: 'PROPERTY_LINES', subcategory: 'Jurisdiction',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_MISC', defaultColor: '#800080',
    defaultLineWeight: 1, defaultLayerId: 'MISC', defaultLabelFormat: 'CTY',
    simplifiedCode: '507', simplifiedDescription: 'County Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'PL08', numericCode: '508', description: 'Contour (natural boundary)',
    category: 'PROPERTY_LINES', subcategory: 'Natural',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_TOPO', defaultColor: '#006400',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'CONT',
    simplifiedCode: '508', simplifiedDescription: 'Contour (natural boundary)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'PL09', numericCode: '509', description: 'Shoreline',
    category: 'PROPERTY_LINES', subcategory: 'Natural',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_TOPO', defaultColor: '#0000FF',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'SHORE',
    simplifiedCode: '509', simplifiedDescription: 'Shoreline', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── STRUCTURES ──────────────────────────────────────────────────────────────

  {
    alphaCode: 'ST01', numericCode: '601', description: 'Building Corner',
    category: 'STRUCTURES', subcategory: 'Building',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_BLDG_CORNER', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'BC',
    simplifiedCode: '601', simplifiedDescription: 'Building Corner', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST02', numericCode: '602', description: 'Building Line',
    category: 'STRUCTURES', subcategory: 'Building',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#000000',
    defaultLineWeight: 1, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'BL',
    simplifiedCode: '602', simplifiedDescription: 'Building Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST03', numericCode: '603', description: 'Garage',
    category: 'STRUCTURES', subcategory: 'Building',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_GARAGE', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'GAR',
    simplifiedCode: '603', simplifiedDescription: 'Garage', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST04', numericCode: '604', description: 'Carport',
    category: 'STRUCTURES', subcategory: 'Building',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_CARPORT', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'CPT',
    simplifiedCode: '604', simplifiedDescription: 'Carport', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST05', numericCode: '605', description: 'Driveway',
    category: 'STRUCTURES', subcategory: 'Pavement',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'DW',
    simplifiedCode: '605', simplifiedDescription: 'Driveway', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST06', numericCode: '606', description: 'Patio/Deck',
    category: 'STRUCTURES', subcategory: 'Pavement',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'PAT',
    simplifiedCode: '606', simplifiedDescription: 'Patio/Deck', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST07', numericCode: '607', description: 'Pool',
    category: 'STRUCTURES', subcategory: 'Pool',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#0000FF',
    defaultLineWeight: 1, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'POOL',
    simplifiedCode: '607', simplifiedDescription: 'Pool', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST08', numericCode: '608', description: 'Fence Corner (struct)',
    category: 'STRUCTURES', subcategory: 'Fence',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_FENCE_CORNER', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'FC',
    simplifiedCode: '608', simplifiedDescription: 'Fence Corner (struct)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST09', numericCode: '609', description: 'Wall',
    category: 'STRUCTURES', subcategory: 'Wall',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#000000',
    defaultLineWeight: 1, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'WL',
    simplifiedCode: '609', simplifiedDescription: 'Wall', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST10', numericCode: '610', description: 'Retaining Wall',
    category: 'STRUCTURES', subcategory: 'Wall',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#000000',
    defaultLineWeight: 1, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'RW',
    simplifiedCode: '610', simplifiedDescription: 'Retaining Wall', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST11', numericCode: '611', description: 'Steps',
    category: 'STRUCTURES', subcategory: 'Steps',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#000000',
    defaultLineWeight: 1, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'STP',
    simplifiedCode: '611', simplifiedDescription: 'Steps', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'ST12', numericCode: '612', description: 'Shed',
    category: 'STRUCTURES', subcategory: 'Building',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_SHED', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'STRUCTURES', defaultLabelFormat: 'SHD',
    simplifiedCode: '612', simplifiedDescription: 'Shed', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── FENCES ──────────────────────────────────────────────────────────────────

  {
    alphaCode: 'FN01', numericCode: '741', description: 'Barbed Wire Fence',
    category: 'FENCES', subcategory: 'Wire Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_BARBED_WIRE', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'BWF',
    simplifiedCode: '741', simplifiedDescription: 'Barbed Wire Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN02', numericCode: '742', description: 'Wood Privacy Fence',
    category: 'FENCES', subcategory: 'Wood Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_WOOD_FENCE', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'WPF',
    simplifiedCode: '742', simplifiedDescription: 'Wood Privacy Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN03', numericCode: '743', description: 'Chain Link Fence',
    category: 'FENCES', subcategory: 'Chain Link',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_CHAIN_LINK', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'CLF',
    simplifiedCode: '743', simplifiedDescription: 'Chain Link Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN04', numericCode: '744', description: 'Pipe Fence',
    category: 'FENCES', subcategory: 'Pipe Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_PIPE_FENCE', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'PF',
    simplifiedCode: '744', simplifiedDescription: 'Pipe Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN05', numericCode: '745', description: 'Net Wire Fence',
    category: 'FENCES', subcategory: 'Wire Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_NET_WIRE', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'NWF',
    simplifiedCode: '745', simplifiedDescription: 'Net Wire Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN06', numericCode: '746', description: 'Rock Wall',
    category: 'FENCES', subcategory: 'Wall',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_ROCK_WALL', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'RKW',
    simplifiedCode: '746', simplifiedDescription: 'Rock Wall', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN07', numericCode: '747', description: 'Wrought Iron Fence',
    category: 'FENCES', subcategory: 'Iron Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_WROUGHT_IRON', defaultColor: '#000000',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'WIF',
    simplifiedCode: '747', simplifiedDescription: 'Wrought Iron Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN08', numericCode: '748', description: 'Electric Fence',
    category: 'FENCES', subcategory: 'Electric Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_ELECTRIC_FENCE', defaultColor: '#FF0000',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'EF',
    simplifiedCode: '748', simplifiedDescription: 'Electric Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN09', numericCode: '749', description: 'Vinyl Fence',
    category: 'FENCES', subcategory: 'Vinyl Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_VINYL_FENCE', defaultColor: '#FFFFFF',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'VF',
    simplifiedCode: '749', simplifiedDescription: 'Vinyl Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN10', numericCode: '750', description: 'Rail Fence',
    category: 'FENCES', subcategory: 'Rail Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_RAIL_FENCE', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'RF',
    simplifiedCode: '750', simplifiedDescription: 'Rail Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN11', numericCode: '751', description: 'Hedge Row Fence',
    category: 'FENCES', subcategory: 'Hedge',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_HEDGE', defaultColor: '#006400',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'HRF',
    simplifiedCode: '751', simplifiedDescription: 'Hedge Row Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN12', numericCode: '752', description: 'Horse Wire Fence',
    category: 'FENCES', subcategory: 'Wire Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_HORSE_WIRE', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'HWF',
    simplifiedCode: '752', simplifiedDescription: 'Horse Wire Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN13', numericCode: '753', description: 'Cedar Post Fence',
    category: 'FENCES', subcategory: 'Post Fence',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_CEDAR_POST', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'CPF',
    simplifiedCode: '753', simplifiedDescription: 'Cedar Post Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN14', numericCode: '754', description: 'Unknown Fence',
    category: 'FENCES', subcategory: 'Unknown',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_FENCE_UNK', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'FENCES', defaultLabelFormat: 'UF',
    simplifiedCode: '754', simplifiedDescription: 'Unknown Fence', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'FN15', numericCode: '755', description: 'Gate',
    category: 'FENCES', subcategory: 'Gate',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_GATE', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'FENCES', defaultLabelFormat: 'GT',
    simplifiedCode: '755', simplifiedDescription: 'Gate', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── UTILITIES ───────────────────────────────────────────────────────────────

  {
    alphaCode: 'UT01', numericCode: '801', description: 'Water Meter',
    category: 'UTILITIES', subcategory: 'Water',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_WATER_METER', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'WM',
    simplifiedCode: '801', simplifiedDescription: 'Water Meter', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT02', numericCode: '802', description: 'Water Valve',
    category: 'UTILITIES', subcategory: 'Water',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_WATER_VALVE', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'WV',
    simplifiedCode: '802', simplifiedDescription: 'Water Valve', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT03', numericCode: '803', description: 'Fire Hydrant',
    category: 'UTILITIES', subcategory: 'Water',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_FIRE_HYDRANT', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'FH',
    simplifiedCode: '803', simplifiedDescription: 'Fire Hydrant', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT04', numericCode: '804', description: 'Water Line',
    category: 'UTILITIES', subcategory: 'Water',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_WATER_LINE', defaultColor: '#0000FF',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'WL',
    simplifiedCode: '804', simplifiedDescription: 'Water Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT05', numericCode: '805', description: 'Sewer Manhole',
    category: 'UTILITIES', subcategory: 'Sewer',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_SEWER_MH', defaultLineTypeId: '', defaultColor: '#8B4513',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'SMH',
    simplifiedCode: '805', simplifiedDescription: 'Sewer Manhole', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT06', numericCode: '806', description: 'Sewer Line',
    category: 'UTILITIES', subcategory: 'Sewer',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SEWER_LINE', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'SWL',
    simplifiedCode: '806', simplifiedDescription: 'Sewer Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT07', numericCode: '807', description: 'Gas Meter',
    category: 'UTILITIES', subcategory: 'Gas',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_GAS_METER', defaultLineTypeId: '', defaultColor: '#FF8000',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'GM',
    simplifiedCode: '807', simplifiedDescription: 'Gas Meter', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT08', numericCode: '808', description: 'Gas Valve',
    category: 'UTILITIES', subcategory: 'Gas',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_GAS_VALVE', defaultLineTypeId: '', defaultColor: '#FF8000',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'GV',
    simplifiedCode: '808', simplifiedDescription: 'Gas Valve', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT09', numericCode: '809', description: 'Gas Line',
    category: 'UTILITIES', subcategory: 'Gas',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_GAS_LINE', defaultColor: '#FF8000',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'GL',
    simplifiedCode: '809', simplifiedDescription: 'Gas Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT10', numericCode: '810', description: 'Electric Meter',
    category: 'UTILITIES', subcategory: 'Electric',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_ELEC_METER', defaultLineTypeId: '', defaultColor: '#FFFF00',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'EM',
    simplifiedCode: '810', simplifiedDescription: 'Electric Meter', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT11', numericCode: '811', description: 'Electric Pole',
    category: 'UTILITIES', subcategory: 'Electric',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_ELEC_POLE', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'EP',
    simplifiedCode: '811', simplifiedDescription: 'Electric Pole', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT12', numericCode: '812', description: 'Electric Line (OH)',
    category: 'UTILITIES', subcategory: 'Electric',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_ELEC_OH', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'EOH',
    simplifiedCode: '812', simplifiedDescription: 'Electric Line (OH)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT13', numericCode: '813', description: 'Electric Line (UG)',
    category: 'UTILITIES', subcategory: 'Electric',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_ELEC_UG', defaultColor: '#FFFF00',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'EUG',
    simplifiedCode: '813', simplifiedDescription: 'Electric Line (UG)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT14', numericCode: '814', description: 'Telephone/Cable Pole',
    category: 'UTILITIES', subcategory: 'Telecom',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_TEL_POLE', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'TCP',
    simplifiedCode: '814', simplifiedDescription: 'Telephone/Cable Pole', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT15', numericCode: '815', description: 'Telephone/Cable Line',
    category: 'UTILITIES', subcategory: 'Telecom',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_TEL_LINE', defaultColor: '#00FF00',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'TCL',
    simplifiedCode: '815', simplifiedDescription: 'Telephone/Cable Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT16', numericCode: '816', description: 'Storm Drain Inlet',
    category: 'UTILITIES', subcategory: 'Storm',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_STORM_INLET', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'SDI',
    simplifiedCode: '816', simplifiedDescription: 'Storm Drain Inlet', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT17', numericCode: '817', description: 'Storm Drain Line',
    category: 'UTILITIES', subcategory: 'Storm',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_STORM_LINE', defaultColor: '#0000FF',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'SDL',
    simplifiedCode: '817', simplifiedDescription: 'Storm Drain Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT18', numericCode: '818', description: 'Irrigation Head',
    category: 'UTILITIES', subcategory: 'Irrigation',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_IRR_HEAD', defaultLineTypeId: '', defaultColor: '#00FFFF',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'IH',
    simplifiedCode: '818', simplifiedDescription: 'Irrigation Head', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT19', numericCode: '819', description: 'Irrigation Line',
    category: 'UTILITIES', subcategory: 'Irrigation',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_IRR_LINE', defaultColor: '#00FFFF',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'IL',
    simplifiedCode: '819', simplifiedDescription: 'Irrigation Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT20', numericCode: '820', description: 'Street Light',
    category: 'UTILITIES', subcategory: 'Electric',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_STREET_LIGHT', defaultLineTypeId: '', defaultColor: '#FFFF00',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'SL',
    simplifiedCode: '820', simplifiedDescription: 'Street Light', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT21', numericCode: '821', description: 'Sign',
    category: 'UTILITIES', subcategory: 'Misc',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_SIGN', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'SGN',
    simplifiedCode: '821', simplifiedDescription: 'Sign', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT22', numericCode: '822', description: 'Guy Wire',
    category: 'UTILITIES', subcategory: 'Electric',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_GUY_WIRE', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'GW',
    simplifiedCode: '822', simplifiedDescription: 'Guy Wire', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT23', numericCode: '823', description: 'Fiber Optic',
    category: 'UTILITIES', subcategory: 'Telecom',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_FIBER', defaultColor: '#00FF00',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'FO',
    simplifiedCode: '823', simplifiedDescription: 'Fiber Optic', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT24', numericCode: '824', description: 'Catv Junction',
    category: 'UTILITIES', subcategory: 'Telecom',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_CATV_JCT', defaultLineTypeId: '', defaultColor: '#00FF00',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'CTV',
    simplifiedCode: '824', simplifiedDescription: 'Catv Junction', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT25', numericCode: '825', description: 'Septic Tank',
    category: 'UTILITIES', subcategory: 'Sewer',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_SEPTIC', defaultLineTypeId: '', defaultColor: '#8B4513',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'SEP',
    simplifiedCode: '825', simplifiedDescription: 'Septic Tank', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT26', numericCode: '826', description: 'Septic Drain Field',
    category: 'UTILITIES', subcategory: 'Sewer',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SEPTIC', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'SDF',
    simplifiedCode: '826', simplifiedDescription: 'Septic Drain Field', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT27', numericCode: '827', description: 'Well',
    category: 'UTILITIES', subcategory: 'Water',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_WELL', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'WL',
    simplifiedCode: '827', simplifiedDescription: 'Well', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT28', numericCode: '828', description: 'Cistern',
    category: 'UTILITIES', subcategory: 'Water',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_CISTERN', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'CIS',
    simplifiedCode: '828', simplifiedDescription: 'Cistern', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT29', numericCode: '829', description: 'Underground Tank',
    category: 'UTILITIES', subcategory: 'Gas',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_UG_TANK', defaultLineTypeId: '', defaultColor: '#FF8000',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'UGT',
    simplifiedCode: '829', simplifiedDescription: 'Underground Tank', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'UT30', numericCode: '830', description: 'Misc Utility',
    category: 'UTILITIES', subcategory: 'Misc',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_MISC_UTIL', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'UTILITIES', defaultLabelFormat: 'MU',
    simplifiedCode: '830', simplifiedDescription: 'Misc Utility', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── VEGETATION ──────────────────────────────────────────────────────────────

  {
    alphaCode: 'VG01', numericCode: '701', description: 'Tree',
    category: 'VEGETATION', subcategory: 'Tree',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_TREE', defaultLineTypeId: '', defaultColor: '#006400',
    defaultLineWeight: 0, defaultLayerId: 'VEGETATION', defaultLabelFormat: 'TRE',
    simplifiedCode: '701', simplifiedDescription: 'Tree', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'VG02', numericCode: '702', description: 'Shrub/Bush',
    category: 'VEGETATION', subcategory: 'Shrub',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_SHRUB', defaultLineTypeId: '', defaultColor: '#006400',
    defaultLineWeight: 0, defaultLayerId: 'VEGETATION', defaultLabelFormat: 'SHR',
    simplifiedCode: '702', simplifiedDescription: 'Shrub/Bush', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'VG03', numericCode: '703', description: 'Palm Tree',
    category: 'VEGETATION', subcategory: 'Tree',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_PALM', defaultLineTypeId: '', defaultColor: '#006400',
    defaultLineWeight: 0, defaultLayerId: 'VEGETATION', defaultLabelFormat: 'PLM',
    simplifiedCode: '703', simplifiedDescription: 'Palm Tree', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'VG04', numericCode: '704', description: 'Dead Tree',
    category: 'VEGETATION', subcategory: 'Tree',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_DEAD_TREE', defaultLineTypeId: '', defaultColor: '#8B4513',
    defaultLineWeight: 0, defaultLayerId: 'VEGETATION', defaultLabelFormat: 'DTR',
    simplifiedCode: '704', simplifiedDescription: 'Dead Tree', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'VG05', numericCode: '705', description: 'Orchard Tree',
    category: 'VEGETATION', subcategory: 'Tree',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_ORCH_TREE', defaultLineTypeId: '', defaultColor: '#006400',
    defaultLineWeight: 0, defaultLayerId: 'VEGETATION', defaultLabelFormat: 'OTR',
    simplifiedCode: '705', simplifiedDescription: 'Orchard Tree', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'VG06', numericCode: '706', description: 'Stump',
    category: 'VEGETATION', subcategory: 'Stump',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_STUMP', defaultLineTypeId: '', defaultColor: '#8B4513',
    defaultLineWeight: 0, defaultLayerId: 'VEGETATION', defaultLabelFormat: 'STM',
    simplifiedCode: '706', simplifiedDescription: 'Stump', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'VG07', numericCode: '729', description: 'Edge of Woods',
    category: 'VEGETATION', subcategory: 'Tree Line',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_WOODS_EDGE', defaultColor: '#006400',
    defaultLineWeight: 1, defaultLayerId: 'VEGETATION', defaultLabelFormat: 'EOW',
    simplifiedCode: '729', simplifiedDescription: 'Edge of Woods', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'VG08', numericCode: '730', description: 'Hedge Row',
    category: 'VEGETATION', subcategory: 'Hedge',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_HEDGE', defaultColor: '#006400',
    defaultLineWeight: 1, defaultLayerId: 'VEGETATION', defaultLabelFormat: 'HR',
    simplifiedCode: '730', simplifiedDescription: 'Hedge Row', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── TOPOGRAPHY ──────────────────────────────────────────────────────────────

  {
    alphaCode: 'TP01', numericCode: '351', description: 'Ground Shot',
    category: 'TOPOGRAPHY', subcategory: 'Ground',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_GROUND_SHOT', defaultLineTypeId: '', defaultColor: '#8B4513',
    defaultLineWeight: 0, defaultLayerId: 'TOPO', defaultLabelFormat: 'GS',
    simplifiedCode: '351', simplifiedDescription: 'Ground Shot', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP02', numericCode: '352', description: 'Spot Elevation',
    category: 'TOPOGRAPHY', subcategory: 'Elevation',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_SPOT_ELEV', defaultLineTypeId: '', defaultColor: '#8B4513',
    defaultLineWeight: 0, defaultLayerId: 'TOPO', defaultLabelFormat: 'SE',
    simplifiedCode: '352', simplifiedDescription: 'Spot Elevation', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP03', numericCode: '353', description: 'Top of Bank',
    category: 'TOPOGRAPHY', subcategory: 'Bank',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_TOPO', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'TOB',
    simplifiedCode: '353', simplifiedDescription: 'Top of Bank', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP04', numericCode: '354', description: 'Toe of Slope',
    category: 'TOPOGRAPHY', subcategory: 'Slope',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_TOPO', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'TOS',
    simplifiedCode: '354', simplifiedDescription: 'Toe of Slope', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP05', numericCode: '355', description: 'Ridge Line',
    category: 'TOPOGRAPHY', subcategory: 'Ridge',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_TOPO', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'RDG',
    simplifiedCode: '355', simplifiedDescription: 'Ridge Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP06', numericCode: '357', description: 'Contour Major',
    category: 'TOPOGRAPHY', subcategory: 'Contour',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_CONTOUR_MAJOR', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'CMAJ',
    simplifiedCode: '357', simplifiedDescription: 'Contour Major', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP07', numericCode: '358', description: 'Contour Minor',
    category: 'TOPOGRAPHY', subcategory: 'Contour',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_CONTOUR_MINOR', defaultColor: '#8B4513',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'CMIN',
    simplifiedCode: '358', simplifiedDescription: 'Contour Minor', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP08', numericCode: '630', description: 'Ditch/Swale',
    category: 'TOPOGRAPHY', subcategory: 'Drainage',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SWALE', defaultColor: '#0000FF',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'DSWL',
    simplifiedCode: '630', simplifiedDescription: 'Ditch/Swale', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP09', numericCode: '632', description: 'Stream',
    category: 'TOPOGRAPHY', subcategory: 'Water',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_STREAM', defaultColor: '#0000FF',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'STR',
    simplifiedCode: '632', simplifiedDescription: 'Stream', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP10', numericCode: '633', description: 'River',
    category: 'TOPOGRAPHY', subcategory: 'Water',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_RIVER', defaultColor: '#0000FF',
    defaultLineWeight: 2, defaultLayerId: 'TOPO', defaultLabelFormat: 'RVR',
    simplifiedCode: '633', simplifiedDescription: 'River', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TP11', numericCode: '634', description: 'Pond/Lake Edge',
    category: 'TOPOGRAPHY', subcategory: 'Water',
    connectType: 'LINE', isAutoSpline: true,
    defaultSymbolId: '', defaultLineTypeId: 'LT_POND', defaultColor: '#0000FF',
    defaultLineWeight: 1, defaultLayerId: 'TOPO', defaultLabelFormat: 'POND',
    simplifiedCode: '634', simplifiedDescription: 'Pond/Lake Edge', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── TRANSPORTATION ──────────────────────────────────────────────────────────

  {
    alphaCode: 'TR01', numericCode: '401', description: 'Centerline',
    category: 'TRANSPORTATION', subcategory: 'Road',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_CENTERLINE', defaultColor: '#FF0000',
    defaultLineWeight: 1, defaultLayerId: 'ROAD', defaultLabelFormat: 'CL',
    simplifiedCode: '401', simplifiedDescription: 'Centerline', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TR02', numericCode: '402', description: 'Edge of Pavement',
    category: 'TRANSPORTATION', subcategory: 'Road',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#000000',
    defaultLineWeight: 1, defaultLayerId: 'ROAD', defaultLabelFormat: 'EOP',
    simplifiedCode: '402', simplifiedDescription: 'Edge of Pavement', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TR03', numericCode: '403', description: 'Back of Curb',
    category: 'TRANSPORTATION', subcategory: 'Curb',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#000000',
    defaultLineWeight: 1, defaultLayerId: 'ROAD', defaultLabelFormat: 'BOC',
    simplifiedCode: '403', simplifiedDescription: 'Back of Curb', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TR04', numericCode: '404', description: 'Face of Curb',
    category: 'TRANSPORTATION', subcategory: 'Curb',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#000000',
    defaultLineWeight: 1, defaultLayerId: 'ROAD', defaultLabelFormat: 'FOC',
    simplifiedCode: '404', simplifiedDescription: 'Face of Curb', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TR05', numericCode: '405', description: 'Gutter',
    category: 'TRANSPORTATION', subcategory: 'Curb',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#000000',
    defaultLineWeight: 1, defaultLayerId: 'ROAD', defaultLabelFormat: 'GTR',
    simplifiedCode: '405', simplifiedDescription: 'Gutter', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TR06', numericCode: '406', description: 'Sidewalk Edge',
    category: 'TRANSPORTATION', subcategory: 'Sidewalk',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'ROAD', defaultLabelFormat: 'SWE',
    simplifiedCode: '406', simplifiedDescription: 'Sidewalk Edge', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TR07', numericCode: '407', description: 'Railroad Track',
    category: 'TRANSPORTATION', subcategory: 'Railroad',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_RAILROAD', defaultColor: '#000000',
    defaultLineWeight: 2, defaultLayerId: 'ROAD', defaultLabelFormat: 'RRT',
    simplifiedCode: '407', simplifiedDescription: 'Railroad Track', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'TR08', numericCode: '408', description: 'Bridge',
    category: 'TRANSPORTATION', subcategory: 'Bridge',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_SOLID', defaultColor: '#000000',
    defaultLineWeight: 2, defaultLayerId: 'ROAD', defaultLabelFormat: 'BRG',
    simplifiedCode: '408', simplifiedDescription: 'Bridge', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── CURVES ──────────────────────────────────────────────────────────────────

  {
    alphaCode: 'CV01', numericCode: '201', description: 'PC (Point of Curvature)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_PC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'PC',
    simplifiedCode: '201', simplifiedDescription: 'PC (Point of Curvature)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'CV02', numericCode: '202', description: 'PT (Point of Tangency)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_PT', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'PT',
    simplifiedCode: '202', simplifiedDescription: 'PT (Point of Tangency)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'CV03', numericCode: '203', description: 'PI (Point of Intersection)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_PI', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'PI',
    simplifiedCode: '203', simplifiedDescription: 'PI (Point of Intersection)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'CV04', numericCode: '204', description: 'RP (Radius Point)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_RP', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'RP',
    simplifiedCode: '204', simplifiedDescription: 'RP (Radius Point)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'CV05', numericCode: '205', description: 'MPC (Mid Point of Curve)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_MPC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'MPC',
    simplifiedCode: '205', simplifiedDescription: 'MPC (Mid Point of Curve)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'CV06', numericCode: '206', description: 'POC (Point on Curve)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_POC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'POC',
    simplifiedCode: '206', simplifiedDescription: 'POC (Point on Curve)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'CV07', numericCode: '207', description: 'PCC (Point of Compound Curvature)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_PCC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'PCC',
    simplifiedCode: '207', simplifiedDescription: 'PCC (Point of Compound Curvature)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'CV08', numericCode: '208', description: 'PRC (Point of Reverse Curvature)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_PRC', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'PRC',
    simplifiedCode: '208', simplifiedDescription: 'PRC (Point of Reverse Curvature)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'CV09', numericCode: '209', description: 'TS (Tangent to Spiral)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_TS', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'TS',
    simplifiedCode: '209', simplifiedDescription: 'TS (Tangent to Spiral)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'CV10', numericCode: '210', description: 'ST (Spiral to Tangent)',
    category: 'CURVES', subcategory: 'Curve Point',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_ST', defaultLineTypeId: '', defaultColor: '#FF00FF',
    defaultLineWeight: 0, defaultLayerId: 'CURVES', defaultLabelFormat: 'ST',
    simplifiedCode: '210', simplifiedDescription: 'ST (Spiral to Tangent)', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },

  // ─── MISCELLANEOUS ───────────────────────────────────────────────────────────

  {
    alphaCode: 'MS01', numericCode: '901', description: 'Generic Point',
    category: 'MISCELLANEOUS', subcategory: 'Misc',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_GENERIC_PT', defaultLineTypeId: '', defaultColor: '#000000',
    defaultLineWeight: 0, defaultLayerId: 'MISC', defaultLabelFormat: 'PT',
    simplifiedCode: '901', simplifiedDescription: 'Generic Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'MS02', numericCode: '902', description: 'Temporary Benchmark',
    category: 'MISCELLANEOUS', subcategory: 'Benchmark',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_TBM', defaultLineTypeId: '', defaultColor: '#0000FF',
    defaultLineWeight: 0, defaultLayerId: 'MISC', defaultLabelFormat: 'TBM',
    simplifiedCode: '902', simplifiedDescription: 'Temporary Benchmark', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'MS03', numericCode: '903', description: 'Reference Point',
    category: 'MISCELLANEOUS', subcategory: 'Reference',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_REF_PT', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'MISC', defaultLabelFormat: 'REF',
    simplifiedCode: '903', simplifiedDescription: 'Reference Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'MS04', numericCode: '904', description: 'Offset Point',
    category: 'MISCELLANEOUS', subcategory: 'Offset',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_OFFSET_PT', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'MISC', defaultLabelFormat: 'OFS',
    simplifiedCode: '904', simplifiedDescription: 'Offset Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'MS05', numericCode: '905', description: 'Construction Point',
    category: 'MISCELLANEOUS', subcategory: 'Construction',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_CONST_PT', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'MISC', defaultLabelFormat: 'CONS',
    simplifiedCode: '905', simplifiedDescription: 'Construction Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'MS06', numericCode: '906', description: 'Flag Point',
    category: 'MISCELLANEOUS', subcategory: 'Flag',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_FLAG_PT', defaultLineTypeId: '', defaultColor: '#FF0000',
    defaultLineWeight: 0, defaultLayerId: 'MISC', defaultLabelFormat: 'FLG',
    simplifiedCode: '906', simplifiedDescription: 'Flag Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'MS07', numericCode: '907', description: 'Photo Point',
    category: 'MISCELLANEOUS', subcategory: 'Photo',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_PHOTO_PT', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'MISC', defaultLabelFormat: 'PHO',
    simplifiedCode: '907', simplifiedDescription: 'Photo Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'MS08', numericCode: '908', description: 'Note Point',
    category: 'MISCELLANEOUS', subcategory: 'Note',
    connectType: 'POINT', isAutoSpline: false,
    defaultSymbolId: 'SYM_NOTE_PT', defaultLineTypeId: '', defaultColor: '#808080',
    defaultLineWeight: 0, defaultLayerId: 'MISC', defaultLabelFormat: 'NOTE',
    simplifiedCode: '908', simplifiedDescription: 'Note Point', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'MS09', numericCode: '909', description: 'Misc Line',
    category: 'MISCELLANEOUS', subcategory: 'Misc',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_MISC', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'MISC', defaultLabelFormat: 'ML',
    simplifiedCode: '909', simplifiedDescription: 'Misc Line', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
  {
    alphaCode: 'MS10', numericCode: '910', description: 'Generic Polygon',
    category: 'MISCELLANEOUS', subcategory: 'Misc',
    connectType: 'LINE', isAutoSpline: false,
    defaultSymbolId: '', defaultLineTypeId: 'LT_MISC', defaultColor: '#808080',
    defaultLineWeight: 1, defaultLayerId: 'MISC', defaultLabelFormat: 'POLY',
    simplifiedCode: '910', simplifiedDescription: 'Generic Polygon', collapses: false,
    monumentAction: null, monumentSize: null, monumentType: null,
    isBuiltIn: true, isNew: false, notes: '',
  },
];
