-- ============================================================================
-- STARR Surveying — ACC SRVY 2343: Surveying Legal Principles I
-- ============================================================================
-- Austin Community College Geospatial Engineering course:
--   SRVY 2343 - Surveying Legal Principles I (3 SCH)
--
-- A study of the laws governing boundaries and land ownership as they apply
-- to the land surveyor. Topics include: real property concepts, types of
-- property ownership, deed interpretation, legal descriptions, the Texas
-- land system (Spanish/Mexican grants, headrights, homesteads), boundary
-- evidence and priority of calls, riparian and littoral rights, easements,
-- adverse possession, and the role of the surveyor as an expert witness.
--
-- Textbook: "Evidence and Procedures for Boundary Location" by
--   Brown, Robillard, and Wilson (7th ed.) or
--   "Boundary Control and Legal Principles" by Brown/Robillard/Wilson
--
-- Prerequisite: SRVY 1341
--
-- ACC semesters are 16 weeks. Each module has:
--   - 14 weekly lessons (weeks without exams)
--   - 1 midterm exam (Week 8)
--   - 1 final exam (Week 16)
--   - Weekly quizzes (5 questions each, non-exam weeks)
--   - Weekly homework sets (3 questions each, non-exam weeks)
--
-- Run AFTER supabase_schema.sql and supabase_seed_curriculum.sql
-- Safe to re-run (uses upserts and delete-then-insert patterns).
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: MODULE DEFINITION (order_index 32)
-- ============================================================================

INSERT INTO learning_modules (id, title, description, difficulty, estimated_hours, order_index, status, tags, xp_reward, created_at, updated_at)
VALUES
  ('acc00004-0000-0000-0000-000000000004',
   'ACC SRVY 2343 — Surveying Legal Principles I',
   'Austin Community College SRVY 2343 (3 SCH). A study of the laws governing boundaries and land ownership as they apply to the land surveyor. Topics include real property concepts, estates and ownership types, deed construction and interpretation, legal descriptions (metes and bounds, lot-and-block, PLSS), the Texas land system and its unique history of Spanish and Mexican land grants, boundary evidence and the priority of calls, riparian and littoral boundaries, easements and right-of-way, adverse possession and acquiescence, the role of the surveyor as expert witness, and professional ethics in boundary determination. This course provides the legal foundation necessary for the Surveyor-in-Training (SIT) and RPLS examinations. Prerequisite: SRVY 1341. Textbook: Evidence and Procedures for Boundary Location by Brown, Robillard, and Wilson.',
   'advanced', 48.0, 32, 'published',
   ARRAY['acc','srvy-2343','legal-principles','boundary-law','property-law','college-course','semester'],
   500, now(), now())

ON CONFLICT (id) DO UPDATE SET
  title           = EXCLUDED.title,
  description     = EXCLUDED.description,
  difficulty      = EXCLUDED.difficulty,
  estimated_hours = EXCLUDED.estimated_hours,
  order_index     = EXCLUDED.order_index,
  status          = EXCLUDED.status,
  tags            = EXCLUDED.tags,
  xp_reward       = EXCLUDED.xp_reward,
  updated_at      = now();


-- ============================================================================
-- SECTION 2: LESSONS (16 weeks — 14 lessons + 2 exam weeks)
-- ============================================================================

DELETE FROM learning_lessons WHERE module_id = 'acc00004-0000-0000-0000-000000000004';
INSERT INTO learning_lessons (id, module_id, title, content, key_takeaways, order_index, estimated_minutes, resources, videos, tags, status)
VALUES
  -- Week 1
  ('acc04b01-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 1: Introduction to Property Law and the Surveyor''s Role',
   'Overview of the relationship between law and land surveying. The surveyor as a quasi-judicial officer: the surveyor does not create boundaries but retraces and identifies them. Real property vs personal property. The bundle of rights concept. Historical development of property law from English common law through the American colonial period. Introduction to the Texas Constitution''s treatment of property rights. Why surveyors must understand legal principles — the surveyor''s opinion carries legal weight and can be challenged in court. Overview of the Texas Board of Professional Engineers and Land Surveyors (TBPELS) and the legal authority of the RPLS.',
   ARRAY['Explain why surveyors must understand property law','Distinguish between real and personal property','Describe the bundle of rights concept','Understand the surveyor''s quasi-judicial role in boundary determination','Identify the legal authority governing Texas land surveyors'],
   1, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-1','property-law','introduction','surveyor-role'], 'published'),

  -- Week 2
  ('acc04b02-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 2: Estates and Ownership in Real Property',
   'Types of estates in land: fee simple absolute, fee simple defeasible (determinable, condition subsequent, executory interest), life estates, and future interests (remainders, reversions). Forms of concurrent ownership: tenancy in common, joint tenancy with right of survivorship, community property (Texas is a community property state). Homestead rights under the Texas Constitution — the unique protections afforded to homestead property in Texas. How ownership types affect the surveyor: understanding who has authority to commission surveys, grant easements, and convey property.',
   ARRAY['Identify and describe the major types of estates in land','Distinguish between fee simple absolute and defeasible estates','Explain community property in Texas','Describe Texas homestead protections and their significance','Understand how ownership affects survey authority and conveyance'],
   2, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-2','estates','ownership','community-property','homestead'], 'published'),

  -- Week 3
  ('acc04b03-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 3: Deeds — Construction, Types, and Interpretation',
   'The anatomy of a deed: grantor, grantee, granting clause, habendum clause, legal description, covenants, exceptions and reservations, acknowledgment, and delivery. Types of deeds: general warranty deed, special warranty deed, quitclaim deed, deed without warranty. Rules of deed construction and interpretation: the intent of the grantor controls, the deed is construed as a whole, specific descriptions prevail over general, and ambiguities are construed against the grantor. The doctrine of merger — oral agreements merge into the written deed. Recording statutes in Texas and the concept of constructive notice.',
   ARRAY['Identify all essential parts of a deed','Distinguish between general warranty, special warranty, and quitclaim deeds','Apply basic rules of deed construction','Explain the doctrine of merger','Understand recording statutes and constructive notice in Texas'],
   3, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-3','deeds','construction','interpretation','recording'], 'published'),

  -- Week 4
  ('acc04b04-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 4: Legal Descriptions — Metes and Bounds',
   'Metes and bounds descriptions: the oldest form of legal description in the United States and the primary method used in Texas. Components: point of beginning (POB), courses (bearings/directions), distances, calls to monuments (natural and artificial), calls to adjoiners, and return to POB for closure. Writing and interpreting metes and bounds descriptions. Common errors in descriptions: gaps, overlaps, misclosures, and ambiguities. Senior vs junior conveyances and how they affect boundary rights. Simultaneous conveyances. Reading and plotting actual deed descriptions from Texas counties.',
   ARRAY['Identify all components of a metes and bounds description','Plot a metes and bounds description from a deed','Recognize and explain common description errors','Distinguish between senior and junior conveyances','Apply rules for resolving conflicts between overlapping descriptions'],
   4, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-4','metes-and-bounds','legal-descriptions','senior-junior'], 'published'),

  -- Week 5
  ('acc04b05-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 5: Legal Descriptions — PLSS and Lot-and-Block',
   'The Public Land Survey System (PLSS): principal meridians, baselines, townships, ranges, sections, and aliquot parts. How PLSS descriptions work (e.g., "NW 1/4 of Section 12, T3N, R5W"). Why Texas does NOT use the PLSS — Texas retained its public lands when it joined the Union in 1845 and used its own land grant system instead. However, surveyors must understand PLSS for work in other states and for the SIT/RPLS exams. Lot-and-block (recorded plat) descriptions: subdivision plats, block and lot numbering, references to recorded plats. How lot-and-block descriptions incorporate the plat by reference. Strip and gore issues.',
   ARRAY['Describe the PLSS and locate land by section, township, and range','Explain why Texas does not use the PLSS','Read and interpret lot-and-block descriptions from subdivision plats','Understand strip and gore problems','Compute acreage from PLSS aliquot part descriptions'],
   5, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-5','PLSS','lot-and-block','legal-descriptions','subdivision'], 'published'),

  -- Week 6
  ('acc04b06-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 6: The Texas Land System — Spanish and Mexican Grants',
   'The unique history of Texas land ownership. Spanish land grants: the empresario system, leagues and labors as units of measure (1 league = 4,428.4 acres, 1 labor = 177.1 acres). Mexican land grants after 1821 independence. The Texas Republic (1836–1845): headright grants, bounty grants, donation grants, and pre-emption rights. Texas land offices and the General Land Office (GLO). How these historical grants created the patchwork of original surveys that define Texas property boundaries today. Reading original field notes from Spanish and Mexican surveys. The vara as a unit of measurement (1 vara = 33-1/3 inches in Texas). Patent vs grant terminology.',
   ARRAY['Describe the Spanish empresario system and its impact on Texas land','Define leagues, labors, and varas as Texas land measurement units','Explain the different types of Republic-era land grants','Understand the role of the Texas General Land Office','Read and interpret original field notes from historical Texas surveys'],
   6, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-6','texas-land-system','spanish-grants','mexican-grants','GLO','vara'], 'published'),

  -- Week 7
  ('acc04b07-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 7: Boundary Evidence and the Priority of Calls',
   'Types of boundary evidence: natural monuments (rivers, trees, rock outcrops), artificial monuments (iron rods, pipes, stones, fences), record evidence (deeds, plats, field notes), and parol evidence (testimony). The hierarchy of calls (priority of evidence) from the Stanolind Oil case and Texas common law: (1) natural monuments, (2) artificial monuments, (3) distances, (4) direction/bearing, (5) area/quantity. Why monuments control over courses and distances. Conflicts between calls and how to resolve them. The concept of the "footsteps of the original surveyor." When area controls — exceptions to the general rule.',
   ARRAY['List and rank the priority of calls in boundary determination','Distinguish between natural and artificial monuments','Explain why monuments take precedence over distances and bearings','Apply the footsteps doctrine to retracement surveys','Resolve conflicts between competing boundary evidence'],
   7, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-7','boundary-evidence','priority-of-calls','monuments','footsteps'], 'published'),

  -- Week 8: MIDTERM EXAM
  ('acc04b08-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 8: Midterm Exam',
   'Midterm examination covering Weeks 1–7: property law fundamentals, estates and ownership, deed construction and interpretation, metes and bounds descriptions, PLSS and lot-and-block descriptions, the Texas land system and historical grants, boundary evidence, and the priority of calls. Expect both conceptual questions and practical problems requiring deed interpretation and description analysis.',
   ARRAY['Review all concepts from Weeks 1-7','Practice deed interpretation problems','Review the priority of calls hierarchy','Study Texas land system history and terminology'],
   8, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-8','midterm','exam'], 'published'),

  -- Week 9
  ('acc04b09-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 9: Original Surveys vs Retracement Surveys',
   'The fundamental distinction between an original survey (creating new boundaries where none existed) and a retracement survey (recovering boundaries established by a prior survey). In an original survey, the surveyor creates boundaries; in a retracement, the surveyor''s duty is to find and follow the original boundaries. The doctrine of retracement: the retracing surveyor must "follow in the footsteps" of the original surveyor and cannot establish new corners where original evidence exists. Proportionate measurement and its application. Lost vs obliterated corners: definitions and procedures for restoration. Single and double proportionate measurement in PLSS states. Texas procedures for lost corners.',
   ARRAY['Distinguish between original and retracement surveys','Explain the retracement doctrine and its legal significance','Define lost corners vs obliterated corners','Describe methods for restoring lost corners','Apply proportionate measurement principles'],
   9, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-9','original-survey','retracement','lost-corners','proportioning'], 'published'),

  -- Week 10
  ('acc04b10-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 10: Riparian and Littoral Boundaries',
   'Water boundaries in surveying: riparian rights (rivers and streams) vs littoral rights (lakes and oceans). The gradient boundary: Texas uses the gradient boundary method for non-navigable streams — the boundary is the gradient of the flowing water. Navigable vs non-navigable waters in Texas: navigable streams are public and the state owns the bed; non-navigable streams have private beds. Accretion (gradual deposit of soil), erosion (gradual removal of soil), reliction (water permanently recedes), and avulsion (sudden change in watercourse). How these doctrines affect property boundaries — accretion and reliction move boundaries but avulsion does not. Meander lines and their purpose: they are not boundaries but rather approximate representations of the water''s edge for area computation.',
   ARRAY['Distinguish between riparian and littoral rights','Explain the gradient boundary method used in Texas','Define accretion, erosion, reliction, and avulsion','Determine how water boundary changes affect property lines','Explain why meander lines are not boundaries'],
   10, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-10','riparian','littoral','water-boundaries','accretion','avulsion'], 'published'),

  -- Week 11
  ('acc04b11-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 11: Adverse Possession and Acquiescence',
   'Adverse possession in Texas: the legal doctrine by which a person can acquire title to land owned by another through continuous, open, notorious, hostile, and exclusive possession for a statutory period. Texas limitation periods: 3-year (under color of title with registered deed), 5-year (cultivated/used and paid taxes), 10-year (general adverse possession), and 25-year (strongest presumption). Elements that must be proven for each period. Acquiescence: long-standing agreement between neighbors on a boundary line (practical location). The difference between adverse possession (hostile taking) and acquiescence (mutual agreement). How practical location can become a legal boundary. Boundary by agreement, estoppel, and parol agreement. Implications for the surveyor: the surveyor measures and reports but does not adjudicate title.',
   ARRAY['List the elements required for adverse possession in Texas','Identify the four Texas limitation periods and their requirements','Distinguish between adverse possession and acquiescence','Explain boundary by agreement and practical location','Understand the surveyor''s role when adverse possession is suspected'],
   11, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-11','adverse-possession','acquiescence','limitation-periods','texas'], 'published'),

  -- Week 12
  ('acc04b12-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 12: Easements and Rights-of-Way',
   'Easements defined: the right to use another person''s land for a specific purpose. Types of easements: appurtenant (benefits a neighboring property — dominant and servient estates) vs in gross (benefits a person or entity, not a property). Methods of creating easements: express grant, reservation, implication, necessity, prescription (adverse use), and dedication. Termination of easements: release, merger, abandonment, expiration, condemnation. Right-of-way easements for roads, utilities, and pipelines. Prescriptive easements — similar requirements to adverse possession but results in use rights rather than ownership. How surveyors locate and depict easements on surveys and plats. ALTA/NSPS survey requirements for easement identification.',
   ARRAY['Define easements and distinguish appurtenant from in gross','Identify the methods by which easements are created','Explain prescriptive easements and their requirements','Describe how easements are terminated','Show easements correctly on survey plats and ALTA surveys'],
   12, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-12','easements','right-of-way','prescriptive','appurtenant'], 'published'),

  -- Week 13
  ('acc04b13-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 13: The Surveyor as Expert Witness',
   'The land surveyor in litigation: boundary disputes, title disputes, and condemnation proceedings. Qualifying as an expert witness under Texas Rules of Evidence. Preparing a survey for litigation: maintaining the chain of evidence, documenting all field observations, creating clear exhibits. Writing a boundary opinion — elements of a professional opinion letter. Testimony: direct examination, cross-examination, and redirect. Common pitfalls for surveyor witnesses. The importance of objectivity — the surveyor is an expert, not an advocate. Case studies from Texas boundary litigation. Daubert standard and its application to surveyor testimony. Professional liability and errors and omissions insurance.',
   ARRAY['Describe the surveyor''s role as an expert witness','Prepare survey documentation suitable for litigation','Explain the qualification process for expert witnesses in Texas','Identify common pitfalls in expert testimony','Understand professional liability exposure'],
   13, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-13','expert-witness','litigation','testimony','professional-liability'], 'published'),

  -- Week 14
  ('acc04b14-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 14: Professional Ethics and Texas Survey Standards',
   'Ethics in land surveying: objectivity, competence, conflicts of interest, and duty to the public. The TBPELS Rules of Professional Conduct for surveyors. Minimum standards for land surveying in Texas: Category 1A through 5 surveys, required accuracy standards, monumentation requirements, plat and description requirements. ALTA/NSPS Land Title Survey standards: Table A optional items, accuracy requirements (relative positional precision of 2 cm + 50 ppm), certification language. Comparison of Texas minimum standards with ALTA/NSPS requirements. Common ethical scenarios: discovering encroachments, discrepancies between record and field, neighbor disputes, and pressure from clients to move boundaries.',
   ARRAY['Describe the TBPELS Rules of Professional Conduct','Identify Texas minimum survey standards by category','Explain ALTA/NSPS survey requirements and Table A items','Apply ethical principles to common surveying scenarios','Understand the consequences of professional misconduct'],
   14, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-14','ethics','standards','TBPELS','ALTA','professional-conduct'], 'published'),

  -- Week 15
  ('acc04b15-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 15: Case Law Review and Comprehensive Exam Preparation',
   'Review of landmark Texas boundary law cases: Stafford v. King (footsteps doctrine), State v. Balli (Spanish grants), Kirby Lumber Co. cases (timber boundaries), Oklahoma v. Texas (Red River boundary). Application of legal principles to practical boundary problems. Comprehensive review of all course topics with practice exam questions. Integration of legal concepts with surveying field practice: how legal principles guide field decisions. Study strategies for the SIT and RPLS examinations — legal principles sections. Review of common exam question formats and traps.',
   ARRAY['Analyze key Texas boundary law cases and their holdings','Apply legal principles to practical boundary scenarios','Integrate legal knowledge with surveying field practice','Prepare for SIT/RPLS exam legal principles sections','Review all major course topics systematically'],
   15, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-15','case-law','review','exam-prep','SIT','RPLS'], 'published'),

  -- Week 16: FINAL EXAM
  ('acc04b16-0000-0000-0000-000000000001', 'acc00004-0000-0000-0000-000000000004',
   'Week 16: Final Exam',
   'Comprehensive final examination covering all course material from Weeks 1–15. Topics include: property law fundamentals, estates and ownership, deeds and deed construction, all three types of legal descriptions, the Texas land system and historical grants, boundary evidence and priority of calls, original vs retracement surveys, riparian and littoral boundaries, adverse possession and acquiescence, easements, expert witness procedures, professional ethics, and Texas survey standards. Both conceptual questions and practical deed/description interpretation problems.',
   ARRAY['Review all course concepts comprehensively','Practice deed interpretation and description analysis','Review priority of calls and boundary evidence resolution','Study adverse possession requirements and water boundary doctrines','Focus on weak areas identified during the semester'],
   16, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2343','week-16','final','exam'], 'published');


-- ============================================================================
-- SECTION 3: QUESTION BANK — Weeks 1-7 (Quiz + Homework)
-- ============================================================================
-- Each non-exam week has 5 quiz questions + 3 homework problems = 8 questions
-- Midterm: 15 questions covering weeks 1-7
-- Final: 20 questions comprehensive

DELETE FROM question_bank WHERE tags @> ARRAY['acc-srvy-2343'];

-- Week 1 Quiz & Homework
INSERT INTO question_bank (question_text, question_type, options, correct_answer, explanation, difficulty, module_id, lesson_id, exam_category, tags) VALUES
('The land surveyor''s role in boundary determination is best described as:', 'multiple_choice', '["Legislative — creating new laws about property","Quasi-judicial — interpreting evidence to locate existing boundaries","Executive — enforcing property rights","Arbitrary — placing boundaries wherever convenient"]'::jsonb, 'Quasi-judicial — interpreting evidence to locate existing boundaries', 'The surveyor acts in a quasi-judicial capacity, weighing evidence (deeds, monuments, testimony) to locate boundaries that already exist in law. The surveyor does not create boundaries in a retracement — they find and mark them.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b01-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-1','quiz','surveyor-role']),
('Real property includes all of the following EXCEPT:', 'multiple_choice', '["Land and soil","Buildings permanently attached to the land","Growing timber","A mobile home on wheels ready to be towed"]'::jsonb, 'A mobile home on wheels ready to be towed', 'Real property includes land, things permanently attached (fixtures), and things growing on the land. A mobile home on wheels that is not permanently affixed is personal property (chattel), not real property.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b01-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-1','quiz','real-property']),
('The "bundle of rights" in real property includes all EXCEPT:', 'multiple_choice', '["Right of possession","Right of enjoyment","Right of disposition","Right to commit waste"]'::jsonb, 'Right to commit waste', 'The bundle of rights includes possession, enjoyment, control, exclusion, and disposition (sale/transfer). Waste — damaging or destroying the property — is generally prohibited, not a right.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b01-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-1','quiz','bundle-of-rights']),
('In Texas, the board that regulates professional land surveyors is:', 'multiple_choice', '["Texas Department of Licensing and Regulation","Texas Board of Professional Engineers and Land Surveyors (TBPELS)","Texas Real Estate Commission","Texas Land Office"]'::jsonb, 'Texas Board of Professional Engineers and Land Surveyors (TBPELS)', 'TBPELS (Texas Board of Professional Engineers and Land Surveyors) is the regulatory body that licenses and regulates both professional engineers and professional land surveyors in Texas.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b01-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-1','quiz','TBPELS','licensing']),
('A surveyor who retraces a boundary creates new property rights for the landowner.', 'true_false', '["True","False"]'::jsonb, 'False', 'A retracement surveyor does NOT create property rights. They locate and mark boundaries that already exist in law from the original survey and conveyance. Only an original survey creates new boundaries.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b01-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-1','quiz','retracement']),
('Explain the difference between real property and personal property, and give two examples of each.', 'essay', '[]'::jsonb, 'Real property: land, buildings, growing crops. Personal property: vehicles, furniture, equipment.', 'Real property (realty) consists of land and everything permanently attached to or growing on it. Examples include a house, a barn, mineral rights, and standing timber. Personal property (personalty/chattels) consists of movable items not attached to land. Examples include vehicles, livestock, furniture, and tools. The distinction matters because real property is conveyed by deed while personal property is conveyed by bill of sale.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b01-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-1','homework','real-vs-personal']),
('Why is it important for land surveyors to study property law? Describe at least three reasons.', 'essay', '[]'::jsonb, 'Surveyors interpret deeds, locate boundaries using legal evidence, may testify as expert witnesses, and must follow professional standards.', 'Surveyors must study property law because: (1) they interpret deeds and legal descriptions as part of every boundary survey, (2) they must understand the priority of calls and rules of evidence to locate boundaries correctly, (3) they may be called as expert witnesses in boundary disputes, (4) they must comply with TBPELS rules and minimum standards, and (5) their survey opinions carry legal weight and can affect property rights. A surveyor ignorant of the law risks malpractice and harm to clients.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b01-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-1','homework','surveyor-law']),
('What is the legal significance of the RPLS license in Texas?', 'short_answer', '[]'::jsonb, 'The RPLS license authorizes independent practice of land surveying in Texas under TBPELS authority', 'The RPLS (Registered Professional Land Surveyor) license, granted by TBPELS, is the legal authorization to practice land surveying independently in Texas. Only an RPLS may certify surveys, sign and seal plats, and offer professional boundary opinions. Practicing without a license is a criminal offense.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b01-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-1','homework','RPLS','licensing']),

-- Week 2 Quiz & Homework
('A fee simple absolute estate is:', 'multiple_choice', '["The highest form of ownership recognized by law","A temporary right to use land","Ownership that automatically ends upon a condition","A lease for 99 years"]'::jsonb, 'The highest form of ownership recognized by law', 'Fee simple absolute is the most complete form of property ownership. The owner has all rights in the bundle of rights with no conditions or limitations on duration. It can be inherited and conveyed freely.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b02-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-2','quiz','fee-simple']),
('Texas is a community property state. This means that property acquired during marriage is generally:', 'multiple_choice', '["Owned solely by the husband","Owned solely by whoever paid for it","Owned equally by both spouses","Owned by the state"]'::jsonb, 'Owned equally by both spouses', 'In Texas (a community property state), property acquired during marriage by either spouse is presumed to be community property owned equally by both. Separate property includes what was owned before marriage or received as a gift or inheritance during marriage.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b02-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-2','quiz','community-property']),
('A fee simple determinable estate automatically ends when:', 'multiple_choice', '["The owner dies","A specified condition occurs","The government condemns the property","The deed expires after 30 years"]'::jsonb, 'A specified condition occurs', 'A fee simple determinable ends automatically when a specified condition occurs (e.g., "to the church so long as used for religious purposes"). When the condition is violated, ownership reverts automatically to the grantor without court action.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b02-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-2','quiz','fee-simple-determinable']),
('A life estate grants ownership for:', 'multiple_choice', '["99 years","The life of the grantee or another specified person","As long as taxes are paid","Forever"]'::jsonb, 'The life of the grantee or another specified person', 'A life estate is ownership measured by the lifetime of a designated person (the life tenant or a third party in a pur autre vie estate). Upon that person''s death, the property passes to the remainderman or reverts to the grantor.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b02-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-2','quiz','life-estate']),
('Under Texas homestead law, a homestead can be seized to pay credit card debt.', 'true_false', '["True","False"]'::jsonb, 'False', 'Texas has among the strongest homestead protections in the nation. A homestead is generally protected from forced sale for most debts. Exceptions include purchase money mortgages, property taxes, home equity loans (with restrictions), and mechanic''s liens for work on the property.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b02-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-2','quiz','homestead']),
('Describe the difference between joint tenancy with right of survivorship and tenancy in common. Which is more common in Texas?', 'essay', '[]'::jsonb, 'Joint tenancy: equal shares, survivorship right. Tenancy in common: unequal shares possible, no survivorship. Tenancy in common is more common in Texas.', 'Joint tenancy with right of survivorship (JTWROS) means co-owners hold equal shares, and when one dies, their share automatically passes to the surviving co-owner(s) outside of probate. Tenancy in common allows unequal shares, each owner can sell or will their share independently, and there is no survivorship right. In Texas, tenancy in common is the default presumption unless JTWROS is explicitly created.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b02-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-2','homework','concurrent-ownership']),
('What is a fee simple defeasible estate? Give an example of language that creates one.', 'short_answer', '[]'::jsonb, 'Ownership that can be lost upon a condition; e.g., "to Grantee so long as used for school purposes"', 'A fee simple defeasible is ownership that can be terminated if a specified condition occurs. Example: "To the City of Austin so long as the land is used as a public park." If the city stops using it as a park, ownership reverts. Key words include "so long as," "while," "during," and "provided that."', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b02-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-2','homework','defeasible-estate']),
('Why should a surveyor understand the type of estate held by the person commissioning a survey?', 'short_answer', '[]'::jsonb, 'To ensure the person has authority to commission the survey and to understand any limitations on the property', 'A surveyor should verify ownership because: (1) only an authorized person should commission a survey, (2) the estate type may affect what can be shown on the survey, (3) life tenants and defeasible fee holders have limitations that may matter, and (4) in community property situations, both spouses may need to be involved in conveying or encumbering the property.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b02-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-2','homework','ownership-authority']),

-- Week 3 Quiz & Homework
('The clause in a deed that states "to have and to hold" is the:', 'multiple_choice', '["Granting clause","Habendum clause","Acknowledgment","Warranty clause"]'::jsonb, 'Habendum clause', 'The habendum clause ("to have and to hold") defines the extent of ownership being conveyed. It follows the granting clause and specifies the type of estate granted. If the habendum conflicts with the granting clause, the granting clause generally controls.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b03-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-3','quiz','habendum']),
('Which type of deed provides the greatest protection to the grantee?', 'multiple_choice', '["Quitclaim deed","Special warranty deed","General warranty deed","Deed without warranty"]'::jsonb, 'General warranty deed', 'A general warranty deed provides the most protection. The grantor warrants against all defects in title, even those arising before the grantor''s ownership. A special warranty deed only warrants against defects during the grantor''s ownership. A quitclaim deed provides no warranties at all.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b03-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-3','quiz','deed-types']),
('In deed interpretation, ambiguities are generally construed against the:', 'multiple_choice', '["Grantee","Grantor","County clerk","Surveyor"]'::jsonb, 'Grantor', 'The rule of construction against the grantor means that when deed language is ambiguous, it is interpreted in favor of the grantee. The reasoning is that the grantor chose the words and could have been more precise.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b03-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-3','quiz','deed-interpretation']),
('Constructive notice means that a properly recorded deed gives notice to the world of its contents.', 'true_false', '["True","False"]'::jsonb, 'True', 'When a deed is properly recorded in the county clerk''s office, it provides constructive notice to everyone. This means all subsequent purchasers are presumed to know about the conveyance, whether or not they actually searched the records.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b03-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-3','quiz','constructive-notice']),
('The doctrine of merger means that:', 'multiple_choice', '["Two parcels become one when purchased by the same owner","All prior oral agreements merge into the written deed upon delivery","A deed is automatically updated when re-recorded","The grantor and grantee become the same person"]'::jsonb, 'All prior oral agreements merge into the written deed upon delivery', 'The doctrine of merger holds that upon delivery and acceptance of a deed, all prior negotiations, oral promises, and contractual terms merge into the deed. The deed becomes the final expression of the parties'' agreement regarding the property transfer.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b03-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-3','quiz','merger-doctrine']),
('Identify and describe the six essential elements of a valid deed in Texas.', 'essay', '[]'::jsonb, 'Grantor, grantee, granting clause, consideration, legal description, delivery and acceptance', 'A valid deed in Texas requires: (1) competent grantor identified by name, (2) identifiable grantee, (3) granting clause (words of conveyance like "grant" or "convey"), (4) consideration (money, love and affection, or other value), (5) adequate legal description sufficient to identify the property, and (6) delivery to and acceptance by the grantee. Additionally, while not required for validity, acknowledgment (notarization) is necessary for recording.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b03-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-3','homework','deed-elements']),
('What is the difference between an exception and a reservation in a deed?', 'short_answer', '[]'::jsonb, 'Exception withholds existing rights from the conveyance; reservation creates a new right retained by the grantor', 'An exception removes something from the conveyance that already exists (e.g., "excepting the mineral rights previously conveyed to X"). A reservation creates a new right retained by the grantor in the property being conveyed (e.g., "reserving an easement for ingress and egress"). Though often used interchangeably in practice, they are technically different.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b03-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-3','homework','exception-reservation']),
('Compare a general warranty deed to a quitclaim deed. When might a surveyor encounter each type?', 'short_answer', '[]'::jsonb, 'General warranty: full title guarantees, most common in sales. Quitclaim: no guarantees, used to clear title defects or transfer between family.', 'A general warranty deed guarantees the title against all defects and encumbrances, even those predating the grantor''s ownership. A quitclaim deed transfers only whatever interest the grantor may have, with no guarantees. Surveyors commonly encounter general warranty deeds in normal property transactions and quitclaim deeds in situations like clearing title defects, transferring between spouses, or boundary line agreements.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b03-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-3','homework','warranty-vs-quitclaim']),

-- Week 4 Quiz & Homework
('In a metes and bounds description, "metes" refers to:', 'multiple_choice', '["Boundary corners only","Measurements of direction and distance","Property area","Adjoining owners"]'::jsonb, 'Measurements of direction and distance', '"Metes" means measurements — specifically the direction (bearing or azimuth) and distance of each boundary line. "Bounds" refers to the boundaries themselves, including monuments and adjoiners.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b04-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-4','quiz','metes-and-bounds']),
('When two deeds from the same grantor overlap, which deed generally has superior rights?', 'multiple_choice', '["The deed with the larger area","The deed recorded first (senior deed)","The deed recorded second (junior deed)","Neither — they split the overlap equally"]'::jsonb, 'The deed recorded first (senior deed)', 'Under the first-in-time rule, the senior deed (conveyed/recorded first) has superior rights. The grantor can only convey what they own. After the first conveyance, the overlap area belongs to the senior grantee, and the junior deed is short that area.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b04-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-4','quiz','senior-junior']),
('A metes and bounds description must always begin and end at the same point (close).', 'true_false', '["True","False"]'::jsonb, 'True', 'A proper metes and bounds description must close — it begins at a defined Point of Beginning (POB) and returns to that same point after traversing all boundary lines. A description that does not close is defective, though it may still be valid if the property can be identified.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b04-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-4','quiz','closure']),
('A "call" in a legal description refers to:', 'multiple_choice', '["A phone call to the county clerk","Any reference to a direction, distance, monument, or adjoiner","The name of the surveyor","The date of the survey"]'::jsonb, 'Any reference to a direction, distance, monument, or adjoiner', 'A "call" is any reference in a legal description that helps locate the boundary. Calls can be for monuments (natural or artificial), directions (bearings), distances, adjoiners (neighboring property owners), or area.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b04-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-4','quiz','calls']),
('A gap between two adjoining deed descriptions means:', 'multiple_choice', '["Both owners share the gap area","The gap area was never conveyed and may still belong to the original grantor","The surveyor made an error that must be corrected","The gap does not legally exist"]'::jsonb, 'The gap area was never conveyed and may still belong to the original grantor', 'A gap (or hiatus) is an area not covered by any deed description. If two parcels were carved from a larger tract and a gap exists between them, that strip was never conveyed and may remain with the original grantor or their heirs. Gaps create title problems.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b04-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-4','quiz','gaps']),
('Given the following partial description, identify all the "calls": "Beginning at an iron rod found in the south line of Oak Street, thence S 45°30'' E, 200.00 feet to an iron rod set..."', 'short_answer', '[]'::jsonb, 'Calls: monument (iron rod found), adjoiner (south line of Oak Street), direction (S 45°30'' E), distance (200.00 feet), monument (iron rod set)', 'The calls are: (1) monument — "iron rod found," (2) adjoiner — "south line of Oak Street," (3) direction — "S 45°30'' E," (4) distance — "200.00 feet," and (5) monument — "iron rod set." Each call is a piece of evidence the surveyor uses to locate the boundary on the ground.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b04-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-4','homework','identifying-calls']),
('Explain the difference between a senior conveyance and a junior conveyance. Why does seniority matter in boundary disputes?', 'essay', '[]'::jsonb, 'Senior conveyance is first in time and has superior rights. Junior conveyance gets what remains. Seniority resolves overlapping claims.', 'A senior conveyance is the first deed out of a common grantor. A junior conveyance is a subsequent deed from the same grantor. Seniority matters because a grantor can only convey what they still own. After the senior conveyance, the grantor''s remaining interest is reduced. If the two descriptions overlap, the senior grantee has superior rights to the overlap area, and the junior grantee is left short.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b04-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-4','homework','senior-junior-analysis']),
('What is the difference between a gap and an overlap in legal descriptions? Which is worse from a title perspective?', 'short_answer', '[]'::jsonb, 'Gap: area not described in any deed. Overlap: area described in two deeds. Both create title problems; overlaps typically cause more disputes.', 'A gap (hiatus) is an area not covered by any description — it was never conveyed. An overlap (conflict) occurs when two descriptions cover the same area. Both create title problems. Overlaps are typically more contentious because two parties claim the same land, requiring resolution through seniority, boundary agreement, or litigation.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b04-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-4','homework','gap-overlap']),

-- Week 5 Quiz & Homework
('In the PLSS, a standard township contains how many sections?', 'multiple_choice', '["4","16","36","64"]'::jsonb, '36', 'A standard PLSS township is 6 miles × 6 miles and contains 36 sections, each approximately 1 mile × 1 mile (640 acres). Sections are numbered 1-36 in a serpentine pattern starting from the NE corner.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b05-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-5','quiz','PLSS','sections']),
('Texas does not use the PLSS because:', 'multiple_choice', '["Texas was too large to survey","Texas retained its public lands when it joined the Union","The PLSS had not been invented yet","Mexico prohibited the PLSS"]'::jsonb, 'Texas retained its public lands when it joined the Union', 'When Texas was annexed in 1845, it was the only state admitted that retained ownership of its public lands (to pay its Republic-era debt). Since the federal government did not own Texas land, it could not impose the PLSS. Texas used its own system of land grants.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b05-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-5','quiz','texas-PLSS']),
('The NW 1/4 of Section 12 contains approximately how many acres?', 'numeric_input', '[]'::jsonb, '160', 'A section is 640 acres. The NW 1/4 = 640/4 = 160 acres.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b05-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-5','quiz','PLSS-area']),
('A lot-and-block description references:', 'multiple_choice', '["GPS coordinates","A recorded subdivision plat","The original land grant","County tax records only"]'::jsonb, 'A recorded subdivision plat', 'A lot-and-block description identifies property by lot number, block number, subdivision name, and reference to the recorded plat (volume and page in the plat records or cabinet and slide). The plat provides the actual dimensions and bearings.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b05-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-5','quiz','lot-and-block']),
('A strip or gore is a narrow parcel of land between two surveys that was unintentionally left unconveyed.', 'true_false', '["True","False"]'::jsonb, 'True', 'A strip or gore is a narrow piece of land between two adjacent surveys that was never included in either survey or conveyance. Strips and gores create title problems similar to gaps and often result from imprecise original surveys.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b05-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-5','quiz','strip-gore']),
('How many acres are in the S 1/2 of the NE 1/4 of Section 20?', 'numeric_input', '[]'::jsonb, '80', 'NE 1/4 = 640/4 = 160 acres. S 1/2 of that = 160/2 = 80 acres.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b05-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-5','homework','PLSS-area-computation']),
('Write a lot-and-block legal description for Lot 5, Block 3 of a subdivision called "Oakwood Heights" recorded in Volume 10, Page 22 of the plat records of Travis County, Texas.', 'short_answer', '[]'::jsonb, 'Lot 5, Block 3, Oakwood Heights, a subdivision in Travis County, Texas, according to the plat thereof recorded in Volume 10, Page 22 of the Plat Records of Travis County, Texas.', 'A proper lot-and-block description includes: lot number, block number, subdivision name, county, state, and the recording reference (volume and page of plat records). This description incorporates the recorded plat by reference, which contains all dimensions and bearings.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b05-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-5','homework','lot-block-writing']),
('Explain why a Texas surveyor still needs to understand the PLSS even though Texas does not use it.', 'short_answer', '[]'::jsonb, 'PLSS knowledge is required for SIT/RPLS exams, for work in other states, and for understanding federal land records', 'Texas surveyors need PLSS knowledge for: (1) the SIT and RPLS exams test PLSS extensively, (2) surveyors licensed in Texas may work in PLSS states or on federal land, (3) understanding PLSS principles aids in understanding general surveying concepts like proportioning and restoration of lost corners, and (4) some federal land within Texas (military bases, national parks) may reference PLSS-like descriptions.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b05-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-5','homework','PLSS-relevance']),

-- Week 6 Quiz & Homework
('A Spanish league of land in Texas contains approximately:', 'multiple_choice', '["177 acres","640 acres","4,428 acres","10,000 acres"]'::jsonb, '4,428 acres', 'A Spanish league (legua) in Texas equals approximately 4,428.4 acres (25 million square varas). A labor equals approximately 177.1 acres (1 million square varas). These are the primary land measurement units from the Spanish/Mexican period.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b06-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-6','quiz','league','spanish-grants']),
('The Texas vara is defined as:', 'multiple_choice', '["Exactly 36 inches","33-1/3 inches","39.37 inches","Exactly 1 meter"]'::jsonb, '33-1/3 inches', 'The Texas vara equals 33-1/3 inches (33.333... inches). This was established by the Texas legislature and is used to interpret all Spanish and Mexican-era land grants in Texas. One vara = 0.8467 meters.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b06-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-6','quiz','vara']),
('Under the empresario system, colonists received land grants in exchange for:', 'multiple_choice', '["Paying cash to the Spanish crown","Settling and developing the land","Military service only","Building churches"]'::jsonb, 'Settling and developing the land', 'The empresario system (used by both Spain and Mexico) granted land to empresarios (land agents like Stephen F. Austin) who recruited settlers. Colonists received land grants in exchange for settling, building homes, and developing the land — typically a league and a labor for ranching families.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b06-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-6','quiz','empresario']),
('The Texas General Land Office (GLO) maintains records of original Texas land grants.', 'true_false', '["True","False"]'::jsonb, 'True', 'The GLO, established in 1836 by the Republic of Texas, is the custodian of all original land grant records, field notes, patents, and maps. It maintains over 35 million acres of state land records and is an essential research resource for Texas surveyors.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b06-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-6','quiz','GLO']),
('A headright grant in the Republic of Texas was given to:', 'multiple_choice', '["Only Stephen F. Austin","Any citizen of the Republic based on arrival date","Only military veterans","Only married men"]'::jsonb, 'Any citizen of the Republic based on arrival date', 'Headright grants were given to citizens of the Republic of Texas based on when they arrived. First-class headrights (arrived before March 2, 1836) received a league and a labor. Second-class (arrived before October 1, 1837) received 1/3 league. Third-class received 640 acres. The amount decreased for later arrivals.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b06-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-6','quiz','headright']),
('Convert 5,000 varas to feet using the Texas vara (33-1/3 inches).', 'numeric_input', '[]'::jsonb, '13889', '5,000 varas × 33.333 inches/vara = 166,667 inches ÷ 12 = 13,888.9 feet ≈ 13,889 feet. Or: 5,000 × (100/36) = 13,888.9 ft.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b06-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-6','homework','vara-conversion']),
('Describe the major types of land grants issued during the Republic of Texas era (1836-1845).', 'essay', '[]'::jsonb, 'Headright grants (by arrival date), bounty grants (military service), donation grants (Battle of San Jacinto veterans), and pre-emption rights (settlers on vacant land).', 'Republic-era grants include: (1) Headright grants — issued based on arrival date in Texas, ranging from a league and labor (first class) to 640 acres (third class). (2) Bounty grants — issued to soldiers for military service during the revolution. (3) Donation grants — special grants to veterans of the Battle of San Jacinto and other key engagements. (4) Pre-emption rights — allowed settlers already occupying vacant public land to purchase it at a reduced price. These grants created the patchwork of original surveys that define Texas property boundaries today.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b06-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-6','homework','republic-grants']),
('What is the difference between a patent and a deed in the context of Texas land grants?', 'short_answer', '[]'::jsonb, 'A patent is the original transfer from the sovereign (Spain, Mexico, Republic, or State of Texas) to the first private owner. A deed is a transfer between private parties.', 'A patent (or grant) is the sovereign''s conveyance of public land to the first private owner — it creates original title. All subsequent transfers between private parties are by deed. The patent and its original field notes are the ultimate root of title for every parcel in Texas.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b06-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-6','homework','patent-vs-deed']),

-- Week 7 Quiz & Homework
('In the priority of calls, which type of evidence ranks highest?', 'multiple_choice', '["Area","Distance","Direction/bearing","Natural monuments"]'::jsonb, 'Natural monuments', 'The priority of calls from highest to lowest: (1) natural monuments (rivers, creeks, rock outcrops), (2) artificial monuments (iron rods, stones, fences), (3) adjoiners/record boundaries, (4) distances, (5) directions/bearings, (6) area/quantity. Natural monuments are the most reliable because they are least susceptible to error.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b07-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-7','quiz','priority-of-calls']),
('When a deed calls for a creek as a boundary, but the measured distance does not reach the creek, the boundary extends to:', 'multiple_choice', '["The measured distance","The creek","Halfway between the distance and the creek","Neither — the description is void"]'::jsonb, 'The creek', 'Natural monuments control over distance. When a deed calls for a creek (natural monument) and a distance, but they conflict, the creek controls. The boundary extends to the creek regardless of the stated distance.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b07-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-7','quiz','monuments-over-distance']),
('"Following in the footsteps of the original surveyor" means:', 'multiple_choice', '["Using the same equipment the original surveyor used","Walking the same path the original surveyor walked","Locating the boundaries exactly as the original surveyor established them","Contacting the original surveyor for directions"]'::jsonb, 'Locating the boundaries exactly as the original surveyor established them', 'The footsteps doctrine requires the retracing surveyor to locate the boundaries as they were actually established on the ground by the original surveyor, even if the original surveyor made errors. The original monuments control, not what the deed says the measurements should be.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b07-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-7','quiz','footsteps-doctrine']),
('An artificial monument found in the field takes precedence over the bearing stated in the deed.', 'true_false', '["True","False"]'::jsonb, 'True', 'Artificial monuments rank higher than directions/bearings in the priority of calls. If a found monument conflicts with the bearing in the deed, the monument controls because it represents where the boundary was actually placed on the ground.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b07-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-7','quiz','monument-over-bearing']),
('Area is the least reliable call in a legal description because it is always computed from other measurements.', 'true_false', '["True","False"]'::jsonb, 'True', 'Area (acreage) is the weakest call because it is a calculated value derived from distances and directions. Any errors in those measurements compound in the area calculation. Area is generally the last evidence considered in resolving boundary conflicts.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b07-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-7','quiz','area-weakest-call']),
('A deed calls for an iron rod at a corner, but the field survey finds the iron rod 2.5 feet from the record position. Explain what the surveyor should do and why.', 'essay', '[]'::jsonb, 'The surveyor should hold the found monument as the corner because monuments control over distances and bearings. Document the discrepancy.', 'The surveyor should hold the found iron rod as the corner position. Under the priority of calls, monuments (even artificial ones) control over distances and bearings. The 2.5-foot discrepancy likely represents normal measurement error or difference between modern and historical methods. The surveyor should document the monument (size, type, condition), record its coordinates, note the discrepancy from record, and show it on the plat. The monument represents where the boundary was actually placed.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b07-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-7','homework','monument-discrepancy']),
('List the priority of calls from strongest to weakest and give an example of each type of evidence.', 'essay', '[]'::jsonb, '1. Natural monuments (creek), 2. Artificial monuments (iron rod), 3. Adjoiners (Jones tract), 4. Distance (200 ft), 5. Direction (N45E), 6. Area (10 acres)', 'Priority from strongest to weakest: (1) Natural monuments — e.g., "to the center of Onion Creek" (permanent, difficult to move). (2) Artificial monuments — e.g., "to an iron rod set" (placed by the surveyor but could be disturbed). (3) Adjoiners — e.g., "along the south line of the Jones tract." (4) Distance — e.g., "200.00 feet" (subject to measurement error). (5) Direction — e.g., "N 45° E" (subject to compass error, declination). (6) Area — e.g., "containing 10 acres" (calculated from other measurements, most error-prone).', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b07-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-7','homework','priority-list']),
('Describe a scenario where area might control over distance in a boundary determination.', 'short_answer', '[]'::jsonb, 'When land was originally sold by the acre with area as the primary intent, and monuments are lost, area may control to preserve the grantor''s intent.', 'Area may control when land was sold "by the acre" (e.g., "10 acres at $500 per acre") and the intent was clearly to convey a specific quantity. If all monuments are lost and the deed emphasizes area as the key element of the transaction, a court may give area more weight than usual. This is the exception, not the rule.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b07-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-7','homework','area-controls']);


-- ============================================================================
-- SECTION 4: MIDTERM EXAM QUESTIONS (15 questions covering Weeks 1-7)
-- ============================================================================

INSERT INTO question_bank (question_text, question_type, options, correct_answer, explanation, difficulty, module_id, lesson_id, exam_category, tags) VALUES
('The surveyor''s role in boundary determination is best described as:', 'multiple_choice', '["Creating new boundaries","Quasi-judicial — locating existing boundaries based on evidence","Arbitrating disputes between neighbors","Deciding who owns the land"]'::jsonb, 'Quasi-judicial — locating existing boundaries based on evidence', 'The surveyor weighs evidence to locate boundaries already established in law. This is a quasi-judicial function, not a legislative or judicial one.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','surveyor-role']),
('Fee simple absolute ownership is characterized by:', 'multiple_choice', '["Limited duration","Conditions on use","Complete ownership with no limitations on duration","Government approval required for transfer"]'::jsonb, 'Complete ownership with no limitations on duration', 'Fee simple absolute is the most complete form of ownership — unlimited duration, freely transferable, inheritable, and subject to no conditions.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','estates']),
('A quitclaim deed:', 'multiple_choice', '["Guarantees clear title","Transfers whatever interest the grantor may have without warranties","Is only used for government land","Must include a survey"]'::jsonb, 'Transfers whatever interest the grantor may have without warranties', 'A quitclaim deed conveys whatever interest the grantor has (which could be nothing) with no warranties or guarantees about the quality of title.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','deeds']),
('In deed construction, specific descriptions prevail over general descriptions.', 'true_false', '["True","False"]'::jsonb, 'True', 'When a deed contains both a specific and general description that conflict, the specific description controls because it better reflects the grantor''s intent.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','deed-construction']),
('The point of beginning (POB) in a metes and bounds description:', 'multiple_choice', '["Can be anywhere on the boundary","Must be a well-defined, identifiable point","Is always in the NE corner","Is optional"]'::jsonb, 'Must be a well-defined, identifiable point', 'The POB must be identifiable on the ground — typically tied to a monument or referenced to a known point. Without a definite POB, the entire description may be void for uncertainty.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','metes-and-bounds']),
('A standard PLSS section contains approximately:', 'multiple_choice', '["40 acres","160 acres","320 acres","640 acres"]'::jsonb, '640 acres', 'A section is approximately 1 mile × 1 mile = 640 acres. A quarter section = 160 acres. A quarter-quarter = 40 acres.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','PLSS']),
('Texas uses the vara as a unit of measure in historical land grants. One vara equals:', 'multiple_choice', '["36 inches","33-1/3 inches","39.37 inches","30 inches"]'::jsonb, '33-1/3 inches', 'The Texas vara = 33-1/3 inches, as established by the Texas legislature for interpreting Spanish and Mexican land grants.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','vara']),
('A labor of land in the Texas land grant system contains approximately:', 'multiple_choice', '["40 acres","177 acres","640 acres","4,428 acres"]'::jsonb, '177 acres', 'A labor = 1,000,000 square varas ≈ 177.1 acres. A league = 25,000,000 square varas ≈ 4,428.4 acres.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','labor']),
('The highest-ranking evidence in the priority of calls is:', 'multiple_choice', '["Distance","Direction","Natural monuments","Area"]'::jsonb, 'Natural monuments', 'Natural monuments (rivers, creeks, ridges) rank first in the priority of calls because they are the most permanent and least susceptible to error or fraud.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','priority-of-calls']),
('When a call for a monument conflicts with a call for distance, the surveyor should:', 'multiple_choice', '["Split the difference","Hold the distance","Hold the monument","Ask the client what they prefer"]'::jsonb, 'Hold the monument', 'Monuments control over distance in the priority of calls. The monument represents where the boundary was actually placed on the ground.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','monument-vs-distance']),
('The Texas General Land Office was established in what year?', 'multiple_choice', '["1776","1821","1836","1845"]'::jsonb, '1836', 'The GLO was established in 1836 when the Republic of Texas was formed. It is the oldest state agency in Texas and maintains all original land grant records.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','GLO']),
('Community property in Texas means that both spouses must sign a deed to convey homestead property.', 'true_false', '["True","False"]'::jsonb, 'True', 'Under Texas law, both spouses must join in a conveyance of the homestead, regardless of how title is held. This protects the non-title-holding spouse''s homestead rights.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','community-property']),
('The senior deed from a common grantor has superior rights to the junior deed.', 'true_false', '["True","False"]'::jsonb, 'True', 'The senior deed (first in time from the same grantor) has superior rights. The grantor could only convey what remained after the first conveyance.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','senior-junior']),
('An empresario was:', 'multiple_choice', '["A type of land unit","A land agent who recruited settlers for Spanish/Mexican land grants","A Texas state official","A type of deed"]'::jsonb, 'A land agent who recruited settlers for Spanish/Mexican land grants', 'An empresario (like Stephen F. Austin) was a land agent authorized by Spain or Mexico to recruit settlers. In return, the empresario received land and the settlers received grants.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','empresario']),
('How many acres are in the NE 1/4 of the SW 1/4 of a section?', 'numeric_input', '[]'::jsonb, '40', 'SW 1/4 = 640/4 = 160 acres. NE 1/4 of that = 160/4 = 40 acres.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b08-0000-0000-0000-000000000001', 'ACC-2343-MIDTERM', ARRAY['acc-srvy-2343','midterm','PLSS-computation']);


-- ============================================================================
-- SECTION 5: QUESTION BANK — Weeks 9-15
-- ============================================================================

INSERT INTO question_bank (question_text, question_type, options, correct_answer, explanation, difficulty, module_id, lesson_id, exam_category, tags) VALUES
-- Week 9
('An original survey differs from a retracement survey in that:', 'multiple_choice', '["An original survey is more accurate","An original survey creates new boundaries; a retracement locates existing ones","A retracement uses better equipment","An original survey requires more monuments"]'::jsonb, 'An original survey creates new boundaries; a retracement locates existing ones', 'An original survey creates boundaries where none previously existed. A retracement survey recovers and marks boundaries established by a prior survey. The legal duties are fundamentally different.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b09-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-9','quiz','original-vs-retracement']),
('A lost corner is one whose position:', 'multiple_choice', '["Can be determined from physical evidence","Cannot be determined from any existing evidence","Was never set","Is underwater"]'::jsonb, 'Cannot be determined from any existing evidence', 'A lost corner is one whose position cannot be determined beyond reasonable doubt from either evidence on the ground or reliable testimony. Its position must be restored using proportionate measurement or other prescribed methods.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b09-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-9','quiz','lost-corner']),
('An obliterated corner is one where the monument is gone but the position can be established from evidence.', 'true_false', '["True","False"]'::jsonb, 'True', 'An obliterated corner has had its monument destroyed or removed, but its position can still be established through witness marks, reference ties, testimony, or other evidence. This distinguishes it from a lost corner.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b09-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-9','quiz','obliterated-corner']),
('Proportionate measurement is used to restore:', 'multiple_choice', '["Obliterated corners","Found monuments","Lost corners","Witness trees"]'::jsonb, 'Lost corners', 'Proportionate measurement is the method used to restore lost corners by distributing the excess or deficiency of measurement proportionally among the remaining lines. It is NOT used for obliterated corners, which are restored from evidence.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b09-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-9','quiz','proportionate-measurement']),
('Explain the footsteps doctrine and why it is important in retracement surveys.', 'essay', '[]'::jsonb, 'The retracing surveyor must locate boundaries as the original surveyor established them, even if the original surveyor made errors.', 'The footsteps doctrine requires the retracing surveyor to follow the original surveyor''s work and locate boundaries where they were actually placed — not where they should have been placed according to the deed. If the original surveyor set a corner 10 feet from the record position, that corner IS the legal boundary. This is important because property rights have been established based on the original survey, and landowners have relied on those boundaries.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b09-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-9','homework','footsteps-essay']),

-- Week 10
('Riparian rights apply to property bordering:', 'multiple_choice', '["Lakes and oceans","Rivers and streams","Any body of water","Underground water"]'::jsonb, 'Rivers and streams', 'Riparian rights apply to property bordering flowing water (rivers and streams). Littoral rights apply to property bordering standing water (lakes and oceans). The distinction matters for boundary determination.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b10-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-10','quiz','riparian']),
('Accretion moves the property boundary because:', 'multiple_choice', '["The state requires it","The gradual deposit of soil is imperceptible and the boundary follows the water","The landowner paid for the new soil","The deed says it does"]'::jsonb, 'The gradual deposit of soil is imperceptible and the boundary follows the water', 'Accretion — the gradual, imperceptible deposit of soil by water action — moves the property boundary because the boundary is the water''s edge (gradient boundary). As soil builds up gradually, the boundary moves with the water. This rewards the riparian owner for the risk of erosion.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b10-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-10','quiz','accretion']),
('A sudden change in a river''s course (such as during a flood) is called:', 'multiple_choice', '["Accretion","Erosion","Avulsion","Reliction"]'::jsonb, 'Avulsion', 'Avulsion is a sudden, perceptible change in a watercourse (e.g., a river cutting a new channel during a flood). Unlike accretion and erosion (which are gradual), avulsion does NOT change the property boundary — the boundary remains at the former channel location.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b10-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-10','quiz','avulsion']),
('Meander lines are boundaries.', 'true_false', '["True","False"]'::jsonb, 'False', 'Meander lines are NOT boundaries. They are approximate lines run along the bank of a body of water for the purpose of computing area. The actual boundary is the water''s edge (gradient boundary), not the meander line.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b10-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-10','quiz','meander-lines']),
('In Texas, who owns the bed of a navigable stream?', 'multiple_choice', '["The adjacent landowners","The State of Texas","The federal government","No one"]'::jsonb, 'The State of Texas', 'In Texas, the state owns the beds of navigable streams (those averaging 30 feet or more in width from the mouth up). The riparian owner''s boundary is the gradient of the flowing water, not the center of the stream.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b10-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-10','quiz','navigable-streams']),

-- Week 11
('Adverse possession in Texas requires possession that is:', 'multiple_choice', '["Continuous, open, notorious, hostile, and exclusive","Continuous and hostile only","Open and notorious only","Exclusive and continuous only"]'::jsonb, 'Continuous, open, notorious, hostile, and exclusive', 'All five elements must be present: (1) Continuous — uninterrupted for the statutory period. (2) Open — visible, not hidden. (3) Notorious — obvious enough that the owner should notice. (4) Hostile — without the owner''s permission. (5) Exclusive — not shared with the owner or public.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b11-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-11','quiz','adverse-possession-elements']),
('The general adverse possession limitation period in Texas is:', 'multiple_choice', '["3 years","5 years","10 years","25 years"]'::jsonb, '10 years', 'The general adverse possession period in Texas (under Texas Civil Practice and Remedies Code §16.026) is 10 years of continuous, open, notorious, hostile, and exclusive possession. The 3-year and 5-year statutes have additional requirements.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b11-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-11','quiz','10-year-statute']),
('Acquiescence differs from adverse possession because acquiescence is:', 'multiple_choice', '["Always hostile","Based on mutual agreement between neighbors","Requires a shorter time period","Only applies to government land"]'::jsonb, 'Based on mutual agreement between neighbors', 'Acquiescence (practical location) is based on mutual agreement or acceptance between neighbors of a boundary line, while adverse possession is a hostile taking without the owner''s consent. Acquiescence creates a boundary by agreement; adverse possession creates one by conflict.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b11-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-11','quiz','acquiescence']),
('The 5-year adverse possession statute in Texas requires the claimant to have paid taxes on the property.', 'true_false', '["True","False"]'::jsonb, 'True', 'The 5-year statute (Texas CPRC §16.025) requires that the claimant cultivated, used, or enjoyed the property AND paid taxes on it during the 5-year period. This additional requirement distinguishes it from the general 10-year statute.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b11-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-11','quiz','5-year-statute']),
('A surveyor can determine that adverse possession has occurred and adjust the boundary accordingly.', 'true_false', '["True","False"]'::jsonb, 'False', 'Only a court can determine that adverse possession has occurred and transfer title. The surveyor should note evidence of potential adverse possession (fences, cultivation, improvements beyond the deed line) and inform the client, but cannot adjudicate title.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b11-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-11','quiz','surveyor-limitation']),

-- Week 12
('An easement appurtenant requires:', 'multiple_choice', '["Only one parcel of land","Two parcels: a dominant estate and a servient estate","Government approval","A written survey"]'::jsonb, 'Two parcels: a dominant estate and a servient estate', 'An easement appurtenant benefits one parcel (the dominant estate) and burdens another (the servient estate). The easement "runs with the land" and transfers automatically with the dominant estate. Example: a driveway easement across a neighbor''s property.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b12-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-12','quiz','easement-appurtenant']),
('An easement by necessity is typically created when:', 'multiple_choice', '["The government needs access","A landlocked parcel needs access to a public road","A utility company needs to install lines","A neighbor agrees to share a driveway"]'::jsonb, 'A landlocked parcel needs access to a public road', 'An easement by necessity arises when a parcel is landlocked (has no access to a public road) as a result of a conveyance. The law implies an easement over the grantor''s remaining land to provide access, because it is presumed the grantor did not intend to convey useless land.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b12-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-12','quiz','easement-necessity']),
('A prescriptive easement requires the same elements as adverse possession.', 'true_false', '["True","False"]'::jsonb, 'True', 'Prescriptive easements require the same elements as adverse possession: continuous, open, notorious, hostile, and exclusive use for the statutory period. The difference is that the claimant acquires a right to USE the land, not own it.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b12-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-12','quiz','prescriptive-easement']),
('An easement in gross:', 'multiple_choice', '["Benefits a neighboring property","Benefits a person or entity, not a property","Cannot be transferred","Must be created by deed only"]'::jsonb, 'Benefits a person or entity, not a property', 'An easement in gross benefits a person or entity rather than a neighboring property. Common examples include utility easements (benefiting the utility company) and billboard easements. There is no dominant estate — only a servient estate.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b12-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-12','quiz','easement-in-gross']),

-- Week 13
('The Daubert standard for expert testimony requires the surveyor to demonstrate:', 'multiple_choice', '["Membership in professional organizations","That their methods are based on reliable principles and applied correctly","At least 20 years of experience","A college degree in surveying"]'::jsonb, 'That their methods are based on reliable principles and applied correctly', 'Under the Daubert standard (adopted in Texas as the Robinson standard), expert testimony must be based on sufficient facts/data, reliable principles/methods, and the expert must have applied those methods reliably. The court acts as a gatekeeper for expert testimony.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b13-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-13','quiz','Daubert']),
('When testifying as an expert witness, the surveyor should be an advocate for their client.', 'true_false', '["True","False"]'::jsonb, 'False', 'The surveyor must be an objective expert, not an advocate. The surveyor''s duty is to present their professional opinion based on the evidence, regardless of which party hired them. Advocacy destroys credibility and may constitute professional misconduct.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b13-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-13','quiz','objectivity']),

-- Week 14
('ALTA/NSPS Land Title Surveys require a relative positional precision of:', 'multiple_choice', '["1 foot","0.1 feet","2 cm + 50 ppm","1 meter"]'::jsonb, '2 cm + 50 ppm', 'ALTA/NSPS standards require a relative positional precision of 2 cm + 50 ppm (parts per million). For example, over a 100-meter traverse, the allowable error is 2 cm + 0.005 m = 2.5 cm.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b14-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-14','quiz','ALTA-precision']),
('TBPELS can revoke or suspend an RPLS license for professional misconduct.', 'true_false', '["True","False"]'::jsonb, 'True', 'TBPELS has the authority to investigate complaints and take disciplinary action including reprimand, probation, suspension, or revocation of an RPLS license for violations of the Professional Land Surveying Practices Act or Rules of Professional Conduct.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b14-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-14','quiz','TBPELS-discipline']),
('Describe three ethical scenarios a surveyor might face and how each should be handled according to professional standards.', 'essay', '[]'::jsonb, 'Scenarios: discovering encroachment, client pressure to move boundary, competence in unfamiliar work. Handle with objectivity, honesty, and professional standards.', 'Common scenarios: (1) Discovering a neighbor''s fence encroaches — the surveyor must report findings accurately even if unfavorable to the client; moving the line would be fraud. (2) A client asks the surveyor to "adjust" a boundary — the surveyor must refuse and explain that boundaries are determined by evidence, not client preference. (3) Being asked to survey unfamiliar terrain (offshore, mining) — the surveyor should decline if they lack competence, per TBPELS rules requiring competence in the work accepted.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b14-0000-0000-0000-000000000001', 'ACC-2343', ARRAY['acc-srvy-2343','week-14','homework','ethics-scenarios']);


-- ============================================================================
-- SECTION 6: FINAL EXAM QUESTIONS (20 questions comprehensive)
-- ============================================================================

INSERT INTO question_bank (question_text, question_type, options, correct_answer, explanation, difficulty, module_id, lesson_id, exam_category, tags) VALUES
('The bundle of rights includes possession, enjoyment, control, exclusion, and:', 'multiple_choice', '["Taxation","Disposition","Eminent domain","Adverse possession"]'::jsonb, 'Disposition', 'The bundle of rights: possession, enjoyment, control, exclusion, and disposition (the right to sell, gift, will, or otherwise transfer the property).', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','bundle-of-rights']),
('The habendum clause in a deed defines:', 'multiple_choice', '["The property boundaries","The extent of ownership being conveyed","The purchase price","The survey method used"]'::jsonb, 'The extent of ownership being conveyed', 'The habendum clause ("to have and to hold") specifies what estate is being conveyed (fee simple, life estate, etc.) and any conditions or limitations.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','habendum']),
('Ambiguities in a deed are construed against the:', 'multiple_choice', '["Grantee","Grantor","Surveyor","County"]'::jsonb, 'Grantor', 'Ambiguities are construed against the grantor because the grantor chose the language and could have been clearer.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','deed-construction']),
('In the priority of calls, directions/bearings rank:', 'multiple_choice', '["First","Second","Third","Fifth"]'::jsonb, 'Fifth', 'Priority: (1) natural monuments, (2) artificial monuments, (3) adjoiners, (4) distances, (5) directions/bearings, (6) area. Directions rank fifth because compass readings are subject to declination and instrument errors.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','priority-of-calls']),
('One Texas league equals approximately:', 'numeric_input', '[]'::jsonb, '4428', 'One league = 25,000,000 square varas ≈ 4,428.4 acres.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','league']),
('Avulsion does NOT change property boundaries because the change is sudden and perceptible.', 'true_false', '["True","False"]'::jsonb, 'True', 'Avulsion (sudden change) does not move the boundary — it remains at the former location of the watercourse. Only gradual, imperceptible changes (accretion and erosion) move the boundary.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','avulsion']),
('The 3-year adverse possession statute in Texas requires:', 'multiple_choice', '["Just possession for 3 years","Possession under color of title with a registered deed","Payment of taxes only","Permission from the owner"]'::jsonb, 'Possession under color of title with a registered deed', 'The 3-year statute (CPRC §16.024) requires possession under title or color of title from the sovereign. This is the shortest AP period and has the strictest requirements.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','3-year-statute']),
('An easement appurtenant runs with the land, meaning it:', 'multiple_choice', '["Expires when the owner dies","Transfers automatically with the dominant estate","Must be renewed every 10 years","Only applies to agricultural land"]'::jsonb, 'Transfers automatically with the dominant estate', 'An easement appurtenant is attached to the dominant estate and transfers automatically when that property is conveyed, even if not mentioned in the deed.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','easement-appurtenant']),
('A lost corner must be restored by:', 'multiple_choice', '["The original surveyor","Proportionate measurement","Simply setting a new monument anywhere","Using only GPS"]'::jsonb, 'Proportionate measurement', 'Lost corners (whose position cannot be determined from evidence) must be restored using proportionate measurement, distributing excess or deficiency equally among the remaining lines.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','lost-corner-restoration']),
('The retracing surveyor may establish new boundaries when the original monuments are found.', 'true_false', '["True","False"]'::jsonb, 'False', 'When original monuments are found, the retracing surveyor must honor them — they represent the actual boundary as established. The surveyor cannot establish new boundaries when evidence of the originals exists.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','retracement']),
('In Texas, navigable streams are defined as those averaging at least ___ feet in width.', 'numeric_input', '[]'::jsonb, '30', 'Under Texas law, a stream is navigable if it averages 30 feet or more in width from its mouth up. The state owns the bed of navigable streams.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','navigable-width']),
('Reliction occurs when:', 'multiple_choice', '["Water gradually covers new land","Water permanently recedes, exposing new land","A river changes course suddenly","A dam is built"]'::jsonb, 'Water permanently recedes, exposing new land', 'Reliction is the gradual, permanent recession of water that exposes new land. Like accretion, reliction moves the property boundary because it is gradual. The exposed land belongs to the riparian/littoral owner.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','reliction']),
('A general warranty deed warrants against defects in title arising:', 'multiple_choice', '["Only during the grantor''s ownership","Only from the original patent","At any time — before and during the grantor''s ownership","Only after the grantee takes possession"]'::jsonb, 'At any time — before and during the grantor''s ownership', 'A general warranty deed provides the broadest protection, warranting against all title defects regardless of when they arose. A special warranty deed, by contrast, only warrants against defects during the grantor''s ownership.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','general-warranty']),
('The W 1/2 of the NE 1/4 of the SE 1/4 of a section contains how many acres?', 'numeric_input', '[]'::jsonb, '20', 'SE 1/4 = 160 acres. NE 1/4 of that = 40 acres. W 1/2 of that = 20 acres.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','PLSS-computation']),
('An easement by prescription can be prevented by:', 'multiple_choice', '["Ignoring the use","Granting permission for the use","Building a fence","Recording a deed"]'::jsonb, 'Granting permission for the use', 'Granting permission defeats the "hostile" element required for a prescriptive easement. If the use is permissive, it cannot be adverse, and no prescriptive rights can accrue no matter how long it continues.', 'hard', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','preventing-prescription']),
('Texas homestead protections prevent forced sale of a homestead for most debts.', 'true_false', '["True","False"]'::jsonb, 'True', 'Texas homestead protections are among the strongest in the nation. The homestead is exempt from forced sale for most debts, with exceptions for purchase-money liens, property taxes, home equity loans, and mechanic''s liens.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','homestead']),
('Convert 8,000 varas to feet.', 'numeric_input', '[]'::jsonb, '22222', '8,000 × 33.333 inches / 12 inches = 22,222.2 feet ≈ 22,222 feet.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','vara-conversion']),
('A surveyor who knowingly moves a monument to favor a client commits:', 'multiple_choice', '["A minor error","Professional misconduct subject to TBPELS discipline","A civil matter only","An accepted practice in boundary disputes"]'::jsonb, 'Professional misconduct subject to TBPELS discipline', 'Knowingly moving or disturbing a monument is a violation of professional ethics and Texas law. It constitutes fraud and professional misconduct subject to license revocation, civil liability, and potentially criminal charges.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','ethics-monuments']),
('The footsteps doctrine requires the retracing surveyor to:', 'multiple_choice', '["Use the same brand of equipment","Locate boundaries where the original surveyor actually placed them","Follow the deed description exactly, ignoring found monuments","Survey only on the same day of year"]'::jsonb, 'Locate boundaries where the original surveyor actually placed them', 'The footsteps doctrine means following the original surveyor''s actual work on the ground, even if it differs from the record. Found monuments from the original survey represent the legal boundary.', 'medium', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','footsteps']),
('An expert witness surveyor should present their findings objectively, not as an advocate for either party.', 'true_false', '["True","False"]'::jsonb, 'True', 'The surveyor''s credibility depends on objectivity. An expert witness must present professional opinions based on evidence and accepted methodology, regardless of which party retained them. Advocacy destroys credibility and violates professional ethics.', 'easy', 'acc00004-0000-0000-0000-000000000004', 'acc04b16-0000-0000-0000-000000000001', 'ACC-2343-FINAL', ARRAY['acc-srvy-2343','final','expert-witness']);


COMMIT;
