-- ============================================================================
-- STARR Surveying — ACC SRVY 2344: Surveying Legal Principles II
-- ============================================================================
-- Austin Community College Geospatial Engineering course:
--   SRVY 2344 - Surveying Legal Principles II (3 SCH)
--
-- Continuation of SRVY 2343. Advanced study of boundary law, deed
-- interpretation, and the surveyor's role in resolving complex boundary
-- problems. Topics include: advanced deed analysis, simultaneous and
-- sequential conveyances, riparian boundary complexities, mineral
-- rights and subsurface estates, eminent domain and condemnation,
-- subdivision platting law, ALTA/NSPS survey standards, Texas
-- administrative code for surveying, advanced case law analysis,
-- and preparation of boundary opinions and expert reports.
--
-- Textbook: "Evidence and Procedures for Boundary Location" by
--   Brown, Robillard, and Wilson (7th ed.) and
--   "Clark on Surveying and Boundaries" (selected chapters)
--
-- Prerequisite: SRVY 2343
--
-- ACC semesters are 16 weeks.
-- Run AFTER supabase_schema.sql and supabase_seed_curriculum.sql
-- Safe to re-run (uses upserts and delete-then-insert patterns).
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: MODULE DEFINITION (order_index 35)
-- ============================================================================

INSERT INTO learning_modules (id, title, description, difficulty, estimated_hours, order_index, status, tags, xp_reward, created_at, updated_at)
VALUES
  ('acc00007-0000-0000-0000-000000000007',
   'ACC SRVY 2344 — Surveying Legal Principles II',
   'Austin Community College SRVY 2344 (3 SCH). Continuation of SRVY 2343 with advanced study of boundary law and the surveyor''s role in complex boundary problems. Topics include advanced deed analysis with multiple conveyances, simultaneous and sequential conveyance conflicts, complex riparian and littoral boundary issues including the Red River boundary and tidal boundaries, mineral rights and the severed estate in Texas, eminent domain and condemnation survey procedures, subdivision platting law and municipal regulations, the ALTA/NSPS Land Title Survey in depth (Table A items, certification, exceptions), Texas Administrative Code Title 22 Part 29 (TBPELS rules for surveyors), advanced Texas case law analysis, writing professional boundary opinions and expert reports, and comprehensive SIT/RPLS exam preparation for the legal principles sections. Prerequisite: SRVY 2343. Textbooks: Evidence and Procedures for Boundary Location by Brown/Robillard/Wilson; Clark on Surveying and Boundaries (selected chapters).',
   'advanced', 48.0, 35, 'published',
   ARRAY['acc','srvy-2344','legal-principles-2','advanced-boundary-law','mineral-rights','ALTA','college-course','semester'],
   500, now(), now())

ON CONFLICT (id) DO UPDATE SET
  title           = EXCLUDED.title,
  description     = EXCLUDED.description,
  difficulty      = EXCLUDED.difficulty,
  estimated_hours = EXCLUDED.estimated_hours,
  order_index     = EXCLUDED.order_index,
  status          = EXCLUDED.status,
  tags            = EXCLUDED.tags,
  xp_reward       = EXCLUDED.xp_reward,
  updated_at      = now();


-- ============================================================================
-- SECTION 2: LESSONS (16 weeks)
-- ============================================================================

DELETE FROM learning_lessons WHERE module_id = 'acc00007-0000-0000-0000-000000000007';
INSERT INTO learning_lessons (id, module_id, title, content, key_takeaways, order_index, estimated_minutes, resources, videos, tags, status)
VALUES
  -- Week 1
  ('acc07b01-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 1: Review of Legal Principles I and Advanced Deed Analysis',
   'Comprehensive review of SRVY 2343 fundamentals: property law, estates, deed construction, legal descriptions, Texas land system, priority of calls, and boundary evidence. Introduction to advanced deed analysis: interpreting complex deed language, identifying ambiguities that require legal analysis, and understanding the limits of the surveyor''s authority in deed interpretation. Multi-generation deed chains: tracing title from the original patent through successive conveyances. Identifying breaks in the chain of title. The role of title abstracts and title insurance in the surveyor''s research. Understanding legal opinions vs surveyor''s opinions — what the surveyor can and cannot determine.',
   ARRAY['Review all key concepts from SRVY 2343','Analyze complex deed language and identify ambiguities','Trace a chain of title from patent to present owner','Distinguish between legal opinions and surveyor opinions','Understand the role of title research in boundary surveys'],
   1, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-1','review','deed-analysis','chain-of-title'], 'published'),

  -- Week 2
  ('acc07b02-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 2: Simultaneous and Sequential Conveyances',
   'Complex conveyance scenarios: when a grantor divides a tract into multiple parcels. Simultaneous conveyances: all parcels conveyed at the same time — no seniority among grantees, boundaries interpreted to be consistent with each other. Sequential conveyances: parcels conveyed at different times — senior/junior rights apply. The "first deed out" rule and its implications. Excess and deficiency: when the total area of all conveyances exceeds or falls short of the parent tract. Rules for distributing excess or deficiency: proportional to area, proportional to frontage, or by intent. Strips and gores between sequential conveyances — who gets the leftover land? The doctrine of after-acquired title (estoppel by deed): if a grantor conveys land they don''t own, and later acquires it, the title automatically passes to the grantee.',
   ARRAY['Distinguish between simultaneous and sequential conveyances','Apply senior/junior rights to sequential conveyances','Distribute excess and deficiency among multiple grantees','Resolve strip and gore issues between conveyances','Explain the doctrine of after-acquired title'],
   2, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-2','simultaneous','sequential','excess-deficiency','after-acquired-title'], 'published'),

  -- Week 3
  ('acc07b03-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 3: Advanced Boundary Conflict Resolution',
   'Resolving complex boundary conflicts that involve multiple types of evidence. Conflicting monuments: when two monuments that should mark the same corner are found in different positions. Conflicting deeds: when adjacent deeds describe overlapping or gapped boundaries from different grantors (not a common grantor). Unwritten rights that affect boundaries: practical location (long acquiescence), boundary by agreement (parol agreement), boundary by estoppel, and boundary by adverse possession. How unwritten rights interact with record boundaries. The surveyor''s duty when encountering conflicting evidence: document everything, apply the priority of calls, note discrepancies, and advise the client to seek legal counsel when title questions arise. Case studies in boundary conflict resolution.',
   ARRAY['Resolve conflicts between multiple found monuments','Handle boundary conflicts from different grantor chains','Identify unwritten rights that may affect boundaries','Document conflicting evidence properly in survey reports','Know when to advise clients to seek legal counsel'],
   3, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-3','boundary-conflicts','unwritten-rights','practical-location','estoppel'], 'published'),

  -- Week 4
  ('acc07b04-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 4: Complex Riparian and Littoral Boundaries',
   'Advanced water boundary issues in Texas. The Red River boundary: the historic dispute between Texas and Oklahoma, the medial line, and the vegetation line doctrine. Tidal boundaries: the mean higher high water (MHHW) line for coastal properties, Texas Open Beaches Act, and public trust doctrine. The gradient boundary in detail: how to establish the gradient of flowing water, field methods for locating the gradient boundary, and the Motl v. Boyd decision. Islands and accretions: when islands form in navigable streams, ownership rules. Oxbow lakes and abandoned channels: when a river changes course (avulsion) and the old channel becomes the boundary. Practical field procedures for riparian surveys: locating the gradient boundary, mapping meander lines, and documenting water boundary evidence. Working with hydrologists and water rights attorneys.',
   ARRAY['Explain the Red River boundary doctrine between Texas and Oklahoma','Describe tidal boundaries and the mean higher high water line','Apply the gradient boundary method from Motl v. Boyd','Determine ownership of islands and accretions','Conduct field procedures for riparian boundary surveys'],
   4, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-4','riparian-advanced','Red-River','tidal','gradient-boundary','Motl-v-Boyd'], 'published'),

  -- Week 5
  ('acc07b05-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 5: Mineral Rights and the Severed Estate',
   'Mineral rights in Texas: the concept of the severed estate — surface rights and mineral rights can be owned by different parties. How mineral severance occurs: reservation in a deed (e.g., "reserving all oil, gas, and other minerals"). The dominant estate doctrine: mineral rights are dominant over surface rights in Texas, meaning the mineral owner has the right to use the surface as reasonably necessary for extraction. Mineral leases, royalty interests, and working interests. The surveyor''s role in mineral surveys: locating well sites, pipeline easements, and mineral lease boundaries. Pooling and unitization. The Railroad Commission of Texas (RRC) and its jurisdiction over oil and gas operations. Horizontal drilling and its impact on surface use. Practical considerations: when a surface owner commissions a boundary survey on land with severed minerals.',
   ARRAY['Explain the severed estate concept for mineral rights in Texas','Describe the dominant estate doctrine and its implications','Identify the surveyor''s role in mineral-related surveys','Understand mineral leases, royalties, and working interests','Describe the Railroad Commission''s role in oil and gas regulation'],
   5, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-5','mineral-rights','severed-estate','dominant-estate','RRC'], 'published'),

  -- Week 6
  ('acc07b06-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 6: Eminent Domain and Condemnation Surveys',
   'Eminent domain: the government''s power to take private property for public use with just compensation (Fifth Amendment, Texas Constitution Art. I, §17). The condemnation process in Texas: negotiation, special commissioners hearing, and judicial proceedings. The surveyor''s role in condemnation: preparing the taking map, metes and bounds description of the taking area, calculating areas (fee taking, permanent easement, temporary easement), and identifying improvements and features within the taking area. Remainder parcels and damages: the effect of the taking on the remaining property. Types of takings: fee simple (full ownership transfer), permanent easement (ongoing use right), temporary construction easement. Inverse condemnation: when the government effectively takes property without formal proceedings. TxDOT condemnation survey requirements and standards. Preparing exhibit maps and legal descriptions for condemnation proceedings.',
   ARRAY['Explain the constitutional basis for eminent domain','Describe the condemnation process in Texas','Prepare taking maps with areas and descriptions','Distinguish between fee takings, permanent easements, and temporary easements','Understand inverse condemnation and regulatory takings'],
   6, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-6','eminent-domain','condemnation','taking-map','TxDOT'], 'published'),

  -- Week 7
  ('acc07b07-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 7: Subdivision Platting Law and Municipal Regulations',
   'Subdivision law in Texas: Texas Local Government Code Chapter 212 (municipal subdivision regulation) and Chapter 232 (county subdivision regulation). The platting process: preliminary plat, construction plans, final plat, recording. Municipal subdivision ordinances: lot size requirements, setbacks, utility easements, drainage easements, street dedication, and public improvement requirements. Extraterritorial jurisdiction (ETJ): the area outside city limits where the city can regulate subdivision. County authority: counties have limited platting authority for tracts under 10 acres outside city limits and ETJ. Creating subdivision plats: required elements (title, surveyor''s certificate, owner''s dedication, dimensions, bearings, curve data, easements, flood zones, scale, north arrow). Amending plats: replats, vacating plats, and plat corrections. Common platting mistakes and how to avoid them.',
   ARRAY['Describe Texas subdivision law under LGC Chapters 212 and 232','Explain the platting process from preliminary to recording','Identify required elements of a subdivision plat','Understand ETJ and county subdivision authority','Prepare a subdivision plat meeting municipal requirements'],
   7, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-7','subdivision','platting','municipal','ETJ','LGC-212'], 'published'),

  -- Week 8: MIDTERM EXAM
  ('acc07b08-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 8: Midterm Exam',
   'Midterm examination covering Weeks 1–7: advanced deed analysis, simultaneous and sequential conveyances, complex boundary conflict resolution, advanced riparian and littoral boundaries, mineral rights and the severed estate, eminent domain and condemnation surveys, and subdivision platting law. Expect scenario-based questions requiring analysis of complex boundary situations, deed interpretation problems, and questions on Texas-specific legal provisions.',
   ARRAY['Review all concepts from Weeks 1-7','Practice complex deed interpretation scenarios','Review mineral rights and eminent domain procedures','Study subdivision platting requirements','Focus on Texas-specific legal provisions'],
   8, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-8','midterm','exam'], 'published'),

  -- Week 9
  ('acc07b09-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 9: ALTA/NSPS Land Title Surveys — Standards and Requirements',
   'The ALTA/NSPS Land Title Survey: the most comprehensive boundary survey standard in the United States, jointly published by the American Land Title Association and the National Society of Professional Surveyors. Purpose: to provide title insurance companies and lenders with reliable boundary and survey information. The 2021 Minimum Standard Detail Requirements: scope, accuracy standards (relative positional precision of 2 cm + 50 ppm at the 95% confidence level), fieldwork requirements, and deliverables. The survey plat/map: required elements (boundaries with dimensions, area, improvements, easements, rights-of-way, encroachments, evidence of utilities, access, flood zone classification). The surveyor''s certification: standard language, what it certifies, and liability implications. When ALTA surveys are required: commercial real estate transactions, refinancing, and institutional lending.',
   ARRAY['Describe the purpose and scope of ALTA/NSPS surveys','State the accuracy requirement (2 cm + 50 ppm at 95%)','Identify required elements on an ALTA survey plat','Understand the surveyor''s certification and its implications','Explain when ALTA surveys are required in commercial transactions'],
   9, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-9','ALTA','NSPS','land-title-survey','certification','accuracy'], 'published'),

  -- Week 10
  ('acc07b10-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 10: ALTA/NSPS Table A Optional Items',
   'Table A of the ALTA/NSPS standards: 20 optional survey responsibilities that can be negotiated between the client and surveyor. Detailed study of each Table A item: Item 1 (monuments placed or to be placed), Item 2 (address of surveyed property), Item 3 (flood zone classification with FEMA map info), Item 4 (gross land area), Items 5a-5b (zoning classification and building setback lines), Item 6 (exterior dimensions of buildings and observable evidence of use), Items 7a-7c (visible utilities — above/below ground, and observed evidence), Item 8 (wetland delineation — requires specialist), Items 9-10 (parking and traffic access), Item 11 (location of utilities from record documents), Items 13-14 (building setback and height restrictions from documents), Item 16 (evidence of earth-moving or building construction), Item 17 (proposed improvements or recorded easements with furnished plans), Item 18 (vertical relief — spot elevations or contours), Item 19 (professional liability insurance), Item 20 (plat or map on previous ALTA standard). Fee implications of Table A items.',
   ARRAY['Describe each Table A optional item and its survey implications','Advise clients on which Table A items are appropriate for their transaction','Understand the additional fieldwork required for each item','Price Table A items appropriately','Coordinate with zoning and environmental specialists when needed'],
   10, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-10','ALTA','Table-A','optional-items','zoning','utilities'], 'published'),

  -- Week 11
  ('acc07b11-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 11: Texas Administrative Code — TBPELS Rules for Surveyors',
   'Texas Administrative Code Title 22, Part 29: the detailed rules governing professional land surveying in Texas. Board organization and procedures (Chapter 1071, Texas Occupations Code). Licensing requirements: SIT qualifications (education and experience), RPLS qualifications (additional experience, exam passage). Continuing education requirements for license renewal. Rules of Professional Conduct: competence, integrity, conflicts of interest, supervision of subordinates, and seal requirements. Minimum standards for surveys: Category 1A (boundary survey), Category 1B (boundary with improvements), Category 2 (topographic), Category 3 (control), Category 4 (construction), Category 5 (geodetic). Plat and description requirements under the rules. Disciplinary process: complaints, investigations, hearings, and sanctions. Recent rule changes and proposed amendments. Comparison with other states'' licensing requirements.',
   ARRAY['Navigate the Texas Administrative Code provisions for surveyors','Identify SIT and RPLS licensing requirements','Describe the TBPELS Rules of Professional Conduct','Apply Texas minimum standards to different survey categories','Understand the disciplinary process for professional misconduct'],
   11, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-11','TAC','TBPELS','licensing','minimum-standards','rules-of-conduct'], 'published'),

  -- Week 12
  ('acc07b12-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 12: Advanced Texas Case Law Analysis',
   'In-depth study of landmark Texas boundary law cases. Stafford v. King (1945): the footsteps doctrine — the retracing surveyor must follow the original surveyor''s work. State v. Balli (1933): interpreting Spanish and Mexican land grants, the role of the General Land Office. Motl v. Boyd (1926): establishing the gradient boundary method for non-navigable streams in Texas. Oklahoma v. Texas (1926): the Red River boundary, the medial line. Kirby Lumber Co. v. Temple Lumber Co.: timber boundaries and the standing timber rule. Myrad Properties v. LaSalle Bank (2009): survey liability and the scope of the surveyor''s duty. Recent Texas appellate decisions affecting surveying practice. How to research and analyze case law using legal databases. Applying case law principles to practical boundary problems.',
   ARRAY['Analyze landmark Texas boundary cases and state their holdings','Apply the Stafford v. King footsteps doctrine to retracement problems','Understand the Motl v. Boyd gradient boundary ruling','Research Texas case law relevant to surveying','Apply case law principles to practical boundary scenarios'],
   12, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-12','case-law','Stafford-v-King','Motl-v-Boyd','State-v-Balli'], 'published'),

  -- Week 13
  ('acc07b13-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 13: Writing Boundary Opinions and Expert Reports',
   'The professional boundary opinion: when and why surveyors write them. Elements of a boundary opinion letter: statement of purpose, scope of work, documents reviewed, field investigation summary, analysis of evidence, conclusions, and caveats/limitations. Writing clear, defensible analysis: supporting each conclusion with evidence and legal authority. Organizing complex boundary problems for presentation. Preparing survey exhibits for litigation: clear graphics, proper labeling, scale considerations, and color coding. The boundary opinion as a professional document: tone, objectivity, and precision of language. Peer review of boundary opinions. Common mistakes in boundary opinions and how to avoid them. The difference between a boundary opinion and a legal opinion — staying within the surveyor''s scope of practice.',
   ARRAY['Write a professional boundary opinion letter','Organize complex boundary analysis for clear presentation','Prepare survey exhibits suitable for litigation','Maintain objectivity and precision in professional writing','Distinguish between surveyor opinions and legal opinions'],
   13, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-13','boundary-opinion','expert-report','litigation','exhibits'], 'published'),

  -- Week 14
  ('acc07b14-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 14: SIT/RPLS Exam Preparation — Legal Principles',
   'Comprehensive preparation for the legal principles portions of the SIT and RPLS examinations. Exam format and structure: multiple choice, scenario-based problems, and computation questions. Key topic areas: property law fundamentals, deed interpretation, legal descriptions (all three types), Texas land history, priority of calls, boundary evidence, retracement principles, water boundaries, adverse possession, easements, eminent domain, subdivision law, ALTA/NSPS standards, and professional ethics. Practice exam questions with detailed explanations. Time management strategies for the exam. Common traps and misleading answer choices. Study resources: recommended textbooks, online resources, and study groups. Texas-specific topics that are heavily tested. Registration procedures and exam logistics.',
   ARRAY['Identify key legal principles topics tested on SIT/RPLS exams','Practice exam-style questions with time constraints','Recognize common exam traps and misleading answers','Develop effective study strategies for the licensing exams','Review Texas-specific legal principles that are heavily tested'],
   14, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-14','SIT','RPLS','exam-prep','licensing','study-strategies'], 'published'),

  -- Week 15
  ('acc07b15-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 15: Comprehensive Review and Integration',
   'Integration of all legal principles topics from both SRVY 2343 and SRVY 2344. Complex scenario problems requiring application of multiple legal principles simultaneously. Mock boundary disputes: students analyze a complete boundary problem from deed research through field investigation to written opinion. Review of all Texas-specific topics: the land grant system, community property, homestead, the vara, the GLO, the gradient boundary, mineral rights, TBPELS rules, and condemnation procedures. Final exam preparation: comprehensive practice problems, formula review, and concept summaries. Career guidance: the path from student to SIT to RPLS, continuing education, and specialization opportunities in boundary law, construction, geodesy, and GIS.',
   ARRAY['Integrate legal principles from both SRVY 2343 and 2344','Analyze complex scenarios requiring multiple legal concepts','Complete a mock boundary dispute from research to opinion','Review all Texas-specific legal topics comprehensively','Prepare for the comprehensive final examination'],
   15, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-15','review','integration','mock-dispute','comprehensive'], 'published'),

  -- Week 16: FINAL EXAM
  ('acc07b16-0000-0000-0000-000000000001', 'acc00007-0000-0000-0000-000000000007',
   'Week 16: Final Exam',
   'Comprehensive final examination covering all material from Weeks 1–15 of SRVY 2344, with integration of SRVY 2343 fundamentals. Topics include: advanced deed analysis, simultaneous/sequential conveyances, complex boundary conflicts, riparian/littoral complexities, mineral rights, eminent domain, subdivision platting, ALTA/NSPS standards and Table A items, TBPELS rules and minimum standards, Texas case law, and boundary opinion writing. Scenario-based questions requiring multi-step analysis of complex boundary problems.',
   ARRAY['Review all course concepts from both legal principles courses','Practice complex scenario-based analysis problems','Review ALTA/NSPS standards and Table A items','Study TBPELS rules and minimum standards categories','Focus on weak areas identified during the semester'],
   16, 180, '[]'::jsonb, '[]'::jsonb,
   ARRAY['acc','srvy-2344','week-16','final','exam'], 'published');


-- ============================================================================
-- SECTION 3: QUESTION BANK — Weeks 1-7 (Quiz + Homework)
-- ============================================================================

DELETE FROM question_bank WHERE tags @> ARRAY['acc-srvy-2344'];

-- Week 1 Quiz & Homework
INSERT INTO question_bank (question_text, question_type, options, correct_answer, explanation, difficulty, module_id, lesson_id, exam_category, tags) VALUES
('A chain of title traces ownership from:', 'multiple_choice', '["The current owner backward to the original patent","The original patent forward to the current owner","The county clerk to the surveyor","The buyer to the seller only"]'::jsonb, 'The original patent forward to the current owner', 'A chain of title traces the complete history of ownership from the sovereign''s original patent through every subsequent conveyance to the current owner. Each link must be unbroken for clear title.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b01-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-1','quiz','chain-of-title']),
('A title abstract is:', 'multiple_choice', '["A summary of all recorded documents affecting a parcel''s title","A survey plat","A type of deed","A court order"]'::jsonb, 'A summary of all recorded documents affecting a parcel''s title', 'A title abstract is a chronological summary of all recorded instruments (deeds, mortgages, liens, easements, judgments) that affect title to a parcel. Surveyors use abstracts to research the deed history before conducting boundary surveys.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b01-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-1','quiz','title-abstract']),
('The surveyor can determine who legally owns a disputed strip of land.', 'true_false', '["True","False"]'::jsonb, 'False', 'Only a court can determine legal ownership. The surveyor locates boundaries based on evidence and the priority of calls, but cannot adjudicate title disputes, adverse possession claims, or other ownership questions.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b01-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-1','quiz','surveyor-limitations']),
('When analyzing a deed, the surveyor should read the entire deed, not just the legal description.', 'true_false', '["True","False"]'::jsonb, 'True', 'The entire deed may contain important information: exceptions, reservations, easements, conditions, and references to other documents. Reading only the legal description can cause the surveyor to miss critical boundary-affecting provisions.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b01-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-1','quiz','deed-analysis']),
('A break in the chain of title means:', 'multiple_choice', '["The deed is too old to read","There is a gap in the recorded conveyance history","The property was surveyed incorrectly","The grantor used a quitclaim deed"]'::jsonb, 'There is a gap in the recorded conveyance history', 'A break means there is a missing link — a period where no recorded instrument accounts for the transfer of title. This creates a title defect that may require a quiet title action or other legal remedy to cure.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b01-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-1','quiz','title-break']),
('What documents should a surveyor review before conducting a boundary survey? List at least five types.', 'essay', '[]'::jsonb, 'Deeds, plats, prior surveys, title abstract/commitment, easements, county records, GLO records, aerial photos', 'A thorough boundary surveyor reviews: (1) current deed and all deeds in the chain of title, (2) recorded plats and subdivision maps, (3) prior surveys of the property and adjoining tracts, (4) title abstract or title commitment from the title company, (5) easement documents (utility, access, drainage), (6) county clerk records, (7) GLO field notes and maps for original grants, (8) aerial photographs for occupation evidence, and (9) any court orders or boundary agreements affecting the property.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b01-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-1','homework','research-documents']),
('Explain the difference between a surveyor''s opinion and a legal opinion regarding boundary location.', 'essay', '[]'::jsonb, 'Surveyor''s opinion: professional judgment on boundary location based on physical evidence and survey methods. Legal opinion: attorney''s judgment on title and ownership rights.', 'A surveyor''s opinion addresses where boundaries are located on the ground based on physical evidence, monuments, measurements, and the priority of calls. A legal opinion addresses questions of title, ownership, and legal rights — who owns the land. Surveyors must not render legal opinions (that constitutes unauthorized practice of law). When title or ownership questions arise, the surveyor should advise the client to consult an attorney.', 'hard', 'acc00007-0000-0000-0000-000000000007', 'acc07b01-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-1','homework','opinion-types']),
('Why is it important to review adjoining property deeds, not just the subject property deed?', 'short_answer', '[]'::jsonb, 'Adjoining deeds may contain calls to the subject property, different descriptions of shared boundaries, or senior rights that affect the subject boundary.', 'Adjoining deeds are essential because: (1) they may call for the subject property as an adjoiner, establishing the boundary by reference, (2) they may contain a different description of the shared boundary that creates a conflict, (3) they may be senior, giving the adjoiner superior rights, and (4) they may contain easements or restrictions that cross onto the subject property.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b01-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-1','homework','adjoining-deeds']),

-- Week 2 Quiz & Homework
('In simultaneous conveyances from a common grantor, which grantee has seniority?', 'multiple_choice', '["The first grantee named","The grantee with the larger parcel","Neither — there is no seniority","The grantee who records first"]'::jsonb, 'Neither — there is no seniority', 'In truly simultaneous conveyances, no grantee has seniority over another. All parcels are interpreted together to be consistent. Any excess or deficiency is shared proportionally rather than being absorbed entirely by the junior grantee.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b02-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-2','quiz','simultaneous']),
('When a grantor conveys more land than they own, the excess is distributed:', 'multiple_choice', '["To the first grantee only","Proportionally among all grantees","To the last grantee only","To the government"]'::jsonb, 'Proportionally among all grantees', 'When the total area of all conveyances exceeds the parent tract, the deficiency is typically distributed proportionally among all grantees (for simultaneous conveyances) or absorbed by the junior grantee (for sequential conveyances).', 'hard', 'acc00007-0000-0000-0000-000000000007', 'acc07b02-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-2','quiz','excess-deficiency']),
('The doctrine of after-acquired title means:', 'multiple_choice', '["A grantee acquires title after the statute of limitations expires","If a grantor conveys land they don''t own and later acquires it, title automatically passes to the grantee","Title can be acquired after death","The government acquires title after condemnation"]'::jsonb, 'If a grantor conveys land they don''t own and later acquires it, title automatically passes to the grantee', 'Estoppel by deed (after-acquired title): if a grantor purports to convey title they don''t own by warranty deed, and later acquires that title, it automatically passes to the original grantee. The grantor is estopped from denying the earlier conveyance.', 'hard', 'acc00007-0000-0000-0000-000000000007', 'acc07b02-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-2','quiz','after-acquired-title']),
('In sequential conveyances, the junior grantee absorbs any deficiency.', 'true_false', '["True","False"]'::jsonb, 'True', 'In sequential conveyances, the senior grantee (first out) gets the full benefit of their deed description. Any overlap or deficiency is borne by the junior grantee because the grantor had already conveyed those rights.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b02-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-2','quiz','junior-absorbs']),
('A strip of unconveyed land between two sequential conveyances is called a:', 'multiple_choice', '["Buffer zone","Strip or gore","Easement","Right-of-way"]'::jsonb, 'Strip or gore', 'A strip or gore is a narrow parcel of land inadvertently left unconveyed between two adjacent tracts. It typically belongs to the original grantor or their heirs. Courts may apply the doctrine of de minimis or other equitable principles to resolve gore disputes.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b02-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-2','quiz','strip-gore']),

-- Week 3 Quiz & Homework
('Practical location (acquiescence) differs from adverse possession because practical location:', 'multiple_choice', '["Requires a shorter time period","Is based on mutual agreement rather than hostility","Requires payment of taxes","Only applies to government land"]'::jsonb, 'Is based on mutual agreement rather than hostility', 'Practical location (acquiescence) is based on mutual recognition and acceptance of a boundary line by adjacent landowners over a long period. It is cooperative, not hostile. Adverse possession is a unilateral hostile taking of possession.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b03-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-3','quiz','practical-location']),
('When two monuments marking the same corner are found in different positions, the surveyor should:', 'multiple_choice', '["Average the two positions","Choose the one closest to the record distance","Investigate to determine which was set by the original surveyor","Ignore both and use the deed description"]'::jsonb, 'Investigate to determine which was set by the original surveyor', 'The surveyor must investigate: examine monument characteristics (type, age, condition), check accessories and reference ties, review prior surveys, and determine which monument was set by or relates to the original survey. The original monument controls.', 'hard', 'acc00007-0000-0000-0000-000000000007', 'acc07b03-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-3','quiz','conflicting-monuments']),
('Boundary by estoppel occurs when a landowner''s conduct prevents them from asserting their true boundary.', 'true_false', '["True","False"]'::jsonb, 'True', 'Estoppel applies when a landowner''s actions or representations cause a neighbor to reasonably rely on a particular boundary line to their detriment. The landowner is then "estopped" (prevented) from claiming the true boundary.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b03-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-3','quiz','estoppel']),

-- Week 4 Quiz & Homework
('The gradient boundary method in Texas was established by which case?', 'multiple_choice', '["Stafford v. King","Motl v. Boyd","Oklahoma v. Texas","State v. Balli"]'::jsonb, 'Motl v. Boyd', 'Motl v. Boyd (1926) established the gradient boundary as the method for determining the boundary of non-navigable streams in Texas. The gradient is the line of the flowing water''s surface at intermediate stage.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b04-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-4','quiz','gradient-boundary']),
('Under the Texas Open Beaches Act, beaches on the Gulf Coast are:', 'multiple_choice', '["All privately owned","Subject to public easement for access and use","Owned by the federal government","Only accessible by permit"]'::jsonb, 'Subject to public easement for access and use', 'The Texas Open Beaches Act provides public access to Gulf Coast beaches from the mean low tide line to the vegetation line. The public has a free and unrestricted right to use this area.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b04-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-4','quiz','open-beaches']),
('An island that forms in a navigable Texas stream is owned by:', 'multiple_choice', '["The adjacent riparian owner","The State of Texas","The federal government","The first person to claim it"]'::jsonb, 'The State of Texas', 'In Texas, the state owns the beds of navigable streams. An island forming in a navigable stream is part of the streambed and belongs to the state. For non-navigable streams, the island belongs to the riparian owner(s).', 'hard', 'acc00007-0000-0000-0000-000000000007', 'acc07b04-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-4','quiz','island-ownership']),

-- Week 5 Quiz & Homework
('In Texas, mineral rights are considered the _____ estate.', 'multiple_choice', '["Servient","Subordinate","Dominant","Surface"]'::jsonb, 'Dominant', 'In Texas, the mineral estate is dominant over the surface estate. This means the mineral owner has the right to use as much of the surface as is reasonably necessary to explore, develop, and produce the minerals, even without the surface owner''s consent.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b05-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-5','quiz','dominant-estate']),
('Mineral rights in Texas can be severed from surface rights.', 'true_false', '["True","False"]'::jsonb, 'True', 'Mineral rights can be reserved or excepted in a deed, creating a "severed estate" where the surface and minerals are owned by different parties. This is extremely common in Texas due to its extensive oil and gas history.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b05-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-5','quiz','severance']),
('The Railroad Commission of Texas regulates:', 'multiple_choice', '["Railroads only","Oil, gas, and mining operations","Land surveying","Real estate transactions"]'::jsonb, 'Oil, gas, and mining operations', 'Despite its name, the Railroad Commission of Texas (RRC) primarily regulates oil, gas, natural gas utilities, pipeline safety, coal and uranium mining, and LP-gas. It no longer regulates railroads.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b05-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-5','quiz','RRC']),

-- Week 6 Quiz & Homework
('Eminent domain requires _____ for the taking of private property.', 'multiple_choice', '["The owner''s consent","Just compensation","A unanimous vote","Court approval in all cases"]'::jsonb, 'Just compensation', 'The Fifth Amendment (and Texas Constitution Art. I, §17) requires that private property taken for public use must be accompanied by adequate or just compensation. The owner''s consent is not required.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b06-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-6','quiz','just-compensation']),
('A taking map prepared by the surveyor must include a metes and bounds description of the taking area.', 'true_false', '["True","False"]'::jsonb, 'True', 'The taking map includes a metes and bounds description defining the exact area being acquired, the area in square feet or acres, and the relationship to the parent tract. This description becomes part of the legal condemnation documents.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b06-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-6','quiz','taking-map']),
('Inverse condemnation occurs when:', 'multiple_choice', '["The government takes property without formal proceedings","The property owner condemns the government","The property is returned to the owner","The condemnation is reversed on appeal"]'::jsonb, 'The government takes property without formal proceedings', 'Inverse condemnation is a claim by a property owner that the government has effectively taken their property (through regulation, flooding, or other action) without formal condemnation proceedings and without paying just compensation.', 'hard', 'acc00007-0000-0000-0000-000000000007', 'acc07b06-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-6','quiz','inverse-condemnation']),

-- Week 7 Quiz & Homework
('In Texas, subdivision platting within a city''s ETJ is regulated by:', 'multiple_choice', '["The county only","The city","The state legislature directly","No one — there is no regulation in the ETJ"]'::jsonb, 'The city', 'Under Texas LGC Chapter 212, cities can regulate subdivision platting within their ETJ (extraterritorial jurisdiction). The ETJ extends from 0.5 to 5 miles beyond city limits depending on city population.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b07-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-7','quiz','ETJ']),
('A subdivision plat must include the surveyor''s certificate and the owner''s dedication.', 'true_false', '["True","False"]'::jsonb, 'True', 'A properly recorded subdivision plat requires: the surveyor''s certificate (certifying the accuracy of the survey), the owner''s dedication (dedicating streets, easements, and public areas), and typically acknowledgment and approval stamps from the applicable jurisdictions.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b07-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-7','quiz','plat-requirements']),
('Texas counties can regulate subdivision of tracts under _____ acres outside city limits and ETJ.', 'numeric_input', '[]'::jsonb, '10', 'Under LGC Chapter 232, Texas counties can require platting for subdivisions of tracts under 10 acres outside city limits and ETJ. Tracts of 10 acres or more are generally exempt from county subdivision regulation.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b07-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-7','quiz','county-authority']);


-- ============================================================================
-- SECTION 4: MIDTERM EXAM (15 questions)
-- ============================================================================

INSERT INTO question_bank (question_text, question_type, options, correct_answer, explanation, difficulty, module_id, lesson_id, exam_category, tags) VALUES
('In simultaneous conveyances, no grantee has seniority.', 'true_false', '["True","False"]'::jsonb, 'True', 'Simultaneous conveyances have no seniority — all parcels are interpreted consistently.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','simultaneous']),
('The junior grantee absorbs excess/deficiency in sequential conveyances.', 'true_false', '["True","False"]'::jsonb, 'True', 'The senior grantee gets full benefit; any shortage falls on the junior.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','sequential']),
('Boundary by estoppel requires the landowner''s conduct to have caused detrimental reliance.', 'true_false', '["True","False"]'::jsonb, 'True', 'Estoppel requires: (1) conduct by the landowner, (2) reasonable reliance by the neighbor, and (3) detriment to the neighbor.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','estoppel']),
('The gradient boundary applies to:', 'multiple_choice', '["Navigable streams only","Non-navigable streams in Texas","Lakes only","Ocean coastline"]'::jsonb, 'Non-navigable streams in Texas', 'Motl v. Boyd established the gradient boundary for non-navigable streams.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','gradient']),
('Mineral rights in Texas are the dominant estate.', 'true_false', '["True","False"]'::jsonb, 'True', 'The mineral estate is dominant over the surface estate in Texas.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','mineral-rights']),
('The Railroad Commission of Texas regulates oil and gas operations.', 'true_false', '["True","False"]'::jsonb, 'True', 'The RRC regulates oil, gas, pipelines, and mining in Texas.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','RRC']),
('Eminent domain requires:', 'multiple_choice', '["Owner consent","Just compensation","Legislative approval for each taking","A jury trial in all cases"]'::jsonb, 'Just compensation', 'Just compensation is constitutionally required for eminent domain takings.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','eminent-domain']),
('Inverse condemnation is initiated by the:', 'multiple_choice', '["Government","Property owner","Surveyor","Title company"]'::jsonb, 'Property owner', 'Inverse condemnation is a claim by the property owner that the government has effectively taken their property.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','inverse-condemnation']),
('A subdivision plat must include a surveyor''s certificate.', 'true_false', '["True","False"]'::jsonb, 'True', 'The surveyor certifies the accuracy of the boundaries, dimensions, and areas shown on the plat.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','plat']),
('Cities can regulate subdivision within their ETJ.', 'true_false', '["True","False"]'::jsonb, 'True', 'Texas LGC Chapter 212 grants cities platting authority within their ETJ.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','ETJ']),
('The Texas Open Beaches Act provides public access to Gulf beaches.', 'true_false', '["True","False"]'::jsonb, 'True', 'The Act provides public access from the mean low tide line to the vegetation line.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','open-beaches']),
('A strip or gore belongs to:', 'multiple_choice', '["The adjacent owners equally","The original grantor or their heirs","The state","Whoever finds it first"]'::jsonb, 'The original grantor or their heirs', 'Unconveyed strips remain with the original grantor (or successors) since they were never conveyed out.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','strip-gore']),
('The doctrine of after-acquired title applies when a grantor later acquires title they previously purported to convey.', 'true_false', '["True","False"]'::jsonb, 'True', 'When a grantor conveys by warranty deed and later acquires the title, it passes to the grantee automatically.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','after-acquired']),
('Only a court can adjudicate title disputes.', 'true_false', '["True","False"]'::jsonb, 'True', 'Surveyors locate boundaries but cannot determine ownership or title rights.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','court-authority']),
('Counties can require platting for tracts under 10 acres outside city limits and ETJ.', 'true_false', '["True","False"]'::jsonb, 'True', 'LGC Chapter 232 gives counties limited subdivision authority for tracts under 10 acres.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b08-0000-0000-0000-000000000001', 'ACC-2344-MIDTERM', ARRAY['acc-srvy-2344','midterm','county-platting']);


-- ============================================================================
-- SECTION 5: QUESTION BANK — Weeks 9-14
-- ============================================================================

INSERT INTO question_bank (question_text, question_type, options, correct_answer, explanation, difficulty, module_id, lesson_id, exam_category, tags) VALUES
-- Week 9
('The ALTA/NSPS accuracy requirement is:', 'multiple_choice', '["1 foot","0.1 feet","2 cm + 50 ppm at 95% confidence","1:10,000 relative precision"]'::jsonb, '2 cm + 50 ppm at 95% confidence', 'The ALTA/NSPS standard requires relative positional precision of 2 cm + 50 ppm at the 95% confidence level. For a 100m traverse, that is 2 cm + 0.5 cm = 2.5 cm allowable.', 'hard', 'acc00007-0000-0000-0000-000000000007', 'acc07b09-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-9','quiz','ALTA-accuracy']),
('An ALTA/NSPS survey must show evidence of utilities observed in the field.', 'true_false', '["True","False"]'::jsonb, 'True', 'The minimum standard requires the surveyor to show observed evidence of utilities (manholes, utility poles, pedestals, meters, etc.) on the plat. Additional utility items may be selected from Table A.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b09-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-9','quiz','ALTA-utilities']),
('The ALTA/NSPS surveyor''s certification is a legal warranty of accuracy.', 'true_false', '["True","False"]'::jsonb, 'False', 'The certification is a professional statement of what was done and what was found — it is NOT a warranty or guarantee. However, the surveyor can be held liable for negligence if the survey does not meet the stated standards.', 'hard', 'acc00007-0000-0000-0000-000000000007', 'acc07b09-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-9','quiz','ALTA-certification']),
('ALTA/NSPS surveys are most commonly required for:', 'multiple_choice', '["Residential home purchases","Commercial real estate transactions","Government surveys","Agricultural sales"]'::jsonb, 'Commercial real estate transactions', 'ALTA/NSPS surveys are primarily required for commercial real estate transactions where title insurance and/or institutional lending are involved. They are rarely required for routine residential purchases.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b09-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-9','quiz','ALTA-purpose']),

-- Week 10
('ALTA Table A Item 1 addresses:', 'multiple_choice', '["Flood zone classification","Monuments placed or to be placed","Zoning information","Parking areas"]'::jsonb, 'Monuments placed or to be placed', 'Table A Item 1 requires the surveyor to place (or report existing) monuments at all major corners of the boundary — an additional requirement beyond the minimum standard.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b10-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-10','quiz','Table-A-1']),
('Table A Item 8 (wetland delineation) requires the surveyor to delineate wetlands.', 'true_false', '["True","False"]'::jsonb, 'False', 'Table A Item 8 requires the surveyor to show wetland boundaries IF delineated by a qualified specialist. The surveyor does not perform the wetland delineation — that requires an environmental scientist or wetland specialist.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b10-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-10','quiz','Table-A-8']),
('Table A Item 19 requires the surveyor to carry professional liability insurance.', 'true_false', '["True","False"]'::jsonb, 'True', 'Item 19 requires the surveyor to carry professional liability (E&O) insurance and provide evidence of coverage. Many commercial clients and lenders require this.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b10-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-10','quiz','Table-A-19']),

-- Week 11
('The SIT examination in Texas requires a minimum of _____ semester hours of qualifying education.', 'multiple_choice', '["16","24","32","48"]'::jsonb, '32', 'Texas requires 32 semester hours of qualifying surveying education to sit for the SIT exam. The coursework must cover specified technical topics including legal principles, surveying methods, and mathematics.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b11-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-11','quiz','SIT-education']),
('A Texas RPLS must complete continuing education to renew their license.', 'true_false', '["True","False"]'::jsonb, 'True', 'Texas RPLSs must complete continuing professional development (CPD) hours during each license renewal period. The requirements are set by TBPELS and include both technical and ethics/rules components.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b11-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-11','quiz','continuing-education']),
('Category 1A under Texas minimum standards refers to:', 'multiple_choice', '["Topographic surveys","Boundary surveys without improvements","Boundary surveys with improvements shown","Construction surveys"]'::jsonb, 'Boundary surveys without improvements', 'Category 1A is a boundary survey that establishes or retraces property boundaries without showing improvements. Category 1B includes improvements. Category 2 = topographic. Category 3 = control.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b11-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-11','quiz','Category-1A']),

-- Week 12
('Stafford v. King established the _____ doctrine.', 'multiple_choice', '["Dominant estate","Gradient boundary","Footsteps","Community property"]'::jsonb, 'Footsteps', 'Stafford v. King (1945) is the landmark Texas case establishing that a retracing surveyor must follow in the footsteps of the original surveyor.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b12-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-12','quiz','Stafford-v-King']),
('State v. Balli dealt with:', 'multiple_choice', '["Water boundaries","Spanish and Mexican land grants","Adverse possession","Mineral rights"]'::jsonb, 'Spanish and Mexican land grants', 'State v. Balli (1933) is a landmark Texas case involving the interpretation of Spanish land grants in the Rio Grande Valley, establishing principles for how these historical grants are interpreted.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b12-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-12','quiz','State-v-Balli']),

-- Week 13
('A boundary opinion letter should include:', 'multiple_choice', '["Only the surveyor''s conclusion","Purpose, scope, documents reviewed, analysis, and conclusions","A legal opinion on ownership","A guarantee of accuracy"]'::jsonb, 'Purpose, scope, documents reviewed, analysis, and conclusions', 'A professional boundary opinion includes: statement of purpose, scope of work, documents reviewed, field investigation summary, analysis of evidence with legal authority, conclusions, and caveats/limitations.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b13-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-13','quiz','boundary-opinion']),
('The surveyor should be an advocate for the client in a boundary opinion.', 'true_false', '["True","False"]'::jsonb, 'False', 'The surveyor must be objective, not an advocate. The boundary opinion must present an unbiased professional analysis based on evidence and legal principles, regardless of which party is paying.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b13-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-13','quiz','objectivity']),

-- Week 14
('The SIT exam tests legal principles heavily.', 'true_false', '["True","False"]'::jsonb, 'True', 'The SIT (and RPLS) examinations in Texas include substantial portions on legal principles, boundary law, deed interpretation, and Texas-specific legal topics.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b14-0000-0000-0000-000000000001', 'ACC-2344', ARRAY['acc-srvy-2344','week-14','quiz','SIT-exam']);


-- ============================================================================
-- SECTION 6: FINAL EXAM (20 questions)
-- ============================================================================

INSERT INTO question_bank (question_text, question_type, options, correct_answer, explanation, difficulty, module_id, lesson_id, exam_category, tags) VALUES
('A chain of title must be unbroken from the original patent to the current owner.', 'true_false', '["True","False"]'::jsonb, 'True', 'Any break in the chain creates a title defect.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','chain-of-title']),
('Simultaneous conveyances have no seniority among grantees.', 'true_false', '["True","False"]'::jsonb, 'True', 'All parcels conveyed simultaneously are interpreted consistently with no priority.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','simultaneous']),
('The after-acquired title doctrine applies to:', 'multiple_choice', '["All deeds","Warranty deeds where the grantor later acquires the title","Quitclaim deeds","Government patents"]'::jsonb, 'Warranty deeds where the grantor later acquires the title', 'After-acquired title (estoppel by deed) only applies to warranty deeds, not quitclaim deeds.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','after-acquired']),
('Practical location is based on mutual agreement, not hostility.', 'true_false', '["True","False"]'::jsonb, 'True', 'Practical location (acquiescence) involves cooperative acceptance of a boundary line.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','practical-location']),
('Motl v. Boyd established the _____ boundary method.', 'multiple_choice', '["Meander","Gradient","Tidal","Vegetation"]'::jsonb, 'Gradient', 'Motl v. Boyd established the gradient boundary for non-navigable streams in Texas.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','Motl-v-Boyd']),
('The mineral estate is dominant in Texas.', 'true_false', '["True","False"]'::jsonb, 'True', 'Mineral rights are dominant over surface rights in Texas.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','dominant']),
('Eminent domain requires just compensation.', 'true_false', '["True","False"]'::jsonb, 'True', 'Constitutional requirement under the 5th Amendment and Texas Constitution.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','compensation']),
('A taking map must include:', 'multiple_choice', '["Only the property address","A metes and bounds description of the taking area with acreage","The owner''s signature","An appraisal"]'::jsonb, 'A metes and bounds description of the taking area with acreage', 'The taking map precisely defines what is being acquired with a legal description and area calculation.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','taking-map']),
('Texas LGC Chapter 212 governs:', 'multiple_choice', '["County roads","Municipal subdivision regulation","State highways","Federal lands"]'::jsonb, 'Municipal subdivision regulation', 'LGC 212 gives cities authority to regulate subdivision within city limits and ETJ.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','LGC-212']),
('ALTA accuracy is 2 cm + 50 ppm at 95% confidence.', 'true_false', '["True","False"]'::jsonb, 'True', 'This is the relative positional precision standard for ALTA/NSPS surveys.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','ALTA-accuracy']),
('Table A Item 1 addresses monuments placed at property corners.', 'true_false', '["True","False"]'::jsonb, 'True', 'Item 1 requires the surveyor to place or identify monuments at major corners.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','Table-A']),
('The ALTA surveyor''s certification is a guarantee of accuracy.', 'true_false', '["True","False"]'::jsonb, 'False', 'It is a professional statement, not a warranty or guarantee.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','certification']),
('Category 1A survey under TBPELS is a boundary survey without improvements.', 'true_false', '["True","False"]'::jsonb, 'True', '1A = boundary only. 1B = boundary with improvements.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','Category-1A']),
('Stafford v. King established the footsteps doctrine.', 'true_false', '["True","False"]'::jsonb, 'True', 'The retracing surveyor must follow in the footsteps of the original surveyor.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','Stafford']),
('A boundary opinion must be objective, not advocacy for the client.', 'true_false', '["True","False"]'::jsonb, 'True', 'Professional objectivity is essential for credibility and ethics.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','objectivity']),
('The SIT requires 32 semester hours of qualifying surveying education.', 'true_false', '["True","False"]'::jsonb, 'True', 'Texas requires 32 SCH of qualifying coursework for the SIT exam.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','SIT-education']),
('An island in a navigable Texas stream belongs to the state.', 'true_false', '["True","False"]'::jsonb, 'True', 'The state owns the beds of navigable streams, including islands.', 'medium', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','island']),
('ETJ stands for Extraterritorial Jurisdiction.', 'true_false', '["True","False"]'::jsonb, 'True', 'ETJ is the area outside city limits where the city can regulate subdivision.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','ETJ']),
('Surveyors can adjudicate title disputes between neighbors.', 'true_false', '["True","False"]'::jsonb, 'False', 'Only courts adjudicate title. Surveyors locate boundaries based on evidence.', 'easy', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','limitation']),
('Describe three key differences between SRVY 2343 and SRVY 2344 in terms of the legal topics covered and the level of complexity.', 'essay', '[]'::jsonb, '2343 covers fundamentals (estates, deeds, descriptions, priority of calls). 2344 covers advanced topics (ALTA, mineral rights, condemnation, case law, boundary opinions).', '2343 provides foundational legal principles: property law basics, deed construction, legal descriptions, the Texas land system, priority of calls, basic water boundaries, and adverse possession. 2344 builds on this with advanced applications: complex conveyance scenarios, mineral rights and severed estates, eminent domain procedures, ALTA/NSPS standards in depth, TBPELS administrative rules, Texas case law analysis, and professional boundary opinion writing. 2344 is more analytical and practice-oriented.', 'hard', 'acc00007-0000-0000-0000-000000000007', 'acc07b16-0000-0000-0000-000000000001', 'ACC-2344-FINAL', ARRAY['acc-srvy-2344','final','comparison']);


COMMIT;
