// __tests__/dnd/library-anchors.test.ts — search results actually reach the thing they name.
//
// The bug this guards: every library search hit rendered as a plain <div>. A reader could see that
// a rule existed and had no way to open it — the one thing a search result must do. Fixing it means
// the search box and the library page have to agree on two facts, and if they ever disagree the
// link fails SILENTLY (it navigates to an anchor nothing carries, and the page just sits there).
//
// So the agreement is asserted here rather than trusted:
//   · every kind the search can emit maps to a section that actually exists on a page, and
//   · the id a hit links to is generated by the same function the page stamps onto the element.
//
// WHAT THIS FILE CANNOT SEE, AND WHERE THAT IS CHECKED. Everything below reasons about SECTIONS and
// about the anchor helpers in isolation. It cannot tell whether the page puts the generated id on an
// element, and for a year it did not: conditions, skills and feats rendered as chips and table rows
// that carried no id, so every one of those results navigated to nothing while all of this stayed
// green. Landing is checked in library-deep-links.test.tsx, which renders the real page and reads the
// ids back out of the HTML. Keep both — this one localises WHICH mapping is wrong; that one is the
// only one that knows whether the reader arrives anywhere.
import { describe, it, expect } from 'vitest';
import { entryAnchorId, sectionForKind, libraryHref } from '@/lib/dnd/library-anchors';
import { libraryPageFor } from '@/lib/dnd/library';
import { GAME_SYSTEMS } from '@/lib/dnd/systems';
import fs from 'node:fs';
import path from 'node:path';

describe('entry anchors are stable and collision-resistant', () => {
  it('slugs a name to a kebab-case id', () => {
    expect(entryAnchorId('Cloak of Elvenkind')).toBe('entry-cloak-of-elvenkind');
    expect(entryAnchorId('Faerie Fire')).toBe('entry-faerie-fire');
  });

  it('is stable across punctuation and case', () => {
    // The same entry must not change id because someone fixed a typo in its punctuation — a
    // changed id silently breaks every existing bookmark and link to it.
    expect(entryAnchorId("Heroes' Feast")).toBe(entryAnchorId('Heroes Feast'));
    expect(entryAnchorId('MAGE HAND')).toBe(entryAnchorId('Mage Hand'));
  });

  it('never returns a bare prefix, even for a nameless entry', () => {
    // '' would make every such entry share the id `entry-`, and the browser would scroll to
    // whichever it found first — a wrong destination is worse than no destination.
    expect(entryAnchorId('!!!')).toBe('entry-unnamed');
    expect(entryAnchorId('')).toBe('entry-unnamed');
  });

  it('cannot collide with a section id', () => {
    // A `weapons` section and an entry named "Weapons" would otherwise produce the same id.
    expect(entryAnchorId('Weapons')).not.toBe('weapons');
    expect(entryAnchorId('Weapons').startsWith('entry-')).toBe(true);
  });
});

describe('every search kind resolves somewhere real', () => {
  // The kinds `librarySearch` can actually emit, read from the source rather than hand-listed —
  // a hand-kept copy is exactly what drifts when someone adds a new content type.
  const src = fs.readFileSync(path.join(process.cwd(), 'lib/dnd/library.ts'), 'utf8');
  const emitted = [...src.matchAll(/push\('([a-z-]+)'/g)].map((m) => m[1]);
  const kinds = [...new Set(emitted)];

  it('finds the kinds the search emits', () => {
    // Guards the guard: a broken regex would make every assertion below vacuously pass.
    expect(kinds.length).toBeGreaterThan(15);
    expect(kinds).toContain('condition');
    expect(kinds).toContain('feat');
  });

  it('maps every emitted kind to a section or explicitly to null', () => {
    // `sectionForKind` returns null for kinds with no section of their own (spells, which
    // SpellBrowser owns). That is a legitimate answer. What must NOT happen is a kind the map has
    // never heard of, which would also return null — indistinguishable from the deliberate case,
    // and the reason this test reads the source instead of trusting the type.
    const known = new Set<string>();
    for (const m of fs.readFileSync(path.join(process.cwd(), 'lib/dnd/library-anchors.ts'), 'utf8')
      .matchAll(/^\s+'?([a-z-]+)'?:\s*(?:'[a-z-]+'|null),$/gm)) known.add(m[1]);

    const unmapped = kinds.filter((k) => !known.has(k));
    expect(
      unmapped,
      'These kinds are emitted by librarySearch but absent from SECTION_BY_KIND, so a search hit ' +
      'of this kind links nowhere. Add them to the map (null is a valid answer, but it has to be ' +
      'a deliberate one).',
    ).toEqual([]);
  });

  it('points every mapped section at one that a real page renders', () => {
    // The other half: a section id that no page produces is a dead link just as surely as a
    // missing mapping. Checked against every system's actual rendered sections.
    const realSections = new Set<string>();
    for (const s of GAME_SYSTEMS) {
      const page = libraryPageFor(s.key);
      for (const sec of page?.sections ?? []) realSections.add(sec.id);
    }
    expect(realSections.size).toBeGreaterThan(5);

    const dangling = kinds
      .map((k) => [k, sectionForKind(k)] as const)
      .filter(([, sec]) => sec !== null && !realSections.has(sec));
    expect(
      dangling.map(([k, sec]) => `${k} → #${sec}`),
      'These kinds map to a section id that no system library page actually renders.',
    ).toEqual([]);
  });
});

describe('libraryHref always produces something navigable', () => {
  it('links to the entry anchor when it has a name', () => {
    expect(libraryHref('dnd5e-2014', 'condition', 'Prone')).toBe('/dnd/library/dnd5e-2014#entry-prone');
  });

  it('falls back to the section when there is no name', () => {
    expect(libraryHref('dnd5e-2014', 'condition')).toBe('/dnd/library/dnd5e-2014#conditions');
  });

  it('falls back to the system page for a kind with no section', () => {
    // Spells have no section by design. The link must still go somewhere useful rather than to a
    // `#spells` anchor that does not exist.
    expect(libraryHref('dnd5e-2014', 'spell', 'Fireball')).toBe('/dnd/library/dnd5e-2014');
  });

  it('never returns an empty or relative-looking href, for any kind', () => {
    // A search result that is not clickable is the bug this module exists to fix, so EVERY path
    // through it has to yield a real URL.
    for (const kind of ['condition', 'feat', 'spell', 'weapon', 'not-a-real-kind']) {
      const href = libraryHref('pathfinder2e', kind, 'Something');
      expect(href.startsWith('/dnd/library/'), `${kind} produced "${href}"`).toBe(true);
    }
  });

  it('encodes a system key that needs it', () => {
    expect(libraryHref('a b', 'condition', 'Prone')).toContain('a%20b');
  });
});
