// lib/dnd/glossary/blades.ts — Blades in the Dark terms (John Harper, Evil Hat).
//
// Blades has no levels, no hit points, no armour class, no initiative, and no turns. It is a d6
// pool game where you read only the SINGLE HIGHEST die, and where the real dials — Position and
// Effect — are set in conversation BEFORE anyone rolls. Stress is the currency; consequences are
// the pacing. Nothing below should ever be described with d20 scaffolding.
import type { SystemGlossary } from './types';

export const BLADES_GLOSSARY: SystemGlossary = [
  // ── Core resolution ──────────────────────────────────────────────────────────────────────
  {
    term: 'Action Roll',
    kind: 'mechanic',
    short: 'Roll d6 equal to your action rating and read only the HIGHEST die: 6 succeeds, 4–5 succeeds with a consequence, 1–3 fails.',
    body: 'The engine of the game. When you do something risky, you and the GM name the **action** you are using, the GM sets **position** and **effect**, and you roll a pool of **d6 equal to your action rating**.\n\nRead **only the single highest die**. Dice are **never added together**:\n\n· **6** — full success. You do it.\n· **4–5** — success **with a consequence**. You do it, but something bites.\n· **1–3** — **failure**. Things go badly; you suffer a consequence and usually don\'t get what you wanted.\n· **two or more 6s** — **critical**. You do it with **increased effect**.\n\nWith a rating of **0 dots**, you still roll: **2d6 and take the LOWEST**. You never can\'t try — you just try badly.\n\nNote what is missing: no target number, no DC, no modifier added to the roll. The difficulty is never in the number you need — it lives entirely in **position** (how bad the consequence will be) and **effect** (how much you accomplish). A desperate 6 and a controlled 6 are both "6".\n\nBefore rolling you can change the pool: **push yourself** (+1d for 2 stress), accept a **Devil\'s Bargain** (+1d), or take an **assist** (+1d).',
    seeAlso: ['Position', 'Effect', 'Action Rating', 'Push Yourself', 'Devil\'s Bargain', 'Assist', 'Consequence'],
    aliases: ['roll', 'action', 'd6 pool', 'dice pool', 'core roll'],
  },
  {
    term: 'Action Rating',
    kind: 'term',
    short: 'The 0–4 dots in a given action; the dot count IS the number of d6 you roll.',
    body: 'Each of the **12 actions** has an **action rating** from **0 to 4 dots**. The rating is not a bonus — it **is your dice pool**. Skirmish 3 means you roll **3d6** when you Skirmish.\n\nAt character creation you get **1 dot** from your playbook\'s starting action, then distribute **4 more dots**, with a **maximum of 2 dots in any single action** at creation. Ratings go up to **4** in play, bought with **XP** from your attribute tracks.\n\nA **0-dot** action is not "untrained, you can\'t" — it is **roll 2d6 and take the lowest**, roughly a 3-in-4 chance of trouble. You can always attempt anything.\n\nAction ratings also feed your **attributes**: your **Insight**, **Prowess** and **Resolve** ratings are simply *how many actions in that group have at least one dot*. That is the only thing attributes are for — sizing **resistance rolls**.',
    seeAlso: ['Action Roll', 'Insight', 'Prowess', 'Resolve', 'Advancement'],
    aliases: ['dots', 'rating', 'action dots', 'skill'],
  },
  {
    term: 'Position',
    kind: 'mechanic',
    short: 'How exposed you are — controlled, risky, or desperate — set before the roll; it decides how bad the consequences are.',
    body: '**Position** is the GM\'s answer to "how much trouble am I in if this goes wrong?" It is declared **before** the roll and it never changes the dice — only what happens next.\n\n· **Controlled** — you act from advantage. Consequences are **minor**, and on a 1–3 you get a chance to **withdraw** rather than eat the worst of it. This is the position for acting on your terms.\n· **Risky** — the default. You are going toe to toe with a real problem. Consequences are **standard**: harm, complications, lost opportunity.\n· **Desperate** — you are overreaching. Consequences are **severe**, and desperate rolls are how people die. On the upside, a desperate roll **marks XP** in that action\'s attribute.\n\nPosition is negotiated in fiction, not calculated. Sneaking up on a distracted guard is controlled; the same move in an open hall is risky; doing it while already bleeding and spotted is desperate.\n\nYou can improve position by taking a **setup action**, by spending **downtime** on preparation, or via a **flashback** — and you can **resist** a consequence after the fact to soften what actually lands.\n\nThe golden pairing: the GM sets position and effect **together**, and the player may always ask for both before deciding to roll.',
    seeAlso: ['Effect', 'Action Roll', 'Consequence', 'Resistance Roll', 'Setup Action'],
    aliases: ['controlled', 'risky', 'desperate', 'positions'],
  },
  {
    term: 'Effect',
    kind: 'mechanic',
    short: 'How much you accomplish on a success — limited, standard, or great — set before the roll alongside position.',
    body: '**Effect** is the other half of the frame: *if you succeed, how much do you get?* Also declared **before** the roll.\n\n· **Limited** — a partial result. One segment on a clock, reduced harm, a foot in the door.\n· **Standard** — what you were going for.\n· **Great** — more than you asked. Extra clock segments, greater harm, a lasting advantage.\n\nThe GM judges effect from three factors:\n\n· **Potency** — do you have the right tool, the leverage, the specialist knowledge?\n· **Scale** — how many of them, how big a space, how large the operation?\n· **Quality / Tier** — how does your gear and crew rank against theirs?\n\nA **critical** bumps effect **up one level** above what was set. **Push yourself** (2 stress) can also buy **+1 effect** instead of +1 die — often the better deal, since it improves the *result* rather than the odds.\n\nThe trade that experienced players make constantly: accept **reduced effect** for **better position**, or **worse position** for **greater effect**. That negotiation is the game.',
    seeAlso: ['Position', 'Action Roll', 'Push Yourself', 'Clock', 'Tier'],
    aliases: ['limited', 'standard', 'great', 'effect level', 'effect factors'],
  },
  {
    term: 'Consequence',
    kind: 'mechanic',
    short: 'What the GM inflicts on a 1–5: harm, reduced effect, complication, lost opportunity, or worse position.',
    body: 'On a **4–5** you succeed *and* take a consequence. On a **1–3** you take a consequence and usually don\'t succeed. The GM chooses from:\n\n· **Reduced effect** — you did it, but less of it.\n· **Complication** — a new problem; often a **clock** ticking up.\n· **Lost opportunity** — the window closes; that approach is spent.\n· **Worse position** — you may try again, but from **risky** instead of controlled, or **desperate** instead of risky.\n· **Harm** — a level of harm on your tracker.\n\nSeverity follows **position**: minor in controlled, standard in risky, severe in desperate. The GM may inflict **more than one** consequence in a bad spot.\n\nCrucially, you get a say **after** they land: you may make a **resistance roll** to reduce or entirely avoid any consequence, paying stress for it. Or spend an **armour** box, if it applies.\n\nThe rhythm — GM states the consequence, player decides whether to resist — is what keeps failure from being a dead end.',
    seeAlso: ['Position', 'Resistance Roll', 'Harm', 'Armour', 'Clock'],
    aliases: ['consequences', 'complication', 'bad outcome'],
  },
  {
    term: 'Resistance Roll',
    kind: 'mechanic',
    short: 'Roll your attribute after a consequence lands: take 6 minus your highest die in stress, and reduce or avoid it.',
    body: 'The player-side lever on every bad outcome. When a consequence lands, you may **resist** it: pick the relevant **attribute** (Insight, Prowess, or Resolve), roll **that many d6**, and read the **highest** die.\n\n· **Stress cost = 6 minus your highest die.**\n· Highest die **6** → **0 stress**. Free.\n· Highest die **4** → **2 stress**.\n· Highest die **1** → **5 stress**. Brutal.\n· **Critical** (two or more 6s) → you **clear 1 stress** instead of taking any.\n· Attribute rating **0** → roll **2d6, take the lowest**.\n\nThe GM then either **reduces** the consequence (severe harm becomes moderate, desperate stays risky) or **removes it entirely** — the GM decides which, based on the fiction.\n\nWhich attribute? It follows what you\'re resisting *with*: **Prowess** for physical harm and force, **Insight** for tricks, deceptions and mistakes, **Resolve** for fear, coercion and the supernatural.\n\nThis is why Blades has no HP: you never "have" defence, you **buy** it, one consequence at a time, from a 9-box stress track. And resisting is almost always correct — right up until the stress kills you.',
    seeAlso: ['Stress', 'Consequence', 'Insight', 'Prowess', 'Resolve', 'Trauma', 'Armour'],
    aliases: ['resist', 'resistance', 'resist roll'],
  },
  {
    term: 'Devil\'s Bargain',
    kind: 'mechanic',
    short: '+1d offered by the GM or another player in exchange for a complication that happens whether you succeed or not.',
    body: 'Before an action roll, the GM (or any player) may offer a **Devil\'s Bargain**: take **+1 die** in exchange for a specific cost. You may **decline** it — it is an offer, not a ruling.\n\nThe defining feature: **the bargain happens regardless of the roll**. A 6 does not save you from it. That is what separates it from a consequence.\n\nGood bargains include:\n\n· Sacrifice **coin** or an item\n· Betray or **compromise a friend or contact**\n· Offend or provoke a **faction**\n· Start or **tick up a clock** you didn\'t want\n· Take **1 stress**, or take **harm**\n· Accept **reduced effect**\n\nThe bargain must be **concrete and immediate** — "something bad happens later" is not a bargain. And it should never be a straight tax; a bargain that only costs stress is just a worse version of pushing yourself.\n\nA Devil\'s Bargain **stacks** with pushing yourself and with an assist: +1d each, up to a pool of any size. The temptation to stack them all is exactly the trap the game is built around.',
    seeAlso: ['Action Roll', 'Push Yourself', 'Assist', 'Consequence'],
    aliases: ['devils bargain', 'bargain', 'devil bargain'],
  },
  {
    term: 'Push Yourself',
    kind: 'mechanic',
    short: 'Spend 2 stress for +1d, OR +1 effect level, OR an extraordinary feat of your attribute.',
    body: 'Pay **2 stress** to get **one** of these on an action roll:\n\n· **+1 die** to the pool\n· **+1 effect level** (limited → standard → great)\n· **Perform an extraordinary feat** — something at the edge of human capability, appropriate to the attribute\n\nYou choose **one**, not all three, and you may only push **once per roll**.\n\nThe experienced-player note: **+1 effect is usually the stronger buy**. An extra die improves your odds a little; an extra effect level improves your *result*, and it applies on the 4–5 you were probably going to get anyway.\n\nPushing **stacks** with a **Devil\'s Bargain** (+1d) and an **assist** (+1d), so a determined character can turn a 2d roll into 5d — at the cost of 2 stress, a complication, and an ally\'s stress.\n\nStress is not free health. Nine boxes and you take **trauma**. Push when it matters.',
    seeAlso: ['Stress', 'Effect', 'Action Roll', 'Devil\'s Bargain', 'Assist', 'Trauma'],
    aliases: ['push', 'pushing', 'push for effect'],
  },
  {
    term: 'Assist',
    kind: 'action',
    short: 'Take 1 stress to give an ally +1d — but you are now exposed to the consequences too.',
    body: 'Another PC is rolling. You describe how you help, take **1 stress**, and they get **+1 die**.\n\nThe catch is fictional and it is real: by helping, **you are now in the scene and exposed to the consequences**. If the roll goes wrong, the GM can put the harm, the complication or the blame on you instead of — or as well as — the roller.\n\nOnly **one assist per roll per helper**, but **multiple characters may each assist**, each for 1 stress and +1d.\n\nAn assist needs a **concrete fictional action**: "I brace the door", "I call out the guard\'s position", "I keep the mark talking". Cheerleading is not an assist.\n\nCompare a **setup action**, which is a roll of your own that improves the ally\'s **position or effect** instead of handing them a die. Setups are stronger and slower; assists are instant and cheap.',
    seeAlso: ['Action Roll', 'Setup Action', 'Stress', 'Group Action'],
    aliases: ['assisting', 'help', 'aid'],
  },
  {
    term: 'Setup Action',
    kind: 'action',
    short: 'Roll an action of your own to improve a teammate\'s position OR effect on their following roll.',
    body: 'A **setup action** is your own **action roll**, made to prepare the ground for someone else. Distract the guard, pick the lock ahead of the runner, sway the target into a receptive mood.\n\nOn a **success**, the teammate\'s next roll gets **+1 position** *or* **+1 effect** — you pick which when you set it up.\n\nOn a **4–5** you still get it, plus a consequence. On a **1–3** the setup fails and things get worse.\n\nSetups are **more powerful than assists** because a position or effect bump changes the outcome, not the odds — but they **cost you a roll**, expose you to your own consequences, and must come **before** the ally acts.\n\nSetups **chain**: one PC sets up another, who sets up a third. A well-built chain can take a desperate/limited job and turn it into a controlled/great one, which is what a good crew looks like when it is working.',
    seeAlso: ['Assist', 'Position', 'Effect', 'Action Roll', 'Group Action'],
    aliases: ['setup', 'set up', 'setup roll'],
  },
  {
    term: 'Group Action',
    kind: 'mechanic',
    short: 'Everyone rolls the same action; use the single best result, and the leader takes 1 stress per failed roll.',
    body: 'When the whole crew does the same thing at once — everyone sneaks past, everyone climbs the wall, everyone holds their nerve — one PC **leads** the group action.\n\n· **Everyone rolls** the same action.\n· The **single best result** counts for the entire group.\n· The **leader takes 1 stress for each roll that failed (1–3)**.\n\nThat stress is the price of coordinating a crew of criminals, and it scales viciously: a five-person group action with three failures costs the leader **3 stress**, a third of their track, before anything has even gone wrong.\n\nEveryone shares the outcome — if the best roll was a 4–5, the **whole group** succeeds with the consequence.\n\nUse group actions when the fiction genuinely requires everyone to do the thing. If one person can do it while others help, that is an **assist** and it is cheaper.',
    seeAlso: ['Action Roll', 'Assist', 'Stress', 'Setup Action'],
    aliases: ['group roll', 'group', 'lead a group action'],
  },
  {
    term: 'Fortune Roll',
    kind: 'mechanic',
    short: 'A dice roll for a question nobody is acting on — the GM rolls to see how the uncertain world resolves.',
    body: 'A **fortune roll** answers an uncertain question when **no PC is taking an action**. How much does the fence pay? Does the rival gang notice? How far does the fire spread? Is the contact still alive?\n\nThe GM builds a pool from whatever factors apply (a faction\'s **tier**, a relevant rating, the sheer odds), rolls, and reads the highest die on the usual ladder:\n\n· **6** — a **good** result / full measure\n· **4–5** — a **mixed** result / partial measure\n· **1–3** — a **poor** result / little or nothing\n· **critical** — a **great** result\n\nBecause nobody acted, there is **no position, no effect, no stress, and nothing to resist**. It is not an action roll and it never marks XP.\n\nFortune rolls also do bookkeeping: they resolve **downtime activities**, size up **clock** progress off-screen, and answer "what does the world do while you\'re not looking".',
    seeAlso: ['Action Roll', 'Clock', 'Downtime', 'Tier'],
    aliases: ['fortune', 'fortune dice', 'gm roll'],
  },
  {
    term: 'Clock',
    kind: 'mechanic',
    short: 'A circle divided into 4, 6, or 8 segments that tracks progress or looming danger; successes fill segments by effect level.',
    body: 'A **progress clock** is how Blades measures anything that takes more than one roll. Draw a circle, divide it into **4, 6, or 8 segments**, and name it.\n\nFill segments on a success, sized by **effect**:\n\n· **Limited effect** — 1 segment\n· **Standard effect** — 2 segments\n· **Great effect** — 3 segments\n\nWhen it fills, the thing happens. Clock sizes signal scope: **4** is a short obstacle, **6** a real task, **8** a serious undertaking.\n\nThe varieties you\'ll actually use:\n\n· **Danger clocks** — the alarm is raised, the ritual completes, the Bluecoats arrive. These tick up on your **consequences**.\n· **Racing clocks** — two clocks side by side, yours and theirs. Whoever fills first wins.\n· **Linked clocks** — filling one starts or unlocks another.\n· **Long-term project clocks** — usually 8+ segments, filled during **downtime**.\n· **Healing clock** — filled by the **Recover** downtime activity.\n\nClocks should be **visible on the table**. A hidden clock is just the GM deciding; a visible one is pressure the players can feel and plan around.',
    seeAlso: ['Effect', 'Consequence', 'Long-Term Project', 'Downtime', 'Recover'],
    aliases: ['clocks', 'progress clock', 'danger clock', 'countdown'],
  },

  // ── Stress, harm, and the body ───────────────────────────────────────────────────────────
  {
    term: 'Stress',
    kind: 'mechanic',
    short: 'A 9-box track you spend to push, assist, flashback and resist; fill all 9 and you take Trauma.',
    body: '**Stress** is the central currency of Blades. Every PC has a **9-box** track and spends from it constantly:\n\n· **Push yourself** — **2 stress** for +1d, +1 effect, or an extraordinary feat\n· **Assist** an ally — **1 stress** for +1d\n· **Resistance roll** — **6 minus your highest die**, so **0–5 stress**\n· **Flashback** — **0, 1, or 2+ stress** depending on how much it stretches\n\nWhen you **mark the 9th box**, you take **Trauma**: choose a trauma condition, **clear your entire stress track**, and carry the scar permanently. Any excess stress from that moment is lost, not carried over.\n\nClear stress in **downtime** by **indulging your vice** — roll your **lowest attribute rating**, clear stress equal to the highest die.\n\nStress is *not* hit points. It is not damage taken; it is effort spent. A character with 8 stress is not bleeding — they are strung out, running on nerve, one hard choice from breaking. That distinction drives every table decision in the last hour of a score.',
    seeAlso: ['Trauma', 'Push Yourself', 'Assist', 'Resistance Roll', 'Flashback', 'Vice', 'Indulge Vice'],
    aliases: ['stress track', 'stress boxes', 'stressed'],
  },
  {
    term: 'Trauma',
    kind: 'condition',
    short: 'Taken when you fill 9 stress: a permanent scar, chosen from eight. Four traumas and the character retires.',
    body: 'Fill the **9th stress box** and you take **trauma**. Choose one of the eight conditions, **clear all stress**, and mark it on your sheet. It is **permanent** — trauma never heals.\n\nThe list:\n\n· **Cold** — you are not moved by emotional appeals or social bonds\n· **Haunted** — you are obsessed with the spirit world, secrets, and the misfortune of others\n· **Obsessed** — you are single-minded about a target, activity, or fixation\n· **Paranoid** — you imagine danger everywhere; you can\'t trust others\n· **Reckless** — you have little regard for your own safety or that of others\n· **Soft** — you lose your edge; you become sentimental and passive\n· **Unstable** — your emotional state is volatile; you can instantly rage, or fall into despair, or freeze\n· **Vicious** — you seek out opportunities to hurt people, even for no reason\n\nWhen a trauma is relevant, you must **play it** — it takes the wheel. Playing your trauma is also an **XP trigger**.\n\nAt **4 traumas**, the character is **retired**: they are done, permanently, and you make a new PC. Retirement is not death; it is a broken person leaving Doskvol, which is often worse.\n\nThe warning that matters: **resisting is how you die**. Not from harm — from stress.',
    seeAlso: ['Stress', 'Resistance Roll', 'Advancement', 'Vice'],
    aliases: ['traumas', 'traumatized', 'cold', 'haunted', 'obsessed', 'paranoid', 'reckless', 'soft', 'unstable', 'vicious'],
  },
  {
    term: 'Harm',
    kind: 'condition',
    short: 'Injury written as words on a 4-level tracker, not numbers: less effect, −1d, need help, then fatal.',
    body: '**Harm** is never a number. You **write what happened** on your harm tracker at the level the GM assigns, and the level tells you what it costs:\n\n· **Level 1 — Lesser** (two boxes): **reduced effect** on relevant actions. *"Battered", "Drained", "Distracted".*\n· **Level 2 — Moderate** (two boxes): **−1d** to relevant rolls. *"Broken Arm", "Deep Cut", "Terrified".*\n· **Level 3 — Severe** (one box): you **need help** to act at all in that area. *"Impaled", "Shattered Leg".*\n· **Level 4 — Fatal**: you are **dead or permanently taken out** unless you **resist**.\n\nHarm only applies **when it is relevant** — a "Broken Arm" doesn\'t penalise your Sway. That is the whole reason harm is words instead of hit points.\n\n**If a level\'s boxes are full**, new harm at that level **moves up a level instead**. Two Lesser harms and a third one arriving means you now have a **Moderate**. This is how a character dies from a thousand cuts.\n\nBefore harm is written, you may **resist** it (paying stress) to reduce it a level or avoid it, or check an **armour** box if it applies. Once written, it comes off only through the **Recover** downtime activity and a **healing clock**.',
    seeAlso: ['Resistance Roll', 'Armour', 'Recover', 'Healing Clock', 'Consequence'],
    aliases: ['injury', 'wounds', 'lesser harm', 'moderate harm', 'severe harm', 'fatal harm', 'damage'],
  },
  {
    term: 'Armour',
    kind: 'term',
    short: 'Checkable boxes on your sheet that reduce harm or negate a consequence for free — this is not armour class.',
    body: '**Armour** in Blades is not a defence number and it is emphatically **not AC** — it never affects a roll. It is a **box you tick** to make a consequence go away without paying stress.\n\n· **Armour** — check the box to **reduce harm by one level** or **avoid a consequence** entirely, in place of a resistance roll.\n· **Heavy armour** — a second box, from taking heavy gear; same use, but heavy armour also carries a **load** cost and makes you conspicuous.\n· **Special armour** — granted by specific playbook **special abilities**, and usable only for what that ability describes.\n\nArmour must be **carried** — you tick armour on your **load** at the start of a score, and armour you didn\'t take is armour you don\'t have.\n\nUsed armour boxes **refresh during downtime**, not during the score. So armour is one free "no" per job, not a standing bonus.\n\nThe decision it creates is sharp: use the armour box on this moderate harm now, or save it for something worse later and pay stress instead?',
    seeAlso: ['Harm', 'Resistance Roll', 'Load', 'Downtime'],
    aliases: ['armor', 'heavy armour', 'special armour', 'armor box'],
  },
  {
    term: 'Healing Clock',
    kind: 'mechanic',
    short: 'A 4-segment clock filled by the Recover downtime activity; when it completes, every harm drops one level.',
    body: 'The **healing clock** is a **4-segment** clock, one per character, that tracks convalescence.\n\nYou fill it with the **Recover** downtime activity. When it **fills**, **reduce the level of each harm on your tracker by one** — and then **reset the clock to empty**. Level 1 harms are erased.\n\nNote the wording carefully: it heals **every** harm by one level, not one harm entirely. A character carrying a Moderate and two Lessers who fills the clock comes out with one Lesser and two blanks. This is why letting harm pile up before healing is efficient, and why nobody does it, because harm hurts.\n\nSegments come from the **Recover** roll — a Physicker\'s treatment, a doctor, or your own crew\'s facilities. Higher **tier** care and better rolls fill more.\n\nIt is the **only** route out of harm. There is no "long rest", no healing spell, no potion. You go home and you get better slowly, and the clock is the game telling you how slowly.',
    seeAlso: ['Recover', 'Harm', 'Clock', 'Downtime'],
    aliases: ['healing', 'heal clock', 'recovery clock'],
  },

  // ── Attributes and the twelve actions ────────────────────────────────────────────────────
  {
    term: 'Insight',
    kind: 'stat',
    short: 'The attribute of perception and cleverness — Hunt, Study, Survey, Tinker. Its rating is how many of those have a dot.',
    body: '**Insight** is one of three attributes, and it is **not a score you buy**. Its rating is simply **how many of its four actions have at least one dot**. Hunt 2, Study 1, Survey 0, Tinker 1 gives you **Insight 3**.\n\nThe four Insight actions:\n\n· **Hunt** — carefully track a target, or make a precise ranged attack\n· **Study** — scrutinise details and interpret evidence\n· **Survey** — observe a situation and anticipate what happens next\n· **Tinker** — fiddle with mechanisms and devices\n\nAttributes are used for **exactly one thing**: sizing your **resistance roll** pool. Resist with Insight when you are resisting the consequences of a **mistake, a deception, or missing something** — the ambush you didn\'t spot, the forged papers you believed, the trap you failed to notice.\n\nInsight is also an **XP track** (6 boxes): mark XP in it when you roll a **desperate** Insight action, and fill it to buy a new action dot.',
    seeAlso: ['Prowess', 'Resolve', 'Resistance Roll', 'Action Rating', 'Advancement'],
    aliases: ['insight attribute'],
  },
  {
    term: 'Prowess',
    kind: 'stat',
    short: 'The attribute of physicality — Finesse, Prowl, Skirmish, Wreck. Its rating is how many of those have a dot.',
    body: '**Prowess** rates your body. Like all attributes, its rating is **the count of its actions with at least one dot** — nothing is bought directly.\n\nThe four Prowess actions:\n\n· **Finesse** — dexterous manipulation, sleight of hand, subtle misdirection, or deft vehicle handling\n· **Prowl** — move with speed and stealth, or make a sneak attack\n· **Skirmish** — entangle a target in close combat so they can\'t escape\n· **Wreck** — unleash savage force to smash, break, and destroy\n\nResist with Prowess when the consequence is **physical**: harm from a blade, a fall, exhaustion, being grabbed. This is the most-rolled resistance in a violent crew, which is why Cutters and Lurks take Prowess dots early.\n\nProwess is a **6-box XP track**. Mark XP when you roll a **desperate** Prowess action; fill the track to buy a new action dot.',
    seeAlso: ['Insight', 'Resolve', 'Resistance Roll', 'Harm', 'Action Rating'],
    aliases: ['prowess attribute'],
  },
  {
    term: 'Resolve',
    kind: 'stat',
    short: 'The attribute of will and presence — Attune, Command, Consort, Sway. Its rating is how many of those have a dot.',
    body: '**Resolve** rates your will and your social force. Its rating, again, is **the number of its actions with at least one dot**.\n\nThe four Resolve actions:\n\n· **Attune** — open your mind to the ghost field, commune with electroplasmic vibrations, and channel spirits\n· **Command** — compel swift obedience through force of personality\n· **Consort** — socialise with friends and contacts to get what you need\n· **Sway** — influence with guile, charm, or logical argument\n\nResist with Resolve against **fear, coercion, deception of the will, and the supernatural** — a spirit clawing at your mind, a rival\'s intimidation, a lie you desperately want to believe.\n\nResolve resistance is the one most crews underinvest in, right up until the first ghost. Whispers live here.\n\nA **6-box XP track**, marked on **desperate** Resolve rolls, filled to buy an action dot.',
    seeAlso: ['Insight', 'Prowess', 'Resistance Roll', 'Action Rating', 'Whisper'],
    aliases: ['resolve attribute'],
  },
  {
    term: 'Hunt',
    kind: 'action',
    short: 'Insight: carefully track a target, or take a precise ranged shot.',
    body: '**Hunt** (Insight) covers both halves of the predator\'s job: **tracking a target** with patience and care, and **hitting it at range** with precision.\n\nUse it to follow someone through Doskvol\'s streets, to stake out a location and know where the mark will be, to read a trail, and to **shoot accurately** — a pistol, a rifle, a thrown knife with intent.\n\nThe distinction that comes up: **Hunt is precise ranged violence; Skirmish is close and messy; Prowl is a sneak attack from hiding**. If you are shooting carefully at a target you have picked out, that is Hunt.\n\nEffect on a Hunt shot is judged by scale and potency like anything else — a single pistol against an armoured heavy is limited effect, no matter how good your dots are.',
    seeAlso: ['Insight', 'Study', 'Survey', 'Tinker', 'Skirmish', 'Prowl'],
    aliases: ['hunting', 'track', 'shoot', 'sniping'],
  },
  {
    term: 'Study',
    kind: 'action',
    short: 'Insight: scrutinise details and interpret evidence.',
    body: '**Study** (Insight) is the scholar\'s action: **examine something closely and understand it**.\n\nRead a document, decipher a code, examine a corpse, research a family\'s history in the archives, work out how a ritual is supposed to function, recall what you know about a noble house.\n\n**Study vs Survey** is the pairing people confuse: Study is **deep and slow** — you\'re digging into a specific thing. Survey is **broad and fast** — you\'re taking in a whole situation at a glance. Reading the ledger is Study; noticing that the room has three exits and a nervous clerk is Survey.\n\nStudy is the backbone of **Long-Term Projects** involving research, and it is the action most likely to be rolled from a **controlled** position — libraries rarely stab you.',
    seeAlso: ['Insight', 'Hunt', 'Survey', 'Tinker', 'Long-Term Project'],
    aliases: ['studying', 'research', 'examine', 'investigate'],
  },
  {
    term: 'Survey',
    kind: 'action',
    short: 'Insight: observe a situation and anticipate what happens next.',
    body: '**Survey** (Insight) is situational awareness: **look at what\'s in front of you and read it**.\n\nSpot the tell on a liar, find the weak point in a patrol route, notice the exits, sense the mood of a crowd turning, guess where a rival will strike, catch the moment a deal is about to go wrong.\n\nSurvey is the **prep action** par excellence — a successful Survey is the classic **setup action**, converting into +1 position or +1 effect for whoever moves next.\n\nIt also pairs naturally with the GM\'s job of framing scenes: a player who Surveys is asking "tell me what I can use here", which is usually the most productive question in a score.\n\nCompare **Study** (deep, on one thing) and **Attune** (reading the *ghost field* rather than the physical world).',
    seeAlso: ['Insight', 'Study', 'Hunt', 'Setup Action', 'Attune'],
    aliases: ['surveying', 'observe', 'perception', 'notice', 'scout'],
  },
  {
    term: 'Tinker',
    kind: 'action',
    short: 'Insight: fiddle with mechanisms, devices, and the arcane machinery of Doskvol.',
    body: '**Tinker** (Insight) is hands-on technical work: **make, break, and manipulate devices**.\n\nPick a lock, disarm a trap, rewire a spark-craft engine, repair a broken mechanism, jury-rig something out of parts, work with alchemicals and electroplasmic gear.\n\n**Tinker vs Wreck** is the question of subtlety: Tinker **opens the lock**, Wreck **breaks the door**. Both get you inside; only one leaves evidence and noise. Choose based on the **effect** you want and the **heat** you can afford.\n\nTinker is the Leech\'s home action and the source of most **Long-Term Projects** that produce a gadget, a formula, or an alchemical.\n\nAt the table, the classic Tinker consequence is not failure but **complication**: the lock opens, and it took long enough that a clock ticked.',
    seeAlso: ['Insight', 'Study', 'Wreck', 'Leech', 'Long-Term Project'],
    aliases: ['tinkering', 'lockpick', 'repair', 'devices'],
  },
  {
    term: 'Finesse',
    kind: 'action',
    short: 'Prowess: dexterous manipulation, sleight of hand, subtle misdirection, or deft vehicle handling.',
    body: '**Finesse** (Prowess) is precision of the body: **do something delicate, quick, and unnoticed**.\n\nPick a pocket, plant an item, palm a card, slip a knife between ribs from a stance nobody read, drive a carriage through a gap that shouldn\'t fit, ride, dodge through a crowd.\n\n**Finesse vs Prowl**: Prowl is **moving unseen**; Finesse is **acting unnoticed while in plain view**. Sneaking down the alley is Prowl. Lifting the merchant\'s purse while chatting to him is Finesse.\n\n**Finesse vs Wreck**: force versus grace on the same problem — Finesse threads the needle, Wreck tears the cloth.\n\nFinesse also covers **vehicle handling** with style, which makes it the getaway action when the getaway is elegant rather than violent.',
    seeAlso: ['Prowess', 'Prowl', 'Skirmish', 'Wreck'],
    aliases: ['finessing', 'sleight of hand', 'pickpocket', 'drive'],
  },
  {
    term: 'Prowl',
    kind: 'action',
    short: 'Prowess: move with speed and stealth, or strike from hiding.',
    body: '**Prowl** (Prowess) is **moving unseen and unheard** — and, when it pays off, **attacking from concealment**.\n\nClimb the wall, cross the rooftops, slip past patrols, tail someone through the fog, hide, and strike before they know you\'re there.\n\nThe **sneak attack** clause matters: a strike made from hiding is a **Prowl** roll, not a Skirmish, and it usually comes with better **position** and **effect** because they never saw you.\n\nProwl is the action most affected by **load** — a Lurk running **light** (3 items) prowls at full effect; someone in heavy armour hauling **heavy load** (6) is going to hear about it in reduced effect and worse position.\n\nThe Lurk\'s signature, and the single most useful action on a stealth plan.',
    seeAlso: ['Prowess', 'Finesse', 'Skirmish', 'Load', 'Lurk'],
    aliases: ['prowling', 'sneak', 'stealth', 'hide', 'climb'],
  },
  {
    term: 'Skirmish',
    kind: 'action',
    short: 'Prowess: entangle a target in close combat so they cannot escape you.',
    body: '**Skirmish** (Prowess) is **close, committed violence**: you engage someone at melee range and **tie them up so they cannot disengage**.\n\nThat wording is deliberate. Skirmish isn\'t "I attack" — it is "I am **on** you now". It covers brawling, blades, and holding a line against several opponents at once.\n\n· **Skirmish vs Hunt** — Hunt is precise and ranged; Skirmish is close and messy.\n· **Skirmish vs Wreck** — Wreck destroys objects and structures; Skirmish fights people.\n· **Skirmish vs Prowl** — a strike from hiding is Prowl; a stand-up fight is Skirmish.\n\n**Scale is the effect killer here.** One Cutter skirmishing six Bluecoats has **limited effect** no matter how many dots they have — that is what special abilities like *Not to be Trifled With* exist to fix.\n\nThe Cutter\'s signature action, and the fastest way to turn a risky score into a desperate one.',
    seeAlso: ['Prowess', 'Wreck', 'Hunt', 'Prowl', 'Cutter', 'Effect'],
    aliases: ['skirmishing', 'melee', 'fight', 'brawl', 'combat'],
  },
  {
    term: 'Wreck',
    kind: 'action',
    short: 'Prowess: unleash savage force to smash, break, and destroy.',
    body: '**Wreck** (Prowess) is **destruction**: break the door, smash the case, set the fire, blow the wall, sabotage the machine, ruin the shipment.\n\nIt is aimed at **objects and structures**, not people — fighting a person is **Skirmish**. Wrecking the floor they\'re standing on is Wreck, and is often the better play.\n\n**Wreck vs Tinker**: same doors, different philosophy. Tinker is quiet, slow, and leaves the lock working. Wreck is fast, loud, and generates **heat**. The GM should price that in: Wreck usually means a **danger clock** starts ticking.\n\nWreck also handles demolitions and arson, which makes it the Leech\'s violent cousin and the Cutter\'s answer to any problem that can\'t hit back.\n\nGreat effect on a Wreck is genuinely enormous — the whole point of the action is that a good roll removes the obstacle permanently.',
    seeAlso: ['Prowess', 'Skirmish', 'Tinker', 'Heat', 'Clock'],
    aliases: ['wrecking', 'smash', 'break', 'destroy', 'demolition'],
  },
  {
    term: 'Attune',
    kind: 'action',
    short: 'Resolve: open your mind to the ghost field, commune with spirits, and channel electroplasmic forces.',
    body: '**Attune** (Resolve) is the supernatural action: **open your mind to the ghost field** — the electroplasmic layer that suffuses Doskvol and everything in it.\n\nUse it to sense spirits, perceive the ghost field, commune with the dead, channel arcane power, work a demon\'s or a spirit\'s influence, feel the resonance in a haunted place, and use arcane implements.\n\nIt is the **most dangerous action in the game to roll**, and the game says so: attuning routinely puts you in **desperate** position because what\'s on the other side notices you back. Consequences from Attune tend to be resisted with **Resolve**, and they tend to be permanent.\n\nThe Whisper\'s home action. Also the reason a crew with **no** Attune dots simply cannot engage with half of Doskvol\'s content — and often the reason they survive longer.',
    seeAlso: ['Resolve', 'Command', 'Consort', 'Sway', 'Whisper', 'Position'],
    aliases: ['attuning', 'ghost field', 'spirits', 'magic', 'arcane'],
  },
  {
    term: 'Command',
    kind: 'action',
    short: 'Resolve: compel swift obedience through force of personality.',
    body: '**Command** (Resolve) is **making people do what you say, now**. Intimidate, order, rally, lead, threaten, take charge of a room.\n\nIt covers commanding your own gang and cowing someone else\'s. The emphasis is on **swift** — Command is the action for immediate compliance, not for building a relationship.\n\n· **Command vs Sway** — Command is force of will and threat; Sway is charm, guile, and argument. "Get on the ground" is Command. "Let\'s talk about what this could be worth to you" is Sway.\n· **Command vs Consort** — Consort is warm and social among people who already know you; Command needs no relationship at all.\n\nCommand tends to work and cost. It gets obedience and buys resentment, and the GM is entitled to make the **consequence** exactly that.\n\nThe Cutter\'s and Spider\'s tool for running a gang.',
    seeAlso: ['Resolve', 'Sway', 'Consort', 'Attune', 'Cutter'],
    aliases: ['commanding', 'intimidate', 'order', 'lead'],
  },
  {
    term: 'Consort',
    kind: 'action',
    short: 'Resolve: socialise with friends and contacts to get what you need.',
    body: '**Consort** (Resolve) is **working your network**: spend time with friends, contacts, and allies to gather information, call in favours, find a person, get an introduction, or simply be welcome somewhere.\n\nIt is the action for the **relationship**, not the transaction. Consort assumes you have people — your playbook **friends and rivals** list, your crew\'s **contacts**, the faction you\'re on good terms with. A crew that has burned every bridge finds Consort rolls getting very hard, and that is correct.\n\n· **Consort vs Sway** — Consort works on people who already like you; Sway persuades people who don\'t.\n· **Consort vs Command** — Consort asks; Command tells.\n\nConsort is the workhorse of **downtime** and the engine of faction play. It is also how you find out what the score even is before you take it.',
    seeAlso: ['Resolve', 'Sway', 'Command', 'Downtime', 'Slide'],
    aliases: ['consorting', 'socialize', 'socialise', 'network', 'contacts'],
  },
  {
    term: 'Sway',
    kind: 'action',
    short: 'Resolve: influence someone with guile, charm, or logical argument.',
    body: '**Sway** (Resolve) is **persuasion**: lie, charm, seduce, bargain, argue, con, manipulate.\n\nIt works on people who have no reason to help you — that is the whole point. Sway is how you get past the guard without violence, how you sell a lie to a noble, how you talk a rival into a deal that is worse than they think.\n\n· **Sway vs Command** — guile versus force. Sway wants them to *want* it; Command doesn\'t care.\n· **Sway vs Consort** — Sway persuades strangers and opponents; Consort works your existing people.\n\nThe **potency** factors matter here more than most: leverage, blackmail, a genuine offer, or a good disguise all raise **effect**. Sway with nothing to offer is limited effect and it should be.\n\nThe Slide\'s signature action, and the action that most often turns a **desperate** plan into a **controlled** one before a single blade is drawn.',
    seeAlso: ['Resolve', 'Command', 'Consort', 'Slide', 'Effect'],
    aliases: ['swaying', 'persuade', 'lie', 'charm', 'deceive', 'con'],
  },

  // ── Scores ───────────────────────────────────────────────────────────────────────────────
  {
    term: 'Score',
    kind: 'mechanic',
    short: 'A job: pick the target, choose a plan type, supply one detail, roll engagement, and start in the middle of the action.',
    body: 'A **score** is one criminal operation, and it is the unit the game is built around. The sequence:\n\n1. **Choose the target** — from your crew\'s claims, a contact\'s offer, a faction\'s need.\n2. **Choose a plan type**: **Assault** (point of attack), **Deception** (the method), **Stealth** (point of infiltration), **Occult** (the arcane method), **Social** (the social connection), or **Transport** (the route).\n3. **Provide the one detail** the plan needs — and only that one. That is the entire planning phase.\n4. **Roll the engagement roll** to see what position you start in.\n5. **Cut straight to the action, in progress.**\n\nThere is **no planning session**. The game explicitly refuses it, because the alternative — **flashbacks** — lets you have "planned" anything you can afford in stress, retroactively, once you know what the problem actually is.\n\nA score ends when the job resolves. Then comes **payoff** (coin and rep from the score\'s tier and scale), **heat** (how hot it left you), **entanglements**, and **downtime**.',
    seeAlso: ['Engagement Roll', 'Flashback', 'Downtime', 'Heat', 'Coin', 'Crew'],
    aliases: ['scores', 'job', 'heist', 'plan', 'plan and detail'],
  },
  {
    term: 'Engagement Roll',
    kind: 'mechanic',
    short: 'One fortune roll that decides how the score opens: 6 starts controlled, 4–5 risky, 1–3 desperate.',
    body: 'The roll that replaces the planning session. After the crew picks a **plan type** and its **one detail**, the GM builds a pool from the situation and rolls:\n\n· **6** — you begin in a **controlled** position\n· **4–5** — you begin in a **risky** position\n· **1–3** — you begin in a **desperate** position\n· **critical** — **controlled** position with **great effect**\n\nThe pool starts at **1d** and is adjusted by the factors the table can see:\n\n· **+1d** if the plan exploits a real **weakness** in the target\n· **+1d** for a **bold** or unorthodox approach the opposition won\'t expect\n· **+1d** if a **friend or ally** is helping\n· **−1d** if the target\'s **faction tier** is higher than yours\n· **−1d** if the target has **elite or specially prepared** defences\n\nThen the GM narrates you **into the middle of the action** at that position. No approach march, no casing the joint — you\'re over the wall already, and the roll told you how well it\'s going.\n\nThis is why the "one detail" is worth thinking about: it is your only pre-score input, and it feeds directly into these modifiers.',
    seeAlso: ['Score', 'Position', 'Fortune Roll', 'Flashback', 'Tier'],
    aliases: ['engagement', 'engagement dice', 'start the score'],
  },
  {
    term: 'Flashback',
    kind: 'mechanic',
    short: 'Retroactively establish that you prepared for this: 0 stress if trivial, 1 if plausible, 2+ if it changes the score.',
    body: 'Blades\' answer to the planning session. **Mid-score**, you declare a **flashback**: cut to a scene *before* the job in which you set something up. Play it out (often a single roll), then cut back — and it is **now true**.\n\nThe GM prices it in **stress**:\n\n· **0 stress** — trivial. Of course you bribed the doorman; you always do.\n· **1 stress** — plausible but takes some doing. You made contact with the housekeeper last week.\n· **2+ stress** — a serious effort that materially changes the score. You spent three days replacing the shipment with forgeries.\n\nInside the flashback you make **real rolls** with **real consequences** — a failed flashback roll means the preparation went wrong, which is often more interesting than if it had worked.\n\nWhat flashbacks **cannot** do: undo something already resolved, or contradict established fiction. You can\'t flashback to "actually I wasn\'t shot".\n\nThis mechanic is why the game refuses to let you plan. Planning in advance means guessing; flashbacks mean **paying stress once you know what the answer needed to be**. It is strictly better and it costs the thing that kills you.',
    seeAlso: ['Score', 'Stress', 'Engagement Roll', 'Trauma'],
    aliases: ['flashbacks', 'flash back', 'retcon'],
  },
  {
    term: 'Load',
    kind: 'mechanic',
    short: 'Declare light (3), normal (5), or heavy (6) at the start of a score; then select items as you need them.',
    body: '**Load** is how Blades handles equipment without a shopping phase. At the **start of a score** you declare your load level:\n\n· **Light — 3 item boxes.** You look like a normal citizen. Best **position** for stealth and social work.\n· **Normal — 5 item boxes.** Obviously carrying something. The default.\n· **Heavy — 6 item boxes.** Openly geared for violence. Reduced effect on stealth, obvious to everyone.\n\nYou do **not** pick the items now. As the score unfolds you **mark items off the list as you use them** — "of course I brought a crowbar" — until your load is full. Heavier items (a **heavy blade**, **heavy armour**) cost **2 boxes**.\n\nThe fiction runs both ways: your load level is what people **see**. A crew running heavy through a party is going to be treated like a crew running heavy through a party, whatever they claim.\n\nItems from your **playbook** are free to select; **fine** items grant better **quality/effect**. Your **armour** boxes are part of your load — armour you didn\'t carry is armour you don\'t have.',
    seeAlso: ['Score', 'Armour', 'Prowl', 'Effect'],
    aliases: ['loadout', 'gear', 'equipment', 'light load', 'heavy load', 'items'],
  },

  // ── Downtime ─────────────────────────────────────────────────────────────────────────────
  {
    term: 'Downtime',
    kind: 'mechanic',
    short: 'The phase between scores: pay upkeep, roll entanglements, then take 2 free activities (more for coin).',
    body: '**Downtime** is the second half of the game\'s loop, and it runs in order:\n\n1. **Payoff** — take **coin** and **rep** for the score, based on its **tier and scale**.\n2. **Heat** — the crew gains heat for how loud, violent and exposed the job was. At **9 heat** your **wanted level** rises.\n3. **Entanglements** — roll to see what trouble the score dragged home.\n4. **Activities** — each PC gets **2 free downtime activities**. Extras cost **1 coin each**.\n\nThe six activities:\n\n· **Long-Term Project** — tick a project clock\n· **Recover** — fill your healing clock\n· **Reduce Heat** — cool off the crew\n· **Train** — mark XP\n· **Indulge Vice** — clear stress\n· **Acquire Asset** — get something temporarily\n\nYou may take the **same activity twice**. The perpetual squeeze: you have two slots, you are carrying 6 stress, a moderate harm, 7 heat, and a half-built project. You cannot do all of it. Choosing what to leave broken is the game.',
    seeAlso: ['Indulge Vice', 'Recover', 'Reduce Heat', 'Train', 'Long-Term Project', 'Acquire Asset', 'Entanglement', 'Heat', 'Coin'],
    aliases: ['downtime phase', 'between scores', 'activities'],
  },
  {
    term: 'Indulge Vice',
    kind: 'action',
    short: 'Clear stress equal to your highest die when rolling your LOWEST attribute rating — and risk overindulging.',
    body: 'The only reliable way to clear **stress**. Go to your **vice purveyor** and do the thing that gets you through the week.\n\n· Roll dice equal to your **lowest attribute rating** (Insight, Prowess, or Resolve — the **worst** one).\n· **Clear stress equal to the highest die.**\n\nRolling your *lowest* attribute is deliberate: the most well-rounded characters are the worst at unwinding.\n\n**Overindulgence** happens when you clear **more stress than you had marked**. You must then choose one:\n\n· **Attract Trouble** — your indulgence causes a problem the GM defines\n· **Brag About Your Exploits** — **+2 heat** for the crew\n· **Lost** — you vanish for the rest of downtime; you\'re somewhere, days later\n· **Tapped Out** — your vice purveyor is unavailable until you **Reduce Heat** or do them a favour\n\nSo a character with 1 stress who rolls a 6 clears 1 and overindulges by 5. Timing your vice is a real decision.\n\nIf you **can\'t** reach your vice, you don\'t clear stress. A Tapped Out or imprisoned character is on a very short clock to **trauma**.',
    seeAlso: ['Vice', 'Stress', 'Trauma', 'Downtime', 'Heat', 'Reduce Heat'],
    aliases: ['vice roll', 'indulge', 'clear stress', 'overindulge', 'overindulgence'],
  },
  {
    term: 'Vice',
    kind: 'term',
    short: 'The compulsion that clears your stress — and the purveyor who supplies it, who is a liability.',
    body: 'Every PC picks a **vice** at creation and a **purveyor** who supplies it. The seven:\n\n· **Faith** — devotion to a deity, order, or cause\n· **Gambling** — games of chance and risk-taking\n· **Luxury** — indulgence in expensive things\n· **Obligation** — duty to a person, family, or organisation\n· **Pleasure** — gratification, company, sensation\n· **Stupor** — drugs, drink, oblivion, electroplasmic haze\n· **Weird** — strange experiments, dangerous rites, the ghost field\n\nThe vice is **not flavour text**. It is the mechanical outlet for **stress**, so it is the thing standing between you and **trauma** — and the **purveyor** is a named NPC with their own interests, which makes your only pressure valve into a hook the GM can pull.\n\nExpressing your vice in play is also an **XP trigger** ("you struggled with issues from your vice, trauma, or need").\n\nPick a vice that gets you into trouble. A vice that never complicates anything is a wasted sheet slot.',
    seeAlso: ['Indulge Vice', 'Stress', 'Trauma', 'Advancement'],
    aliases: ['vices', 'purveyor', 'faith', 'gambling', 'luxury', 'obligation', 'pleasure', 'stupor', 'weird'],
  },
  {
    term: 'Recover',
    kind: 'action',
    short: 'A downtime activity: roll to fill segments on your healing clock and get harm off your sheet.',
    body: '**Recover** is the downtime activity that heals **harm**. Spend the activity getting treatment — from a **Physicker** in the crew, a doctor, or your crew\'s facilities — and roll to fill segments on your **healing clock**.\n\nThe roll and its size depend on who\'s treating you. A PC with the **Physicker** ability rolls their own action; a hired doctor is a **fortune roll** off their tier and quality; treating yourself is worse than either.\n\nSegments fill by result quality, like any clock. When the **4-segment healing clock fills**, **every harm on your tracker drops one level**, and the clock resets.\n\nThis is the entire healing system. There is **no rest mechanic**, no potion, no spell. A severe harm might take two or three downtimes to clear, during which it is **−1d or "need help"** on everything relevant.\n\nWhich is why **resisting** harm before it lands, or spending an **armour** box, is nearly always better than healing it after.',
    seeAlso: ['Healing Clock', 'Harm', 'Downtime', 'Resistance Roll', 'Armour', 'Leech'],
    aliases: ['recovery', 'heal', 'healing', 'physicker'],
  },
  {
    term: 'Reduce Heat',
    kind: 'action',
    short: 'A downtime activity: roll to lower the crew\'s heat by laying low, bribing, or misdirecting the law.',
    body: 'A downtime activity that **lowers the crew\'s heat**. Describe how — lay low, bribe an inspector, feed the Bluecoats a rival\'s name, destroy the evidence, let the noise die down.\n\nRoll a **fortune roll** and the crew\'s heat drops by the result quality: a poor roll shaves a little, a good roll shaves more.\n\nWhy you care: heat accumulates from every score, and at **9 heat** the crew\'s **wanted level increases by 1** and heat resets to 0. Wanted level is permanent-ish, drives worse **entanglements**, and makes every future job harder.\n\nHeat also feeds the **entanglement** roll directly — the hotter you are, the worse the trouble that finds you between scores.\n\nThis is the activity everyone skips because stress and harm are more urgent, and it is why crews spiral. Heat is the slow-moving problem that eats campaigns.',
    seeAlso: ['Heat', 'Wanted Level', 'Entanglement', 'Downtime', 'Fortune Roll'],
    aliases: ['lay low', 'cool off', 'lower heat'],
  },
  {
    term: 'Train',
    kind: 'action',
    short: 'A downtime activity: mark 1 XP on an attribute track or your playbook track.',
    body: 'Spend a downtime activity to **mark 1 XP** on a track of your choice:\n\n· An **attribute** track — **Insight**, **Prowess**, or **Resolve** (6 boxes each, buys an action dot)\n· Your **playbook** track (8 boxes, buys a special ability)\n\nYou can train **each track once per downtime**, so you can\'t dump both activities into the same one.\n\nWhich track you may train is gated by your **crew\'s upgrades** — the crew must have the relevant **training upgrade** for a given track, and with the upgrade you may mark **2 XP** instead of 1 in that area. Crews that invest in training advance visibly faster.\n\nTraining is the **guaranteed, boring** XP. The interesting XP comes from **end-of-session triggers** and from **desperate rolls** (mark XP in that action\'s attribute immediately) — but those are unreliable, and training is the floor under your progression.\n\nIt is also the activity you sacrifice first when you\'re bleeding and strung out, which is why the crews that need to improve are the ones that can\'t.',
    seeAlso: ['Advancement', 'Downtime', 'Insight', 'Prowess', 'Resolve', 'Crew'],
    aliases: ['training', 'mark xp', 'practice'],
  },
  {
    term: 'Long-Term Project',
    kind: 'action',
    short: 'A downtime activity: roll an action to tick segments on a project clock the GM sized to the ambition.',
    body: 'A **Long-Term Project** is anything too big for one downtime: researching a ritual, building a device, cultivating a contact, investigating a mystery, gathering evidence against a faction, hunting a specific person.\n\n· Describe the project; the GM sets a **clock** sized to its ambition — **4** for modest, **8** for serious, **12+** for a campaign-defining undertaking.\n· Each downtime activity spent on it is an **action roll** with an appropriate action (usually **Study**, **Tinker**, **Consort**, or **Attune**).\n· Fill segments by **effect**: limited 1, standard 2, great 3.\n\nProjects are the players\' handle on the world. A score is what the GM offers you; a project is what **you** decide the campaign is about. Want to find out who really killed your brother? That\'s an 8-clock.\n\nYou can run several at once — but each tick costs an activity, and you only get **2 per downtime** free.\n\nProject rolls can go badly. A failed Attune project roll doesn\'t just waste the activity; it can put something in the room with you.',
    seeAlso: ['Clock', 'Downtime', 'Study', 'Tinker', 'Attune', 'Consort'],
    aliases: ['project', 'projects', 'long term project', 'project clock'],
  },
  {
    term: 'Acquire Asset',
    kind: 'action',
    short: 'A downtime activity: roll your crew\'s tier to temporarily get gear, people, or access at that quality.',
    body: 'Spend a downtime activity to get hold of something you don\'t own: a boat, a set of documents, a gang of thugs for the night, access to a building, a rare alchemical.\n\n· Roll dice equal to your **crew\'s tier**.\n· The result sets the **quality** of what you get — roughly your crew\'s tier, better on a good roll, worse on a poor one.\n· You may spend **coin** to bump the quality up.\n\nThe asset is **temporary** — you have it for the score, not forever. Permanent gains are **claims**, **upgrades**, and **long-term projects**.\n\nQuality matters because it feeds **effect**: a quality-3 forged writ against a tier-2 opponent gives you good effect; a quality-1 one gives you limited effect and probably a complication.\n\nAsking "can I acquire an asset for that?" is often the answer to a problem the crew has no dots in. You cannot Tinker the vault open, but you can acquire a person who can.',
    seeAlso: ['Downtime', 'Tier', 'Coin', 'Effect', 'Crew'],
    aliases: ['asset', 'acquire', 'get gear', 'hire'],
  },

  // ── The crew and the world ───────────────────────────────────────────────────────────────
  {
    term: 'Heat',
    kind: 'term',
    short: 'The crew\'s attention from the law and rivals; at 9 heat your wanted level rises and heat resets to 0.',
    body: '**Heat** is how much attention the crew has drawn. It is a **crew** stat, not a personal one — one member\'s mess is everyone\'s problem.\n\nAfter each score, the crew takes heat based on:\n\n· The **exposure** of the target — a quiet job on a nobody, or a public one on a noble house?\n· The **violence and chaos** — a clean job adds little; killing people adds more\n· **Witnesses**, evidence, and whether anyone can name you\n· **Bragging** about it in downtime — **+2 heat** from an overindulged vice\n\nAt **9 heat**, the crew\'s **wanted level increases by 1** and **heat resets to 0**. Heat also sizes the **entanglement** roll at the start of each downtime — more heat, worse trouble.\n\nLower it with the **Reduce Heat** downtime activity, or by letting a quiet stretch pass.\n\nThe strategic read: heat is the price of doing loud business, and a crew that never pays it down is buying a wanted level on instalments.',
    seeAlso: ['Wanted Level', 'Reduce Heat', 'Entanglement', 'Downtime', 'Crew'],
    aliases: ['heat level', 'attention'],
  },
  {
    term: 'Wanted Level',
    kind: 'term',
    short: 'A crew stat from 0 to 4 that rises each time heat hits 9; higher means the law comes for you specifically.',
    body: '**Wanted level** runs **0 to 4** and it is the long-term consequence track for the crew. Every time **heat reaches 9**, the wanted level **goes up by 1** and heat resets.\n\nWhat it does:\n\n· It makes **entanglements** worse and more law-focused — at high wanted level, the Bluecoats aren\'t looking for someone, they\'re looking for **you**.\n· It raises the stakes on **incarceration**: a crew member who gets taken serves time scaled to the wanted level.\n· It shapes how factions treat you — associating with a wanted crew is itself dangerous.\n\nWanted level does **not** come down through the Reduce Heat activity (that only cools **heat**). Lowering it takes serious effort in the fiction: taking the fall, doing time, a major favour to the right faction, or a long-term project.\n\nA wanted level 4 crew is playing a different, much harder game — which is exactly the arc the system wants you to have.',
    seeAlso: ['Heat', 'Reduce Heat', 'Entanglement', 'Crew'],
    aliases: ['wanted', 'wanted level 4', 'law'],
  },
  {
    term: 'Entanglement',
    kind: 'mechanic',
    short: 'Trouble rolled at the start of downtime; the crew\'s heat and wanted level determine how bad it gets.',
    body: 'At the start of **downtime**, before activities, the GM rolls an **entanglement**: the mess your score dragged home.\n\nThe crew\'s **heat** governs how bad the roll goes — a cold crew gets minor nuisances, a hot crew gets the serious end of the table. The **wanted level** shapes which entanglements are on the table at all.\n\nTypical entanglements include:\n\n· **Cooperation** — another faction wants a favour, and refusing costs you standing\n· **Demonic Notice** — something arcane has taken an interest in you\n· **Gang Trouble** — your own people cause a problem\n· **Interrogation** — a crew member gets picked up and questioned\n· **Reprisals** — a faction you hurt hits back\n· **Rivals**, **Show of Force**, **The Bluecoats**, **Unquiet Dead**, **Usual Suspects**\n\nEntanglements are **not optional**. You deal with them in the fiction, often burning downtime activities or coin to make them go away — which is exactly why heat matters even when nobody\'s shooting at you.\n\nThey are also the GM\'s best tool for keeping the world alive between jobs.',
    seeAlso: ['Heat', 'Wanted Level', 'Downtime', 'Reduce Heat', 'Fortune Roll'],
    aliases: ['entanglements', 'downtime trouble'],
  },
  {
    term: 'Crew',
    kind: 'term',
    short: 'The shared "character" the whole table plays: it has its own type, tier, XP, upgrades, claims, and hold.',
    body: 'The **crew** is a character sheet the whole table shares. You pick a **crew type** at the start of the campaign, and it defines what your scores look like:\n\n· **Assassins**, **Bravos**, **Cult**, **Hawkers**, **Shadows**, **Smugglers**\n\nThe crew tracks:\n\n· **Tier** (0–IV) — its rank among Doskvol\'s factions\n· **Hold** — **strong** or **weak**, how stable its grip on its tier is\n· **Rep** — progress toward the next tier\n· **Coin** — money on hand, and **stash** for retirement\n· **Heat** and **wanted level**\n· **Claims** — the turf and assets it controls, on a claims map\n· **Upgrades** — permanent improvements, including training and crew abilities\n· **Its own XP track** — filled by the crew\'s own triggers each session\n\nThe crew **advances separately** from the PCs, and a smart table treats crew advancement as a real decision rather than an afterthought. Crew upgrades — a Physicker\'s workshop, training slots, better gear quality — often improve the party more than a personal action dot does.',
    seeAlso: ['Tier', 'Coin', 'Heat', 'Wanted Level', 'Advancement', 'Acquire Asset'],
    aliases: ['crews', 'crew sheet', 'crew type', 'claims', 'hold', 'rep'],
  },
  {
    term: 'Tier',
    kind: 'term',
    short: 'A faction\'s rank from 0 to IV; it sizes your quality and effect against everyone else in Doskvol.',
    body: '**Tier** rates a faction\'s power, resources, and reach on a scale of **0 to IV**. Your crew has one; so does every gang, noble house, and institution in the city.\n\nWhat tier does mechanically:\n\n· Sets the **quality** of your gear, assets, and hired help — an **Acquire Asset** roll uses your tier as the pool.\n· Feeds **effect** as one of the three factors (potency, scale, **quality/tier**). Going against a faction two tiers above you means **reduced effect** by default.\n· Sizes your **payoff** from scores.\n· Modifies the **engagement roll** against higher-tier targets.\n\nRaise tier by earning **rep** and spending **coin**, which is one of the main things the crew\'s downtime is for. Tier also has **hold** — **strong** or **weak** — which is whether you can sustain your position; a weak-hold crew can be knocked down a tier.\n\nStarting crews are **Tier 0**. The Bluecoats are not. Understanding the tier gap between you and your target is the single most useful piece of pre-score analysis available.',
    seeAlso: ['Crew', 'Effect', 'Acquire Asset', 'Engagement Roll', 'Coin'],
    aliases: ['tiers', 'faction tier', 'tier iv'],
  },
  {
    term: 'Coin',
    kind: 'term',
    short: 'Abstract money in single units — spend it on downtime activities, asset quality, tier, and your stash.',
    body: '**Coin** is deliberately coarse: **1 coin** is a meaningful amount of money to a scoundrel, not a currency denomination. There is no itemised shopping list.\n\nWhat coin is actually for:\n\n· **Extra downtime activities** — **1 coin** each, beyond your 2 free\n· Bumping **Acquire Asset** quality\n· Paying the crew\'s **upgrades** and advancing **tier**\n· Greasing entanglements away\n· Your **stash** — the retirement fund\n\n**Payoff** from a score is split: some to the crew, some to individuals, sized by the score\'s **tier and scale**.\n\n**Stash** is the endgame. Coin moved into your personal stash is out of play permanently, and your stash total at retirement determines what life your character gets when they walk away. Since **4 traumas forces retirement**, every scoundrel is quietly racing their own stress track — get out rich, or get out broken.\n\nThat tension between "spend it to survive tonight" and "stash it to survive the campaign" is the entire economy.',
    seeAlso: ['Downtime', 'Crew', 'Tier', 'Acquire Asset', 'Trauma'],
    aliases: ['money', 'stash', 'payoff', 'coins'],
  },
  {
    term: 'Advancement',
    kind: 'mechanic',
    short: 'Mark XP from triggers, fill a track (8 for playbook, 6 for attributes), buy a special ability or an action dot.',
    body: 'There are **no levels and no XP totals**. You mark XP on **tracks**, and filling a track buys exactly one thing.\n\n**The tracks:**\n\n· **Playbook track — 8 boxes** → a new **special ability**\n· **Insight / Prowess / Resolve — 6 boxes each** → a new **action dot** in that attribute\n\n**Marking XP during play:**\n\n· When you roll a **desperate** action, **mark 1 XP** in that action\'s attribute — immediately.\n\n**At the end of each session**, mark **1 XP** on your **playbook** track for each of these that happened (**2** if it happened a lot):\n\n· You addressed a challenge with your **playbook\'s signature approach**\n· You expressed your **beliefs, drives, heritage, or background**\n· You struggled with issues from your **vice, trauma, or need**\n\nPlus the **Train** downtime activity for a guaranteed mark.\n\nThe crew has its **own** XP track and triggers, advancing in parallel.\n\nRead what the triggers reward: **playing your character badly on purpose**. Desperate rolls, vice problems, trauma driving the bus. The game pays you to make things worse, which is why Blades characters do.',
    seeAlso: ['Action Rating', 'Trauma', 'Vice', 'Train', 'Position', 'Crew'],
    aliases: ['xp', 'experience', 'xp triggers', 'level up', 'levelling', 'advance'],
  },

  // ── Playbooks ────────────────────────────────────────────────────────────────────────────
  {
    term: 'Playbook',
    kind: 'class',
    short: 'Not a class: a bundle of XP triggers, a special-ability list, starting dots, and friends/rivals. It never levels.',
    body: 'A **playbook** is the closest thing Blades has to a class, and the differences matter more than the similarities.\n\nA playbook gives you:\n\n· A **starting action dot** and suggested dot spread\n· A **special ability list** — you take one at creation, more by filling your **8-box playbook XP track**\n· A **playbook XP trigger** — the specific behaviour that earns you XP\n· **Friends and rivals** — named NPCs you must place on a like/dislike scale\n· A **signature item** and playbook-specific gear\n\nWhat it does **not** give you: a **level**, a **hit die**, **hit points**, an **attack bonus**, **saves**, a **spell list**, or any per-level progression whatsoever. A Cutter with eight special abilities has the same 9 stress boxes and the same harm tracker as one made this morning.\n\nThe seven playbooks: **Cutter**, **Hound**, **Leech**, **Lurk**, **Slide**, **Spider**, **Whisper**.\n\nYou are not locked in. Any character can take **any action dot**, and playbooks share the same 12 actions — the playbook shapes what you\'re *rewarded* for, not what you\'re *allowed*.',
    seeAlso: ['Cutter', 'Hound', 'Leech', 'Lurk', 'Slide', 'Spider', 'Whisper', 'Advancement', 'Action Rating'],
    aliases: ['playbooks', 'class', 'character sheet', 'special ability'],
  },
  {
    term: 'Cutter',
    kind: 'class',
    short: 'A dangerous, intimidating fighter — the crew\'s violence and its nerve. Skirmish and Command.',
    body: 'The **Cutter** is the one people are afraid of. Their business is **Skirmish** and **Command**: close violence and the force of will to make a room go quiet.\n\n· **Signature actions** — Skirmish, Command, Wreck\n· **XP trigger** — you addressed a challenge with **violence or coercion**\n· **Special abilities** include *Battleborn*, *Bodyguard*, *Ghost Fighter*, *Savage*, *Not to be Trifled With*, *Vigorous*\n\n*Not to be Trifled With* is the one that defines them: it lets you fight a **whole gang** at reasonable effect, which the **scale** factor otherwise makes impossible.\n\nMechanically the Cutter has **no more hit points than anyone else** — there are none. What they have is **Prowess** dots for physical resistance rolls, and abilities that reduce the stress cost of surviving.\n\nThat is the honest read on the Cutter: they are not durable, they are **efficient at buying durability with stress**. Which means the Cutter is usually the first to **trauma**.',
    seeAlso: ['Playbook', 'Skirmish', 'Command', 'Prowess', 'Trauma'],
    aliases: ['cutters', 'fighter'],
  },
  {
    term: 'Hound',
    kind: 'class',
    short: 'A deadly shot and tracker — the crew\'s eyes and its rifle. Hunt and Survey.',
    body: 'The **Hound** finds people and shoots them. Their actions are **Hunt** and **Survey**: tracking a target across the city, then ending the conversation from a rooftop.\n\n· **Signature actions** — Hunt, Survey, Prowl\n· **XP trigger** — you addressed a challenge with **tracking or violence**\n· **Special abilities** include *Sharpshooter*, *Focused*, *Ghost Hunter*, *Scout*, *Tough as Nails*, *Vengeful*\n\nThe Hound owns a **hunting pet** (often a rail hound) as a signature item, and *Ghost Hunter* upgrades it to something that can perceive and fight the dead.\n\n*Sharpshooter* is the key ability: it lets you push yourself to **shoot at extreme range or hit multiple targets**, which fixes the **scale** problem for ranged work the way *Not to be Trifled With* fixes it for melee.\n\nThe Hound is the crew\'s reconnaissance as much as its gun — a **Survey** setup action from a Hound with dots is how a desperate score becomes a risky one.',
    seeAlso: ['Playbook', 'Hunt', 'Survey', 'Prowl', 'Setup Action'],
    aliases: ['hounds', 'sniper', 'tracker'],
  },
  {
    term: 'Leech',
    kind: 'class',
    short: 'A saboteur and technician — alchemy, gadgets, and the crew\'s medic. Tinker and Wreck.',
    body: 'The **Leech** builds things and breaks things. Their actions are **Tinker** and **Wreck**, and they are the crew\'s only real answer to a locked problem or a wounded friend.\n\n· **Signature actions** — Tinker, Wreck, Study\n· **XP trigger** — you addressed a challenge with **technical skill or mayhem**\n· **Special abilities** include *Alchemist*, *Physicker*, *Saboteur*, *Analyst*, *Fortitude*, *Venomous*\n\nTwo abilities carry the playbook:\n\n· **Alchemist** — you have a **formula book** and can create alchemicals as **long-term projects**; you start with a supply\n· **Physicker** — you can treat **harm** properly, rolling to fill teammates\' **healing clocks** during **Recover**\n\n*Physicker* is close to mandatory in a crew that intends to survive, because it is the only good version of healing that exists. Without a Physicker you are paying coin to hired doctors and healing at a crawl.\n\nThe Leech carries a **wrecking tools** and **documents** signature kit, and their **load** is always the tightest decision on the sheet.',
    seeAlso: ['Playbook', 'Tinker', 'Wreck', 'Recover', 'Healing Clock', 'Long-Term Project'],
    aliases: ['leeches', 'alchemist', 'physicker', 'medic', 'tech'],
  },
  {
    term: 'Lurk',
    kind: 'class',
    short: 'A stealthy infiltrator and thief — in and out before anyone knew. Prowl and Finesse.',
    body: 'The **Lurk** goes where they shouldn\'t be. Their actions are **Prowl** and **Finesse**: over the wall, past the guards, hands on the thing, gone.\n\n· **Signature actions** — Prowl, Finesse, Hunt\n· **XP trigger** — you addressed a challenge with **stealth or evasion**\n· **Special abilities** include *Infiltrator*, *Shadow*, *Ambush*, *Daredevil*, *Rooks Gambit*, *The Devil\'s Footsteps*\n\n*Infiltrator* removes the **quality/tier penalty** on bypassing security measures — the single cleanest answer to breaking into places above your crew\'s tier.\n\n*Rook\'s Gambit* is one of the best abilities in the game: **take 2 stress to roll an action you didn\'t use**, at reduced effect. It is a universal escape hatch.\n\nThe Lurk lives on **load**. Running **light (3)** is what makes Prowl work at full effect, so the Lurk is perpetually deciding what not to bring — and **flashbacks** are how they get it anyway.',
    seeAlso: ['Playbook', 'Prowl', 'Finesse', 'Load', 'Flashback'],
    aliases: ['lurks', 'thief', 'infiltrator', 'stealth'],
  },
  {
    term: 'Slide',
    kind: 'class',
    short: 'A subtle manipulator and spy — the crew\'s face and its liar. Sway and Consort.',
    body: 'The **Slide** talks. Their actions are **Sway** and **Consort**: getting people to open doors that don\'t need breaking.\n\n· **Signature actions** — Sway, Consort, Study\n· **XP trigger** — you addressed a challenge with **deception or influence**\n· **Special abilities** include *Rook\'s Gambit*, *Mesmerism*, *Trust in Me*, *Cloak & Dagger*, *Ghost Voice*, *Like Looking into a Mirror*\n\n*Cloak & Dagger* is the classic: when you use a **disguise or false identity**, you get **+1d** or **improved position** — which turns social infiltration from desperate into risky.\n\n*Mesmerism* lets you **Sway** someone and then have them forget the encounter, which is exactly as useful as it sounds.\n\nThe Slide is the playbook that most often makes a score **not happen** — a good Sway can obtain the thing without anyone drawing a blade, generating almost no **heat**. Crews that underrate the Slide are crews with a wanted level.',
    seeAlso: ['Playbook', 'Sway', 'Consort', 'Heat', 'Position'],
    aliases: ['slides', 'face', 'spy', 'talker'],
  },
  {
    term: 'Spider',
    kind: 'class',
    short: 'A cunning schemer and planner — the crew\'s brain, working through other people. Consort and Study.',
    body: 'The **Spider** does not do the job. The Spider **arranges** the job. Their actions are **Consort** and **Study**: knowing everyone, knowing everything, and being three moves ahead.\n\n· **Signature actions** — Consort, Study, Sway\n· **XP trigger** — you addressed a challenge with **calculation or conspiracy**\n· **Special abilities** include *Foresight*, *Mastermind*, *Weaving the Web*, *Connected*, *Functioning Vice*, *Ghost Contract*\n\n*Foresight* gives the crew a **free downtime activity** for a long-term project or a flashback\'s worth of preparation — the Spider\'s time is worth more than anyone\'s.\n\n*Mastermind* lets you **protect a teammate** by taking their stress for a **resistance roll**, which makes the Spider the crew\'s shock absorber.\n\n*Functioning Vice* means you can **indulge your vice without the usual mess**, one of the quiet best abilities in the game — a Spider who never overindulges is a Spider whose stress track actually works.\n\nThe Spider owns the **downtime** and **faction** layer of the game more than the score layer.',
    seeAlso: ['Playbook', 'Consort', 'Study', 'Downtime', 'Indulge Vice', 'Crew'],
    aliases: ['spiders', 'mastermind', 'planner', 'fixer'],
  },
  {
    term: 'Whisper',
    kind: 'class',
    short: 'An arcane adept in touch with the ghost field — the crew\'s answer to the dead. Attune and Study.',
    body: 'The **Whisper** deals with what\'s on the other side. Their actions are **Attune** and **Study**: perceiving the ghost field, commanding spirits, and paying for it.\n\n· **Signature actions** — Attune, Study, Consort\n· **XP trigger** — you addressed a challenge with **knowledge or arcane power**\n· **Special abilities** include *Compel*, *Tempest*, *Ritual*, *Ghost Mind*, *Warded*, *Iron Will*\n\n*Ritual* is the playbook\'s engine: you can **learn and perform rituals** as **long-term projects**, and rituals are the only route to the game\'s genuinely large-scale supernatural effects. They also cost **harm and stress** to perform — arcane power in Blades is always paid for out of the character.\n\n*Compel* lets you **summon and command a spirit**. *Tempest* throws lightning and calls the storm.\n\nThe Whisper is the highest-variance playbook. **Attune** is routinely rolled from **desperate** position, which means a Whisper generates XP fast and **trauma** faster. A Whisper who reaches 4 traumas is not a failure of play; it is the playbook working as designed.',
    seeAlso: ['Playbook', 'Attune', 'Study', 'Resolve', 'Trauma', 'Long-Term Project'],
    aliases: ['whispers', 'occultist', 'mage', 'ritual'],
  },
];
