// lib/dnd/glossary/coc7e.ts — Call of Cthulhu 7e terms, as the Keeper Rulebook defines them.
//
// CoC is a PERCENTILE ROLL-UNDER game: you roll d100 and want to land at or under a number you
// already have written on your sheet. There is no d20 anywhere in it, no AC, no proficiency bonus,
// no levels, no classes, and no XP. Difficulty is not a DC handed to you by the Keeper — it is a
// fraction of your OWN skill (half for Hard, one fifth for Extreme). Everything below is written so
// a player can resolve it mid-session without opening the book.
import type { SystemGlossary } from './types';

export const COC7E_GLOSSARY: SystemGlossary = [
  // ── Core resolution ──────────────────────────────────────────────────────────────────────
  {
    term: 'Skill Roll',
    kind: 'mechanic',
    short: 'Roll d100 and try to land at or UNDER the skill or characteristic you are using — low is good.',
    body: 'The one roll the whole game runs on. Roll **percentile dice** (a tens die and a units die, read as 01–100) and compare the result to the **skill or characteristic value** on your sheet. Roll **equal to or under** it and you succeed. Low is good — this is the exact inverse of a d20 game.\n\nThe number you already have IS the target. A Locksmith of 45 succeeds on 01–45. The Keeper never invents a DC; instead they choose how **hard** the roll is, which shrinks the target to a fraction of your own value:\n\n· **Regular** — roll ≤ your full skill\n· **Hard** — roll ≤ **half** your skill (round down)\n· **Extreme** — roll ≤ **one fifth** of your skill (round down)\n\nSo Locksmith 45 needs 01–45 Regular, 01–22 Hard, 01–09 Extreme. Higher success levels are not "better" by default — the Keeper calls for them when the task is genuinely harder, and some effects (like a firearm impale) key off achieving one.\n\nIf a roll cannot possibly matter, do not make it. The Keeper only calls for a roll when failure is interesting and the outcome is in doubt.',
    seeAlso: ['Regular Success', 'Hard Success', 'Extreme Success', 'Critical Success', 'Fumble', 'Bonus Die', 'Pushing a Roll'],
    aliases: ['d100', 'percentile', 'roll under', 'skill check', 'percentiles', 'roll'],
  },
  {
    term: 'Regular Success',
    kind: 'mechanic',
    short: 'A d100 result at or under your full skill value — the ordinary "you did it".',
    body: 'The baseline. Your d100 lands **at or under the skill value** as written on the sheet.\n\nA **Regular** success is the default the Keeper asks for. It means the task is done, competently, with no particular flourish — the lock opens, the reference is found, the shot connects.\n\nA Regular success also **marks the skill** for improvement at the end of the scenario, which is the only way most skills ever grow.',
    seeAlso: ['Skill Roll', 'Hard Success', 'Skill Improvement Check'],
    aliases: ['normal success', 'regular'],
  },
  {
    term: 'Hard Success',
    kind: 'mechanic',
    short: 'A d100 result at or under HALF your skill value, rounded down.',
    body: 'A **Hard** success requires the roll to come in at or under **half** your skill, rounding down. Persuade 70 means a Hard success on **01–35**.\n\nThe Keeper calls for Hard difficulty when the task is meaningfully harder than routine — talking past a guard who has already been warned, spotting a detail deliberately concealed. Rolling over half but under your full value on a **Hard** roll is a **failure**, not a partial win.\n\nHard also appears as a threshold in resolution: some opposed contests and some weapon effects care specifically about whether you cleared the half mark.',
    seeAlso: ['Skill Roll', 'Regular Success', 'Extreme Success'],
    aliases: ['hard', 'half value', 'hard difficulty'],
  },
  {
    term: 'Extreme Success',
    kind: 'mechanic',
    short: 'A d100 result at or under ONE FIFTH of your skill value, rounded down.',
    body: 'An **Extreme** success needs the roll at or under **one fifth** of your skill, rounding down. Firearms (Handgun) 60 gives an Extreme range of **01–12**.\n\nThe Keeper sets Extreme difficulty for tasks near the edge of possibility. It also matters mechanically in combat: an Extreme success with an **impaling** weapon does **maximum damage plus a rolled damage die**, and an Extreme success on a manoeuvre or an opposed roll beats any lesser success.\n\nIf your skill is under 5, its Extreme value rounds to 0 and an Extreme success is simply impossible — the fifth is not "at least 1".',
    seeAlso: ['Skill Roll', 'Hard Success', 'Impale', 'Critical Success'],
    aliases: ['extreme', 'fifth value', 'one fifth'],
  },
  {
    term: 'Critical Success',
    kind: 'mechanic',
    short: 'A roll of 01 — the best possible outcome, whatever the difficulty was.',
    body: 'A d100 result of **01** is a **critical success**. It always succeeds, regardless of the difficulty level called for and regardless of how low the skill is — a 3% skill still criticals on 01.\n\nA critical is a licence for the Keeper to give you more than you asked for: the perfect angle, the extra clue, the shot that ends it. In combat a critical does the same damage an **Extreme** success would.\n\nNote what it is NOT. There is no "crit range", no doubling of dice, no confirmation roll. It is exactly one result on one die pair.',
    seeAlso: ['Skill Roll', 'Fumble', 'Extreme Success'],
    aliases: ['crit', '01', 'critical'],
  },
  {
    term: 'Fumble',
    kind: 'mechanic',
    short: 'A roll of 100 always fumbles; so does 96–99 when the skill being rolled is below 50.',
    body: 'A **fumble** is a failure that actively makes things worse. Two cases:\n\n· A result of **100** is always a fumble, no matter how good the skill is.\n· A result of **96–99** is a fumble **only if the skill or characteristic being rolled is below 50**.\n\nThat second clause is the elegant bit — the less competent you are, the wider your fumble band. A Firearms of 20 fumbles on 96–100; a Firearms of 75 fumbles only on 100.\n\nThe Keeper decides the consequence in the fiction: the gun jams, the rope parts, the lie lands catastrophically. A fumbled roll **cannot be pushed** — the failure is already final and messy.\n\n**Luck** cannot be spent to climb out of a fumble either.',
    seeAlso: ['Skill Roll', 'Critical Success', 'Pushing a Roll', 'Luck'],
    aliases: ['fumbled', 'botch', '100', 'critical failure'],
  },
  {
    term: 'Bonus Die',
    kind: 'mechanic',
    short: 'An extra TENS die; keep whichever tens result is better (lower). Not a numeric bonus.',
    body: 'A **bonus die** does not add anything. You roll **one extra tens die** and keep whichever tens result gives you the **better (lower)** final number, with the same single units die.\n\nExample: units die 4, tens dice 6 and 2. Your options are **64** and **24** — with a bonus die you take **24**.\n\nTwo bonus dice means three tens dice, still keeping the best. Bonus dice come from aiming, from a helpful ally, from good circumstances, and from certain abilities. Bonus and **penalty** dice **cancel one for one** before you roll; if any remain, roll that many extra tens dice.\n\nRemember the special case: a tens die of **0** with a units die of **0** reads as **100**, not 00.',
    seeAlso: ['Penalty Die', 'Skill Roll', 'Fumble'],
    aliases: ['bonus dice', 'bd'],
  },
  {
    term: 'Penalty Die',
    kind: 'mechanic',
    short: 'An extra TENS die; you are forced to keep the worse (higher) tens result.',
    body: 'The mirror of a bonus die. Roll **one extra tens die** and keep the **worse (higher)** result.\n\nUnits die 4, tens dice 6 and 2 gives you **64** and **24** — with a penalty die you are stuck with **64**.\n\nPenalty dice model bad conditions: firing at a fast-moving target, working in the dark, acting while badly hurt. **Bonus and penalty dice cancel each other one for one** — three bonus and two penalty leaves you rolling with one bonus die.\n\nThis is deliberately not a −20 modifier. Because it warps the tens die only, a penalty die hurts a low skill far less in absolute terms than a flat subtraction would, and it can never push you below a 1-in-10 chance of the units die saving you.',
    seeAlso: ['Bonus Die', 'Skill Roll'],
    aliases: ['penalty dice', 'pd'],
  },
  {
    term: 'Pushing a Roll',
    kind: 'mechanic',
    short: 'Re-attempt a failed roll by describing what extra you do — but a failed push has a real, worse consequence.',
    body: 'After a **failed** roll, you may **push** it: describe what you are doing differently or harder — taking more time, forcing the door instead of picking it, pressing the witness who has already said no — and roll **again** against the same target.\n\nThe Keeper must agree the justification is real. Pushing is not a free reroll; it is a bargain. **If the pushed roll also fails, the Keeper introduces a serious consequence**, not just "nothing happens". The door opens onto the thing you did not want to meet; the witness calls the police; the rope you strained gives way at the worst point.\n\nRestrictions worth knowing at the table:\n\n· A **fumble** cannot be pushed.\n· You get **one push per roll** — you cannot push a push.\n· **Luck cannot be spent to save a failed pushed roll.**\n\nPushing is the game\'s pressure valve and its trap at once: it is how investigators find the clue the scenario needs, and how they walk into the room that kills them.',
    seeAlso: ['Skill Roll', 'Fumble', 'Luck'],
    aliases: ['pushing', 'push', 'push the roll', 'pushed roll'],
  },
  {
    term: 'Opposed Roll',
    kind: 'mechanic',
    short: 'Both sides roll against their own skill; the higher LEVEL of success wins, ties go to the higher skill.',
    body: 'When two people directly contest — arm-wrestling, a chase of wits, hiding versus searching — **both** roll against their **own** value.\n\nResolve it by **level of success**, not by margin: Critical beats Extreme beats Hard beats Regular beats failure. Whoever achieved the higher level wins.\n\n· If both achieve the **same level**, the one with the **higher skill value** wins.\n· If those are also equal, roll again.\n· If both **fail**, nothing changes — the status quo holds.\n\nNote what is absent: you never subtract one roll from the other, and there is no "beat their number". Two Regular successes are a tie broken by whose skill is bigger, even if one player rolled 03 and the other rolled 60.\n\nCombat is a chain of opposed rolls: the attacker rolls their weapon skill and the defender chooses to **Fight Back** or **Dodge**. In combat, **ties go to the attacker**.',
    seeAlso: ['Skill Roll', 'Fighting Back', 'Dodge', 'Hard Success'],
    aliases: ['opposed', 'contest', 'contested roll', 'opposed test'],
  },
  {
    term: 'Idea Roll',
    kind: 'mechanic',
    short: 'A d100 roll-under against INT — the "does my investigator work it out?" roll.',
    body: 'An **Idea roll** is simply a roll-under against your **INT** characteristic. The Keeper calls for it when an investigator has all the pieces but the player has not connected them, or when a character would plausibly grasp something the player cannot know.\n\nIt is also the trigger step for **Temporary Insanity**: when you lose 5 or more Sanity from a single Sanity check, you make an **Idea roll**, and *succeeding* means your mind has fully grasped the horror — which is what tips you into a bout of madness.\n\nThat inversion is intentional and catches new players every time: on the madness check, **passing the Idea roll is the bad outcome**.',
    seeAlso: ['INT', 'Know Roll', 'Temporary Insanity', 'Sanity Check'],
    aliases: ['idea', 'int roll', 'idea check'],
  },
  {
    term: 'Know Roll',
    kind: 'mechanic',
    short: 'A d100 roll-under against EDU — general education recall.',
    body: 'A **Know roll** is a roll-under against **EDU**. It covers general knowledge an educated person of the era would carry around: what a Latin phrase means, who runs the county, roughly how a magneto works.\n\nUse it when no specific skill fits. If a specific skill *does* fit — History, Occult, Science — roll that instead; it is usually a better number and the Know roll is not a way to bypass having failed the specialist skill.\n\nEDU is also the basis for **occupation skill points (EDU × 4)** and the **EDU improvement check**, so it does double duty as both a stat and a resource.',
    seeAlso: ['EDU', 'Idea Roll', 'Occupation Skill Points'],
    aliases: ['know', 'edu roll', 'know check', 'general knowledge'],
  },

  // ── Characteristics ──────────────────────────────────────────────────────────────────────
  {
    term: 'Characteristics',
    kind: 'term',
    short: 'The eight core numbers plus Luck, all rated as PERCENTAGES from 0–99, not 3–18 scores.',
    body: 'Investigators have eight characteristics — **STR, CON, SIZ, DEX, APP, INT, POW, EDU** — plus **Luck**. Every one of them is a **percentage**, in the same units as a skill. There is **no modifier table**: the characteristic *is* the target number you roll under, and its **half** and **fifth** values give you Hard and Extreme.\n\nRolling them up:\n\n· **STR, CON, DEX, APP, POW** — **3d6 × 5** (15–90)\n· **SIZ, INT, EDU** — **(2d6 + 6) × 5** (40–90)\n· **Luck** — **3d6 × 5**\n\nOr point-buy: distribute **460 points** across the eight characteristics, **maximum 80** in any one at creation.\n\nDerived values come straight off these: **Hit Points = (CON + SIZ) ÷ 10**, **Sanity = POW**, **Damage Bonus and Build** from STR + SIZ, and **Move** from comparing STR and DEX to SIZ.\n\nAging adjusts them — investigators over 40 take deductions to physical characteristics and gains to EDU, which is why the "seasoned professor" is smart, rich in skills, and easy to kill.',
    seeAlso: ['STR', 'CON', 'SIZ', 'DEX', 'APP', 'INT', 'POW', 'EDU', 'Luck', 'Hit Points', 'Damage Bonus'],
    aliases: ['stats', 'attributes', 'characteristic', 'abilities'],
  },
  {
    term: 'STR',
    kind: 'stat',
    short: 'Strength as a percentage — raw physical power; with SIZ it sets Damage Bonus and Build.',
    body: '**Strength**, rolled **3d6 × 5**. It is the target for rolls of brute force: forcing a door, holding a rope, an arm-wrestle resolved as an opposed STR roll.\n\nSTR + SIZ together determine your **Damage Bonus** and **Build**, which is why a big, strong investigator hits harder in melee without any "attack bonus" existing anywhere.\n\nSTR is also one of the two characteristics compared to SIZ to find your **Move rate**, and it is the base for the Climb, Jump and Swim skills.\n\nSTR can be **permanently drained** by some Mythos entities. A character reduced to **STR 0** cannot move under their own power.',
    seeAlso: ['SIZ', 'Damage Bonus', 'Build', 'Move Rate', 'Characteristics'],
    aliases: ['strength'],
  },
  {
    term: 'CON',
    kind: 'stat',
    short: 'Constitution as a percentage — health and endurance; with SIZ it sets Hit Points.',
    body: '**Constitution**, rolled **3d6 × 5**. Roll under CON to resist poison, disease, drowning, exposure and exhaustion — CoC has **no saving throws**, so a CON roll *is* the poison save.\n\n**Hit Points = (CON + SIZ) ÷ 10**, rounded down. CON is therefore half your durability.\n\nCON is also the roll you make when you take a **Major Wound**: succeed and you stay conscious, fail and you go down. While **dying**, a failed CON roll each round is what kills you.\n\n**CON 0** is death.',
    seeAlso: ['SIZ', 'Hit Points', 'Major Wound', 'Dying', 'Characteristics'],
    aliases: ['constitution'],
  },
  {
    term: 'SIZ',
    kind: 'stat',
    short: 'Size as a percentage — height and mass combined; feeds Hit Points, Damage Bonus, Build and Move.',
    body: '**Size**, rolled **(2d6 + 6) × 5** — note it uses the *higher* generation formula, so nobody is tiny by accident. SIZ folds height and weight into one number.\n\nIt is the most load-bearing characteristic on the sheet despite rarely being rolled directly:\n\n· **Hit Points = (CON + SIZ) ÷ 10**\n· **Damage Bonus and Build** come from **STR + SIZ**\n· **Move** is found by comparing STR and DEX against SIZ\n\nSIZ is rolled directly mostly in opposed rolls — being knocked down, squeezing through a gap, being carried off by something with more of it than you.\n\nBig investigators are tougher and hit harder but move more slowly and hide worse. That trade is the whole design.',
    seeAlso: ['STR', 'CON', 'Hit Points', 'Damage Bonus', 'Build', 'Move Rate'],
    aliases: ['size'],
  },
  {
    term: 'DEX',
    kind: 'stat',
    short: 'Dexterity as a percentage — speed and agility; it also sets your place in the combat order.',
    body: '**Dexterity**, rolled **3d6 × 5**. It is the base for Dodge (Dodge starts at **DEX ÷ 2**), Stealth, Locksmith, Sleight of Hand, Drive Auto, Throw and the Firearms skills.\n\nDEX also decides turn order: combat runs in **DEX order, highest first**. There is no initiative roll — you simply compare DEX values, which stay the same all scenario. (Investigators with a readied firearm act first, at DEX order among themselves.)\n\nDEX is compared against SIZ, alongside STR, to determine your **Move rate**.',
    seeAlso: ['Dodge', 'Combat Round', 'Move Rate', 'Characteristics'],
    aliases: ['dexterity'],
  },
  {
    term: 'APP',
    kind: 'stat',
    short: 'Appearance as a percentage — physical attractiveness and personal charisma.',
    body: '**Appearance**, rolled **3d6 × 5**. It covers looks, bearing and the impression you make before you have said anything.\n\nAPP is the base characteristic for **Charm**, **Fast Talk**, **Persuade** and **Disguise**, so it is the "face" characteristic without ever being a Charisma stat in the d20 sense — it grants no bonuses, it just parents those skills at creation.\n\nIt is occasionally rolled directly when someone\'s reaction depends purely on how you look. Some Mythos exposure and severe injury can permanently lower APP, and a **Major Wound** to the face is the classic way it happens.',
    seeAlso: ['Characteristics', 'Credit Rating'],
    aliases: ['appearance', 'looks'],
  },
  {
    term: 'INT',
    kind: 'stat',
    short: 'Intelligence as a percentage — reasoning power; it is the Idea roll and it buys personal-interest skills.',
    body: '**Intelligence**, rolled **(2d6 + 6) × 5**. Roll under INT for an **Idea roll**, the "do I put it together?" check.\n\nINT buys your **personal interest skill points: INT × 2**, spent on any skills at all, free of your occupation\'s list.\n\nIt is the base for Psychology, Track and Cthulhu Mythos. Crucially, INT is **not** a Sanity stat — Sanity comes from POW — and being smart is if anything a liability, because the **Idea roll you pass is the one that drives you mad**.',
    seeAlso: ['Idea Roll', 'Personal Interest Skill Points', 'POW', 'Cthulhu Mythos'],
    aliases: ['intelligence'],
  },
  {
    term: 'POW',
    kind: 'stat',
    short: 'Power as a percentage — willpower and spiritual force; your starting Sanity EQUALS your POW.',
    body: '**Power**, rolled **3d6 × 5**. It measures force of will, life force, and latent magical potential.\n\nThe headline: **starting Sanity = POW**. A POW 65 investigator begins with 65 Sanity. POW itself does **not** drop when you lose Sanity — the two numbers separate immediately after creation and drift apart forever after.\n\nPOW is rolled directly to resist magic, and is the base for Listen, Spot Hidden and Intimidate. It is also the fuel for **spells**, which cost **magic points** — you have **POW ÷ 5** magic points, and they regenerate over about a day.\n\nPOW is one of the very few characteristics that can *rise* in play: succeed at certain confrontations with the Mythos and you may earn a POW increase.',
    seeAlso: ['Sanity', 'Sanity Check', 'Characteristics'],
    aliases: ['power', 'willpower', 'magic points', 'mp'],
  },
  {
    term: 'EDU',
    kind: 'stat',
    short: 'Education as a percentage — formal learning; it is the Know roll and it buys EDU × 4 occupation points.',
    body: '**Education**, rolled **(2d6 + 6) × 5**. Roll under EDU for a **Know roll**.\n\nEDU is the economic engine of character creation: **occupation skill points = EDU × 4** for most occupations. It is also the parent characteristic for the great mass of knowledge skills — History, Law, Library Use, Medicine, Science, Accounting, First Aid, Credit Rating.\n\nEDU is the only characteristic that reliably **grows**. Aging gives EDU improvement checks at creation, and between scenarios you may make an **EDU improvement check** — roll d100 above your current EDU to gain **1d10** points. EDU is capped at **99**.\n\nThat is why elderly investigators are so skilled and so brittle: decades of EDU checks, and physical characteristics eaten away by aging deductions.',
    seeAlso: ['Know Roll', 'Occupation Skill Points', 'Skill Improvement Check', 'Credit Rating'],
    aliases: ['education'],
  },
  {
    term: 'Luck',
    kind: 'stat',
    short: 'A 3d6 × 5 spendable pool you burn point-for-point to drag a failed roll up into a success.',
    body: '**Luck** is rolled **3d6 × 5** like a characteristic, but it behaves like a **currency**. After you see a failed roll, you may **spend Luck points one-for-one to reduce the rolled result** until it reaches a success level. Roll 58 against a skill of 50? Spend **8 Luck** and it becomes a Regular success.\n\nSpent Luck is **gone** — the pool does not refresh at the end of the session the way a d20 game\'s resources do. It is regained slowly, via a **Luck recovery check** between scenarios (roll d100 above your current Luck to gain **1d10**) and via Keeper awards.\n\nWhat Luck **cannot** do — this is the list that matters at the table:\n\n· It cannot be spent on **damage rolls**.\n· It cannot be spent on **Sanity rolls**.\n· It cannot be spent on **Luck rolls** themselves.\n· It cannot rescue a **failed pushed roll**.\n· It cannot turn a **fumble** into anything.\n\nLuck is also rolled *as* a characteristic — a **Luck roll** — when the Keeper needs to know whether pure chance favours you: is the shop still open, was the car left unlocked, which investigator does the thing notice first.',
    seeAlso: ['Luck Roll', 'Pushing a Roll', 'Fumble', 'Sanity Check'],
    aliases: ['luck points', 'spend luck', 'lck'],
  },
  {
    term: 'Luck Roll',
    kind: 'mechanic',
    short: 'A roll-under against your current Luck value to see whether blind chance goes your way.',
    body: 'When an outcome depends on nothing but fortune, the Keeper calls for a **Luck roll**: roll d100 against your **current** Luck value.\n\nBecause Luck is a pool you spend down, spending it makes you *worse at Luck rolls* — an investigator who has burned 40 points to survive gunfights will start failing the "is the door unlocked" rolls. That feedback loop is deliberate.\n\nYou may **not spend Luck points on a Luck roll**. Luck rolls also decide which investigator an ambiguous event lands on, and are sometimes used to set up scenario details.',
    seeAlso: ['Luck', 'Skill Roll'],
    aliases: ['luck check', 'roll luck'],
  },
  {
    term: 'Damage Bonus',
    kind: 'term',
    short: 'Extra melee damage from STR + SIZ, ranging from −2 up through +1d4, +1d6, +2d6 and beyond.',
    body: '**Damage Bonus (DB)** is the only "you hit harder" number in the game, and it is derived purely from **STR + SIZ**:\n\n· **2–64** — DB **−2**\n· **65–84** — DB **−1**\n· **85–124** — DB **none**\n· **125–164** — DB **+1d4**\n· **165–204** — DB **+1d6**\n· **205–284** — DB **+2d6**\n· **285–364** — DB **+3d6**\n\nAdd DB to **melee and thrown** weapon damage. It does **not** apply to firearms — a bullet does not care how big you are.\n\nA negative DB subtracts. A wiry investigator with STR 40 and SIZ 50 punches at 1d3 **−2**, which can round down to nothing at all.',
    seeAlso: ['Build', 'STR', 'SIZ', 'Fighting Back'],
    aliases: ['db', 'damage modifier'],
  },
  {
    term: 'Build',
    kind: 'term',
    short: 'A single number from STR + SIZ, on the same ladder as Damage Bonus, used for grapples and manoeuvres.',
    body: '**Build** comes off the same **STR + SIZ** table as Damage Bonus and moves in lockstep with it: **−2, −1, 0, 1, 2, 3, 4**, and upward for the genuinely enormous.\n\nBuild is not damage. It is the number that answers "can I physically move this thing?" — grapples, shoves, disarms, and any **manoeuvre**. If your Build is **2 or more lower** than your target\'s, you **cannot manoeuvre it at all**; you simply are not big enough to wrestle that.\n\nBuild also gives **bonus dice** in a fight when you outmass an opponent, and it is what makes a swarm of small things a real threat: Build stacks when multiple attackers combine on one target.',
    seeAlso: ['Damage Bonus', 'STR', 'SIZ', 'Fighting Back'],
    aliases: ['build value'],
  },
  {
    term: 'Move Rate',
    kind: 'term',
    short: 'MOV 7, 8 or 9 depending on how STR and DEX compare to SIZ, minus 1 per decade over 40.',
    body: '**Move (MOV)** is not rolled and not in feet — it is an abstract rate used mostly in **chases**:\n\n· If **both** STR and DEX are **less than** SIZ — **MOV 7**\n· If **both** STR and DEX are **greater than** SIZ — **MOV 9**\n· Any other combination (including ties) — **MOV 8**\n\nThen apply age: **reduce MOV by 1 for each full decade over 40**. A 62-year-old professor with MOV 8 is at **MOV 6**.\n\nThat is nearly the whole rule. Chases compare MOV to work out who gains and loses ground, and a difference of even 1 matters enormously when something is behind you.',
    seeAlso: ['STR', 'DEX', 'SIZ'],
    aliases: ['mov', 'move', 'movement', 'speed'],
  },
  {
    term: 'Hit Points',
    kind: 'term',
    short: 'HP = (CON + SIZ) ÷ 10, rounded down — a small number, usually 10–15, and it never grows with "levels".',
    body: '**Hit Points = (CON + SIZ) ÷ 10**, rounded down. CON 60 and SIZ 65 gives **12 HP**. That is it. That is your whole body.\n\nHP do **not scale**. There are no levels, no hit dice, no Constitution modifier per level — an investigator who has survived twenty scenarios has exactly the same HP as one made this morning, unless their CON or SIZ changed. A shotgun does 4d6.\n\nKey thresholds:\n\n· Damage of **half your maximum HP or more from a single attack** is a **Major Wound**.\n· At **0 HP** you fall unconscious. With a Major Wound in play, you are **dying**.\n· At **negative HP equal to your maximum**, you are simply dead.\n\nHealing is glacial: **1 HP per day** of rest, or **1d3** with a successful First Aid, or faster under Medicine. There is no magical healing to import here.',
    seeAlso: ['CON', 'SIZ', 'Major Wound', 'Dying', 'First Aid'],
    aliases: ['hp', 'hitpoints', 'health'],
  },

  // ── Sanity ───────────────────────────────────────────────────────────────────────────────
  {
    term: 'Sanity',
    kind: 'term',
    short: 'A pool starting equal to POW; maximum Sanity is 99 minus your Cthulhu Mythos skill.',
    body: '**Sanity (SAN)** starts equal to your **POW** and is tracked separately from it forever after. It is the resource the game is actually about.\n\nYour **maximum Sanity is 99 − your Cthulhu Mythos skill**. Every point of Mythos knowledge you gain permanently lowers the ceiling you can ever recover to. Learn enough about the truth and there is no sane version of you left to return to.\n\nSanity is spent involuntarily via **Sanity checks**, and thresholds fire off it:\n\n· Lose **5 or more** from a single check → possible **Temporary Insanity**\n· Lose **one fifth of your current Sanity** within a single day → **Indefinite Insanity**\n· Reach **Sanity 0** → **permanent insanity**; the investigator is retired to the Keeper\n\nIt comes back in trickles: scenario awards for resolving the horror, and **Psychoanalysis** between sessions. Sanity lost to a direct Mythos encounter is largely never coming back.',
    seeAlso: ['Sanity Check', 'POW', 'Cthulhu Mythos', 'Temporary Insanity', 'Indefinite Insanity', 'Sanity Recovery'],
    aliases: ['san', 'sanity points', 'sanity pool'],
  },
  {
    term: 'Sanity Check',
    kind: 'mechanic',
    short: 'A roll-under against current Sanity when you meet something wrong; failing costs the higher listed loss.',
    body: 'When an investigator sees something that should not exist, the Keeper calls a **Sanity check**: roll d100 against your **current Sanity**.\n\nThe cost is written as a pair, e.g. **1/1d6** or **0/1d4** or **1d10/1d100**:\n\n· **Succeed** → lose the **left** number (often 0 or 1)\n· **Fail** → lose the **right** number\n\nYou lose Sanity **either way** on most sights — success just means you lose less. A roll of **01** costs the minimum possible; a roll of **100** always costs the maximum.\n\nYou never make the same Sanity check twice for the same thing: once you have paid for seeing a ghoul, ghouls no longer cost you.\n\nCritically: **Luck cannot be spent on Sanity checks, and a Sanity check cannot be pushed.** This is the one roll where nothing can save you.',
    seeAlso: ['Sanity', 'Temporary Insanity', 'Indefinite Insanity', 'Luck', 'Idea Roll'],
    aliases: ['san check', 'sanity roll', 'san roll', 'sanity test'],
  },
  {
    term: 'Temporary Insanity',
    kind: 'condition',
    short: 'Triggered by losing 5+ Sanity from one check; you suffer a bout of madness, then remain shaken for 1d10 hours.',
    body: 'If a single Sanity check costs you **5 or more Sanity points**, your mind has taken a shock it cannot absorb. Make an **Idea roll** (roll under INT):\n\n· **Pass the Idea roll** → you fully comprehend what you just saw, and you go **temporarily insane**.\n· **Fail** → your mind mercifully has not put it together yet, and you are spared for now.\n\nYes: **passing is the bad result**. Intelligence is a hazard in this game.\n\nGoing temporarily insane means an immediate **bout of madness**, after which you remain in the temporary insanity state for **1d10 hours** of game time. While in it, you are fragile — the Keeper may apply penalty dice, and further Sanity checks land on an already-broken mind.\n\nInvestigators who come out the far side often carry a new **phobia** or **mania** with them.',
    seeAlso: ['Bout of Madness', 'Sanity Check', 'Idea Roll', 'Indefinite Insanity', 'Phobia', 'Mania'],
    aliases: ['temp insanity', 'temporary madness', 'went mad'],
  },
  {
    term: 'Bout of Madness',
    kind: 'condition',
    short: 'The immediate episode when you snap: 1d10 rounds of real-time madness, or 1d10 hours of summarised madness.',
    body: 'A **bout of madness** is the scene where you lose control. The Keeper rolls on a madness table (or picks) and you play it out. Two flavours:\n\n· **Real time** — the bout lasts **1d10 rounds**, resolved right now at the table. Hysteria, fleeing, fainting, violence, catatonia, a psychosomatic disability.\n· **Summary** — the bout lasts **1d10 hours** and is narrated after the fact. You come back to yourself somewhere else, with time missing and evidence of what you did.\n\nDuring a bout, the player does not fully steer the character — that is the point of it. Common results include an **underlying insanity** surfacing, an amnesia gap, or a delusional episode where you cannot tell what was real.\n\nThe bout ends; the **temporary insanity** it belongs to persists for **1d10 hours** afterwards.',
    seeAlso: ['Temporary Insanity', 'Indefinite Insanity', 'Phobia', 'Mania'],
    aliases: ['madness', 'bout', 'madness episode', 'insanity table'],
  },
  {
    term: 'Indefinite Insanity',
    kind: 'condition',
    short: 'Triggered by losing one fifth of your Sanity within a single day; lasts a minimum of 1d6 months of game time.',
    body: 'The heavier of the two insanities. If you lose **one fifth or more of your current Sanity within a single day** of game time — from any combination of checks, not one big one — you go **indefinitely insane**.\n\nA Sanity 60 investigator crosses the line at **12 points lost in a day**. Two bad checks can do it.\n\nIndefinite insanity lasts a **minimum of 1d6 months** of game time and is not something you shrug off between scenes. The investigator is typically institutionalised or cared for; the Keeper and player agree how they function, and a **phobia**, **mania** or full delusional structure becomes part of the character.\n\nRecovering from it is one of the few reliable ways to gain Sanity back — an investigator who comes out the other side regains a meaningful amount and returns changed.\n\nThis is the reason experienced groups count Sanity loss *per day*, not per scene.',
    seeAlso: ['Sanity', 'Temporary Insanity', 'Sanity Recovery', 'Psychoanalysis', 'Phobia', 'Mania'],
    aliases: ['indefinite', 'indefinite madness', 'fifth of sanity'],
  },
  {
    term: 'Phobia',
    kind: 'condition',
    short: 'An irrational terror acquired from madness; confronting it forces a Sanity check or flight.',
    body: 'A **phobia** is a lasting fear attached to a specific thing, taken on as a result of a bout of madness or an insanity. The Keeper rolls or chooses from the phobia list — the classics are there (heights, enclosed spaces, the dark, blood, water) alongside far stranger ones.\n\nAt the table: when the investigator is **confronted with the object of the phobia**, they must deal with it — typically a **Sanity check**, and on a failure the character flees, freezes, or is at penalty dice for the duration. A phobia is not colour text; it is a mechanical liability the Keeper is entitled to press.\n\nPhobias can be treated with **Psychoanalysis** over time, or overcome through play. Investigators tend to accumulate them, and the collection is usually the best record of what a character has been through.',
    seeAlso: ['Mania', 'Bout of Madness', 'Psychoanalysis', 'Sanity Check'],
    aliases: ['phobias', 'fear'],
  },
  {
    term: 'Mania',
    kind: 'condition',
    short: 'A compulsive obsession acquired from madness — the pull toward a thing rather than away from it.',
    body: 'A **mania** is a phobia\'s mirror: a **compulsion** rather than an aversion. Where a phobia makes you flee, a mania makes you unable to leave it alone — collecting, cleaning, hoarding, setting fires, an obsessive fixation on a person or an idea.\n\nMechanically it works the same way: when the object of the mania is present, the investigator is drawn to it, and the Keeper may require a roll to act against the compulsion or apply penalty dice to anything that isn\'t indulging it.\n\nManias are often more dangerous to a party than phobias, because a phobic investigator runs from the crypt and a maniac walks into it.\n\nLike phobias, they are acquired from bouts of madness and insanities, and treated with **Psychoanalysis**.',
    seeAlso: ['Phobia', 'Bout of Madness', 'Psychoanalysis'],
    aliases: ['manias', 'compulsion', 'obsession'],
  },
  {
    term: 'Cthulhu Mythos',
    kind: 'term',
    short: 'A skill that starts at 0, can never be un-learned, and permanently caps your Sanity at 99 minus its value.',
    body: 'The **Cthulhu Mythos** skill is what you know about the true shape of the universe. It starts at **0** — no investigator begins with any — and it **cannot be bought with skill points at creation**. You only ever gain it by reading the books, surviving the encounters, and casting the spells.\n\nIts effect is the game\'s central bargain: **your maximum Sanity is 99 − your Cthulhu Mythos**. Push Mythos to 30 and you can never again exceed **69** Sanity, no matter how much therapy you get. The knowledge that lets you fight the thing is the knowledge that makes you incapable of being well.\n\nMechanically it lets you **identify** Mythos entities, books and rituals, and it is required to understand many spells. Roll it to recognise what you are looking at — and then live with knowing.\n\nIt cannot be reduced. There is no forgetting.',
    seeAlso: ['Sanity', 'Sanity Recovery', 'INT'],
    aliases: ['mythos', 'cthulhu mythos skill', 'mythos skill'],
  },
  {
    term: 'Sanity Recovery',
    kind: 'mechanic',
    short: 'Sanity returns only in small awards for resolving horrors, through Psychoanalysis, and by recovering from insanity.',
    body: 'There is **no long rest** for the mind. Sanity comes back in three ways, all of them slow:\n\n· **Scenario awards.** At the end of a scenario, the Keeper grants Sanity for having actually resolved the horror — banishing the thing, saving the victims, closing the gate. Failing to resolve it grants nothing.\n· **Psychoanalysis.** A successful treatment session between scenarios restores a small amount.\n· **Recovering from Indefinite Insanity.** Coming out the far side of a long madness restores a meaningful chunk.\n\nSome self-directed activity (indulging a passion, spending time in a normal life, personal projects) can also return points at the Keeper\'s discretion.\n\nAll of it runs into the ceiling: **maximum Sanity is 99 − Cthulhu Mythos**. Recovery can never take you past that, so a veteran investigator recovers *toward a lower and lower number*. The arc only bends one way.',
    seeAlso: ['Sanity', 'Psychoanalysis', 'Cthulhu Mythos', 'Indefinite Insanity'],
    aliases: ['regain sanity', 'recover san', 'healing sanity'],
  },
  {
    term: 'Psychoanalysis',
    kind: 'term',
    short: 'The skill that treats madness: successful sessions restore Sanity and can lift a phobia or mania.',
    body: '**Psychoanalysis** is the only skill that repairs the mind, and it is a between-scenarios activity, not a combat move.\n\nA successful roll over a course of treatment restores a small amount of **Sanity** to the patient, and can be used to lift a **phobia** or **mania** or to shorten an **indefinite insanity**. A **failed** roll can make things worse — a bungled analysis can cost the patient Sanity.\n\nIt cannot be self-administered, and it cannot exceed the patient\'s **maximum Sanity (99 − Cthulhu Mythos)**. It also cannot touch the underlying problem, because the underlying problem is that the things are real.\n\nThe skill is a favourite for parties precisely because it is the one lever they have, and because a group with a psychiatrist survives roughly twice as long.',
    seeAlso: ['Sanity Recovery', 'Phobia', 'Mania', 'Indefinite Insanity'],
    aliases: ['psychoanalyse', 'therapy', 'psychiatry'],
  },

  // ── Combat ───────────────────────────────────────────────────────────────────────────────
  {
    term: 'Combat Round',
    kind: 'mechanic',
    short: 'Turn order is DEX, highest first — no initiative roll — and each turn is one action plus movement.',
    body: 'Combat runs in **DEX order, highest first**. There is **no initiative roll**; you compare a number that is already on the sheet and it does not change from round to round or scenario to scenario.\n\nAn investigator with a **readied firearm** acts before those without, resolving among themselves in DEX order.\n\nOn your turn you get **one action** and you may **move**. That is the whole action economy: no bonus actions, no reactions, no attacks of opportunity, no free object interaction. If you want to do two things, you take two turns.\n\nDefending is not a turn cost. When someone attacks you, you choose **Fight Back** or **Dodge** as part of their attack, and that choice does not consume your own action — but you can only Fight Back or Dodge **once per round** without penalty dice piling on.',
    seeAlso: ['DEX', 'Fighting Back', 'Dodge', 'Opposed Roll'],
    aliases: ['initiative', 'turn order', 'combat turn', 'round'],
  },
  {
    term: 'Fighting Back',
    kind: 'action',
    short: 'Defend by attacking back: an opposed Fighting roll where winning means you deal damage instead of them.',
    body: 'When attacked in melee you may **Fight Back**. Roll your **Fighting** skill against the attacker\'s roll as an **opposed roll**.\n\n· **You win** → their attack misses **and you damage them**.\n· **They win** → their attack lands normally.\n· **Tie** → **the attacker wins**.\n\nThat asymmetry is the entire tactical question of CoC melee: Fighting Back is the only defence that hurts them, and it is the defence that punishes you for being worse at it than they are.\n\nYou may Fight Back or Dodge **once per round** cleanly; a second and subsequent defence in the same round takes a **penalty die**. You cannot Fight Back against a **firearm** at range — bare hands do not reach.\n\nWinning by fighting back also lets you use a **manoeuvre** instead of damage if you have the **Build** for it.',
    seeAlso: ['Dodge', 'Opposed Roll', 'Build', 'Damage Bonus', 'Combat Round'],
    aliases: ['fight back', 'fighting', 'melee', 'brawl'],
  },
  {
    term: 'Dodge',
    kind: 'action',
    short: 'Defend by getting out of the way: an opposed Dodge roll that avoids damage but deals none. Starts at DEX ÷ 2.',
    body: '**Dodge** is a skill starting at **DEX ÷ 2**, and it is the safe defence. When attacked, roll Dodge as an **opposed roll** against the attacker.\n\n· **You win** → the attack misses.\n· **They win** → it hits.\n· **Tie** → **the attacker wins**.\n\nDodging deals **no damage back**. It is strictly defensive, and it is usually the right call against something you cannot hurt.\n\nDodge is unusual among skills: it **improves when you succeed with it**, exactly like any other marked skill, so investigators who survive get better at surviving.\n\nAgainst **firearms** you cannot simply Dodge the bullet — the equivalent is **diving for cover**, which takes your action and drops you prone. The rule of thumb that saves lives: you cannot dodge a gun.',
    seeAlso: ['Fighting Back', 'DEX', 'Opposed Roll', 'Firearms'],
    aliases: ['dodging', 'evade', 'dive for cover'],
  },
  {
    term: 'Firearms',
    kind: 'term',
    short: 'Skill-based ranged attacks that cannot be dodged or fought back, hit harder at close range, and impale.',
    body: '**Firearms** are split by weapon family — **Handgun**, **Rifle/Shotgun**, **Submachine Gun**, **Machine Gun** — each its own skill, each based on DEX.\n\nWhat makes them lethal in this system:\n\n· A target **cannot Dodge or Fight Back** against a gun at range. Their only option is **diving for cover**, which costs their action.\n· At **point blank range** (up to DEX ÷ 5 in yards), you get a **bonus die**.\n· Beyond the weapon\'s **base range** you take a **penalty die**; well beyond it, two.\n· Firearms **impale**, so an **Extreme success** does maximum damage plus a rolled damage die.\n· **Damage Bonus does not apply** — a bullet does not care about your STR.\n\nEach weapon has a **malfunction number**: roll it or higher and the weapon jams. **Aiming** for a full round grants a bonus die. Multiple shots in a round take penalty dice after the first.\n\nA .45 automatic does **1d10 + 2**. An investigator has around **12 HP**. Do the arithmetic before you start a gunfight.',
    seeAlso: ['Impale', 'Dodge', 'Major Wound', 'Bonus Die', 'Armour'],
    aliases: ['guns', 'firearm', 'shooting', 'handgun', 'rifle'],
  },
  {
    term: 'Impale',
    kind: 'mechanic',
    short: 'A property of piercing weapons: an Extreme success (or 01) deals maximum damage PLUS a rolled damage die.',
    body: '**Impaling** weapons — firearms, arrows, spears, knives, anything that punches through rather than mashes — have a special critical effect.\n\nOn an **Extreme success** (or a **critical 01**), the weapon **impales**: it deals its **maximum possible damage**, and then you **roll the damage dice again and add that**.\n\nA .45 automatic doing **1d10 + 2** impales for **10 + 2 + 1d10 + 2** — between **17 and 26**. That kills a typical investigator outright.\n\nThis is why an Extreme success matters even when the Keeper only asked for a Regular one: with an impaling weapon, rolling under one fifth of your skill is not just success, it is a lethal outcome.\n\nBlunt weapons and unarmed attacks do **not** impale; they simply deal maximum damage on an Extreme or critical, with no extra rolled die.',
    seeAlso: ['Extreme Success', 'Firearms', 'Critical Success', 'Major Wound'],
    aliases: ['impaling', 'impales', 'impaling weapon'],
  },
  {
    term: 'Armour',
    kind: 'term',
    short: 'A flat value SUBTRACTED from damage that gets through — there is no armour class and it does not affect the roll.',
    body: '**Armour** in CoC is a straight **subtraction from damage**, never a defence number. An attack that hits rolls its damage, then armour is deducted, and the remainder comes off HP.\n\nThere is **no armour class**. Armour never makes you harder to hit; it makes you harder to hurt. Do not import AC here.\n\nInvestigators in the 1920s are essentially unarmoured — a heavy coat is worth almost nothing. Armour matters mostly on the other side of the table: many Mythos creatures have substantial armour values, and some are immune to mundane weapons entirely no matter how much damage you roll.\n\nBecause armour reduces damage *after* the hit, it also affects whether the blow was a **Major Wound** — you compare the **damage that actually got through** against half your maximum HP.',
    seeAlso: ['Hit Points', 'Major Wound', 'Firearms'],
    aliases: ['armor', 'armour value', 'protection'],
  },
  {
    term: 'Major Wound',
    kind: 'condition',
    short: 'Any single attack dealing HALF your maximum HP or more; forces a CON roll to stay conscious.',
    body: 'A **Major Wound** happens when a **single attack** deals damage **equal to or greater than half your maximum hit points**, after armour. A 12 HP investigator takes a Major Wound from any single hit of **6 or more**.\n\nImmediately:\n\n· Make a **CON roll**. **Fail** and you are knocked **unconscious**.\n· You fall **prone**, and the Keeper may inflict a lasting injury — a broken limb, a permanent APP loss, a scar that changes the character.\n\nA Major Wound is also the switch that turns 0 HP from "unconscious" into "**dying**". Reaching 0 HP *without* a Major Wound just knocks you out and you are stable. Reaching 0 HP *with* one means you are bleeding to death.\n\nHealing a Major Wound is a separate, slower track: you need a successful **CON roll each day** before natural healing even begins.',
    seeAlso: ['Hit Points', 'Dying', 'CON', 'First Aid', 'Armour'],
    aliases: ['major wounds', 'serious wound', 'big hit'],
  },
  {
    term: 'Dying',
    kind: 'condition',
    short: 'At 0 HP with a Major Wound: lose 1 HP per round until First Aid stabilises you, then a CON roll each hour.',
    body: 'Two very different things happen at **0 hit points**:\n\n· **0 HP, no Major Wound** → **unconscious but stable**. You wake in roughly an hour, or sooner with First Aid.\n· **0 HP with a Major Wound** → **dying**. You lose **1 HP every round**. When a successful **First Aid** roll is made you stabilise at **1 HP** — but you are not safe: you must then make a **CON roll each hour**, and a failure means you slip back into dying.\n\nAt **negative HP equal to your maximum**, the investigator is **dead** — no roll, no save, no resurrection. There is nothing in this system that brings people back, and the things that claim to are lying.\n\nA dying investigator is a clock the whole table can see. Somebody has to spend their action on First Aid, right now, instead of shooting the thing.',
    seeAlso: ['Hit Points', 'Major Wound', 'First Aid', 'CON'],
    aliases: ['dying', 'bleeding out', 'zero hp', 'death'],
  },
  {
    term: 'First Aid',
    kind: 'action',
    short: 'A one-action skill roll that stabilises a dying investigator and restores 1d3 HP — once per wound.',
    body: '**First Aid** is the emergency skill and it is the difference between a dead friend and a live one.\n\nA successful roll:\n\n· **Stabilises** a **dying** investigator, bringing them to **1 HP**.\n· Restores **1d3 hit points** to the injured.\n\nIt takes **one action** (about a round) and can only be applied **once per wound** by one person — a second attempt on the same injury by the same investigator does nothing. Another character may try their own roll.\n\nFirst Aid **cannot heal a Major Wound**; it only stabilises. Repairing a Major Wound needs the **Medicine** skill and time, and even then the investigator must pass a **CON roll each day** to begin recovering.\n\nOrdinary healing without any of this is **1 HP per day** of rest. Nobody gets healthy fast in this game.',
    seeAlso: ['Dying', 'Major Wound', 'Hit Points'],
    aliases: ['first aid', 'stabilise', 'stabilize', 'medicine', 'heal'],
  },

  // ── Character construction & advancement ─────────────────────────────────────────────────
  {
    term: 'Occupation',
    kind: 'class',
    short: 'A package of skills and a Credit Rating band — NOT a class. It has no levels, no hit die, and no abilities.',
    body: 'An **Occupation** is what your investigator does for a living: Antiquarian, Author, Detective, Dilettante, Doctor of Medicine, Journalist, Librarian, Occultist, Parapsychologist, Police Detective, Private Investigator, Professor, and dozens more.\n\nIt is emphatically **not a class**. It grants:\n\n· A **list of skills** you may spend occupation points on\n· A **Credit Rating range** appropriate to the job\n· A **points formula** — usually **EDU × 4**, though some use combinations like **EDU × 2 + DEX × 2** or **EDU × 2 + APP × 2**\n\nThat is all. There is **no hit die**, **no level**, **no class feature**, **no spellcasting progression**, and nothing about the occupation changes for the rest of the campaign. A Professor and a Detective differ only in which skills were cheap to buy on day one.\n\nOnce play begins, the occupation is a biography. Skills grow through use, not through the job.',
    seeAlso: ['Occupation Skill Points', 'Personal Interest Skill Points', 'Credit Rating', 'Skill Improvement Check'],
    aliases: ['occupations', 'job', 'profession', 'class'],
  },
  {
    term: 'Occupation Skill Points',
    kind: 'mechanic',
    short: 'Usually EDU × 4 points, spendable only on your occupation\'s skill list and Credit Rating.',
    body: 'Your occupation gives you a pool of points to spend at creation, most commonly **EDU × 4**. An EDU 75 professor gets **300 points**.\n\nSome occupations use different formulas that reward a second characteristic — **EDU × 2 + DEX × 2** for physical jobs, **EDU × 2 + APP × 2** for social ones — so a con artist is not punished for being uneducated.\n\nRules for spending:\n\n· Points go **only** on the occupation\'s listed skills, plus **Credit Rating**.\n· No single skill may be raised above **the maximum for your era** (typically **75%** at creation for a 1920s game; some tables allow higher for the Modern era).\n· Points **add to** the skill\'s base value — they do not replace it. Spot Hidden has a base of 25, so 30 points makes it 55.\n· You **cannot** buy **Cthulhu Mythos** with them. Ever.\n\nSpend them all. They do not carry over, and there is no XP later to make up for hoarding.',
    seeAlso: ['Occupation', 'Personal Interest Skill Points', 'EDU', 'Credit Rating', 'Cthulhu Mythos'],
    aliases: ['occupation points', 'edu x4', 'skill points'],
  },
  {
    term: 'Personal Interest Skill Points',
    kind: 'mechanic',
    short: 'INT × 2 extra points that may be spent on ANY skill, regardless of occupation.',
    body: 'On top of your occupation points you get **INT × 2** points to spend on **any skill you like**, with no regard for your occupation\'s list. An INT 70 investigator gets **140** of them.\n\nThis is where the character stops being a job title. The librarian who shoots, the police detective who reads Latin, the dilettante with a pilot\'s licence — all of them come from personal interest points.\n\nSame restrictions apply: **Cthulhu Mythos cannot be bought**, and the era\'s creation cap still holds.\n\nThe common mistake is dumping personal interest points into more knowledge skills. The investigators who live tend to be the ones who spent them on **Dodge**, a **Firearms** skill, and **Spot Hidden**.',
    seeAlso: ['Occupation Skill Points', 'INT', 'Cthulhu Mythos', 'Dodge'],
    aliases: ['personal points', 'int x2', 'interest points', 'hobby points'],
  },
  {
    term: 'Credit Rating',
    kind: 'term',
    short: 'A skill that IS your wealth: it sets your cash, assets and standard of living, and is capped by occupation.',
    body: '**Credit Rating (CR)** is a skill bought with occupation points, and it doubles as your entire economy. There is no gold piece total — your CR value tells you your **spending level**, your **cash on hand**, and your **assets**:\n\n· **0** — penniless\n· **1–9** — poor\n· **10–49** — average\n· **50–89** — wealthy\n· **90–98** — rich\n· **99** — super rich\n\nEach occupation sets a **CR range** — a Dilettante starts high, a Hobo cannot. You must spend occupation points to reach your occupation\'s minimum.\n\nCR is **rolled** when you need someone to extend you credit, take you seriously as a person of means, or when the question is whether you can afford something unusual. It also drifts in play: sustained high living, or a scenario that ruins you, moves it.\n\nIt is the fastest way to shortcut a scenario — a rich investigator simply buys the boat.',
    seeAlso: ['Occupation', 'Occupation Skill Points', 'EDU', 'APP'],
    aliases: ['cr', 'credit', 'wealth', 'money'],
  },
  {
    term: 'Skill Improvement Check',
    kind: 'mechanic',
    short: 'Between scenarios, roll d100 ABOVE each skill you succeeded with; beat it and gain 1d10 points. There is no XP.',
    body: 'CoC has **no experience points and no levels**. Skills grow one way: by being used successfully.\n\nDuring play, whenever you **succeed** at a skill roll, tick the box next to that skill — it is **marked**. (Marking happens on a success, not on an attempt; failing teaches you nothing.)\n\nBetween scenarios, for each marked skill:\n\n· Roll **d100**.\n· If the result is **greater than the current skill value**, add **1d10** points to it.\n· Then clear the mark.\n\nThe genius of the inversion: **the better you already are, the harder it is to improve**. A skill of 30 improves on 31–100; a skill of 90 improves only on 91–100. Skills naturally plateau without any level cap existing.\n\n**EDU** gets the same treatment via an **EDU improvement check**, capped at **99**. **Luck** may be recovered with the same mechanic at the Keeper\'s option.\n\nA skill that reaches **90+** earns the investigator a Sanity bonus for mastery at some tables — but the core loop is just this: use it, mark it, roll high, grow.',
    seeAlso: ['Regular Success', 'EDU', 'Luck', 'Occupation'],
    aliases: ['improvement', 'skill check', 'advancement', 'xp', 'experience', 'levelling', 'marked skill'],
  },
];
