// lib/dnd/glossary/cyberpunk-red.ts — Cyberpunk RED terms (R. Talsorian Games).
//
// The core roll is 1d10 + STAT + SKILL against a DV. Not d20. There are no levels, no classes, no
// hit dice, no proficiency bonus, and no armor class — armor has STOPPING POWER, which subtracts
// from damage and wears out, and is a completely different animal from AC. Roles are jobs with a
// signature Role Ability, not classes; advancement is a continuous IP spend, never a level-up.
import type { SystemGlossary } from './types';

export const CYBERPUNK_RED_GLOSSARY: SystemGlossary = [
  // ── Core resolution ──────────────────────────────────────────────────────────────────────
  {
    term: 'Check',
    kind: 'mechanic',
    short: 'Roll 1d10 + STAT + SKILL and meet or beat a DV (or the opposing roll) — a single d10, never a d20.',
    body: 'Everything resolves the same way: **1d10 + STAT + SKILL + modifiers**, compared to a **DV (Difficulty Value)** or to an opponent\'s roll.\n\nMeet **or beat** the DV and you succeed. A Handgun 6 Solo with REF 8 rolls **1d10 + 8 + 6**, so they hit a DV 15 on anything but a natural 1 — competent people in this game are genuinely competent, and the d10 is a small swing on top of a large fixed base.\n\nThat is the crucial structural difference from a d20 game. Your **stat + skill** is usually **10–18** and the die is **1–10**, so **who you are matters more than what you roll**. There is no proficiency bonus scaling in the background; the number is just the number.\n\nTwo things break the pattern, and they break it hard:\n\n· A **natural 10** **explodes upward** — roll again and add.\n· A **natural 1** **explodes downward** — roll again and subtract, and it is a **Critical Failure**.\n\nWhen two people directly oppose each other — a Facedown, a grapple, sneaking past a guard — both roll the same way and **the higher total wins**, with ties going to the higher **stat**.',
    seeAlso: ['DV', 'Critical Success', 'Critical Failure', 'Stats', 'Skills', 'Facedown'],
    aliases: ['skill check', 'roll', 'd10', 'stat check', 'test'],
  },
  {
    term: 'DV',
    kind: 'term',
    short: 'Difficulty Value — the number your 1d10 + STAT + SKILL must meet or beat. The common ladder is 13/15/17/21/24.',
    body: '**DV (Difficulty Value)** is the target number. Meet or beat it.\n\nThe standard difficulty ladder:\n\n· **Everyday** — **DV 13**\n· **Difficult** — **DV 15**\n· **Professional** — **DV 17**\n· **Heroic** — **DV 21**\n· **Incredible** — **DV 24**\n\nMany tasks have their own published **DV tables** rather than a vibe-based number — this is the part of the system that most resembles a reference manual. Ranged attacks are the big one: each weapon type has a **DV per range bracket**, so a Very Heavy Pistol at 0–6m is a different DV than the same gun at 25–50m. You look it up; the GM does not invent it.\n\nOther things with their own DV tables: **driving** manoeuvres, **Netrunning** actions against a NET Architecture, **First Aid** and **Paramedic**, **Demolitions**, and the **Trauma Team** response.\n\nBecause STAT + SKILL is typically 10–18, a **DV 13** is nearly automatic for a professional and genuinely uncertain for an amateur. That is the design: DVs sort the trained from the untrained far more than they create drama for experts.',
    seeAlso: ['Check', 'Critical Success', 'Ranged Attack', 'Netrunning'],
    aliases: ['difficulty value', 'dv table', 'target number', 'dc'],
  },
  {
    term: 'Critical Success',
    kind: 'mechanic',
    short: 'A natural 10 on the d10 EXPLODES: roll another d10 and add it to the total.',
    body: 'Roll a **natural 10** on your d10 and it **explodes upward**: roll another **d10** and **add** it to your total.\n\nSo a natural 10 gives you **10 + (1–10)** on the die alone, before stat and skill — a range of **11 to 20** from a single d10. That is what lets an amateur occasionally do something extraordinary, and it is why no DV is ever strictly impossible.\n\nThe second die does **not** explode again. You roll once more and that is the end of it — no infinite chains.\n\nThis applies to **any** check: attacks, skills, opposed rolls. It does **not** apply to **damage** rolls (those are d6s and have their own critical rule) and it does **not** apply to the **Death Save** (which is a roll-under against BODY, where a 10 is simply the worst possible result).\n\nNote what this is not: there is no "critical hit" doubling of damage from a natural 10. A natural 10 makes you more likely to **hit**; the separate **Critical Injury** rule governs whether the hit was catastrophic.',
    seeAlso: ['Check', 'Critical Failure', 'Critical Injury', 'Death Save'],
    aliases: ['crit', 'natural 10', 'exploding die', 'explodes', 'critical'],
  },
  {
    term: 'Critical Failure',
    kind: 'mechanic',
    short: 'A natural 1 on the d10 explodes DOWNWARD: roll another d10 and subtract it, and something goes wrong.',
    body: 'Roll a **natural 1** and the die **explodes downward**: roll another **d10** and **subtract** it from your total.\n\nA natural 1 therefore contributes **1 − (1–10)**, a range of **−9 to 0**. A Solo with REF 8 and Handgun 6 who rolls a natural 1 and then a 9 ends up at **14 − 9 = 5**, and misses a shot they could not otherwise have missed.\n\nAs with the upward version, the **second die does not explode again**.\n\nA natural 1 is also a **Critical Failure** in the fiction, and the GM is entitled to attach a complication on top of the arithmetic: the gun jams, the tool slips, the lie lands wrong, the vehicle fishtails. Some subsystems have explicit fumble tables (Netrunning and driving in particular).\n\nThe important consequence for play: **nobody is ever safe**. A 10% chance of the floor falling out means the ganger with a cheap pistol can genuinely embarrass the corporate hitman, which is exactly the tone the system wants.',
    seeAlso: ['Check', 'Critical Success', 'DV'],
    aliases: ['fumble', 'natural 1', 'crit fail', 'critical fail', 'botch'],
  },
  {
    term: 'Stats',
    kind: 'term',
    short: 'Ten stats rated 2–8 at creation: INT REF DEX TECH COOL WILL LUCK MOVE BODY EMP. Added directly, no modifier table.',
    body: 'Cyberpunk RED has **ten STATS**, each rated **2–8** at creation (humans cap around **10** in play, and some cyberware raises them).\n\nThere is **no modifier table**. The stat is **added directly** to the roll — STAT 8 means **+8**, not +3. This is why a starting character is already good at their job and why the d10 rarely overturns a gap in competence.\n\n· **INT** — Intelligence: perception, education, deduction, Netrunning\n· **REF** — Reflexes: shooting, initiative, dodging, driving\n· **DEX** — Dexterity: athletics, melee, stealth, brawling\n· **TECH** — Technique: repairing, building, medicine, picking locks\n· **COOL** — Cool: nerve, persuasion, interrogation, resisting a Facedown\n· **WILL** — Willpower: resisting torture, concentration, resolve\n· **LUCK** — Luck: a **spendable pool**, refreshed each session\n· **MOVE** — Movement: how far you go per Move Action\n· **BODY** — Body: melee damage, HP, carrying, and the **Death Save**\n· **EMP** — Empathy: reading people, conversation, and the visible face of **Humanity**\n\nBuilding them: the **Streetrat** and **Edgerunner** templates hand you an array; **Complete Package** point-buy gives you a pool to distribute, minimum **2** and maximum **8** in any stat.\n\nTwo stats are unlike the others. **LUCK** is a currency you spend down. **EMP** is not really yours — it is **Humanity ÷ 10**, and it drops every time you install chrome.',
    seeAlso: ['BODY', 'EMP', 'LUCK', 'MOVE', 'Hit Points', 'Humanity', 'Check'],
    aliases: ['stat', 'attributes', 'int', 'ref', 'dex', 'tech', 'cool', 'will'],
  },
  {
    term: 'BODY',
    kind: 'stat',
    short: 'Physical toughness: it sets your HP with WILL, your melee damage, and it is what you roll under on a Death Save.',
    body: '**BODY** is the stat that decides whether you live.\n\nThree jobs:\n\n· **Hit Points** — **HP = 10 + 5 × (the average of BODY and WILL, rounded up)**\n· **Melee and Brawling damage** — your damage dice come off a **BODY table**, not the weapon: BODY 4 is 1d6, 5–6 is 2d6, 7–10 is 3d6, and 11+ is 4d6\n· **The Death Save** — while **Mortally Wounded** you roll **d10 and must come in UNDER your BODY**, with a cumulative penalty\n\nThat last one is why BODY is not just another stat. A **BODY 8** character survives Mortal Wounds that kill a **BODY 4** character outright, and no amount of skill compensates.\n\nBODY also governs carrying capacity, resisting being knocked down or grappled, and how much armor you can wear without penalty.\n\nCyberware — **Grafted Muscle and Bone Lace** and the like — can raise BODY, which is one of the two reasons Solos chrome up. The other reason is that they are shot at frequently.',
    seeAlso: ['Hit Points', 'Death Save', 'Mortally Wounded', 'Stats', 'Melee Attack'],
    aliases: ['body stat', 'toughness'],
  },
  {
    term: 'EMP',
    kind: 'stat',
    short: 'Empathy: reading and connecting with people — and it is simply your Humanity ÷ 10, dropping as you install chrome.',
    body: '**EMP (Empathy)** is the only stat you do not fully control, because **EMP = your current Humanity ÷ 10, rounded down**.\n\nEvery piece of **cyberware** you install costs **Humanity**, and each full **10 points** of Humanity lost takes **1 point of EMP** with it. Chrome yourself to Humanity 39 and your EMP is **3**, permanently, until you get therapy.\n\nEMP is the parent stat for the skills that make you a person: **Conversation**, **Human Perception**, **Interview**, and the social read that tells you someone is lying. A low-EMP character is not just bad at talking — they are **visibly wrong** to other people, which the GM should play.\n\nAt **Humanity 0**, EMP reaches 0 and the character is lost to **cyberpsychosis** and becomes an NPC.\n\nThis is the central bargain of the whole game and it runs in one direction: the chrome that keeps you alive on the street is the thing that stops you being someone worth keeping alive. Every Solo is spending EMP to buy REF, and the bill always comes.',
    seeAlso: ['Humanity', 'Cyberware', 'Cyberpsychosis', 'Stats'],
    aliases: ['empathy', 'emp stat'],
  },
  {
    term: 'LUCK',
    kind: 'stat',
    short: 'A spendable pool: burn points BEFORE a roll to add +1 each. Refreshes fully every session.',
    body: '**LUCK** is a stat and a currency at once. Your LUCK rating is the size of the pool.\n\n· **Spend Luck points BEFORE you roll**, one at a time; each adds **+1** to the check.\n· You may spend as many as you have, on any check.\n· The pool **refreshes completely at the start of each session**.\n\nThe timing rule is what makes it interesting: you must commit **before** seeing the die. You cannot look at a 4 and buy your way to a 15. So spending Luck is a bet on how badly you need this particular roll, made in ignorance.\n\nUse it on: the shot that has to land, the Death Save arithmetic you want to survive, the DV 17 you cannot otherwise reach, the Facedown you cannot afford to lose.\n\nUnlike **Humanity**, Luck comes back — and unlike stress in other games, it costs you nothing but itself. It is the one unambiguously generous mechanic in Night City, which is presumably a joke.',
    seeAlso: ['Stats', 'Check', 'Death Save', 'Improvement Points'],
    aliases: ['luck', 'luck points', 'luck pool', 'spend luck'],
  },
  {
    term: 'MOVE',
    kind: 'stat',
    short: 'Movement: one Move Action carries you MOVE × 2 metres; you get one Move and one Action per turn.',
    body: '**MOVE** is how far you go. A single **Move Action** carries you **MOVE × 2 metres** — MOVE 6 means **12m** per Move Action.\n\nEach turn you get **1 Move Action + 1 Action**, and you may **trade the Action for a second Move**, so a full sprint covers **MOVE × 4 metres** and you do nothing else. That is the whole movement system.\n\nMOVE also governs:\n\n· How high you **jump** (roughly MOVE ÷ 4 metres vertically, with a running start)\n· How far you **leap**\n· **Athletics** and climbing distances\n\nBoth **Seriously Wounded** and **Mortally Wounded** apply penalties to MOVE, which is what makes a wounded character in the open into a dead character. It is the most-forgotten wound penalty at the table and the most lethal.\n\nCyberlegs raise MOVE. A Nomad on a bike does not use MOVE at all — vehicles have their own speeds.',
    seeAlso: ['The Turn', 'Stats', 'Seriously Wounded', 'Mortally Wounded'],
    aliases: ['move stat', 'movement', 'speed', 'run'],
  },
  {
    term: 'Skills',
    kind: 'term',
    short: 'Rated 0–10 and added directly to the roll; bought with points at creation and raised with IP forever after.',
    body: '**Skills** are rated **0 to 10** and are **added directly** to the check alongside the stat. There is no proficiency bonus and no "trained/untrained" binary — a skill of **0** just means you contribute nothing but the stat and the die.\n\nEvery skill has a **parent stat** and an **IP multiplier**:\n\n· Most skills are **×1** — ordinary to learn\n· Some are **×2** — **Difficult** skills that cost double, like the martial arts, Autofire, Heavy Weapons, and the specialised technical skills\n\nEveryone gets a set of free **core skills** at rank 2 or so (Athletics, Brawling, Concentration, Conversation, Education, Evasion, First Aid, Human Perception, Language, Local Expert, Perception, Persuasion, Stealth) — those are the baseline of being a person in Night City.\n\nA skill above **6** is expensive to raise, and a **10** is world-class. The practical ceiling in play is around 8 for most characters.\n\nThe number that matters at the table is **STAT + SKILL**, not either alone. REF 8 + Handgun 4 (**12**) and REF 5 + Handgun 7 (**12**) shoot identically — but the first character also drives, dodges and rolls initiative better, which is why REF is the most contested stat in the game.',
    seeAlso: ['Check', 'Improvement Points', 'Stats', 'DV'],
    aliases: ['skill', 'skill level', 'skill list'],
  },

  // ── Combat ───────────────────────────────────────────────────────────────────────────────
  {
    term: 'The Turn',
    kind: 'mechanic',
    short: 'One Move Action plus one Action per turn — no bonus actions, no reactions. Trade the Action for a second Move.',
    body: 'Each turn you get exactly:\n\n· **1 Move Action** — travel up to **MOVE × 2 metres**\n· **1 Action** — attack, use a skill, operate something, run a Netrunner turn\n\nYou may **swap your Action for a second Move Action** to sprint (**MOVE × 4m**, doing nothing else).\n\nThat is the complete action economy. There are **no bonus actions**, **no reactions**, **no free object interactions**, and **no attacks of opportunity**. If it is a thing, it costs the Action.\n\nThings that cost your Action: firing a weapon (single shot, or **Autofire**, or a **Suppressive Fire** burst), an **Aimed Shot**, a melee attack, First Aid on a friend, hacking, jacking in, drawing *and* firing in the same turn if the GM is strict about it.\n\n**Dodging bullets** is not free — it requires the **Evasion** skill and, for gunfire specifically, a REF **8 or higher** to even attempt. Most people simply get shot at and rely on their **armor**.\n\nOne round is roughly **3 seconds**. Combat is short and it is decisive.',
    seeAlso: ['Initiative', 'MOVE', 'Ranged Attack', 'Melee Attack', 'Armor'],
    aliases: ['turn', 'action economy', 'move action', 'actions', 'round'],
  },
  {
    term: 'Initiative',
    kind: 'mechanic',
    short: 'Roll 1d10 + REF once at the start of combat; act highest first, and keep that order all fight.',
    body: '**Initiative = 1d10 + REF**, rolled **once** at the start of combat. Highest goes first, and that order **holds for the whole fight** — you do not re-roll each round.\n\nThat single roll is why **REF** is the most valuable stat in Cyberpunk RED. A REF 8 character with a good roll acts before everyone, every round, for the entire fight — and in a game where a Very Heavy Pistol does **4d6** into a **35 HP** body, acting first is frequently the entire fight.\n\n**Cyberware** buys initiative directly: the **Sandevistan** and **Kerenzikov** speedware boost initiative or grant extra actions, and they are among the most expensive **Humanity** costs in the book for exactly that reason.\n\nThe **Solo\'s Combat Awareness** Role Ability can be spent on **Initiative Reaction**, adding to the roll — one of the ways a Solo simply refuses to lose the first round.\n\nTies go to the higher **REF**; if that ties too, roll off.',
    seeAlso: ['The Turn', 'Stats', 'Cyberware', 'Solo'],
    aliases: ['init', 'initiative roll', 'turn order'],
  },
  {
    term: 'Ranged Attack',
    kind: 'action',
    short: '1d10 + REF + weapon skill vs a DV read off the weapon\'s range table — the DV rises with distance.',
    body: 'Shooting is **1d10 + REF + the weapon\'s skill** (Handgun, Shoulder Arms, Heavy Weapons, Archery) against a **DV read from the weapon\'s range table**.\n\nThe DV is not invented — every weapon type has a published row of DVs by **range bracket** (0–6m, 7–12m, 13–25m, 26–50m, 51–100m, and out). A pistol at 6m might be **DV 13**; the same pistol at 50m is far harder. **Look it up.**\n\nModes of fire, each costing your **Action**:\n\n· **Single shot** — the default\n· **Aimed Shot** — **−8** to the roll, but you pick a **body location**; a hit on the **head** does **double damage** after that location\'s armor\n· **Autofire** — uses the **Autofire** skill (a ×2 skill); a hit multiplies damage by the margin, capped by the weapon\'s autofire rating\n· **Suppressive Fire** — no damage; forces targets in the area to keep their heads down\n\nDamage is a **flat dice value per weapon** — a Very Heavy Pistol does **4d6**, an Assault Rifle **5d6** — with **no stat added**. Then **armor Stopping Power subtracts**.\n\nYou cannot dodge bullets without **REF 8+** and the **Evasion** skill. Everyone else takes it on the armor.',
    seeAlso: ['DV', 'Armor', 'Stopping Power', 'Critical Injury', 'The Turn', 'Melee Attack'],
    aliases: ['shooting', 'shoot', 'gun', 'attack', 'autofire', 'aimed shot'],
  },
  {
    term: 'Melee Attack',
    kind: 'action',
    short: '1d10 + DEX + Melee Weapon (or Brawling); damage comes off a BODY table, not the weapon.',
    body: 'Melee is **1d10 + DEX + Melee Weapon** (or **Brawling** for fists), opposed by the defender\'s **Evasion** or against a DV the GM sets.\n\nThe unusual part is damage: it comes from a **BODY table**, not from the weapon.\n\n· **BODY 4 or less** — **1d6**\n· **BODY 5–6** — **2d6**\n· **BODY 7–10** — **3d6**\n· **BODY 11+** — **4d6**\n\nA weapon then modifies or replaces this — a **Very Heavy Melee Weapon** does more, **Cyberarms** and **Wolvers** have their own values — but the baseline principle stands: **how hard you hit is about how big you are**, not what you\'re holding.\n\nA **Martial Arts** skill (a ×2 skill) unlocks special moves and better damage than raw Brawling.\n\nMelee reaches **2 metres**. Grappling, choking, and throwing all resolve as opposed BODY-based checks. And melee damage runs into **armor SP** exactly like a bullet does — punching a Solo in a Metalgear jacket accomplishes nothing.',
    seeAlso: ['BODY', 'Ranged Attack', 'Armor', 'Stopping Power', 'The Turn'],
    aliases: ['melee', 'brawling', 'punch', 'martial arts', 'grapple'],
  },
  {
    term: 'Hit Points',
    kind: 'term',
    short: 'HP = 10 + 5 × (the average of BODY and WILL, rounded up) — typically 25–45, and it never grows with "levels".',
    body: '**HP = 10 + 5 × (the average of BODY and WILL, rounded up)**.\n\nBODY 6 and WILL 5 average to 5.5, rounds to **6**, so **HP = 10 + 30 = 40**. BODY 4 and WILL 4 gives **HP = 30**.\n\nMost characters live between **25 and 45 HP**. That is the whole range, forever. **HP does not scale** — there is no level, no hit die, no per-level HP gain. A character who has survived a year of campaigns has exactly the HP their BODY and WILL say they have, and an Assault Rifle still does **5d6**.\n\nThe two thresholds that matter:\n\n· **Seriously Wounded** at **half your maximum HP or below**\n· **Mortally Wounded** at **0 HP or below** — Death Saves begin\n\nRecovery is slow and medical, not magical: you heal HP per day of rest based on BODY, faster with a successful **First Aid** or **Paramedic** check, faster still in a **Trauma Team** bay or a cryotank. Nothing in this setting brings back the dead — **Trauma Team** just gets there before you finish dying, if you paid the subscription.',
    seeAlso: ['BODY', 'Seriously Wounded', 'Mortally Wounded', 'Death Save', 'Stopping Power'],
    aliases: ['hp', 'health', 'hit points', 'wounds'],
  },
  {
    term: 'Armor',
    kind: 'term',
    short: 'Rated in Stopping Power, which subtracts from damage and ablates as it takes hits. There is NO armor class.',
    body: 'Armor in Cyberpunk RED is worn **by location** — **head** and **body** each have their own armor and their own **SP** — and it does exactly one thing: **subtract from damage**.\n\n**It never affects whether you are hit.** There is **no armor class** here. A Solo in a Metalgear is just as easy to shoot as a naked civilian; the bullets simply do not accomplish much.\n\nThe common armor ladder by SP:\n\n· **Leathers** — SP 4\n· **Kevlar** — SP 7\n· **Light Armorjack** — SP 11\n· **Medium Armorjack** — SP 12\n· **Heavy Armorjack** — SP 13\n· **Flak** — SP 15\n· **Metalgear** — SP 18\n\nHeavier armor imposes a **penalty to REF, DEX and MOVE** — Metalgear makes you a slow, invulnerable target, which is a real trade.\n\nIf you wear two layers, you use the **higher SP** and take a penalty; you do **not** add them together.\n\nArmor **ablates** — every hit it stops wears it down — and it can be repaired with **TECH**. **Subdermal armor** and **Skinweave** cyberware give SP that cannot be shot off, at a Humanity cost.',
    seeAlso: ['Stopping Power', 'Ablation', 'Armor-Piercing', 'Hit Points', 'Cyberware'],
    aliases: ['armour', 'sp', 'kevlar', 'armorjack', 'metalgear', 'ac'],
  },
  {
    term: 'Stopping Power',
    kind: 'mechanic',
    short: 'SP is SUBTRACTED from each hit\'s damage before it touches HP. It is not AC and never changes the attack roll.',
    body: '**Stopping Power (SP)** is the number that makes armor work: when a hit lands, **damage minus SP** is what reaches your HP.\n\nA Heavy Pistol does **3d6**. Against **SP 11 Light Armorjack**, an average roll of 10 or 11 does **nothing at all**. Against a naked target it does 10. That is the entire difference between an armored edgerunner and a corpse.\n\nSay it plainly, because this is the single most common cross-system error: **SP is not armor class**. It does not go on a defence roll. It does not make you harder to hit. It reduces damage **after** the attack has already succeeded.\n\nThree consequences that shape every firefight:\n\n· **Small guns become useless** against real armor. A 2d6 SMG round cannot get through SP 11 reliably, so you bring a bigger gun or you bring **Armor-Piercing**.\n· **Armor wears out** — every hit **ablates** it by 1.\n· **Critical Injuries bypass SP entirely** — the +5 from a Critical Injury goes straight through.\n\nSP is checked **per location**. A head shot compares against the **head\'s** SP, which is why Aimed Shots at an unarmoured head end fights.',
    seeAlso: ['Armor', 'Ablation', 'Armor-Piercing', 'Critical Injury', 'Ranged Attack'],
    aliases: ['sp', 'stopping power', 'armor value', 'damage reduction'],
  },
  {
    term: 'Ablation',
    kind: 'mechanic',
    short: 'Every time armor stops damage its SP drops by 1; at SP 0 it is destroyed. Repair it with TECH.',
    body: '**Ablation** is the rule that stops armor from being a permanent solution. **Each time a location\'s armor stops damage, its SP is reduced by 1.**\n\nSo **SP 11 Light Armorjack** that has absorbed four hits is now **SP 7**, and by the end of a long firefight it is not doing the job you bought it for. Armor at **SP 0** is **destroyed** and offers nothing.\n\nIt ablates **faster** against some things:\n\n· **Armor-Piercing** rounds ablate it by **2**\n· Some heavy weapons and explosives chew through it quickly\n\nRepair it between jobs with a **TECH** check and time — a Tech with the **Maker** ability does this properly and cheaply, which is one of the quiet reasons a crew wants a Tech.\n\n**Subdermal armor** and **Skinweave** cyberware also ablate, but they are repaired surgically rather than at a workbench.\n\nThe practical upshot: armor is **consumable**. The Solo who wins the first fight of the night walks into the second one wearing something meaningfully worse, and that attrition curve is how Night City kills people who won.',
    seeAlso: ['Armor', 'Stopping Power', 'Armor-Piercing', 'Tech'],
    aliases: ['ablate', 'ablates', 'armor damage', 'armor wear'],
  },
  {
    term: 'Armor-Piercing',
    kind: 'term',
    short: 'AP ammunition halves the target\'s SP (rounding up) and ablates it by 2 — but does less damage once through.',
    body: '**Armor-Piercing (AP)** ammunition is the answer to Stopping Power, and it costs you something for the privilege.\n\n· It **halves the target\'s SP** for that hit, **rounding up**. SP 11 Light Armorjack becomes **SP 6**.\n· It **ablates** the armor by **2** instead of 1.\n· But the round does **reduced damage** once it has punched through — you trade raw stopping force for penetration.\n\nAgainst an unarmoured target, AP is strictly worse than a normal round. Against **Metalgear (SP 18 → 9)**, it is the difference between a firefight and a waste of ammunition.\n\nThis is the arms-race the setting runs on. Armor gets heavier; ammunition gets smarter; the Solo carries two magazines and has to guess which fight they are walking into.\n\nOther specialist ammunition exists on the same principle — **Expansive** does more damage but is stopped cold by armor, **Rubber** is non-lethal, **Incendiary** and **Biotoxin** have their own effects. They are all **per-shot** decisions that cost eddies.',
    seeAlso: ['Stopping Power', 'Armor', 'Ablation', 'Ranged Attack'],
    aliases: ['ap', 'ap ammo', 'armour piercing', 'armor piercing rounds'],
  },
  {
    term: 'Critical Injury',
    kind: 'mechanic',
    short: 'Roll two 6s on the damage dice: +5 damage that IGNORES armor, plus a rolled lasting injury.',
    body: 'The nastiest rule in the combat chapter, and it fires off the **damage** roll rather than the attack roll.\n\nIf **two or more of your damage d6s come up 6**, you have inflicted a **Critical Injury**:\n\n· **+5 damage**, and that 5 **bypasses armor entirely** — SP does nothing against it\n· **Roll on the Critical Injury table** for the body location you hit\n\nThe injuries are lasting and specific — **Foreign Object**, **Broken Ribs**, **Broken Arm**, **Collapsed Lung**, **Damaged Eye**, **Concussion**, **Whiplash**, and at the head end, things that end careers. Each carries its own ongoing penalty and its own **DV to treat** (some need **surgery**, not a First Aid check).\n\nThis is why **more damage dice** matter more than the average suggests. A **5d6** Assault Rifle has a far better chance of showing two 6s than a **2d6** SMG, so heavy weapons are not just louder — they are structurally more likely to cripple.\n\nAnd it is why armor does not make you safe. **SP 18 Metalgear** stops the bullets and does nothing whatsoever about the +5 and the broken ribs.',
    seeAlso: ['Stopping Power', 'Ranged Attack', 'Seriously Wounded', 'Hit Points'],
    aliases: ['crit injury', 'critical hit', 'crit', 'two sixes', 'injury table'],
  },
  {
    term: 'Seriously Wounded',
    kind: 'condition',
    short: 'At half your maximum HP or below: −2 to REF, DEX and MOVE. The spiral starts here.',
    body: 'You are **Seriously Wounded** the moment your HP drops to **half your maximum or below** (round up).\n\nThe penalty: **−2 to REF, DEX and MOVE**.\n\nThat looks small. It is not. **REF** is your attack roll and your initiative; **DEX** is your melee and stealth; **MOVE** is your ability to get out of the open. A −2 to all three, applied at the exact moment you most need them, is the game\'s way of saying that fights are won in the first round.\n\nThe knock-on effects are what actually kill you:\n\n· You **hit less**, so the fight lasts longer, so you get shot more.\n· You **move slower**, so you cannot reach cover.\n· You are two bad rolls from **Mortally Wounded**.\n\nSome cyberware and drugs (**Berserker**, **Black Lace**, and the like) suppress the penalty, at their own cost. The **Solo\'s Combat Awareness** can offset some of it.\n\nThe correct read: when a party member goes Seriously Wounded, that is the signal to change what you are doing. Not to press on.',
    seeAlso: ['Hit Points', 'Mortally Wounded', 'Death Save', 'First Aid', 'MOVE'],
    aliases: ['seriously wounded', 'sw', 'half hp', 'wounded'],
  },
  {
    term: 'Mortally Wounded',
    kind: 'condition',
    short: 'At 0 HP or below: you make a Death Save every turn, at a penalty that grows each time.',
    body: 'At **0 HP or below** you are **Mortally Wounded**. You are not dead — yet — and you are not simply unconscious either.\n\nWhat happens:\n\n· You must make a **Death Save every turn**, and the penalty on it **grows with each one you take**\n· Your stats take a **severe penalty** — far worse than the Seriously Wounded −2\n· You cannot act meaningfully; you are bleeding out on the ground\n\nGetting out requires someone to **stabilise** you: a **First Aid** or **Paramedic** check against a DV, which stops the Death Saves. It does **not** heal you — it stops the clock. You are still Mortally Wounded until you are treated properly.\n\nDamage taken **while** Mortally Wounded pushes you further negative, and there is a floor: exceed it and you are simply **dead**, with no save.\n\n**Trauma Team** exists for this exact moment. If you have the subscription and someone hits the button, an AV drops medics onto the street with guns and a cryotank. This is the closest thing Night City has to resurrection and it costs a monthly fee.',
    seeAlso: ['Death Save', 'Hit Points', 'Seriously Wounded', 'First Aid', 'BODY'],
    aliases: ['mortally wounded', 'mw', 'dying', 'zero hp', 'bleeding out'],
  },
  {
    term: 'Death Save',
    kind: 'mechanic',
    short: 'While Mortally Wounded: roll d10 and come in UNDER your BODY. The penalty rises by 1 with every save you make.',
    body: 'The one roll in Cyberpunk RED that runs **backwards**. While **Mortally Wounded**, at the start of each of your turns:\n\n· Roll **1d10** and **add your accumulated Death Save penalty**\n· The result must come in **UNDER your BODY**\n· **Fail and you die.**\n\nAnd then the trap: **each Death Save you make increases your penalty by 1**, cumulatively. Your first save with **BODY 7** needs under 7 on a clean d10 — good odds. Your fourth needs **d10 + 3** under 7, meaning you must roll a 3 or less. Your seventh is arithmetically impossible.\n\n**You cannot survive this by rolling well.** You can only survive it by someone **stabilising** you — a **First Aid** or **Paramedic** check — before the penalty catches up. The Death Save is not a survival mechanic; it is a **countdown telling your friends how many turns they have**.\n\nNote it is not a d20 death save, and there are no "successes to stabilise". There is no threshold of three. There is only the ticking penalty and the arithmetic.\n\n**BODY** is everything here. **LUCK cannot help** — Luck adds, and here adding is what kills you.',
    seeAlso: ['Mortally Wounded', 'BODY', 'First Aid', 'Hit Points'],
    aliases: ['death save', 'death saves', 'dying roll', 'death save penalty'],
  },
  {
    term: 'First Aid',
    kind: 'action',
    short: 'A TECH-based check to stabilise a Mortally Wounded character and stop the Death Saves. It does not really heal.',
    body: '**First Aid** is a **TECH**-based skill, and it is the button somebody has to press when a friend hits 0.\n\nA successful check against the DV **stabilises** a **Mortally Wounded** character: the **Death Saves stop**. It restores a small amount of HP, and that is all — the character is still critically hurt, still penalised, and still needs real medical care.\n\n**Paramedic** is the better version — a ×2 skill that handles harder cases and higher DVs.\n\nEscalating up the ladder:\n\n· **First Aid** (TECH) — stop the bleeding, stop the saves\n· **Paramedic** (TECH, ×2) — field medicine that actually works\n· **Surgery** (TECH, ×2) — the only way to fix many **Critical Injuries**\n· A **Medtech** with the **Medicine** Role Ability — the real thing; they can treat Critical Injuries, install cyberware, and use a cryotank\n· **Trauma Team** — a paid subscription and an armed AV\n\nWhat is absent, deliberately: **there is no healing magic, no potion, and no overnight full heal**. Recovery is days of rest scaled by BODY, or a cryotank and a bill.',
    seeAlso: ['Mortally Wounded', 'Death Save', 'Hit Points', 'Medtech', 'Critical Injury'],
    aliases: ['first aid', 'paramedic', 'stabilise', 'stabilize', 'heal', 'medicine'],
  },
  {
    term: 'Facedown',
    kind: 'action',
    short: 'An opposed 1d10 + COOL + Reputation roll — the loser backs down before anyone draws.',
    body: 'A **Facedown** is the stare across the bar, and it is a real mechanic: **1d10 + COOL + Reputation**, opposed, against the other party\'s same roll.\n\nThe loser **backs down** — walks away, defers, blinks. The winner gets what they were pushing for without a shot being fired.\n\nWhy **Reputation** is in that formula is the whole point. Being *known* is mechanically load-bearing. A Solo with a Rep of 6 walks into rooms already halfway to winning the argument, because everyone present has heard what happened to the last people who tried.\n\nFacedowns work on **NPCs** in a structured way — the GM rolls for them like a check, and gangers with low COOL and no Rep genuinely fold.\n\nThe honest strategic note: a Facedown is the **cheapest possible win** in this game. Combat costs armor ablation, ammunition, Critical Injuries, and Death Saves. Winning the Facedown costs a roll. Characters who build COOL and Rep are choosing not to bleed.',
    seeAlso: ['Reputation', 'Stats', 'Check'],
    aliases: ['facedown', 'face down', 'stare down', 'cool roll'],
  },
  {
    term: 'Reputation',
    kind: 'term',
    short: 'A 0–10 rating of how known you are; it feeds Facedowns and shapes how Night City reacts to you.',
    body: '**Reputation (Rep)** rates how famous — or infamous — you are on the Street, from **0** (nobody) to **10** (a legend people tell stories about).\n\nWhat it does mechanically:\n\n· It is **added to Facedown rolls** (1d10 + COOL + Rep)\n· It gates how NPCs treat you before you have said a word\n· It shapes what jobs come to you, and what jobs come *for* you\n\nYou earn Rep by doing things people **witness and talk about**. Killing a famous Solo in public raises it. Quietly succeeding at a job nobody saw raises nothing — and that is a genuine tension for a crew that would rather not be known.\n\nRep is **not** a stat you buy at creation with points and it is not raised with **IP** the way skills are. It accrues from play.\n\nIt is also a liability. High Rep means people can find you, name you, and price your head. The Solo everyone has heard of is the Solo somebody is currently being paid to remove.',
    seeAlso: ['Facedown', 'Stats', 'Improvement Points'],
    aliases: ['rep', 'reputation', 'fame', 'street rep'],
  },

  // ── Humanity and chrome ──────────────────────────────────────────────────────────────────
  {
    term: 'Humanity',
    kind: 'term',
    short: 'Starts at EMP × 10; every piece of cyberware costs some. Your EMP is always Humanity ÷ 10.',
    body: '**Humanity** starts at **your EMP × 10** — EMP 7 means **70 Humanity** — and it only ever goes down.\n\nEvery piece of **cyberware** has a **Humanity Loss** cost, rolled on installation (commonly **2d6** for ordinary chrome, much more for the extreme stuff). Subtract the roll from your Humanity.\n\nThen the rule that gives the whole game its shape: **EMP = Humanity ÷ 10, rounded down**. Drop from 70 to 69 and nothing happens. Drop to 59 and your **EMP falls to 5** — permanently, along with every Conversation, Human Perception and Interview check you will ever make.\n\nAt **Humanity 0**, the character becomes a **cyberpsycho** and is taken by the GM.\n\nHumanity can be **restored** — this is the mechanic most tables forget exists. A **Therapy** check from a qualified professional, over time and for real money, can heal Humanity back up (though never above your original maximum, and never past what your remaining chrome permits).\n\nCheap cyberware is cheap in eddies. It is never cheap in Humanity. That is the joke the setting is built on: the more you can survive Night City, the less of you there is that Night City could have hurt.',
    seeAlso: ['EMP', 'Cyberware', 'Cyberpsychosis', 'Medtech'],
    aliases: ['humanity loss', 'hl', 'humanity points'],
  },
  {
    term: 'Cyberware',
    kind: 'term',
    short: 'Implants bought with eddies, surgery time, and HUMANITY — the third cost is the one that matters.',
    body: '**Cyberware** costs three things, and players only ever budget for the first two:\n\n· **Eddies** (money)\n· **Surgery** — a difficulty rating, a Medtech, and downtime; botched surgery does real damage\n· **Humanity Loss** — rolled on installation, and this one never comes back on its own\n\nThe categories: **Fashionware** (nearly free in Humanity), **Neuralware** (the Neural Link, and everything that plugs into it), **Cyberoptics**, **Cyberaudio**, **Internal** and **External Body**, **Cyberlimbs**, and **Borgware** (which will cost you enormously).\n\nWhat chrome actually buys you is the things that win fights: **initiative** (Sandevistan, Kerenzikov), **stats** (Grafted Muscle raises BODY), **SP that cannot be shot off** (Subdermal Armor, Skinweave), **built-in weapons**, and, for a Netrunner, the **Interface Plugs** without which they cannot work at all.\n\nThe **Netrunner** and the **Solo** are the two Roles that essentially cannot function unchromed, and they are correspondingly the two Roles closest to **cyberpsychosis** at any given moment.\n\nA **Medtech** with the Medicine ability installs it. A ripperdoc in a back alley installs it cheaper. You get what you pay for.',
    seeAlso: ['Humanity', 'EMP', 'Cyberpsychosis', 'Medtech', 'Netrunner', 'Armor'],
    aliases: ['chrome', 'implants', 'cyber', 'borgware', 'cyberlimb'],
  },
  {
    term: 'Cyberpsychosis',
    kind: 'condition',
    short: 'What happens at Humanity 0: the character is gone, taken by the GM as an NPC. It is not a status you recover from.',
    body: '**Cyberpsychosis** is the end state of the Humanity track. At **Humanity 0**, the character stops being yours. The GM takes them as an **NPC** — a **cyberpsycho**, one of the things the Psycho Squad gets called about.\n\nThere is no saving throw, no roll, and no coming back. It is not a condition you play through. It is a **retirement mechanic** with a body count.\n\nThe warning signs are mechanical and visible for a long time before it happens:\n\n· **EMP falling** as Humanity drops — you become visibly wrong to other people\n· Difficulty with the EMP skills: **Conversation**, **Human Perception**\n· The GM is entitled to press on your alienation as your Humanity sinks\n\nThe brake is **Therapy**: a qualified professional, real money, and real time can restore Humanity before you hit the floor. It is expensive and it requires the character to actually **stop and do it**, which is exactly what an edgerunner spiralling toward zero will not do.\n\nThis is the moral engine of Cyberpunk. It is not a punishment for bad play — it is the destination the system points every optimised character at, and staying human is a **choice you have to keep paying for**.',
    seeAlso: ['Humanity', 'EMP', 'Cyberware'],
    aliases: ['cyberpsycho', 'psycho', 'humanity zero'],
  },
  {
    term: 'Improvement Points',
    kind: 'mechanic',
    short: 'IP is the only advancement: spend it per-skill. There are no levels and no level-up moments.',
    body: '**Improvement Points (IP)** are what Cyberpunk RED has instead of levels, and they work continuously rather than in jumps.\n\nThe GM awards IP for a session\'s work — doing your Role\'s job well, achieving goals, taking risks. You then spend it **per skill**:\n\n· The IP cost to raise a skill is based on the **new level** you are buying, multiplied by the skill\'s **IP multiplier** (**×1** for ordinary skills, **×2** for Difficult ones)\n· Raising a skill **above 6** costs **double**, which is why 7+ in anything is a statement\n· **Role Abilities** are raised with IP the same way\n\nThere is **no level, no level-up, no XP threshold, no hit die, no class feature you unlock at 5th**. Nothing about your character changes because a number crossed a line. You get better at exactly the things you spend on.\n\nThe consequences for play are real: **advancement is slow and narrow**. You will not become good at a new skill quickly. If you want to be a Netrunner, you should have been one at creation.\n\nWhat you *can* buy fast is **chrome** — cyberware costs eddies, not IP, and eddies come from jobs. This is why characters improve by getting more dangerous rather than more skilled, and why Humanity falls.',
    seeAlso: ['Skills', 'Role Ability', 'Cyberware', 'Reputation'],
    aliases: ['ip', 'improvement points', 'xp', 'experience', 'advancement', 'level up'],
  },

  // ── Roles ────────────────────────────────────────────────────────────────────────────────
  {
    term: 'Role',
    kind: 'class',
    short: 'Your job in Night City plus one signature Role Ability. NOT a class: no levels, no hit die, no class features.',
    body: 'Your **Role** is what you do for a living, and it grants exactly one mechanical thing: a **Role Ability**, rated **1–10** and raised with **IP**.\n\nThe ten Roles: **Rockerboy**, **Solo**, **Netrunner**, **Tech**, **Medtech**, **Media**, **Exec**, **Lawman**, **Fixer**, **Nomad**.\n\nWhat a Role is **not**: it is **not a class**. There is **no hit die**, **no level**, **no saving throw progression**, **no spell list**, and **no feature you unlock later**. A Solo and a Fixer have the same HP formula, the same skill list available to them, and the same access to every weapon in the book. The Solo is not "the fighter" — a Fixer with REF 8 and Handgun 6 shoots exactly as well.\n\nWhat the Role Ability does is give you a thing **nobody else can do at all**. Only a Netrunner can run the NET. Only a Medtech can treat a Critical Injury properly. Only a Tech can build and upgrade. That exclusivity, not raw power, is what makes Roles matter.\n\nYou can take a **second Role** (Multi-Role) by splitting your IP between two Role Abilities, and it is usually a mistake — a rank 4 Solo and a rank 4 Netrunner is worse at both jobs than either specialist.',
    seeAlso: ['Role Ability', 'Solo', 'Netrunner', 'Tech', 'Medtech', 'Fixer', 'Improvement Points'],
    aliases: ['roles', 'class', 'job', 'archetype'],
  },
  {
    term: 'Role Ability',
    kind: 'feature',
    short: 'The one thing your Role can do that nobody else can, rated 1–10 and raised with IP.',
    body: 'Each Role has exactly **one** Role Ability, rated **1–10**, raised with **IP**. It is the whole mechanical content of the Role.\n\n· **Solo — Combat Awareness.** Allocate your rank across **Damage Deflection**, **Fumble Recovery**, **Initiative Reaction**, **Precision Attack**, **Spot Weakness** and **Threat Detection**.\n· **Netrunner — Interface.** Rates the NET actions (**Backdoor**, **Cloak**, **Control**, **Eye-Dee**, **Pathfinder**, **Slide**, **Virus**, **Zap**) and governs what you can do in a NET Architecture. Without it you cannot run the NET at all.\n· **Tech — Maker.** Allocate rank across **Field Expertise**, **Upgrade Expertise**, **Fabrication Expertise** and **Invention Expertise**. Repair, improve and build.\n· **Medtech — Medicine.** Allocate across **Surgery**, **Pharmaceuticals** and **Cryosystem Operation**. Treat Critical Injuries, install cyberware, run a cryotank.\n· **Rockerboy — Charismatic Impact.** Move crowds; sway a mob to your cause.\n· **Media — Credibility.** Get the story believed, and get people to talk to you.\n· **Exec — Teamwork.** Corporate resources and a team of people who answer to you.\n· **Lawman — Backup.** Call in the badge; how much of it arrives depends on rank.\n· **Fixer — Operator.** Find, buy, sell, and broker; the only Role that reliably gets scarce things.\n· **Nomad — Moto.** Family vehicles and the pull of the pack.\n\nSeveral of them (Combat Awareness, Maker, Medicine) are **point pools you allocate**, not flat bonuses — you choose what kind of Solo or Tech you are within the ability.',
    seeAlso: ['Role', 'Solo', 'Netrunner', 'Tech', 'Medtech', 'Fixer', 'Improvement Points'],
    aliases: ['role abilities', 'ability', 'combat awareness', 'interface', 'maker', 'operator'],
  },
  {
    term: 'Solo',
    kind: 'class',
    short: 'The professional killer. Their Role Ability, Combat Awareness, is a pool spent across six combat edges.',
    body: 'The **Solo** is a hired gun, bodyguard, assassin, or corporate enforcer — the person you bring when the answer is violence.\n\nTheir Role Ability is **Combat Awareness**, and it works as a **pool of points equal to your rank**, allocated across six sub-abilities:\n\n· **Damage Deflection** — reduce damage that gets through\n· **Fumble Recovery** — soften a natural 1\n· **Initiative Reaction** — add to initiative, so you act first\n· **Precision Attack** — reduce the penalty on **Aimed Shots**\n· **Spot Weakness** — extra damage against a target you have studied\n· **Threat Detection** — you are not surprised\n\nAllocating those points is the real character choice. A Solo built into Initiative Reaction and Precision Attack is a first-round decapitator; one built into Damage Deflection and Threat Detection is a bodyguard who does not die.\n\nWhat the Solo does **not** get: **no extra HP**, **no hit die**, **no attack bonus**, **no armor class**. Their HP formula is everyone\'s HP formula. They survive by acting first, by **chrome**, and by **Metalgear** — and every one of those costs **Humanity**.\n\nThe Solo is the Role that goes cyberpsycho. Not by accident — by design.',
    seeAlso: ['Role Ability', 'Initiative', 'Cyberware', 'Humanity', 'Cyberpsychosis', 'Armor'],
    aliases: ['solos', 'combat awareness', 'gunslinger', 'fighter'],
  },
  {
    term: 'Netrunner',
    kind: 'class',
    short: 'The hacker. Their Interface ability is the only way to run a NET Architecture — nobody else can do it at all.',
    body: 'The **Netrunner** runs the NET. Their Role Ability is **Interface**, and it is the single most exclusive ability in the game: **without it you cannot Netrun**. Not badly — **at all**.\n\nInterface rank rates each of the Netrunner\'s NET actions and governs how much they can accomplish per NET turn:\n\n· **Backdoor** — get past a Password node\n· **Cloak** — hide from Black ICE and other runners\n· **Control** — take over a system, camera, door, or turret\n· **Eye-Dee** — identify a file or program\n· **Pathfinder** — map the architecture ahead of you\n· **Slide** — escape from an attacking program\n· **Virus** — install a hostile program\n· **Zap** — attack a program or another runner directly\n\nThe Netrunner is the most **equipment-dependent** Role: they need **Interface Plugs** (cyberware, so **Humanity**), a **cyberdeck**, and a set of **programs** — Boosters, Defenders, Attackers, and Anti-Program. All of it costs eddies, and the deck has limited **slots**.\n\nAnd the structural problem the table has to solve: a Netrunner\'s **NET turn happens on their own action**, in a different space, while everyone else is being shot at. Running the NET is fast in the fiction and slow at the table — good tables cut between the two constantly.',
    seeAlso: ['Netrunning', 'NET Architecture', 'Role Ability', 'Cyberware', 'Humanity'],
    aliases: ['netrunners', 'runner', 'hacker', 'interface'],
  },
  {
    term: 'Netrunning',
    kind: 'mechanic',
    short: 'Diving a NET Architecture floor by floor with Interface actions, fighting ICE and racing the clock.',
    body: '**Netrunning** is the Netrunner\'s parallel game. A **NET Architecture** is a **vertical stack of floors**, and you descend it one at a time.\n\nHow it runs:\n\n· You **jack in** (Interface Plugs, cyberdeck) and start at the top floor.\n· Each floor holds **one thing**: a **Password**, a **File**, a **Control Node**, or a piece of **Black ICE**.\n· You spend **NET Actions** on your turn — **Pathfinder** to see what is below, **Backdoor** to crack a Password, **Eye-Dee** to identify a File, **Control** to seize a Node, **Zap** or a program to fight ICE, **Slide** to escape.\n· You do **not** know what is on the next floor until you look. Diving blind is how runners die.\n\n**Black ICE** fights back and it fights back **at your brain**. Damage from ICE can hit the Netrunner directly, and being **jacked in** while your body is in a firefight is exactly as bad an idea as it sounds.\n\nPrograms fill your deck\'s **slots** and come in four kinds: **Boosters** (improve your actions), **Defenders** (protect you), **Attackers** (kill ICE and other runners), and **Anti-Program** (specialised counters).\n\nA run is a **race**. The architecture is not passive — the longer you are in it, the more likely something notices.',
    seeAlso: ['Netrunner', 'NET Architecture', 'Role Ability', 'DV'],
    aliases: ['netrun', 'hacking', 'the net', 'net run', 'jack in'],
  },
  {
    term: 'NET Architecture',
    kind: 'term',
    short: 'A system rendered as a stack of floors, each holding one password, file, control node, or piece of Black ICE.',
    body: 'A **NET Architecture** is how Cyberpunk RED models a computer system: **a tower of floors** the Netrunner descends one at a time. It is deliberately not a sprawling virtual world — the Net collapsed, and what is left is small, local, and defended.\n\nEach floor contains **exactly one** thing:\n\n· A **Password** — locked; get past it with **Backdoor**\n· A **File** — the data you came for; identify it with **Eye-Dee**\n· A **Control Node** — the door, the camera, the turret; seize it with **Control**\n· **Black ICE** — a defensive program that will attack you\n\nThe GM builds the architecture in advance — depth, contents, and what ICE is lurking — and the Netrunner discovers it via **Pathfinder** or by walking into it.\n\n**Depth signals value.** A two-floor architecture is a vending machine. A seven-floor one with three pieces of Black ICE is guarding something that will get you killed.\n\nThe important structural point: architectures are **local**. You generally have to be physically near the thing you are hacking, which is why the Netrunner is **in the van outside** rather than at home in bed — and why they are in the firefight too.',
    seeAlso: ['Netrunning', 'Netrunner', 'Role Ability'],
    aliases: ['architecture', 'net arch', 'the net', 'floors', 'black ice', 'ice'],
  },
  {
    term: 'Tech',
    kind: 'class',
    short: 'The builder and repairer. Maker lets them fix, upgrade, fabricate, and invent things nobody else can.',
    body: 'The **Tech** makes things work. Their Role Ability is **Maker**, a **pool of points equal to their rank** allocated across four specialities:\n\n· **Field Expertise** — repair things fast, in the field, with what you have\n· **Upgrade Expertise** — improve weapons, armor and gear beyond factory spec\n· **Fabrication Expertise** — build gear from parts, cheaper than buying it\n· **Invention Expertise** — create genuinely new things\n\nWhy a crew wants one: **armor ablates** and **weapons break**. A Tech repairs your Metalgear back to SP 18 between jobs instead of you buying new Metalgear. Over a campaign that is an enormous amount of money, and money is what buys **chrome**.\n\n**Upgrade Expertise** is the one that changes fights — an upgraded weapon or a **excellent-quality** armor set is a permanent edge nobody else in Night City has.\n\nThe Tech is the least glamorous Role and the one that most reliably makes the party richer. They also tend to have the **highest TECH**, which means they are frequently the party\'s backup **First Aid**, **Demolitions**, and lockpick.\n\nNo hit die, no level, no class features — like every Role, just the ability and the skills you bought.',
    seeAlso: ['Role Ability', 'Ablation', 'Armor', 'Improvement Points'],
    aliases: ['techs', 'maker', 'mechanic', 'engineer'],
  },
  {
    term: 'Medtech',
    kind: 'class',
    short: 'The street doctor. Medicine is the only ability that properly treats Critical Injuries and installs cyberware.',
    body: 'The **Medtech** is the reason anyone survives a campaign. Their Role Ability is **Medicine**, a **pool of points equal to their rank** allocated across three specialities:\n\n· **Surgery** — treat **Critical Injuries** properly; without this, many of them simply do not heal\n· **Pharmaceuticals** — manufacture drugs, from combat stims to real medicine\n· **Cryosystem Operation** — run a cryotank, which is the closest thing Night City has to a resurrection\n\nWhat only a Medtech can do:\n\n· **Install cyberware** safely (a back-alley ripperdoc is cheaper and worse)\n· **Repair Critical Injuries** that a First Aid check cannot touch\n· **Restore Humanity** through **Therapy** — the one brake on the cyberpsychosis spiral\n\nThat last one is quietly the most important sentence in the Role. A crew with a Medtech can afford to chrome up; a crew without one is on a one-way trip.\n\nThe Medtech is **not a healer class** in the d20 sense. There is no per-day resource, no spell slots, and nothing they do is instant. Everything is a **TECH check, a DV, time, and money**. They are a doctor, and doctors are slow.',
    seeAlso: ['Role Ability', 'First Aid', 'Critical Injury', 'Humanity', 'Cyberware', 'Cyberpsychosis'],
    aliases: ['medtechs', 'medicine', 'doctor', 'ripperdoc', 'medic'],
  },
  {
    term: 'Fixer',
    kind: 'class',
    short: 'The broker. Operator is the only reliable way to find, buy, and sell things Night City does not sell openly.',
    body: 'The **Fixer** is the person who knows a person. Their Role Ability is **Operator**, and it governs their ability to **find, acquire, broker and move** things — legal, illegal, and the enormous grey space between.\n\nAt higher ranks the Fixer can source progressively more absurd things: not just guns and chrome but vehicles, documents, access, people, and information that officially does not exist. They also **buy and sell** at rates nobody else gets, and they generate **jobs** — the Fixer is usually the reason the party has work at all.\n\nDifferent Fixers specialise, and the rank buys a specific flavour of operation: the procurement specialist, the broker of services, the one who moves stolen goods, the one who runs a network of contacts.\n\nWhy the Role matters structurally: **Cyberpunk RED gates gear behind availability, not just price**. You cannot simply buy a Militech assault rifle because you have the eddies. Someone has to **get** it. That someone is the Fixer, and a party without one is stuck with whatever the shops openly stock.\n\nPair it with **COOL** and **Reputation** and the Fixer also wins **Facedowns**, which is how they survive being the person everyone needs and nobody trusts.',
    seeAlso: ['Role Ability', 'Reputation', 'Facedown', 'Improvement Points'],
    aliases: ['fixers', 'operator', 'broker', 'dealer'],
  },
  {
    term: 'Rockerboy',
    kind: 'class',
    short: 'The rebel performer. Charismatic Impact moves crowds — the only Role that can turn a mob into a weapon.',
    body: 'The **Rockerboy** is a musician, performer, or firebrand who uses art as a weapon against the Corps. Their Role Ability is **Charismatic Impact**.\n\nWhat it does: it lets you **sway a crowd**. At rank, a Rockerboy can whip an audience into a mood — adoration, outrage, a riot — and point it at something. That is not a metaphor; a mob is a genuine tactical asset, and no other Role can manufacture one.\n\nIt also gives them **an audience**, which means information, cover, safe houses, and people who will lie to the police for them.\n\nMechanically the Rockerboy is a **COOL** character, which means they are also good at **Facedowns**, **Persuasion**, and **Wardrobe & Style**. They are not a combat Role and have no combat bonuses — no hit die, no extra HP, no attack bonus, because **no Role has those**.\n\nThe Rockerboy is Cyberpunk\'s thesis statement in Role form: the point of the setting is that style, noise and refusal are weapons. A crew with a Rockerboy has a way to make a problem **public**, and in Night City publicity is sometimes the only leverage that works on a Corp.',
    seeAlso: ['Role', 'Role Ability', 'Facedown', 'Reputation'],
    aliases: ['rockerboys', 'rocker', 'charismatic impact', 'musician'],
  },
  {
    term: 'Media',
    kind: 'class',
    short: 'The journalist. Credibility gets the story believed and gets people to talk — information as a weapon.',
    body: 'The **Media** is a reporter, streamer, or investigative journalist. Their Role Ability is **Credibility**.\n\nWhat it does: it governs whether **people believe your story** and whether **sources will talk to you**. At high rank a Media can publish something that a Corporation genuinely cannot make go away, and can get access to people and places on the strength of a press badge and a reputation.\n\nWhy that matters: in a setting where the Corps own the law, **exposure** is one of the very few levers that works on them. A Media who breaks the story is doing something a Solo with a rifle cannot.\n\nThe Media is an **INT** character — Education, Perception, Local Expert, Human Perception, Composition, Interview. They are researchers first.\n\nAnd the Role comes with a target on your back. A Media who is credible is a Media the Corp needs discredited, sued, or disappeared — which is usually where the campaign hooks come from.\n\nNo hit die, no level, no class features. Like every Role, just the ability and the skills you bought with **IP**.',
    seeAlso: ['Role', 'Role Ability', 'Reputation', 'Improvement Points'],
    aliases: ['medias', 'credibility', 'journalist', 'reporter', 'streamer'],
  },
  {
    term: 'Exec',
    kind: 'class',
    short: 'The corporate. Teamwork provides a team of subordinates and corporate resources — power through structure.',
    body: 'The **Exec** works for a Corporation and has climbed far enough to matter. Their Role Ability is **Teamwork**.\n\nWhat it does: it grants **corporate resources** and **a team of people who answer to you** — subordinates with their own skills, budgets, vehicles, and the ability to make things happen without you being present. At rank, the Exec is not one character; they are a small organisation.\n\nThat is genuinely powerful and genuinely dangerous. The resources belong to the **Corp**, not to you. They come with oversight, obligations, and the standing possibility that the Corp decides you are a liability — at which point every asset you had becomes an asset hunting you.\n\nThe Exec is a **COOL** character: Persuasion, Bureaucracy, Business, Wardrobe & Style, Human Perception, and enough **Reputation** to win **Facedowns** in rooms where nobody is armed.\n\nThe design tension is the point of the Role. Every other Role is an outsider; the Exec is inside, and the campaign question is always **how long that lasts** and **what it costs**.\n\nNo levels, no hit die — a rank 8 Exec has exactly the HP their BODY and WILL give them.',
    seeAlso: ['Role', 'Role Ability', 'Reputation', 'Facedown'],
    aliases: ['execs', 'teamwork', 'corporate', 'corpo', 'suit'],
  },
  {
    term: 'Lawman',
    kind: 'class',
    short: 'The badge. Backup calls in official support — how much arrives depends on the rank and the situation.',
    body: 'The **Lawman** is police, corporate security, a Psycho Squad officer, or a bounty hunter with a warrant. Their Role Ability is **Backup**.\n\nWhat it does: it **calls in official support**. At low rank that is a patrol car; at high rank it is an armed response team, an AV, and the authority to shut a street down. The rank determines **what shows up** and **how fast**.\n\nIt also grants **jurisdiction and access** — the Lawman can walk into places, request records, and detain people in ways nobody else at the table can.\n\nThe catch, and it is a big one: **Backup is not free and it is not private**. Calling it means the department now knows where you were and what you were doing. A Lawman running with a crew of edgerunners has to explain things, constantly, and every use of Backup is a paper trail.\n\nThe Lawman is a **COOL** character with Interrogation, Perception, Tactics, Streetwise, and a **Reputation** that wins **Facedowns** with gangers who know what the badge means.\n\nStructurally the Role exists to be **compromised**. The interesting Lawman is the one deciding, session by session, which side the badge is actually on.',
    seeAlso: ['Role', 'Role Ability', 'Reputation', 'Facedown'],
    aliases: ['lawmen', 'backup', 'cop', 'police', 'psycho squad'],
  },
  {
    term: 'Nomad',
    kind: 'class',
    short: 'The family driver. Moto grants vehicles from your Pack and the people who come with them.',
    body: 'The **Nomad** belongs to a **Pack** — an extended family that lives on the road, runs the highways, and moves the goods nobody else will move. Their Role Ability is **Moto**.\n\nWhat it does: it grants **vehicles**, scaling with rank from a bike up through cars, trucks, and eventually the sort of thing that has a crew. Higher ranks also mean the **family** is more willing to help — the Nomad can call on the Pack for people, shelter, and transport.\n\nThat family connection is the real ability. Other Roles buy things; the Nomad **belongs to something**, which in Cyberpunk RED\'s post-collapse Night City is a rarer and more valuable asset than chrome.\n\nThe Nomad is a **REF** character: Drive Land Vehicle, Handgun, Athletics, Survival, Streetwise, Wilderness Survival. Every crew needs a driver, and the Nomad is the one who owns the vehicle they are driving.\n\nAnd it costs. The Pack has claims on you. Family obligations are the hook the GM will pull, and a Nomad who burns their family has burned the Role.\n\nNo hit die, no level, no class feature — just Moto, and the skills you spent **IP** on.',
    seeAlso: ['Role', 'Role Ability', 'MOVE', 'Improvement Points'],
    aliases: ['nomads', 'moto', 'driver', 'pack', 'family'],
  },
  {
    term: 'Eurodollars',
    kind: 'term',
    short: 'The money, called eddies (€$). It buys gear, chrome, and lifestyle — and gear is gated by availability, not just price.',
    body: '**Eurodollars** — universally called **eddies**, written **€$** — are the currency of Night City.\n\nWhat they buy:\n\n· **Gear** — weapons, armor, cyberdecks, vehicles\n· **Cyberware** — plus the surgery and the **Humanity** cost that comes with it\n· **Lifestyle** — rent, food, and a place to sleep that locks\n· **Medical care**, **Trauma Team** subscriptions, and **Therapy** to restore Humanity\n· **Repairs** — your **ablated** armor does not fix itself\n\nThe crucial rule: **money is not enough**. Every item has an **availability**, and the good things are not on a shelf. You need a **Fixer** and a roll to source a Militech assault rifle, no matter how many eddies you are holding.\n\nAnd the structural point that shapes every campaign: **eddies improve your character faster than IP does**. A skill point is a long grind; a **Sandevistan** is a purchase. So runners get more dangerous by getting more chrome, and chrome costs **Humanity**, and Humanity does not come back on its own.\n\nThat is the treadmill. You take jobs to buy the chrome that lets you take jobs. The bill is denominated in something other than eddies.',
    seeAlso: ['Improvement Points', 'Cyberware', 'Humanity', 'Fixer', 'Ablation'],
    aliases: ['eddies', 'eurodollar', 'money', 'cash', 'eb'],
  },
];
