// lib/dnd/glossary/dnd5e-2024.ts — terms as the 2024 Player's Handbook defines them.
//
// The shared file holds everything both editions define identically. THIS file holds what the 2024
// revision CHANGED. Every entry here is a place where quoting the 2014 book at a 2024 table (or
// vice versa) gives a genuinely wrong answer — Exhaustion and Surprise most of all.
import type { SystemGlossary } from './types';
import { DND5E_SHARED_GLOSSARY } from './dnd5e-shared';

const EDITION_2024: SystemGlossary = [
  {
    term: 'Exhaustion',
    kind: 'condition',
    short: '2024: each level is a flat −2 to d20 rolls and −5 ft speed; you die at 6.',
    body: 'The **2024** rules replace the 2014 staircase with one simple rule. While you have Exhaustion:\n\n· **−2 × your exhaustion level** to **every d20 Test** (ability checks, attack rolls, saving throws)\n· **−5 feet × your exhaustion level** to your **Speed**\n· at **level 6**, you **die**\n\nThat is all of it — no halved HP maximum, no speed-0 tier. It is a smooth ramp instead of six different rules.\n\nA **long rest** removes **one level**. This is NOT the 2014 version, where level 1 is disadvantage on checks, level 2 halves speed, level 4 halves your HP maximum, and so on.',
    seeAlso: ['Long Rest'],
    aliases: ['exhausted', 'exhaustion levels'],
  },
  {
    term: 'Grappled',
    kind: 'condition',
    short: '2024: speed 0 AND disadvantage on attacks against anyone but the grappler.',
    body: 'A **Grappled** creature:\n\n· has **Speed 0** and cannot benefit from bonuses to speed\n· has **disadvantage on attack rolls** against any target **other than the grappler**\n· **moves with the grappler** when it moves (at half speed, unless the grappler is two sizes larger)\n\nThe disadvantage clause is new in 2024 — in 2014 Grappled was speed 0 and nothing else.\n\nGrappling is now the **Unarmed Strike: Grapple** option, and the target makes a **saving throw** (STR or DEX, its choice) against **8 + your STR modifier + your proficiency bonus** — it is no longer a contested check. Escaping costs the target an action to repeat the save.',
    seeAlso: ['Prone', 'Restrained', 'Unarmed Strike'],
    aliases: ['grapple', 'grappling'],
  },
  {
    term: 'Prone',
    kind: 'condition',
    short: '2024: crawl at half speed; your attacks have disadvantage; attacks within 5 ft have advantage, beyond have disadvantage.',
    body: 'A **Prone** creature:\n\n· can only **crawl** (each foot of movement costs an extra foot) unless it stands\n· has **disadvantage** on its **attack rolls**\n· is attacked with **advantage** if the attacker is **within 5 feet**, and with **disadvantage** otherwise\n\nStanding up costs **half your Speed**.\n\nIn 2024 you knock a target prone with the **Unarmed Strike: Shove** option — the target makes a **STR or DEX save** against **8 + your STR modifier + your proficiency bonus**, rather than the 2014 contested check. Shove can instead push the target 5 feet.',
    seeAlso: ['Grappled', 'Unarmed Strike'],
    aliases: ['prone', 'knocked down', 'shove'],
  },
  {
    term: 'Unconscious',
    kind: 'condition',
    short: '2024: incapacitated, prone, drop everything, auto-fail STR/DEX saves; hits within 5 ft are critical.',
    body: 'An **Unconscious** creature:\n\n· is **Incapacitated**, **cannot move or speak**, and is **unaware of its surroundings**\n· **drops whatever it is holding** and falls **Prone**\n· **automatically fails Strength and Dexterity saving throws**\n· is attacked with **advantage**\n· **any attack that hits it from within 5 feet is a critical hit**\n\nMechanically unchanged from 2014 — but note it now sits alongside the 2024 Exhaustion rules, so a character revived at 0 HP is not carrying the old tiered penalties.',
    seeAlso: ['Death Saving Throw', 'Incapacitated', 'Exhaustion'],
    aliases: ['unconscious', 'knocked out', 'ko'],
  },
  {
    term: 'Surprise',
    kind: 'mechanic',
    short: '2024: surprise gives DISADVANTAGE ON INITIATIVE — you are not frozen for a round.',
    body: 'The **2024** rules rewrote surprise completely. A surprised creature now has **disadvantage on its Initiative roll** — and that is the entire effect.\n\nIt **acts normally on its turn**: it can move, take actions and take reactions. There is no lost round.\n\nThis is one of the biggest single changes between editions. In **2014**, a surprised creature **cannot move or act on its first turn and cannot react until that turn ends** — a full turn gone. Quoting the wrong one materially changes an ambush.',
    seeAlso: ['Initiative'],
    aliases: ['surprised', 'surprise round', 'ambush'],
  },
  {
    term: 'Heroic Inspiration',
    kind: 'mechanic',
    short: '2024: spend it to REROLL a d20 — you either have it or you do not.',
    body: '**Heroic Inspiration** (the 2024 name) lets you **reroll a d20** immediately and **must use the new roll**.\n\nThat is a real change from 2014, where Inspiration granted **advantage** on a roll you had not made yet. Rerolling after seeing the result is more reliable in practice.\n\nYou either have it or you do not — it does not stack. If you gain it while you already have it, nothing happens. **Humans** get it back on every long rest as a species trait.',
    seeAlso: ['Advantage'],
    aliases: ['inspiration', 'hero inspiration'],
  },
  {
    term: 'Weapon Mastery',
    kind: 'feature',
    short: '2024 only: martials unlock a weapon’s mastery property — Cleave, Graze, Nick, Push, Sap, Slow, Topple, Vex.',
    body: '**Weapon Mastery** is new in 2024. Martial classes gain mastery of a number of weapons and get that weapon\'s **mastery property** whenever they attack with it. The eight:\n\n· **Cleave** — a hit with a Heavy melee weapon lets you attack a second creature within 5 ft of the first\n· **Graze** — on a **miss**, deal damage equal to your ability modifier\n· **Nick** — the extra Light-weapon attack becomes part of your Attack action, not a bonus action\n· **Push** — push the target up to 10 feet away\n· **Sap** — the target has **disadvantage** on its next attack roll\n· **Slow** — reduce the target\'s Speed by 10 feet\n· **Topple** — the target makes a CON save or is knocked **Prone**\n· **Vex** — you have **advantage** on your next attack against that target\n\nFighters get the most; Barbarians, Paladins, Rangers and Rogues get some. **This does not exist in 2014 at all.**',
    seeAlso: ['Attack Roll', 'Prone'],
    aliases: ['mastery', 'weapon masteries', 'cleave', 'graze', 'vex', 'topple'],
  },
  {
    term: 'Origin Feat',
    kind: 'feature',
    short: '2024 only: every character gets a free feat at level 1, from their background.',
    body: 'In **2024**, feats are a **core rule**, not optional, and every character starts with one: your **background grants an Origin feat** at level 1.\n\nThe origin feats include **Alert**, **Healer**, **Lucky**, **Magic Initiate**, **Musician**, **Savage Attacker**, **Skilled**, **Tavern Brawler** and **Tough**.\n\nFeats are now sorted into categories — **Origin**, **General** (the ones you take with an ASI at 4/8/12/16), **Fighting Style**, and **Epic Boon** (level 19). **None of this exists in 2014**, where feats are optional and there is no free level-1 feat.',
    seeAlso: ['Feat', 'Background', 'Ability Score Improvement'],
    aliases: ['origin feats', 'level 1 feat'],
  },
  {
    term: 'Feat',
    kind: 'feature',
    short: '2024: a CORE rule, in four categories, with a free Origin feat at level 1.',
    body: 'Feats in 2024 are a **core part of character creation**, not an optional module, and they are **categorised**:\n\n· **Origin** — one free at level 1 from your **background**\n· **General** — taken in place of an **Ability Score Improvement** at **4, 8, 12, 16** (plus class extras). Each has a **prerequisite of level 4+** and nearly all grant **+1 to an ability score**\n· **Fighting Style** — now feats, granted by the martial classes\n· **Epic Boon** — taken at **level 19**, and they can push an ability score to **30**\n\nMost General feats now include their own ability bump, so taking one costs much less than the 2014 all-or-nothing ASI trade. Feats can be taken **only once** unless they say otherwise.',
    seeAlso: ['Origin Feat', 'Ability Score Improvement'],
    aliases: ['feats', 'general feat', 'epic boon'],
  },
  {
    term: 'Ability Score Improvement',
    kind: 'feature',
    short: '2024: at 4/8/12/16 (+19 Epic Boon), raise one ability by 2 or two by 1 — or take a General feat.',
    body: 'In 2024 the **Ability Score Improvement** is itself presented as a **feat** you can take at **levels 4, 8, 12 and 16** (Fighters and Rogues get extras).\n\nIt gives **+2 to one ability** or **+1 to two abilities**, to a maximum of **20**. The alternative is any **General feat** — and since most General feats carry their own +1, the choice is far less lopsided than in 2014.\n\nAt **level 19** every class takes an **Epic Boon** instead, which can raise a score to **30**. 2014 has no Epic Boons and puts its last ASI at 19.',
    seeAlso: ['Feat', 'Origin Feat'],
    aliases: ['asi'],
  },
  {
    term: 'Background',
    kind: 'feature',
    short: '2024: backgrounds now grant your ability score increases, an Origin feat, skills and a tool.',
    body: 'Backgrounds do far more work in **2024**. Each one grants:\n\n· **+3 to abilities** — either +2/+1 to two of its three listed abilities, or +1/+1/+1 across all three\n· an **Origin feat**\n· **two skill proficiencies**\n· **one tool proficiency**\n· starting **equipment** (or 50 GP)\n\nThis is the big structural change: **species no longer give ability score increases** — your background does. A 2014 character gets its +2/+1 from its race, which is exactly the wrong answer at a 2024 table.\n\nExample — **Farmer**: Strength, Constitution, Wisdom · **Tough** feat · Animal Handling and Nature · Carpenter\'s Tools.',
    seeAlso: ['Origin Feat', 'Species'],
    aliases: ['backgrounds', 'origin'],
  },
  {
    term: 'Species',
    kind: 'feature',
    short: '2024: species give traits ONLY — never ability score increases (those come from your background).',
    body: 'In 2024 the term is **species**, not race, and — the key rule — **a species grants no ability score increases**. Those come from your **background**.\n\nSpecies now give **traits only**, plus a size and a speed. Each has a **Creature Type** and most have a **Darkvision** or resistance package.\n\nThe 2024 PHB list: **Aasimar, Dragonborn, Dwarf, Elf, Gnome, Goliath, Halfling, Human, Orc, Tiefling**. Standalone **Half-Elf** and **Half-Orc** are gone (folded into Elf/Orc + background choices), while **Aasimar, Goliath and Orc** are new to the core list.\n\nHuman\'s traits: **Resourceful** (Heroic Inspiration on a long rest), **Skillful** (a free skill proficiency), **Versatile** (a free Origin feat).',
    seeAlso: ['Background', 'Heroic Inspiration'],
    aliases: ['race', 'races', 'lineage'],
  },
  {
    term: 'Unarmed Strike',
    kind: 'action',
    short: '2024: choose Damage, Grapple or Shove each time — it is no longer just a punch.',
    body: 'The 2024 **Unarmed Strike** is a menu. Each time you make one, choose **one**:\n\n· **Damage** — an attack roll; on a hit, **1 + STR modifier** bludgeoning damage\n· **Grapple** — the target makes a **STR or DEX save** vs **8 + your STR mod + your proficiency bonus** or is **Grappled**\n· **Shove** — same save; on a failure, push it **5 feet** or knock it **Prone**\n\nGrapple and Shove are **saving throws now**, not the 2014 contested Athletics checks — a real change, because it means the target\'s own skill no longer matters.\n\nThe target must be no more than **one size larger** than you, and you need a free hand.',
    seeAlso: ['Grappled', 'Prone', 'Attack Roll'],
    aliases: ['unarmed', 'punch', 'grapple', 'shove'],
  },
  {
    term: 'Skill',
    kind: 'mechanic',
    short: 'The same 18 skills as 2014, each tied to one ability by default.',
    body: 'The **18 skills** and their governing abilities are **unchanged** from 2014:\n\n· **STR** — Athletics\n· **DEX** — Acrobatics, Sleight of Hand, Stealth\n· **INT** — Arcana, History, Investigation, Nature, Religion\n· **WIS** — Animal Handling, Insight, Medicine, Perception, Survival\n· **CHA** — Deception, Intimidation, Performance, Persuasion\n\n**Constitution has no skills.** What changed is where proficiencies come from: **backgrounds** now reliably give two, and species give none.\n\nThe 2024 book leans harder on the DM choosing the ability and the skill separately — Strength (Intimidation) is explicitly supported.',
    seeAlso: ['Proficiency Bonus', 'Expertise', 'Background'],
    aliases: ['skills', 'skill list'],
  },
  {
    term: 'Passive Perception',
    kind: 'term',
    short: '10 + your Perception modifier — what you notice without looking.',
    body: '**Passive Perception** = **10 + your Wisdom (Perception) modifier**, including proficiency and Expertise.\n\nIt is a floor rather than a roll — what you notice without searching. **Advantage** on Perception adds **+5**, **disadvantage** subtracts **5**.\n\nIn 2024 it matters slightly less for ambushes than it did, because surprise now only costs you initiative advantage rather than your whole first turn.',
    seeAlso: ['Skill', 'Surprise'],
    aliases: ['passive perception', 'pp', 'passive'],
  },

  // ── The action economy (2024) ────────────────────────────────────────────────────────────────
  // On your turn you get: MOVEMENT up to your Speed, ONE action, and (if something grants it) ONE
  // Bonus Action. A Reaction is separate and happens off your turn. The 2024 book renamed and
  // regularized the standard actions into the list below.
  {
    term: 'Action',
    kind: 'mechanic',
    short: 'On your turn: your Movement, ONE action, and a Bonus Action if you have one to spend.',
    body: 'On your turn you can **move** up to your Speed and take **one action**. If a feature or spell grants a **Bonus Action**, you can also take that; you never get a Bonus Action unless something specifically gives you one.\n\nThe **standard actions** in 2024 are: **Attack, Dash, Disengage, Dodge, Help, Hide, Influence, Magic, Ready, Search, Study, Utilize**. You can also do things not on the list (the DM adjudicates), and interact with **one object** for free.\n\nA **Reaction** is not an action — it is a separate response you can take once per round, off your turn, when its trigger occurs (the most common is an Opportunity Attack).',
    seeAlso: ['Bonus Action', 'Reaction', 'Attack', 'Opportunity Attack'],
    aliases: ['actions', 'action economy', 'your turn', 'turn'],
  },
  {
    term: 'Bonus Action',
    kind: 'action',
    short: 'An extra, faster action — but only when a feature or spell explicitly grants one.',
    body: 'A **Bonus Action** is a second, smaller action you can take on your turn — but **only if a feature, spell, or item says you can** (two-weapon fighting, a Rogue\'s Cunning Action, casting a bonus-action spell, etc.).\n\nYou can take **at most one** Bonus Action per turn, and you choose when during your turn to take it. If you have nothing that grants one, you simply do not get one.\n\n**Spell rule:** if you cast a spell as a Bonus Action, the only other spell you can cast on that turn is a **cantrip with a casting time of one action**.',
    seeAlso: ['Action', 'Reaction'],
    aliases: ['bonus action', 'ba'],
  },
  {
    term: 'Attack',
    kind: 'action',
    short: 'The action to make one (or more, with Extra Attack) melee or ranged attacks.',
    body: 'The **Attack action** lets you make **one attack** with a weapon or an Unarmed Strike. Features like **Extra Attack** let you make more than one attack with this single action.\n\nWith the Attack action you can also use a weapon\'s **mastery property**, replace an attack with an **Unarmed Strike option** (Grapple, Shove) if you have a free hand, or with a **Utilize**/**object interaction** where allowed.\n\nDistinct from casting an attack-roll spell, which is the **Magic** action.',
    seeAlso: ['Attack Roll', 'Unarmed Strike', 'Opportunity Attack', 'Magic'],
    aliases: ['attack action', 'make an attack'],
  },
  {
    term: 'Dash',
    kind: 'action',
    short: 'Gain extra movement equal to your Speed this turn.',
    body: 'The **Dash** action gives you **extra movement equal to your Speed** for the current turn (after any modifiers). Take it twice-over with features and you cover a lot of ground.\n\nExample: with a Speed of 30, Dashing lets you move up to **60 feet** this turn instead of 30.',
    seeAlso: ['Action', 'Difficult Terrain'],
    aliases: ['dash', 'run'],
  },
  {
    term: 'Disengage',
    kind: 'action',
    short: 'Your movement no longer provokes Opportunity Attacks this turn.',
    body: 'When you take the **Disengage** action, your movement for the rest of the turn **does not provoke Opportunity Attacks** from any creature.\n\nIt is the safe way to leave melee. Compare the Rogue\'s Cunning Action, which lets it Disengage as a **Bonus Action**.',
    seeAlso: ['Opportunity Attack', 'Action'],
    aliases: ['disengage'],
  },
  {
    term: 'Dodge',
    kind: 'action',
    short: 'Attackers have disadvantage against you; you have advantage on DEX saves — until your next turn.',
    body: 'When you take the **Dodge** action, until the start of your next turn: any **attack roll against you has disadvantage** if you can see the attacker, and you make **Dexterity saving throws with advantage**.\n\nYou lose these benefits if you are **Incapacitated** or your **Speed drops to 0**.',
    seeAlso: ['Saving Throw', 'Action'],
    aliases: ['dodge'],
  },
  {
    term: 'Help',
    kind: 'action',
    short: 'Give an ally advantage — on their next check, or on their next attack against a foe within 5 ft of you.',
    body: 'The **Help** action does one of two things:\n· **Assist a task** — you help with an ability check you are also capable of; the ally makes their next check on that task with **advantage** before your next turn.\n· **Assist an attack** — you distract a foe **within 5 feet** of you; the next attack roll an ally makes against it (before your next turn) has **advantage**.',
    seeAlso: ['Advantage', 'Action'],
    aliases: ['help', 'assist'],
  },
  {
    term: 'Hide',
    kind: 'action',
    short: 'Make a DC 15 Stealth check to become Invisible (unseen and unheard) until you give yourself away.',
    body: 'The **Hide** action lets you try to conceal yourself. You must be **Heavily Obscured** or behind **at least three-quarters cover**, out of any enemy\'s line of sight, and make a **Dexterity (Stealth) check against DC 15**.\n\nOn a success you have the **Invisible condition** (see the entry) — you are treated as unseen and unheard. You stop being Hidden if you make a sound louder than a whisper, an enemy finds you (a **Search** action opposed by your Stealth total), you make an attack, or you cast a spell with a verbal component.',
    seeAlso: ['Invisible', 'Search', 'Passive Perception'],
    aliases: ['hide', 'sneak'],
  },
  {
    term: 'Influence',
    kind: 'action',
    short: 'The social action: make a Charisma check to change a creature\'s attitude or get it to do something.',
    body: 'The **Influence** action (new-named in 2024) covers the social pillar in combat or out. You attempt a **Charisma or other check** — Deception, Intimidation, Performance, or Persuasion, or sometimes an **Animal Handling** check — to alter a monster\'s attitude or coax an action from it.\n\nThe DM sets the DC from the creature\'s **Intelligence** and how much your request costs it. A creature never takes an obviously self-destructive action from being Influenced, and it can\'t be Influenced again about the same thing until it finishes a short rest (roughly).',
    seeAlso: ['Skill', 'Action'],
    aliases: ['influence', 'social', 'persuade', 'intimidate'],
  },
  {
    term: 'Magic',
    kind: 'action',
    short: 'The action used to cast a spell with a casting time of an action, or use a magical feature.',
    body: 'The **Magic action** (renamed in 2024 from "Cast a Spell") is how you **cast a spell** whose casting time is one action, or use a **magic item or feature** that says it uses the Magic action.\n\nBonus-action and reaction spells use those instead. The **one-spell rule** still applies: if you cast a spell as a Bonus Action, any other spell that turn must be a cantrip with an action casting time.',
    seeAlso: ['Spell Slot', 'Cantrip', 'Concentration', 'Bonus Action'],
    aliases: ['magic action', 'cast a spell', 'cast'],
  },
  {
    term: 'Ready',
    kind: 'action',
    short: 'Prepare a Reaction now: pick a trigger and an action, and take it when the trigger happens.',
    body: 'The **Ready** action lets you act on a **trigger** you name. You choose a perceivable circumstance and an action (or a single move), and you take that action as a **Reaction** when the trigger occurs, before the start of your next turn.\n\nReadying a **spell** requires you to **cast it now and hold its energy** with Concentration, releasing it as your Reaction when the trigger fires — and it costs the slot even if the trigger never comes.',
    seeAlso: ['Reaction', 'Concentration', 'Action'],
    aliases: ['ready', 'readied action', 'hold action'],
  },
  {
    term: 'Search',
    kind: 'action',
    short: 'Make a Perception (or Investigation/Insight/Medicine) check to find something — including a hidden creature.',
    body: 'The **Search** action is an active look for something the DM has hidden — a trap, a clue, or a **Hidden creature**. You make a **Wisdom (Perception)** check, or **Intelligence (Investigation)**, **Wisdom (Insight)**, or **Wisdom (Medicine)** as the situation fits.\n\nAgainst a Hidden creature, your Perception check is opposed by that creature\'s **Stealth total**; beating it ends the creature\'s Invisible-from-hiding status against you.',
    seeAlso: ['Hide', 'Passive Perception', 'Invisible'],
    aliases: ['search', 'look', 'find'],
  },
  {
    term: 'Study',
    kind: 'action',
    short: 'Make an Intelligence check to recall or deduce lore — Arcana, History, Nature, Religion, Investigation.',
    body: 'The **Study** action (new-named in 2024) is the knowledge action: you make an **Intelligence** check — **Arcana, History, Investigation, Nature, or Religion** — to recall lore or work something out.\n\nIt splits the old "use Investigation/recall knowledge" grab-bag into a clean named action, parallel to Search (senses) and Influence (social).',
    seeAlso: ['Skill', 'Search', 'Action'],
    aliases: ['study', 'recall knowledge', 'lore check'],
  },
  {
    term: 'Utilize',
    kind: 'action',
    short: 'The action to use a non-weapon object whose use takes an action (a healer\'s kit, a lever, a wand).',
    body: 'The **Utilize** action is how you **use an object** when using it takes an action — administering a Healer\'s Kit, pulling a heavy lever, drinking a potion someone hands you, activating certain magic items.\n\nYou still get **one free object interaction** per turn (draw a weapon, open an unlocked door); Utilize is for the things that need more than that.',
    seeAlso: ['Action'],
    aliases: ['utilize', 'use an object', 'use item'],
  },

  // ── Core combat mechanics ────────────────────────────────────────────────────────────────────
  {
    term: 'Bloodied',
    kind: 'term',
    short: '2024: a creature is Bloodied while at half its Hit Point maximum or fewer. Some features key off it.',
    body: 'A creature is **Bloodied** while it has **half its Hit Point maximum or fewer** remaining. New as a defined keyword in **2024** — several monster traits and a few player features trigger "while Bloodied."\n\nIt is purely a threshold, not a condition: it imposes nothing by itself, it just gives rules a clean way to say "this creature is badly hurt."',
    seeAlso: ['Temporary Hit Points', 'Death Saving Throw'],
    aliases: ['bloodied', 'half hp'],
  },
  {
    term: 'Temporary Hit Points',
    kind: 'term',
    short: 'A buffer of extra HP that is lost first, never stacks, and is not real healing.',
    body: '**Temporary Hit Points** are a separate buffer that sits on top of your real Hit Points. Damage comes off your **temp HP first**; only the overflow reduces your real HP.\n\nThey do **not stack** — a new source replaces the old (you keep the larger). They are **not healing** (you can gain them at full HP), they **vanish on a Long Rest**, and losing them does not break Concentration on their own unless the overflow damages you.',
    seeAlso: ['Bloodied', 'Long Rest', 'Concentration'],
    aliases: ['temp hp', 'temporary hit points', 'thp'],
  },
  {
    term: 'Cover',
    kind: 'mechanic',
    short: 'Obstacles give +2 AC / +2 DEX saves (half), +5 (three-quarters), or block entirely (total).',
    body: 'Standing behind something between you and an attacker grants **Cover**:\n· **Half cover** (a low wall, a creature) — **+2 to AC and Dexterity saving throws**.\n· **Three-quarters cover** (an arrow slit, a tree trunk) — **+5 to AC and Dexterity saving throws**.\n· **Total cover** — you **cannot be targeted directly** at all.\n\nTake the **most protective** degree that applies; cover from multiple sources does not add. A target behind total cover can still be caught by an area of effect that reaches around it only if the effect says so.',
    seeAlso: ['Armor Class (AC)', 'Saving Throw'],
    aliases: ['cover', 'half cover', 'three-quarters cover', 'total cover'],
  },
  {
    term: 'Difficult Terrain',
    kind: 'mechanic',
    short: 'Every foot of movement costs an extra foot — rubble, deep snow, a crowd, undergrowth.',
    body: '**Difficult Terrain** — rubble, undergrowth, deep snow, a dense crowd, a creature\'s space — makes each **foot of movement cost one extra foot**. Moving 10 feet through it uses 20 feet of your Speed.\n\nDifferent kinds of difficult terrain in the same square **do not stack** (it is still just double cost). Some features (a Barbarian\'s, a Druid\'s Land\'s Stride) let you **ignore** nonmagical difficult terrain.',
    seeAlso: ['Dash', 'Prone'],
    aliases: ['difficult terrain', 'rough terrain'],
  },
  {
    term: 'Damage Types & Resistance',
    kind: 'mechanic',
    short: 'Resistance halves a damage type; Vulnerability doubles it; Immunity ignores it. Applied after other math.',
    body: 'Damage has a **type** — Acid, Bludgeoning, Cold, Fire, Force, Lightning, Necrotic, Piercing, Poison, Psychic, Radiant, Slashing, or Thunder — and defenses key off the type:\n· **Resistance** — you take **half** damage of that type.\n· **Vulnerability** — you take **double**.\n· **Immunity** — you take **none**.\n\nApply **all other modifiers first**, then resistance/vulnerability, and **each applies only once** no matter how many sources grant it. Resistance and vulnerability to the same type **cancel** to normal damage.',
    seeAlso: ['Attack Roll', 'Saving Throw', 'Temporary Hit Points'],
    aliases: ['resistance', 'vulnerability', 'immunity', 'damage types', 'damage type'],
  },
  {
    term: 'Vision & Light',
    kind: 'mechanic',
    short: 'Lightly obscured → disadvantage on Perception; heavily obscured → the Blinded condition toward it.',
    body: 'Light and obscurement drive what you can see:\n· **Bright light** — normal sight.\n· **Dim light** (a **Lightly Obscured** area) — **disadvantage on Wisdom (Perception) checks** that rely on sight.\n· **Darkness** / a **Heavily Obscured** area — you effectively have the **Blinded** condition when trying to see into it.\n\n**Darkvision** lets you treat dim light as bright and darkness as dim (in shades of grey) out to its range — it does **not** pierce magical darkness or a heavily obscured area beyond that. **Blindsight**, **Tremorsense**, and **Truesight** bypass these limits within their range.',
    seeAlso: ['Blinded', 'Hide', 'Passive Perception'],
    aliases: ['darkvision', 'obscured', 'lightly obscured', 'heavily obscured', 'dim light', 'vision', 'light'],
  },
];

export const DND5E_2024_GLOSSARY: SystemGlossary = [...DND5E_SHARED_GLOSSARY, ...EDITION_2024];
