// lib/dnd/glossary/dnd5e-2014.ts — terms as the 2014 Player's Handbook defines them.
//
// The shared file holds everything both editions define identically. THIS file holds the ones the
// 2024 revision changed — Exhaustion, Grappled, Prone, Surprise, Unconscious, Inspiration, feats,
// the Ranger/Sorcerer identities. Keeping them apart is the point: "how does exhaustion work" has
// two different correct answers depending on which book is on the table.
import type { SystemGlossary } from './types';
import { DND5E_SHARED_GLOSSARY } from './dnd5e-shared';

const EDITION_2014: SystemGlossary = [
  {
    term: 'Exhaustion',
    kind: 'condition',
    short: '2014: six levels, each with its own escalating penalty, from disadvantage on checks up to death at 6.',
    body: 'In the **2014** rules Exhaustion is measured in **six levels**, and each level adds its own distinct effect **cumulatively**:\n\n· **1** — Disadvantage on **ability checks**\n· **2** — **Speed halved**\n· **3** — Disadvantage on **attack rolls and saving throws**\n· **4** — **Hit point maximum halved**\n· **5** — **Speed reduced to 0**\n· **6** — **Death**\n\nThis is the tiered "staircase" version. It is NOT the 2024 rules, where every level is a flat −2 to d20 rolls.\n\nA **long rest** removes **one level**, provided you have eaten and drunk. Effects that give exhaustion stack levels, and there is no partial recovery.',
    seeAlso: ['Long Rest'],
    aliases: ['exhausted', 'exhaustion levels'],
  },
  {
    term: 'Grappled',
    kind: 'condition',
    short: '2014: speed 0. Escaping is a contested Athletics/Acrobatics check.',
    body: 'A **Grappled** creature has its **speed reduced to 0** and cannot benefit from any bonus to speed.\n\nThat is the entire condition in 2014 — it does **not** impose disadvantage on attacks (that is the 2024 version).\n\nGrappling is a **special melee attack**: use one attack of your Attack action to make a **Strength (Athletics) check contested by the target\'s Strength (Athletics) or Dexterity (Acrobatics)**, its choice. The target must be no more than one size larger than you.\n\nEscaping costs the grappled creature an **action** to repeat the same contest. The grapple ends if you are Incapacitated, or if an effect moves either of you apart.',
    seeAlso: ['Restrained', 'Prone'],
    aliases: ['grapple', 'grappling'],
  },
  {
    term: 'Prone',
    kind: 'condition',
    short: '2014: crawl at half speed; your attacks have disadvantage; melee attacks against you have advantage, ranged have disadvantage.',
    body: 'A **Prone** creature:\n\n· can only **crawl** (each foot costs an extra foot of movement) unless it stands up\n· has **disadvantage** on its attack rolls\n· is attacked with **advantage** if the attacker is **within 5 feet**, and with **disadvantage** otherwise\n\nStanding up costs **half your speed**. That ranged clause is the reason going prone against archers is a real tactic.\n\nYou can **knock a creature prone** with a **Shove** — one attack from your Attack action, a Strength (Athletics) check contested by the target\'s Athletics or Acrobatics.',
    seeAlso: ['Grappled', 'Advantage'],
    aliases: ['prone', 'knocked down', 'shove'],
  },
  {
    term: 'Unconscious',
    kind: 'condition',
    short: '2014: incapacitated, prone, drop everything, auto-fail STR/DEX saves; melee hits within 5 ft are critical.',
    body: 'An **Unconscious** creature:\n\n· is **Incapacitated**, **cannot move or speak**, and is **unaware of its surroundings**\n· **drops whatever it is holding** and falls **Prone**\n· **automatically fails Strength and Dexterity saving throws**\n· is attacked with **advantage**\n· **any attack that hits it from within 5 feet is a critical hit**\n\nThis is why a downed character next to an enemy is in genuine danger: each hit is a crit, and a hit at 0 HP costs **two** death save failures.',
    seeAlso: ['Death Saving Throw', 'Incapacitated', 'Prone'],
    aliases: ['unconscious', 'knocked out', 'ko'],
  },
  {
    term: 'Surprise',
    kind: 'mechanic',
    short: '2014: a surprised creature cannot move or act on its first turn, and cannot react until that turn ends.',
    body: 'In **2014**, surprise is a **condition of the first round**, not an initiative modifier.\n\nThe DM compares each hiding creature\'s **Dexterity (Stealth)** to the **passive Perception** of each opponent. Any creature that fails to notice a threat is **surprised** at the start of the encounter.\n\nA surprised creature **cannot move or take an action on its first turn**, and **cannot take a reaction until that turn ends**. Note it is per-creature: some of the party can be surprised while others are not.\n\nThis is NOT the 2024 rule, which instead gives surprised creatures **disadvantage on their initiative roll** and lets them act normally.',
    seeAlso: ['Initiative'],
    aliases: ['surprised', 'surprise round', 'ambush'],
  },
  {
    term: 'Inspiration',
    kind: 'mechanic',
    short: '2014: a binary you-have-it-or-not token, spent for advantage on any one d20 roll.',
    body: '**Inspiration** in 2014 is a simple flag: you either **have it or you do not** — you cannot stockpile it.\n\nThe DM grants it for playing to your **personality trait, ideal, bond or flaw**. Spend it to give yourself **advantage on one attack roll, saving throw or ability check**.\n\nYou can also **give your inspiration to another player** who you feel earned it. In 2024 this is renamed **Heroic Inspiration** and works by letting you **reroll** a d20 instead.',
    seeAlso: ['Advantage'],
    aliases: ['inspiration point', 'bardic'],
  },
  {
    term: 'Feat',
    kind: 'feature',
    short: '2014: an OPTIONAL rule — you trade an entire Ability Score Improvement for one.',
    body: 'Feats in 2014 are explicitly an **optional rule** the DM must allow, and there is no free one at level 1.\n\nWhen a class grants an **Ability Score Improvement** (typically levels **4, 8, 12, 16, 19**), you may instead take **one feat**. It is the whole ASI — you give up +2 to one ability or +1 to two.\n\nSome feats grant a **+1 ability increase** alongside their benefit ("half feats"), which softens the trade. There are no **Origin feats**, no **Epic Boons** at 19, and no feat categories — that structure is the 2024 revision.',
    seeAlso: ['Ability Score Improvement'],
    aliases: ['feats'],
  },
  {
    term: 'Ability Score Improvement',
    kind: 'feature',
    short: '2014: at 4/8/12/16/19, raise one ability by 2 or two abilities by 1 — or take a feat instead.',
    body: 'Most classes grant an **Ability Score Improvement** at levels **4, 8, 12, 16 and 19**. Fighters get extra ones at **6 and 14**; Rogues get one at **10**.\n\nYou may **increase one ability score by 2**, or **two ability scores by 1 each**. No score can exceed **20** this way.\n\nIf your table uses the optional **feat** rule, you can take a feat instead. Multiclassing uses **class** levels for ASIs, not character level — a common way to lose them by accident.',
    seeAlso: ['Feat', 'Proficiency Bonus'],
    aliases: ['asi'],
  },
  {
    term: 'Ranger',
    kind: 'class',
    short: '2014: a half-caster with Favored Enemy and Natural Explorer — the edition’s most-criticised class.',
    body: 'The **2014 Ranger** is a d10 half-caster with **Favored Enemy** and **Natural Explorer** at level 1.\n\nBoth are famously narrow: they key to a **chosen creature type or terrain** and do nothing outside it. This is the class the designers themselves revisited repeatedly (Tasha\'s offers replacement options like Deft Explorer and Favored Foe).\n\n· **Hit die** d10 · **Key ability** DEX (or STR) · **Saves** STR & DEX\n· **Fighting Style** at 2, **spellcasting** from 2 (WIS, half-caster)\n· **Extra Attack** at 5, **Land\'s Stride** at 8, **Hide in Plain Sight** at 10\n\nThe 2024 Ranger drops Favored Enemy entirely and gives Hunter\'s Mark for free — a genuinely different class.',
    seeAlso: ['Feat'],
    aliases: ['favored enemy', 'natural explorer'],
  },
  {
    term: 'Skill',
    kind: 'mechanic',
    short: 'The 18 skills, each tied to one ability by default.',
    body: 'There are **18 skills**, each with a default governing ability:\n\n· **STR** — Athletics\n· **DEX** — Acrobatics, Sleight of Hand, Stealth\n· **INT** — Arcana, History, Investigation, Nature, Religion\n· **WIS** — Animal Handling, Insight, Medicine, Perception, Survival\n· **CHA** — Deception, Intimidation, Performance, Persuasion\n\nProficiency in a skill adds your **proficiency bonus** to checks made with it. **Constitution has no skills** — it is the only ability that never has one.\n\nThe pairing is a default, not a law: the DM can call for **Strength (Intimidation)** or **Intelligence (Perception)** when the fiction fits.',
    seeAlso: ['Proficiency Bonus', 'Expertise', 'Ability Check'],
    aliases: ['skills', 'skill list'],
  },
  {
    term: 'Passive Perception',
    kind: 'term',
    short: '10 + your Perception modifier — what you notice without looking.',
    body: '**Passive Perception** = **10 + your Wisdom (Perception) modifier** (including proficiency and Expertise if you have them).\n\nIt is a **floor, not a roll**: it is what you notice without actively searching. Advantage on Perception adds **+5**; disadvantage subtracts **5**.\n\nThe DM compares a hiding creature\'s **Stealth check** against it, usually without telling you — which is exactly why it is passive.',
    seeAlso: ['Skill', 'Surprise'],
    aliases: ['passive perception', 'pp', 'passive'],
  },

  // ── The action economy (2014) ────────────────────────────────────────────────────────────────
  // On your turn: MOVEMENT up to your Speed, ONE action, and (if a feature grants it) ONE Bonus
  // Action. A Reaction is separate. The 2014 book's standard actions are listed below — note the
  // names differ from 2024 (2014 says "Cast a Spell" and "Use an Object", not "Magic"/"Utilize").
  {
    term: 'Action',
    kind: 'mechanic',
    short: '2014: your Movement, ONE action, and a Bonus Action if something grants one.',
    body: 'On your turn you can **move** up to your Speed and take **one action**. A **Bonus Action** is available only if a feature, spell, or item grants one.\n\nThe **standard actions** in 2014 are: **Attack, Cast a Spell, Dash, Disengage, Dodge, Help, Hide, Ready, Search, Use an Object**. You can also interact with **one object** for free, and attempt things not on the list (the DM adjudicates).\n\nNote the 2024 book renamed and expanded this list (adding Influence, Study, Utilize, Magic) — at a 2014 table those names do not apply.',
    seeAlso: ['Bonus Action', 'Reaction', 'Attack', 'Cast a Spell'],
    aliases: ['actions', 'action economy', 'turn', 'your turn'],
  },
  {
    term: 'Bonus Action',
    kind: 'action',
    short: 'An extra action you get only when a feature or spell grants one; at most one per turn.',
    body: 'A **Bonus Action** is a second, smaller action, available **only when a feature, spell, or item explicitly grants one** (two-weapon fighting, a Rogue\'s Cunning Action, a bonus-action spell). You can take **at most one** per turn.\n\n**Spell rule:** if you cast a spell as a Bonus Action, the only other spell you can cast that turn is a **cantrip with a casting time of one action**.',
    seeAlso: ['Action', 'Reaction'],
    aliases: ['bonus action', 'ba'],
  },
  {
    term: 'Attack',
    kind: 'action',
    short: '2014: the action to make one attack — more with Extra Attack. No weapon mastery in 2014.',
    body: 'The **Attack action** lets you make **one attack** with a weapon or an unarmed strike. **Extra Attack** (Fighters, and others) lets you make more than one with the single action.\n\nUnlike 2024, there is **no weapon mastery** and no built-in Grapple/Shove "options" attached to the Attack action — grappling and shoving are **special melee attacks** you make in place of an attack, resolved with a **contested check** (your Athletics vs the target\'s Athletics or Acrobatics).',
    seeAlso: ['Attack Roll', 'Opportunity Attack'],
    aliases: ['attack action', 'grapple', 'shove', 'extra attack'],
  },
  {
    term: 'Cast a Spell',
    kind: 'action',
    short: '2014: the action used to cast a spell whose casting time is one action.',
    body: 'The **Cast a Spell** action casts a spell whose casting time is **one action** (2024 renamed this the **Magic** action). Spells with a casting time of a Bonus Action or Reaction use those instead.\n\nThe **one-spell rule** applies: if you cast a spell as a Bonus Action, any other spell that turn must be a **cantrip with an action casting time**.',
    seeAlso: ['Spell Slot', 'Cantrip', 'Concentration', 'Bonus Action'],
    aliases: ['cast a spell', 'casting', 'cast'],
  },
  {
    term: 'Dash',
    kind: 'action',
    short: 'Gain extra movement equal to your Speed this turn.',
    body: 'The **Dash** action gives you **extra movement equal to your Speed** for the current turn (after modifiers). With a Speed of 30 you can move up to **60 feet** this turn.',
    seeAlso: ['Action', 'Difficult Terrain'],
    aliases: ['dash', 'run'],
  },
  {
    term: 'Disengage',
    kind: 'action',
    short: 'Your movement no longer provokes Opportunity Attacks this turn.',
    body: 'When you take the **Disengage** action, your movement for the rest of the turn **does not provoke Opportunity Attacks**. It is the safe way to leave melee. The Rogue can Disengage as a **Bonus Action** (Cunning Action).',
    seeAlso: ['Opportunity Attack', 'Action'],
    aliases: ['disengage'],
  },
  {
    term: 'Dodge',
    kind: 'action',
    short: 'Attackers have disadvantage against you; you make DEX saves with advantage — until your next turn.',
    body: 'Until the start of your next turn: any **attack roll against you has disadvantage** if you can see the attacker, and you make **Dexterity saving throws with advantage**. You lose these benefits if you are **Incapacitated** or your **Speed is 0**.',
    seeAlso: ['Saving Throw', 'Action'],
    aliases: ['dodge'],
  },
  {
    term: 'Help',
    kind: 'action',
    short: 'Give an ally advantage — on their next ability check, or their next attack against a foe within 5 ft of you.',
    body: 'The **Help** action does one of two things: help with an **ability check** you could also make (the ally gets **advantage** on their next check on that task), or distract a foe **within 5 feet** of you so the next attack an ally makes against it has **advantage**.',
    seeAlso: ['Advantage', 'Action'],
    aliases: ['help', 'assist'],
  },
  {
    term: 'Hide',
    kind: 'action',
    short: '2014: make a Dexterity (Stealth) check to hide — no fixed DC, opposed by Perception.',
    body: 'The **Hide** action lets you attempt to conceal yourself with a **Dexterity (Stealth) check**. Unlike 2024, there is **no fixed DC 15 and no Invisible condition** — your Stealth result is the number others must beat with a **Wisdom (Perception)** check (or your total is compared to their Passive Perception).\n\nYou can\'t hide from a creature that can see you clearly, and you give yourself away if you come into view, make noise, or attack.',
    seeAlso: ['Search', 'Passive Perception', 'Invisible'],
    aliases: ['hide', 'sneak'],
  },
  {
    term: 'Ready',
    kind: 'action',
    short: 'Prepare a Reaction: pick a trigger and an action, take it when the trigger happens.',
    body: 'The **Ready** action lets you act on a **trigger**. Choose a perceivable circumstance and an action (or a single move); you take it as a **Reaction** when the trigger occurs before your next turn.\n\nReadying a **spell** requires you to **cast it now and hold it** with Concentration, releasing it as your Reaction — and the slot is spent even if the trigger never fires.',
    seeAlso: ['Reaction', 'Concentration', 'Action'],
    aliases: ['ready', 'readied action', 'hold action'],
  },
  {
    term: 'Search',
    kind: 'action',
    short: 'Devote your attention to finding something — a Perception or Investigation check.',
    body: 'The **Search** action is an active look for something hidden — a trap, a clue, a concealed creature. Depending on what you are looking for, you make a **Wisdom (Perception)** or **Intelligence (Investigation)** check.',
    seeAlso: ['Hide', 'Passive Perception'],
    aliases: ['search', 'look', 'find'],
  },
  {
    term: 'Use an Object',
    kind: 'action',
    short: '2014: the action to use a second object, or an object that needs an action to use.',
    body: 'You normally interact with **one object for free** during your move or action. The **Use an Object** action is for when you want to interact with a **second** object, or use one that specifically **requires an action** (drinking a potion, pulling a heavy lever). The 2024 book calls this **Utilize**.',
    seeAlso: ['Action'],
    aliases: ['use an object', 'use item', 'interact'],
  },

  // ── Core combat mechanics ────────────────────────────────────────────────────────────────────
  {
    term: 'Temporary Hit Points',
    kind: 'term',
    short: 'A buffer of extra HP lost first; never stacks; not healing.',
    body: '**Temporary Hit Points** are a buffer on top of your real HP. Damage comes off **temp HP first**; only the overflow reduces real HP.\n\nThey **do not stack** (a new source replaces the old — keep the larger), are **not healing** (you can gain them at full HP), and are **lost on a Long Rest**.',
    seeAlso: ['Long Rest', 'Concentration'],
    aliases: ['temp hp', 'temporary hit points', 'thp'],
  },
  {
    term: 'Cover',
    kind: 'mechanic',
    short: 'Half cover +2 AC/DEX saves; three-quarters +5; total cover cannot be targeted.',
    body: 'Obstacles between you and an attacker grant **Cover**: **half cover** = **+2 AC and Dexterity saving throws**; **three-quarters cover** = **+5**; **total cover** = you **cannot be targeted directly**. Take the **most protective** degree; cover does not stack.',
    seeAlso: ['Armor Class (AC)', 'Saving Throw'],
    aliases: ['cover', 'half cover', 'three-quarters cover', 'total cover'],
  },
  {
    term: 'Difficult Terrain',
    kind: 'mechanic',
    short: 'Every foot of movement costs an extra foot.',
    body: '**Difficult Terrain** — rubble, undergrowth, deep snow, a crowd — makes each **foot of movement cost one extra foot** (10 feet through it uses 20 of your Speed). Kinds do not stack. Some features let you ignore nonmagical difficult terrain.',
    seeAlso: ['Dash', 'Prone'],
    aliases: ['difficult terrain', 'rough terrain'],
  },
  {
    term: 'Damage Types & Resistance',
    kind: 'mechanic',
    short: 'Resistance halves a damage type; Vulnerability doubles it; Immunity ignores it.',
    body: 'Damage has a **type** (Acid, Bludgeoning, Cold, Fire, Force, Lightning, Necrotic, Piercing, Poison, Psychic, Radiant, Slashing, Thunder). **Resistance** = half that type; **Vulnerability** = double; **Immunity** = none.\n\nApply other modifiers first, then resistance/vulnerability, and **each once**. Resistance and vulnerability to the same type **cancel**.',
    seeAlso: ['Attack Roll', 'Saving Throw', 'Temporary Hit Points'],
    aliases: ['resistance', 'vulnerability', 'immunity', 'damage types', 'damage type'],
  },
  {
    term: 'Vision & Light',
    kind: 'mechanic',
    short: 'Lightly obscured → disadvantage on sight Perception; heavily obscured → effectively Blinded.',
    body: 'A **Lightly Obscured** area (dim light, patchy fog) imposes **disadvantage on Wisdom (Perception)** checks that rely on sight. A **Heavily Obscured** area (darkness, dense fog) means you effectively have the **Blinded** condition looking into it.\n\n**Darkvision** treats dim light as bright and darkness as dim (in greyscale) out to its range — it does **not** pierce magical darkness. **Blindsight**, **Tremorsense**, and **Truesight** bypass these within range.',
    seeAlso: ['Blinded', 'Hide', 'Passive Perception'],
    aliases: ['darkvision', 'obscured', 'lightly obscured', 'heavily obscured', 'dim light', 'vision', 'light'],
  },
];

export const DND5E_2014_GLOSSARY: SystemGlossary = [...DND5E_SHARED_GLOSSARY, ...EDITION_2014];
