// lib/dnd/glossary/shadowrun6e.ts — Shadowrun 6e terms (Sixth World Core Rulebook).
//
// Shadowrun rolls a POOL of d6 equal to Attribute + Skill and COUNTS hits on 5s and 6s. Dice are
// never summed. There is no d20, no armor class, no levels, no classes, no hit dice, and no
// proficiency bonus — Street Samurai and Decker are build concepts, not classes, and advancement is
// a continuous Karma spend. Damage lands on two separate condition tracks, not one HP number.
import type { SystemGlossary } from './types';

export const SHADOWRUN6E_GLOSSARY: SystemGlossary = [
  // ── Core resolution ──────────────────────────────────────────────────────────────────────
  {
    term: 'Test',
    kind: 'mechanic',
    short: 'Roll a pool of d6 equal to Attribute + Skill and count how many show 5 or 6 — those are hits.',
    body: 'Everything in Shadowrun is a **Test**. Build a **dice pool** — normally **Attribute + Skill** — roll that many **d6**, and **count the hits**.\n\n· A die showing **5 or 6** is a **hit**.\n· Everything else is nothing.\n· **Dice are never added together.** There is no total, no target number to beat with a sum, and no d20.\n\nAn Agility 5 street samurai with Firearms 6 rolls **11 dice** and averages about **3.7 hits** (each die is a 1-in-3 chance). That average is the number you learn to feel — **pool ÷ 3** is roughly what you will get.\n\nWhat you do with the hits depends on the test type:\n\n· **Simple Test** — beat a **threshold** the GM sets\n· **Opposed Test** — beat the other side\'s hits\n· **Extended Test** — accumulate hits across multiple rolls until you reach a large threshold\n\nModifiers change **the size of the pool**, never a total. Bad light, a wound, a bad position — all of them take **dice away**. That is why a wounded runner in the dark is not "at −4"; they are rolling fewer dice and their whole probability curve has collapsed.\n\nTwo things can go wrong regardless of hits: a **glitch** (more than half your dice show 1s), and its nastier cousin the **critical glitch**.',
    seeAlso: ['Hit', 'Threshold', 'Opposed Test', 'Glitch', 'Critical Glitch', 'Edge', 'Skills'],
    aliases: ['roll', 'dice pool', 'pool', 'test', 'd6 pool', 'skill test'],
  },
  {
    term: 'Hit',
    kind: 'term',
    short: 'A die showing 5 or 6. Hits are counted, never summed, and each die is roughly a 1-in-3 chance.',
    body: 'A **hit** is any die that comes up **5 or 6**. That is the entire currency of the system.\n\nEach d6 has a **1-in-3** chance, so a pool of **N** dice averages about **N ÷ 3** hits. Internalise that ratio and you can read any situation instantly: a 9-dice pool is "about 3 hits", a 15-dice pool is "about 5".\n\n**Net hits** is the number that usually matters — your hits minus the opposition\'s hits, or your hits minus the threshold. Net hits scale the outcome: extra net hits on an attack add **damage**, on a spell add **effect**, on a social test buy **more** than you asked for.\n\nHits are **counted, never added**. A pool of 12 that rolls 6-6-6-5-5-5-4-3-2-2-1-1 has **6 hits** — not 46, not anything else. The 6s and the 5s are worth exactly the same.\n\nYou can also **buy hits** in non-dramatic situations: take **1 automatic hit per 4 dice** in the pool instead of rolling, when the GM allows it and nothing is at stake. It is how you skip the boring rolls.',
    seeAlso: ['Test', 'Threshold', 'Opposed Test', 'Edge'],
    aliases: ['hits', 'net hits', 'successes', '5 or 6'],
  },
  {
    term: 'Threshold',
    kind: 'term',
    short: 'The number of hits a test needs to succeed — typically 1 for easy up to 4+ for very hard.',
    body: 'A **threshold** is how many **hits** you need. It is not a number you add up to — it is a count.\n\nThe rough ladder:\n\n· **1 hit** — easy; anyone competent manages it\n· **2 hits** — average; the everyday professional standard\n· **4 hits** — hard; you want a real pool for this\n· **6+ hits** — extreme; you need Edge, or a specialist, or both\n\nBecause pools average **pool ÷ 3**, a threshold of 4 needs roughly **12 dice** to be reliable. That arithmetic is the whole of Shadowrun character optimisation: people do not chase "+2 to hit", they chase **dice**.\n\n**Net hits** — hits above the threshold — usually do something extra. Extra net hits on a Firearms attack add **damage** directly; on a Perception test they tell you more; on a Con test they buy you a bigger lie.\n\n**Extended Tests** use a large threshold reached across **multiple rolls** over time, with the pool shrinking by 1 each interval. That is how the game handles research, repairs, and long tasks — and running out of dice before you reach the threshold means you have failed and wasted the time.',
    seeAlso: ['Test', 'Hit', 'Opposed Test'],
    aliases: ['thresholds', 'difficulty', 'target', 'extended test'],
  },
  {
    term: 'Opposed Test',
    kind: 'mechanic',
    short: 'Both sides roll their own pool; whoever has more hits wins, and the margin is the net hits.',
    body: 'When two parties contest, **both roll** their own pools and compare **hits**. The higher count wins, and the difference is the **net hits** that scale the outcome.\n\nThe common ones:\n\n· **Attack** — Agility + Firearms vs the defender\'s **Reaction + Intuition**\n· **Sneaking** — Agility + Stealth vs the guard\'s **Intuition + Perception**\n· **Con** — Charisma + Con vs the mark\'s **Willpower + Logic**\n· **Spellcasting** — Magic + Sorcery vs the target\'s **Willpower + relevant attribute**\n· **Damage resistance** — **Body + armor** against the incoming damage value\n\n**Ties go to the defender.** The status quo holds; nothing happens.\n\nNet hits are where the action is. On an attack, each **net hit adds 1 to the Damage Value** — so a runner who wins by 4 net hits is doing four more boxes than base, which is frequently the difference between a wounded guard and a dead one.\n\nNote the shape of this compared to a d20 game: there is **no AC** and nothing static to beat. The defender always **rolls**, which means the defender always has a chance, and a lucky defence roll can shrug off the best attack in the room.',
    seeAlso: ['Test', 'Hit', 'Threshold', 'Attack Rating', 'Armor'],
    aliases: ['opposed', 'contest', 'defence test', 'defense test'],
  },
  {
    term: 'Glitch',
    kind: 'mechanic',
    short: 'More than HALF your dice show 1s — something goes wrong even if you got enough hits to succeed.',
    body: 'A **glitch** happens when **more than half the dice in your pool show 1s**. Count the 1s, compare to half the pool, and if the 1s win, you glitched.\n\n· Pool of **6** — glitch on **4 or more** ones\n· Pool of **11** — glitch on **6 or more** ones\n· Pool of **4** — glitch on **3 or more** ones\n\n**A glitch is independent of success.** You can roll 4 hits *and* glitch. You succeeded, and something still went wrong: the gun jams after the shot, the lock opens but the alarm trips, the lie lands but you left a trace. The GM narrates a complication proportional to the situation.\n\nThe cruel structural detail: **small pools glitch far more often than large ones**. A 4-dice pool glitches roughly 1 time in 8. A 15-dice pool almost never does. So the things you are **bad at** are not just unlikely to succeed — they are actively likely to blow up in your face.\n\nThis is a strong argument against **defaulting**, and a strong argument for spending **Edge** on the one roll you cannot afford to have go sideways.\n\nIf you glitch **and get zero hits**, it is a **critical glitch**, and that is a different order of problem.',
    seeAlso: ['Critical Glitch', 'Test', 'Hit', 'Defaulting', 'Edge'],
    aliases: ['glitched', 'glitching', 'ones'],
  },
  {
    term: 'Critical Glitch',
    kind: 'mechanic',
    short: 'A glitch with ZERO hits: you failed and something genuinely bad happens.',
    body: 'A **critical glitch** is a **glitch** (more than half the dice showing 1s) that also produced **zero hits**.\n\nBoth conditions must be true. Four 1s out of six dice with one 5 among the rest is an ordinary glitch — you succeeded messily. Four 1s out of six with **no** 5s or 6s is a **critical glitch**, and the GM is now entitled to be genuinely cruel.\n\nWhat that looks like in practice:\n\n· The **weapon breaks**, not just jams\n· The **spell backfires** and the Drain lands as **Physical** damage\n· The **Matrix run** dumps you and your **Overwatch Score** spikes\n· The **vehicle crashes**\n· The **surgery** goes wrong\n\nCritical glitches are the reason low pools are dangerous rather than merely useless. A runner **defaulting** on a skill they do not have is rolling a small pool, which means they are simultaneously likely to fail **and** disproportionately likely to fail catastrophically.\n\n**Edge** can save you. Spending Edge to add dice or reroll before the glitch is locked in is one of the best uses of the resource — and one of the main reasons to keep a couple of points in reserve rather than dumping them on the first attack of the night.',
    seeAlso: ['Glitch', 'Test', 'Edge', 'Defaulting', 'Drain'],
    aliases: ['crit glitch', 'critical fail', 'catastrophe'],
  },
  {
    term: 'Edge',
    kind: 'mechanic',
    short: 'A points currency earned in play — mostly from the Attack Rating vs Defense Rating comparison — and spent to bend rolls.',
    body: '**Edge** is Shadowrun 6e\'s signature mechanic, and it works differently from the Edge of earlier editions. It is a **flowing currency**, not a once-a-session lifeline.\n\n**Earning it** — the main engine is the **Attack Rating vs Defense Rating** comparison, checked every time someone attacks:\n\n· If your **Attack Rating exceeds their Defense Rating by 4 or more**, **you gain 1 Edge**\n· If their **Defense Rating exceeds your Attack Rating by 4 or more**, **they gain 1 Edge**\n· Within 3 either way, nobody gains anything\n\nSo Edge flows to whoever has the better matchup — the right gun against the wrong armor, the ambusher against the ambushed. It is a mechanical reward for **setting up favourable fights**, which is exactly what shadowrunners are supposed to do.\n\n**Limits:** you can gain at most **2 Edge per combat round** from all sources, and your Edge pool is capped at **7** regardless of your Edge attribute.\n\n**Spending it** — Edge is spent from lists of **Edge Boosts** (cheap, mechanical: extra dice, rerolls, buying a hit) and **Edge Actions** (expensive, dramatic: doing something no roll would allow). Costs run roughly **1 to 5** points, and some are declared **before** the roll while others can be used **after** you see the result.\n\nThe strategic read: **Edge is not saved, it is cycled**. A runner who ends a session with 7 unspent Edge played badly.',
    seeAlso: ['Attack Rating', 'Defense Rating', 'EDG', 'Test', 'Critical Glitch'],
    aliases: ['edge points', 'spend edge', 'edge boost', 'edge action'],
  },
  {
    term: 'Attack Rating',
    kind: 'term',
    short: 'How threatening your attack is; compare it to the target\'s Defense Rating to see who earns Edge.',
    body: '**Attack Rating (AR)** is a static number describing how dangerous a given attack is. It is **not** an attack roll and it does **not** decide whether you hit — that is still an **Opposed Test**.\n\nAR comes from the attack itself: the **weapon\'s own AR** (usually listed per range band), plus relevant attributes and modifiers. A gun has a different AR at 5 metres than at 200; a spell and a Matrix action have their own AR too.\n\nIts **only** job is the comparison with **Defense Rating**:\n\n· **AR ≥ DR + 4** → **the attacker gains 1 Edge**\n· **DR ≥ AR + 4** → **the defender gains 1 Edge**\n· Otherwise → **nobody gains Edge**\n\nThat is it. AR does not add dice, does not add damage, and does not modify the roll.\n\nBut it reshapes tactics completely, because it means **positioning is worth Edge**. Closing to a range band where your weapon\'s AR spikes, or picking the target whose armor is weakest, earns you a resource that then bends the actual rolls. The system pays you for choosing your fights well — which is the whole fantasy of being a professional.',
    seeAlso: ['Defense Rating', 'Edge', 'Armor', 'Opposed Test'],
    aliases: ['ar', 'attack rating', 'ar/dr'],
  },
  {
    term: 'Defense Rating',
    kind: 'term',
    short: 'Body + your armor rating; compare it to the attacker\'s Attack Rating to see who earns Edge. This is not AC.',
    body: '**Defense Rating (DR)** is a static number describing how hard you are to threaten. It is essentially **Body + your total armor rating**.\n\nSay this clearly: **DR is not armor class**. It never affects whether you are hit. Being hit is decided by an **Opposed Test** — the attacker rolls Agility + Firearms, you roll **Reaction + Intuition**, and hits are compared. Your DR is not part of that at all.\n\nDR does exactly one thing: the **AR vs DR** comparison.\n\n· **DR ≥ AR + 4** → **you gain 1 Edge**\n· **AR ≥ DR + 4** → **the attacker gains 1 Edge**\n· Within 3 → nobody gains anything\n\nSo good armor does not make you harder to shoot. It makes attacking you **unprofitable** — the shooter earns no Edge, and you might earn some, which you then spend to make their life worse.\n\nArmor **also** helps separately when the bullet lands: your **damage resistance test** is **Body + armor rating**, and each hit removes a box of damage. So armor appears in the maths twice, in two completely different places, and neither of them is AC.',
    seeAlso: ['Attack Rating', 'Edge', 'Armor', 'BOD', 'Opposed Test'],
    aliases: ['dr', 'defense rating', 'defence rating', 'ac'],
  },
  {
    term: 'Defaulting',
    kind: 'mechanic',
    short: 'Using a skill you do not have: roll the attribute alone at a penalty, with a real chance of glitching.',
    body: 'You can attempt almost anything without the skill. **Defaulting** means rolling the **linked attribute alone**, at a **penalty**, with no skill dice at all.\n\nWhat that means in practice is brutal. Instead of Agility 4 + Firearms 5 (**9 dice**, ~3 hits), you are rolling Agility 4 minus the penalty (**~3 dice**, ~1 hit). And a pool that small is deep in **glitch** territory: 3 dice glitch whenever 2 of them come up 1, which is not rare.\n\nSo defaulting is not merely "worse". It is:\n\n· Unlikely to reach even a **threshold 2**\n· Disproportionately likely to **glitch**\n· Genuinely likely to **critically glitch** — a glitch with zero hits, which a 3-dice pool produces often\n\nSome skills **cannot be defaulted** at all — the specialised, trained ones. You cannot default your way into performing surgery, summoning a spirit, or running the Matrix. Those require the skill and, in several cases, an **attribute you do not have** (**MAG**, **RES**).\n\nThe design lesson: Shadowrun does not gate you out of trying, it just makes amateurism dangerous. Which is why runner teams are **specialists**, and why the team without a Decker does not "try hacking" — they hire one.',
    seeAlso: ['Test', 'Skills', 'Glitch', 'Critical Glitch'],
    aliases: ['default', 'untrained', 'no skill'],
  },
  {
    term: 'Skills',
    kind: 'term',
    short: 'Rated 1–6 and ADDED to an attribute to size the dice pool. Specializations add +2 dice, expertise +3.',
    body: '**Skills** are rated **1 to 6** and are **added to an attribute** to build the dice pool. The skill is not a bonus to a roll — it is **dice**.\n\nSixth World uses a **short, broad skill list** rather than a sprawling one: **Astral, Athletics, Biotech, Close Combat, Con, Conjuring, Cracking, Electronics, Enchanting, Engineering, Exotic Weapons, Firearms, Influence, Outdoors, Perception, Piloting, Sorcery, Stealth, Tasking**. One skill covers what earlier editions split into five.\n\nNarrowing back down happens through:\n\n· **Specialization** — **+2 dice** when the specialty applies (Firearms: Assault Rifles)\n· **Expertise** — **+3 dice** in a narrower area, and it replaces the specialization rather than stacking with it\n\nSo the real pool for a specialist is **Attribute + Skill + 2** (or **+3**), and that is what you should be reading off the sheet in play.\n\n**Skill 6** is the practical human maximum and represents world-class ability. Note what is *not* here: no proficiency bonus scaling with level, no trained/untrained binary, no skill ranks per level. A skill is a flat number that you raise with **Karma**, one point at a time, forever.\n\nSome skills are gated by an attribute you may not possess: **Sorcery**, **Conjuring** and **Enchanting** need **MAG**; **Tasking** needs **RES**.',
    seeAlso: ['Test', 'Defaulting', 'Karma', 'MAG', 'RES'],
    aliases: ['skill', 'skill rating', 'specialization', 'specialisation', 'expertise'],
  },

  // ── Attributes ───────────────────────────────────────────────────────────────────────────
  {
    term: 'BOD',
    kind: 'stat',
    short: 'Body: physical toughness. It sets your Physical track, your Defense Rating, and your damage resistance.',
    body: '**Body** is how much punishment you can take. Rated **1–6** for most metahumans, higher for **Orks** and **Trolls**.\n\nIts jobs:\n\n· **Physical condition monitor = 8 + (BOD ÷ 2, rounded up)** boxes\n· **Damage resistance test = Body + armor rating** — each hit soaks a box of damage\n· **Defense Rating** = Body + armor rating\n· **Overflow** — how far past the end of your Physical track you can go before dying is based on Body\n· Resisting **toxins, disease, fatigue** and **drain-adjacent** physical effects\n\nBody appears in the survival maths **three separate times** — track size, damage resistance, and overflow — which is why a low-Body character is not merely fragile but compoundingly fragile.\n\nIt is also the attribute most eroded by the game\'s central trade: **cyberware costs Essence**, and Essence loss does not reduce Body directly, but the low-Essence street samurai has typically bought **augmented Body** and armor to compensate for what they can no longer do naturally.\n\n**Bone Lace**, **Dermal Plating** and **Orthoskin** all raise Body or armor. All of them cost Essence.',
    seeAlso: ['Condition Monitor', 'Armor', 'Defense Rating', 'Dying', 'ESS'],
    aliases: ['body', 'body attribute'],
  },
  {
    term: 'AGI',
    kind: 'stat',
    short: 'Agility: the attribute of shooting, sneaking, and close combat — the street samurai\'s primary.',
    body: '**Agility** is physical precision and coordination, rated **1–6** for most metahumans (**Elves** go higher).\n\nIt pairs with the skills that decide firefights:\n\n· **Agility + Firearms** — the attack test for every gun in the book\n· **Agility + Close Combat** — melee\n· **Agility + Stealth** — sneaking, the opposed test against a guard\'s Perception\n· **Agility + Athletics** — running, climbing, jumping\n· **Agility + Exotic Weapons**\n\nThat concentration makes Agility the most contested attribute for anyone who expects to shoot people, which is most runners. An **Agility 6 + Firearms 6 + specialization** street samurai rolls **14 dice** and averages nearly **5 hits**, which is roughly the ceiling of unaugmented human capability.\n\nAnd it is the attribute **cyberware** most aggressively targets. **Muscle Toner**, **Wired Reflexes** and a **Cyberarm** all raise it, and augmented attributes may exceed the natural maximum by up to **+4** — at an **Essence** cost that permanently lowers a magician\'s **MAG**.\n\nThe augmentation-versus-magic tension is not abstract. It is exactly this attribute.',
    seeAlso: ['REA', 'Skills', 'ESS', 'MAG', 'Attack Rating'],
    aliases: ['agility', 'agi attribute'],
  },
  {
    term: 'REA',
    kind: 'stat',
    short: 'Reaction: dodging and driving, and half of your Initiative — REA + INT + 1d6.',
    body: '**Reaction** is reflexive speed, rated **1–6** naturally.\n\nWhere it lives:\n\n· **Initiative = REA + INT + 1d6** — and Initiative Score determines how many **Minor Actions** you get\n· **REA + INT** — the **defence test** against every incoming attack\n· **REA + Piloting** — driving and flying\n\nThat middle one is the load-bearing use. **Every time anyone shoots at you, you roll Reaction + Intuition.** There is no armor class here — you defend by rolling, every single time, and Reaction is half that pool.\n\nSo Reaction is the attribute that keeps you alive *before* the damage step, in the same way Body keeps you alive after it. A runner who has invested in one and not the other has a hole.\n\n**Wired Reflexes**, **Synaptic Boosters** and **Reaction Enhancers** all raise it, and they are among the most common pieces of chrome in the Sixth World precisely because Reaction pays out twice — better defence **and** more actions per round.\n\nThey also cost **Essence**, which is why the wired street samurai will never be a mage.',
    seeAlso: ['Initiative', 'INT', 'Major and Minor Actions', 'ESS', 'Opposed Test'],
    aliases: ['reaction', 'rea attribute'],
  },
  {
    term: 'STR',
    kind: 'stat',
    short: 'Strength: melee damage, lifting, and climbing. It sets what your close combat actually does.',
    body: '**Strength** is raw physical power, rated **1–6** naturally (**Dwarves**, **Orks** and especially **Trolls** exceed that).\n\nIts main mechanical role is **melee damage**: close combat weapons base their **Damage Value** on Strength, so the same monofilament whip in a Troll\'s hand and a decker\'s hand are different weapons. Unarmed damage is Strength-derived too.\n\nIt also handles lifting, carrying, breaking things, and it contributes to **Athletics** tests for climbing and jumping alongside Agility.\n\nStrength is the attribute most runners **dump**, and mostly they are right to: guns do not care about Strength, and Shadowrun is a game about guns. It matters if you are building a melee adept, a Troll, or a character who intends to solve problems physically.\n\n**Muscle Replacement** and **Bone Lace** raise it; **Cyberarms** have their own Strength rating that replaces yours for what that limb does. Adepts raise it with **Improved Physical Attribute** power points, which is one of the few ways to get high physical stats **without** paying Essence — and is exactly why physical adepts exist.',
    seeAlso: ['AGI', 'BOD', 'Adept', 'ESS'],
    aliases: ['strength', 'str attribute'],
  },
  {
    term: 'WIL',
    kind: 'stat',
    short: 'Willpower: your Stun track, your Drain resistance, and your defence against mental influence.',
    body: '**Willpower** is mental fortitude, rated **1–6** naturally, and it is the most quietly universal attribute in the game.\n\n· **Stun condition monitor = 8 + (WIL ÷ 2, rounded up)** boxes\n· **Drain resistance** — **WIL + LOG** (hermetic) or **WIL + CHA** (shamanic), the roll that stops spellcasting from hurting you\n· **Fading resistance** for technomancers\n· **WIL + LOG** — resisting **Con** and social manipulation\n· **WIL + INT** — composure, resisting fear and intimidation\n· Resisting **direct combat spells**\n\nNo character can safely dump Willpower. A low-WIL character has a **small Stun track**, which means they get knocked out by tasers, punches, fatigue and stun rounds — and stun damage that overflows a full Stun track **bleeds into the Physical track**, so "just" being tased twice can start actually killing you.\n\nFor a **magician** it is worse: Willpower is half the Drain resistance pool, and failed Drain resistance is how mages hurt themselves. A mage with WIL 2 casting a big spell is doing more damage to themselves than to the target.',
    seeAlso: ['Condition Monitor', 'Stun Damage', 'Drain', 'Fading', 'LOG', 'CHA'],
    aliases: ['willpower', 'wil attribute', 'will'],
  },
  {
    term: 'LOG',
    kind: 'stat',
    short: 'Logic: analysis, technical skills, and — for hermetic mages — half the Drain resistance pool.',
    body: '**Logic** is trained reasoning and technical knowledge, rated **1–6** naturally.\n\nIt pairs with:\n\n· **LOG + Cracking** — Matrix hacking, the Decker\'s core skill\n· **LOG + Electronics** — devices, software, sensors, Matrix search\n· **LOG + Engineering** — building, demolitions, mechanics\n· **LOG + Biotech** — first aid, medicine, cybersurgery\n· **WIL + LOG** — **Drain resistance** for **hermetic** traditions, and resisting Con\n\nThe Drain clause is what makes Logic a **magician\'s** stat as much as a technician\'s. A hermetic mage lives and dies by **WIL + LOG**; a shamanic one uses **WIL + CHA** instead. Choosing your tradition is choosing which of these attributes you cannot afford to dump.\n\nLogic is also the **Decker\'s** primary, in a Role that is otherwise gated behind expensive gear. A Decker with **LOG 6 + Cracking 6** rolls 12 dice against ICE, and that pool is the entire difference between a successful run and a **critical glitch** that spikes their **Overwatch Score**.\n\nUnlike Agility, Logic is rarely worth chroming — **Cerebral Boosters** exist, but the Essence cost lands hardest on exactly the mages who need Logic most.',
    seeAlso: ['Drain', 'Decker', 'Matrix', 'WIL', 'INT'],
    aliases: ['logic', 'log attribute'],
  },
  {
    term: 'INT',
    kind: 'stat',
    short: 'Intuition: perception, instinct, and half of both your Initiative and your defence roll.',
    body: '**Intuition** is instinct and situational awareness, rated **1–6** naturally, and it is arguably the best attribute in the game because it appears in three places that all matter constantly.\n\n· **Initiative = REA + INT + 1d6**\n· **REA + INT** — the **defence test** against every attack\n· **INT + Perception** — noticing everything, including the ambush\n· **INT + Astral** — astral perception\n· **INT + Outdoors** — navigation and survival\n· **WIL + INT** — composure\n\nRead that list again. Intuition contributes to **acting first**, to **not being shot**, and to **seeing it coming**. No other attribute does all three.\n\nThe practical consequence: **nobody dumps Intuition**, regardless of build. The mage needs it to not die; the decker needs it to not be surprised; the samurai needs it for initiative and defence.\n\nIt is also the attribute that most resists chroming — perception-enhancing cyberware helps the **Perception test** with dice bonuses, but Intuition itself is hard to buy. It is the one thing on the sheet that has to be **you**.',
    seeAlso: ['REA', 'Initiative', 'Opposed Test', 'Astral', 'WIL'],
    aliases: ['intuition', 'int attribute'],
  },
  {
    term: 'CHA',
    kind: 'stat',
    short: 'Charisma: social force, summoning power, and — for shamanic mages — half the Drain resistance pool.',
    body: '**Charisma** is force of personality, rated **1–6** naturally (**Elves** reach higher, which is why the archetypal Face is an Elf).\n\n· **CHA + Influence** — negotiation, leverage, persuasion, leadership\n· **CHA + Con** — lying, impersonation, the fast talk\n· **CHA + Conjuring** — **summoning and binding spirits**\n· **WIL + CHA** — **Drain resistance** for **shamanic** traditions\n\nThe interesting overlap is that Charisma is simultaneously the **Face\'s** stat and the **conjurer\'s** stat. Summoning a spirit is a **CHA + Conjuring** opposed test against the spirit\'s Force — you are talking it into service, and that is exactly as social as it sounds.\n\nFor a **shamanic** mage, Charisma is also half their Drain pool, which makes the shaman/Face the single most natural multi-hat build in Shadowrun.\n\nCharisma is the attribute **cyberware punishes most indirectly** — there is nothing to install that makes you charming, and heavy visible chrome tends to make social situations worse. The Face is usually the least-augmented person on the team, and that is not a coincidence.',
    seeAlso: ['Drain', 'Summoning', 'Spirit', 'WIL', 'Magician'],
    aliases: ['charisma', 'cha attribute', 'face'],
  },
  {
    term: 'EDG',
    kind: 'stat',
    short: 'Edge attribute: how much Edge you start each session with — it is not the Edge you spend in play.',
    body: '**Edge (EDG)** is a **special attribute**, rated **1–6** for most metahumans (**Humans** go to **7**, and that is their signature advantage).\n\nDistinguish two things carefully, because the same word does both jobs:\n\n· The **Edge attribute** — a rating on your sheet, raised with Karma\n· The **Edge pool** — the points you actually spend, which you gain and burn throughout play\n\nYour **attribute** sets what you begin each session with. Then during play you **earn more** — principally from the **Attack Rating vs Defense Rating** comparison — up to a hard **cap of 7 points**, gaining no more than **2 per combat round**.\n\nSo a **Human** with **EDG 7** is not "luckier". They start with a full pool, and the cap means they cannot bank any more — they are under constant pressure to **spend**. That is the intended play pattern for the metatype.\n\nA low-EDG character is not locked out of Edge; they just have to **earn** theirs from good tactics. Which is exactly the point of the 6e redesign: Edge is a reward for playing well, not a birthright.',
    seeAlso: ['Edge', 'Attack Rating', 'Defense Rating', 'Metatype', 'Karma'],
    aliases: ['edge attribute', 'edg'],
  },
  {
    term: 'ESS',
    kind: 'stat',
    short: 'Essence: starts at 6, drops with every implant, and every full point lost costs a magician 1 MAGIC.',
    body: '**Essence** starts at **6.00** for everyone and only ever goes down. It is the measure of your intact metahuman soul.\n\nEvery piece of **cyberware** and **bioware** has an Essence cost, subtracted permanently on installation. Wired Reflexes, a cyberarm, a datajack — all of it comes out of the same 6 points.\n\nThe rule that defines the setting:\n\n· **Each full point of Essence lost reduces MAGIC (or RESONANCE) by 1.**\n\nSo a mage who installs 1.2 Essence of chrome loses **1 point of MAGIC** — permanently, and it does not come back when the ware is removed. Enough augmentation and a magician is simply **not a magician any more**. This is why the street samurai and the mage are different people; the game makes it arithmetically impossible to be both.\n\n· **Essence 0 is death.** Not unconsciousness. There is a floor and you can hit it on a surgery table.\n· Low Essence has social weight too — the mostly-chrome runner reads as *wrong* to people and to spirits.\n\nEssence cannot be restored by any ordinary means. It is the one number on the sheet that is genuinely, permanently one-way.',
    seeAlso: ['MAG', 'RES', 'Magician', 'Adept'],
    aliases: ['essence', 'ess attribute', 'essence loss'],
  },
  {
    term: 'MAG',
    kind: 'stat',
    short: 'Magic: only Awakened characters have it. It sizes spellcasting and summoning, and Essence loss eats it.',
    body: '**Magic (MAG)** is a **special attribute** that most people **do not have at all**. It exists only for the **Awakened**: magicians (mages, shamans, mystic adepts) and **adepts**.\n\nWhat it does:\n\n· It is a **skill\'s linked attribute** — **MAG + Sorcery** to cast, **MAG + Conjuring** to summon, **MAG + Enchanting** for foci and alchemy\n· It caps the **Force** of spells you can handle safely\n· For **adepts**, it grants **power points** — 1 per point of Magic — to buy adept powers\n· It gates **astral projection** and how far you can push it\n\nYou get MAG through **priority character creation** — you must assign a priority to Magic/Resonance, and how high a rating you get depends on how high a priority you spent.\n\nAnd then the trap: **every full point of Essence lost reduces MAG by 1**, permanently, and it never comes back. A mage who takes a datajack and a cybereye has quietly paid a point of Magic for the convenience. A mage who takes Wired Reflexes has stopped being a mage.\n\nMAG can be raised with **Karma**, but only back toward — never above — the ceiling your Essence permits.',
    seeAlso: ['ESS', 'Magician', 'Adept', 'Drain', 'Spellcasting', 'Priority Character Creation'],
    aliases: ['magic', 'mag attribute', 'awakened'],
  },
  {
    term: 'RES',
    kind: 'stat',
    short: 'Resonance: the technomancer\'s equivalent of Magic. Essence loss eats it exactly the same way.',
    body: '**Resonance (RES)** is the **special attribute** of the **Emerged** — technomancers, who interact with the Matrix as a native phenomenon rather than through hardware.\n\nIt is structurally the mirror of **MAG**:\n\n· **RES + Tasking** — **compiling, registering and commanding sprites**\n· It sizes **complex forms** — the technomancer\'s answer to spells and programs\n· It sets the technomancer\'s **living persona** Matrix attributes, so they need no cyberdeck at all\n· **Fading** resistance is **WIL + RES**\n\nAnd it carries the same curse: **every full point of Essence lost reduces RES by 1**, permanently. A technomancer who chromes up stops being a technomancer, exactly as a mage does. There is no version of this game where augmentation and the numinous coexist.\n\nYou get RES through **priority character creation** — Magic and Resonance share a single priority column, so you choose one or the other, never both.\n\nTechnomancers are the rarest and most feared thing in the Sixth World: they have **no cyberdeck to confiscate**, which corporations find genuinely alarming, and which makes them the target of a great deal of unfriendly research.',
    seeAlso: ['ESS', 'Technomancer', 'Sprite', 'Fading', 'Matrix', 'Priority Character Creation'],
    aliases: ['resonance', 'res attribute', 'emerged'],
  },

  // ── Damage and combat ────────────────────────────────────────────────────────────────────
  {
    term: 'Condition Monitor',
    kind: 'term',
    short: 'Two separate damage tracks — Physical (8 + BOD÷2) and Stun (8 + WIL÷2). Not one HP number.',
    body: 'Shadowrun has **no hit points**. It has **two condition monitors**, tracked separately in boxes:\n\n· **Physical — 8 + (BOD ÷ 2, rounded up)** boxes. Bullets, blades, falls, fire.\n· **Stun — 8 + (WIL ÷ 2, rounded up)** boxes. Fists, tasers, gas, fatigue, **Drain**.\n\nSo **BOD 4** gives a **10-box** Physical track; **WIL 3** gives a **10-box** Stun track. The numbers are small and they do **not scale** — there is no level, no hit die, no per-level increase. A veteran of forty runs has the same track as a rookie with the same Body.\n\nBoth tracks matter, and the second one is the one people forget:\n\n· Damage in **either** track imposes **wound modifiers** that shrink **every dice pool you roll**\n· Filling the **Stun** track knocks you **unconscious**\n· **Stun damage that overflows a full Stun track becomes Physical damage**, box for box\n· Filling the **Physical** track means you are **dying**\n\nThat overflow rule is why "non-lethal" is a lie in the Sixth World. Enough taser hits will absolutely kill you — the damage simply changes tracks and keeps going.',
    seeAlso: ['Physical Damage', 'Stun Damage', 'Wound Modifier', 'Dying', 'BOD', 'WIL'],
    aliases: ['condition monitors', 'damage track', 'hp', 'health', 'boxes'],
  },
  {
    term: 'Physical Damage',
    kind: 'condition',
    short: 'Real injury on the 8 + BOD÷2 track. Fill it and you are dying; overflow past it and you are dead.',
    body: '**Physical damage** goes on the track of **8 + (BOD ÷ 2, rounded up)** boxes. It is what guns, blades, falls, fire and Physical Drain do.\n\nHow much you take: the attack has a **Damage Value**, increased by the attacker\'s **net hits**. You then roll a **damage resistance test** of **Body + armor rating**, and **each hit removes one box**. What is left goes on the track.\n\nThat resistance roll is the whole reason armor matters. A DV 9 assault rifle burst against **Body 5 + armor 12** means rolling **17 dice** and soaking about **5 or 6** boxes — leaving 3 or 4. The same burst against an unarmoured civilian is most of a track.\n\nAs the track fills, **wound modifiers** subtract dice from **everything** you do, which is the death spiral: hurt means fewer dice means worse defence means more hurt.\n\n· **Fill the track** → you are **dying** and must be stabilised\n· **Overflow past it** by more than your **Body** → **dead**\n\nHealing is slow and medical — days, not hours, with a **Body + Willpower** test per interval, or a **Biotech** test to speed it. There is no healing magic that simply undoes it, and even **Heal** spells have limits and cost **Drain**.',
    seeAlso: ['Condition Monitor', 'Stun Damage', 'Wound Modifier', 'Dying', 'Healing', 'Armor'],
    aliases: ['physical track', 'physical', 'wounds', 'damage'],
  },
  {
    term: 'Stun Damage',
    kind: 'condition',
    short: 'Non-lethal damage on the 8 + WIL÷2 track. Fill it and you black out; overflow becomes PHYSICAL damage.',
    body: '**Stun damage** goes on the track of **8 + (WIL ÷ 2, rounded up)** boxes. Sources: fists, tasers, stick-n-shock rounds, gas, fatigue, and — critically — **Drain** from spellcasting and **Fading** from complex forms.\n\nResist it with **Body + armor** as normal for most physical stun, or with the appropriate pool for Drain and Fading.\n\nWhat it costs:\n\n· Stun damage imposes the same **wound modifiers** as physical — **−1 die to every pool per 3 boxes**\n· **Filling the Stun track** knocks you **unconscious**\n· **Overflow from a full Stun track converts to Physical damage**, box for box\n\nThat conversion is the rule that catches everyone. "Non-lethal" weapons kill people in Shadowrun. Enough stun and you are not asleep — you are bleeding out, because the excess has jumped tracks.\n\nIt is also the mage\'s personal problem. **Drain is Stun damage** by default, and a mage who casts too much too fast fills their Stun track and drops. Push a spell hard enough that its **Drain Value exceeds their MAGIC** and the Drain lands as **Physical** instead — which is how magicians kill themselves.\n\nStun heals **fast** — roughly an hour per box with a **BOD + WIL** test. Physical does not.',
    seeAlso: ['Condition Monitor', 'Physical Damage', 'Wound Modifier', 'Drain', 'Fading', 'Healing'],
    aliases: ['stun track', 'stun', 'unconscious', 'knocked out'],
  },
  {
    term: 'Wound Modifier',
    kind: 'mechanic',
    short: 'Every 3 boxes of damage on a track costs you −1 die on every pool you roll. The death spiral is mechanical.',
    body: 'For every **3 boxes of damage** in a condition monitor, you take **−1 die to every dice pool you roll**. Both tracks count, and they **stack**.\n\nSo a runner with **6 boxes of Physical** and **3 boxes of Stun** is at **−3 dice** on **everything**: attacks, defence, Perception, driving, hacking, spellcasting, and their own damage resistance test.\n\nRead that last one again. **Wound modifiers apply to the damage resistance test.** Being hurt makes you soak less, which makes you more hurt, which makes you soak less. That is not flavour — it is a compounding mechanical spiral, and it is the reason Shadowrun combat resolves fast and badly.\n\nWhy it hits so much harder than a flat penalty in a d20 game: **−3 dice off a 9-dice pool is a third of your capability gone**, and it drags your expected hits from 3 down to 2. It also pushes you closer to **glitch** territory, since a smaller pool glitches more readily.\n\nThe practical rule at the table: the moment wound modifiers appear, the fight has changed. Runners who keep trading shots at −3 are runners who die. This is what **Edge**, cover, and leaving are for.\n\n**Pain editors** and similar chrome suppress the modifier — at an Essence cost, and with their own consequences.',
    seeAlso: ['Condition Monitor', 'Physical Damage', 'Stun Damage', 'Glitch', 'Test'],
    aliases: ['wound modifiers', 'wound penalty', 'damage penalty'],
  },
  {
    term: 'Dying',
    kind: 'condition',
    short: 'A full Physical track means you are bleeding out; overflow past your Body rating means dead.',
    body: 'When your **Physical condition monitor fills**, you are **unconscious and dying**. You are losing further boxes as **overflow** past the end of the track.\n\n· The **overflow allowance** is based on your **Body** — you can absorb roughly Body\'s worth of boxes past a full track.\n· **Exceed that** and you are **dead**. No roll.\n· Damage taken **while** already at a full track goes straight into overflow, which is why shooting a downed runner is so effective and so common.\n\nStopping it requires someone to **stabilise** you: a **Biotech (First Aid)** test, a Medkit, or a magician\'s **Heal** spell. First Aid stops the bleed and can restore a box or two; it does not make you well.\n\nRemember the other route in: **Stun overflow becomes Physical damage**. A character can be beaten unconscious with fists and then, with no change in weapon, beaten to death — the damage simply moves tracks.\n\nWhat does not exist: **resurrection**. Nothing brings back the dead in the Sixth World. **DocWagon** is the closest analogue — a paid contract that dispatches a heavily armed medical team to your last known location, and it is a subscription service with tiers, response times, and fine print.',
    seeAlso: ['Physical Damage', 'Condition Monitor', 'Healing', 'BOD', 'Stun Damage'],
    aliases: ['dying', 'death', 'overflow', 'bleeding out', 'docwagon'],
  },
  {
    term: 'Healing',
    kind: 'mechanic',
    short: 'Stun heals in about an hour per box; Physical takes days. Biotech and Heal spells speed it up.',
    body: 'Recovery runs on **natural healing tests** at fixed intervals, and the two tracks heal at wildly different rates.\n\n· **Stun** — roughly **one hour** per interval; roll **BOD + WIL** and **each hit clears a box**\n· **Physical** — roughly **one day** per interval; roll **BOD + WIL** and each hit clears a box\n\nSo the mage who Drained themselves unconscious is fine after lunch. The samurai who took 8 boxes of Physical is out for the better part of a week.\n\nSpeeding it up:\n\n· **Biotech (First Aid)** — immediate field treatment, restores boxes, and it is the thing that **stabilises a dying** character. One attempt per wound.\n· **Biotech (Medicine)** — proper treatment, improves the healing interval\n· **Heal** spell — a magician can heal **Physical** damage directly, but only within limits, only on relatively fresh wounds, and always at the cost of **Drain**\n· A **clinic** or **street doc** with real facilities — money buys recovery time\n\nWhat there is **not**: any equivalent of a long rest that refills you overnight, or a healing resource per day. Injury in Shadowrun is **downtime**, and downtime costs **lifestyle** money. Getting shot has a bill attached.',
    seeAlso: ['Physical Damage', 'Stun Damage', 'Dying', 'Condition Monitor', 'Lifestyle'],
    aliases: ['heal', 'recovery', 'first aid', 'medkit', 'rest'],
  },
  {
    term: 'Armor',
    kind: 'term',
    short: 'A rating that feeds Defense Rating and adds dice to damage resistance — it never makes you harder to hit.',
    body: '**Armor** has a **rating**, and that rating does two jobs — **neither of which is armor class**.\n\n· **Defense Rating = Body + armor rating.** Compared to the attacker\'s **Attack Rating** to see who earns **Edge**.\n· **Damage resistance = Body + armor rating.** Rolled when a hit lands; each hit removes a box of damage.\n\nWhat armor **never** does: affect the attack roll. Being hit is decided by an **Opposed Test** — the attacker\'s Agility + Firearms against your **Reaction + Intuition**. Armor is not in that equation at all.\n\nSo heavy armor makes you **just as easy to shoot** and **much harder to hurt**, and it makes shooting you **unprofitable** in Edge terms. Those are three different statements and only the last two are true of armor here.\n\nThe standard kit runs from an **armor jacket** up through **full body armor** and **milspec**. Armor is worn as a **primary garment** with accessories adding to it — you do not stack five jackets.\n\nCyberware alternatives — **Dermal Plating**, **Orthoskin**, **Bone Lace** — provide armor that cannot be taken off or shot away, and cost **Essence**, which costs a magician their **MAG**.',
    seeAlso: ['Defense Rating', 'Attack Rating', 'Physical Damage', 'BOD', 'Edge', 'ESS'],
    aliases: ['armour', 'armor rating', 'armor jacket', 'ac'],
  },
  {
    term: 'Initiative',
    kind: 'mechanic',
    short: 'REA + INT + 1d6. Your Initiative Score also buys extra Minor Actions — every 5 full points is one more.',
    body: '**Initiative = REA + INT + 1d6**, rolled at the start of combat. Highest **Initiative Score** acts first.\n\nBut the score does more than order the turns. It **buys you actions**:\n\n· Everyone gets **1 Major Action** and **1 Minor Action** per combat round\n· You gain **one additional Minor Action for every full 5 points** of your **Initiative Score**\n\nSo an Initiative Score of **17** yields **3 extra Minor Actions** on top of the base — six things happening in a round where a slower character does two. This is where **Wired Reflexes** and **Synaptic Boosters** earn their **Essence** cost: they add dice to the initiative roll and raise **REA**, which is the same as buying actions.\n\nNote what changed from earlier editions: Initiative Score does **not** grant extra full Initiative Passes any more. You do not act three separate times. You get **more Minor Actions inside your one turn**, which is a meaningfully smaller advantage — deliberately so.\n\nA **Major Action can be traded down** for a Minor Action if you want more small things instead of one big one.\n\nThe augmented street samurai still goes first, still does more, and still cannot be a mage.',
    seeAlso: ['Major and Minor Actions', 'REA', 'INT', 'ESS'],
    aliases: ['init', 'initiative score', 'turn order', 'wired reflexes'],
  },
  {
    term: 'Major and Minor Actions',
    kind: 'mechanic',
    short: 'One Major and one Minor per round, plus an extra Minor per full 5 points of Initiative Score.',
    body: 'Each combat round you get:\n\n· **1 Major Action**\n· **1 Minor Action**\n· **+1 Minor Action per full 5 points of your Initiative Score**\n\nA **Major Action** is the big one: **firing a weapon**, casting a **spell**, a **melee attack**, summoning, a Matrix attack. One per round unless you have something special.\n\n**Minor Actions** are the connective tissue: **moving**, drawing or **readying a weapon**, **taking aim**, changing position, **reloading**, calling a shot, hitting the deck, speaking. Several of them stack usefully — **Aim** as a Minor Action improves your attack.\n\nYou can **trade a Major Action down for a Minor Action** if you want more small things. You cannot trade upward — four Minors do not become a Major.\n\nWhat this means for the wired samurai: they do not get to **shoot four times**. They get to shoot once and then **move, aim, reload and reposition** while everyone else is standing still. The advantage is **tempo and control**, not raw output — which is a real change from the older editions where high initiative meant multiple full turns.\n\nThe practical read: **one attack per round, for everyone**. Fights are decided by who lands theirs.',
    seeAlso: ['Initiative', 'REA', 'Test'],
    aliases: ['major action', 'minor action', 'actions', 'action economy', 'turn'],
  },

  // ── Magic ────────────────────────────────────────────────────────────────────────────────
  {
    term: 'Magician',
    kind: 'class',
    short: 'An Awakened character who casts spells, summons spirits, and projects astrally — a build concept, not a class.',
    body: 'A **magician** is an Awakened character with a **MAG** attribute who can **cast**, **summon**, and work **astrally**. It is a **build concept**, not a class: no level, no hit die, no spell slots, no spells-per-day.\n\nWhat defines one:\n\n· **MAG + Sorcery** — casting spells\n· **MAG + Conjuring** — summoning spirits\n· **MAG + Enchanting** — foci, alchemy, rituals\n· **Astral perception** and **astral projection**\n· A **tradition**, which decides your **Drain** pool: **hermetic** uses **WIL + LOG**, **shamanic** uses **WIL + CHA**\n\nThere is **no spell list per level and no daily budget**. You can cast the same spell all day. The limiter is **Drain** — every cast hurts you, and the harder you push the **Force**, the more it hurts. Mages are limited by their **Stun track**, not by resources.\n\nThe permanent cost of being one: **Essence loss reduces MAG point for point**, so a magician essentially cannot use **cyberware**. No Wired Reflexes, no Dermal Plating, no cybereyes without paying for them in Magic. The mage is the **unaugmented** member of the team, with a 10-box Stun track, standing in a firefight.\n\n**Mystic adepts** split MAG between spellcasting and adept powers, and are worse at both.',
    seeAlso: ['MAG', 'Drain', 'Spellcasting', 'Summoning', 'Astral', 'Adept', 'ESS'],
    aliases: ['mage', 'shaman', 'magicians', 'awakened', 'mystic adept', 'spellcaster'],
  },
  {
    term: 'Drain',
    kind: 'mechanic',
    short: 'Every spell hurts the caster: resist with WIL + LOG or WIL + CHA, and unresisted Drain is Stun damage.',
    body: '**Drain** is the price of magic, and it is why Shadowrun needs no spell slots.\n\nEvery time you cast, the spell has a **Drain Value**. You roll a **Drain resistance test** and each hit reduces it. What is left you **take as damage**.\n\n· **Hermetic** traditions resist with **WIL + LOG**\n· **Shamanic** traditions resist with **WIL + CHA**\n· Unresisted Drain is **Stun damage**\n· **If the Drain Value exceeds your MAGIC rating, it is PHYSICAL damage instead**\n\nThat last clause is the one that kills mages. Pushing a spell beyond what your Magic can handle does not fail — it **injures you for real**, on the track that takes days to heal.\n\nBecause Drain lands on the **Stun** track, and Stun overflow **converts to Physical**, a mage who chain-casts through a firefight is knocking themselves out and then killing themselves without anyone shooting at them.\n\nThis is the whole resource system for magic. There is **no per-day limit**, no slots, no recharging. You can cast as much as you can physically survive, and the spell that saves the team may be the spell that drops you.\n\n**Fading** is the technomancer\'s identical mechanic, resisted with **WIL + RES**.',
    seeAlso: ['Spellcasting', 'Magician', 'Stun Damage', 'MAG', 'Fading', 'WIL'],
    aliases: ['drain value', 'dv', 'drain resistance', 'overcasting'],
  },
  {
    term: 'Spellcasting',
    kind: 'action',
    short: 'MAG + Sorcery as a Major Action, opposed by the target; then resist the Drain it costs you.',
    body: '**Spellcasting** is a **Major Action**: roll **MAG + Sorcery**, usually as an **Opposed Test** against the target\'s resistance (**Willpower** plus a relevant attribute, depending on the spell).\n\nNet hits scale the effect — more net hits means more damage, a longer duration, a stronger effect.\n\nThen you **pay**: roll your **Drain resistance** (**WIL + LOG** or **WIL + CHA**) against the spell\'s **Drain Value**, and take what is left as **Stun** damage.\n\nThe categories:\n\n· **Combat** — direct (resisted by Willpower, ignores armor) and indirect (resisted like a physical attack, armor helps)\n· **Detection** — perceiving, analysing, mind reading\n· **Health** — **Heal**, **Increase Attribute**, antidotes\n· **Illusion** — obscuring, deceiving senses, both physical and mana-based\n· **Manipulation** — telekinesis, control, physical barriers\n\n**Direct combat spells bypass armor entirely** — they are resisted with **Willpower** alone. That is why the mage is the answer to the armoured target that guns cannot dent, and why corp security cares so much about magical threats.\n\nNo slots, no preparation, no daily budget. You know your spells; you can cast them until your **Stun track** stops you.',
    seeAlso: ['Drain', 'Magician', 'MAG', 'Stun Damage', 'Astral'],
    aliases: ['cast', 'casting', 'spell', 'spells', 'sorcery', 'force'],
  },
  {
    term: 'Summoning',
    kind: 'action',
    short: 'CHA + Conjuring opposed by the spirit\'s Force; net hits are the services it owes you. Then resist Drain.',
    body: '**Summoning** is a **Major Action** and it is a negotiation: roll **CHA + Conjuring** in an **Opposed Test** against the spirit\'s **Force**.\n\n· Your **net hits** are the number of **services** the spirit owes you.\n· If the spirit wins, you get nothing — and you still take **Drain**.\n· Drain from summoning scales with the spirit\'s **Force** and with how badly the contest went.\n\nSummoning **Force higher than your MAGIC** is the classic mistake: the spirit is more likely to beat you, and the Drain is more likely to land as **Physical** damage.\n\n**Services** are the currency. Each service is one significant task — attack that, guard this, carry us there, use a power on my behalf. When the services run out, the spirit goes home. A spirit with **4 services** is a serious asset for a run; a spirit with **1** is a single favour.\n\n**Binding** a spirit — a longer ritual with its own Drain — gives you a spirit you can call on repeatedly rather than one summoned in the moment.\n\nSpirits are **not pets**. They are intelligent, they have their own agendas, and a spirit summoned by a runner who glitches is a spirit that is now free and annoyed.',
    seeAlso: ['Spirit', 'CHA', 'Drain', 'Magician', 'Astral'],
    aliases: ['summon', 'conjuring', 'services', 'binding'],
  },
  {
    term: 'Spirit',
    kind: 'term',
    short: 'A summoned entity rated by Force; its attributes derive from Force and it owes you a set number of services.',
    body: 'A **spirit** is an intelligent entity from the astral, summoned by a magician\'s **Conjuring**. Its power is a single number: its **Force**.\n\nAlmost everything about a spirit derives from Force — its attributes, its dice pools, its condition monitor. A **Force 6** spirit is a serious combatant that will comfortably beat most metahumans at most things.\n\nThe types follow the **tradition**: spirits of **Air**, **Earth**, **Fire**, **Water**, **Man**, **Beast**, and task/guardian/plant spirits, each with its own powers. Common ones include **Immunity to Normal Weapons** — mundane bullets simply do not work — which is why a summoned spirit in a firefight is a crisis for anyone without magic or a weapon focus.\n\nThey **materialise** to act physically, or stay **astral** where only astral perception can see them.\n\nThe leash is **services**. A spirit performs the number of services it owes and then departs. It is not obedient — it is contractually obliged, and it will interpret instructions with exactly as much goodwill as the summoning went with.\n\nA **critically glitched** summoning produces a free, hostile, Force-rated spirit that knows exactly who summoned it. This is the single most reliable way for a magician to end a campaign.',
    seeAlso: ['Summoning', 'Magician', 'Astral', 'Critical Glitch', 'CHA'],
    aliases: ['spirits', 'force', 'elemental', 'summoned'],
  },
  {
    term: 'Astral',
    kind: 'mechanic',
    short: 'The parallel plane magicians can perceive or bodily project into — where living things glow and lies show.',
    body: 'The **astral plane** is a parallel layer overlaying the physical world, and only the **Awakened** can interact with it.\n\nTwo different things:\n\n· **Astral perception** — you stay in your body and **see** the astral. **INT + Astral**. Living things blaze with auras, magic is visible, emotions leave residue. You can spot a spirit, read an aura, notice that someone is Awakened. While perceiving you are **distracted** in the physical world and defend worse.\n· **Astral projection** — **magicians only** (not adepts). You **leave your body** and travel astrally at enormous speed. Your body sits there, defenceless, breathing. You cannot interact with the physical world at all — you can only see, move, and fight **other astral things**.\n\n**Astral combat** uses **WIL** and the **Astral** skill and hits your **Stun** track. Getting killed on the astral kills you for real.\n\nWhat it is good for: **reconnaissance** (walls do not stop you), **spotting wards and spirits**, **reading auras** to tell if someone is lying or chromed or Awakened.\n\nWhat stops you: **wards**, **mana barriers**, and other magicians. Corp facilities have astral security precisely because a projecting mage would otherwise walk through every wall in the building.\n\n**Adepts cannot project.** They can sometimes perceive, with the right power.',
    seeAlso: ['Magician', 'Spirit', 'Adept', 'INT', 'Stun Damage'],
    aliases: ['astral plane', 'astral projection', 'astral perception', 'aura', 'wards'],
  },
  {
    term: 'Adept',
    kind: 'class',
    short: 'Awakened, but internal: MAG buys power points for physical powers. No spells, no summoning, no projection.',
    body: 'An **adept** channels their Magic **inward** rather than outward. Same **MAG** attribute, completely different use.\n\n· **MAG gives power points** — **1 point per point of Magic**\n· Spend those points on **adept powers**: **Improved Reflexes**, **Improved Physical Attribute**, **Combat Sense**, **Killing Hands**, **Improved Ability** (a skill), **Danger Sense**, **Wall Running**, and more\n· Powers cost fractional or whole points, so a **MAG 6** adept is building from a 6-point budget\n\nWhat an adept **cannot** do: **cast spells**, **summon spirits**, or **project astrally**. They are Awakened without being a magician.\n\nWhy they exist mechanically: an adept gets **superhuman physical capability without spending Essence**. **Improved Reflexes** does what Wired Reflexes does, and costs **power points** instead of the soul you would need to keep being Awakened. The adept is the answer to "I want to be fast and I want to stay magical".\n\nAnd the catch is symmetrical: **Essence loss still reduces MAG**, so an adept who chromes up loses power points and stops being an adept. They face exactly the same wall as the mage, from the other side.\n\n**Mystic adepts** split MAG between spellcasting and power points, and are meaningfully worse at both than a specialist.',
    seeAlso: ['MAG', 'Magician', 'ESS', 'Astral', 'STR'],
    aliases: ['adepts', 'physical adept', 'power points', 'mystic adept'],
  },

  // ── The Matrix ───────────────────────────────────────────────────────────────────────────
  {
    term: 'Matrix',
    kind: 'mechanic',
    short: 'The wireless world. Deckers hack it with LOG + Cracking; every illegal action feeds your Overwatch Score.',
    body: 'The **Matrix** is the wireless network everything in the Sixth World is attached to — guns, doors, cyberware, cars, cameras, people. If it has a wireless connection, someone can hack it.\n\nRunning it means:\n\n· **LOG + Cracking** for the illegal actions — **Hack on the Fly**, **Brute Force**, and the rest\n· **LOG + Electronics** for the legal ones — **Matrix Search**, **Matrix Perception**, device control\n· Your **Matrix attributes** — **Attack, Sleaze, Data Processing, Firewall** — from your **cyberdeck**\n· **Marks** on a target to interact with it\n· And a rising **Overwatch Score** every time you do something illegal\n\nTwo ways to be there:\n\n· **AR (augmented reality)** — overlays on your normal vision. Slower in the Matrix, but you keep your body and your senses. Safe.\n· **VR (virtual reality)** — full immersion. Much faster, much better initiative, and your body is now a slumped object on the floor. **Hot-sim** is fastest of all and exposes you to **biofeedback damage**.\n\nThat is the Decker\'s central bet, every single run: **hot-sim VR** or stay safe. Fast enough to matter, or alive enough to enjoy it.\n\nThe clock is always ticking. **GOD** converges at **Overwatch Score 40**, and it does not negotiate.',
    seeAlso: ['Decker', 'Matrix Attributes', 'Overwatch Score', 'Convergence', 'Mark', 'Technomancer'],
    aliases: ['the matrix', 'net', 'hacking', 'vr', 'ar', 'hot sim'],
  },
  {
    term: 'Decker',
    kind: 'class',
    short: 'The hacker: LOG + Cracking and a cyberdeck. A build concept, not a class, and utterly gear-dependent.',
    body: 'A **Decker** hacks the Matrix with a **cyberdeck** and the **Cracking** skill. It is a **build concept**, not a class — no level, no hit die, no class features.\n\nWhat makes one:\n\n· **LOG** as the primary attribute\n· **Cracking** and **Electronics** skills\n· A **cyberdeck** — expensive, confiscatable, and the source of their **Matrix attributes**\n· **Datajack** or **direct neural interface** cyberware to jack in\n\nThe Decker\'s problems are structural and worth understanding:\n\n· **Total gear dependency.** No deck, no Decker. Losing the deck is losing the character\'s entire function, and decks are legally incriminating.\n· **The Overwatch clock.** Every illegal action raises the **Overwatch Score**, and at **40** GOD converges. The Decker is always racing.\n· **The body problem.** In **VR** their body is unconscious on the floor while the team is in a firefight. In **AR** they are slower at the only job they have.\n· **Biofeedback.** Hot-sim VR means **Black IC** and hostile deckers can damage them directly, and **dumpshock** hurts if the connection is cut.\n\nThe **Technomancer** is the Decker\'s counterpart with none of the gear problems and a completely different set of them.',
    seeAlso: ['Matrix', 'Matrix Attributes', 'Overwatch Score', 'Convergence', 'Technomancer', 'LOG'],
    aliases: ['deckers', 'hacker', 'cyberdeck', 'runner'],
  },
  {
    term: 'Matrix Attributes',
    kind: 'term',
    short: 'Attack, Sleaze, Data Processing, Firewall — your deck\'s four ratings, reassignable between them.',
    body: 'Every persona in the Matrix has four attributes, commonly called **ASDF**:\n\n· **Attack** — offensive Matrix actions; damaging programs, other personas, and IC\n· **Sleaze** — going unnoticed; the stat behind quiet, illegal work\n· **Data Processing** — speed and throughput; the legal work, and Matrix initiative\n· **Firewall** — defending yourself against attacks and IC\n\nThey come from your **cyberdeck** (or, for a **technomancer**, from their **living persona** and **RES**). A deck has a set of ratings and you **assign** them to the four slots — and you can **reconfigure** them, which is the Decker\'s core tactical decision.\n\nThat reassignment is the whole game. A Decker sneaking in wants **Sleaze** high; the moment they are spotted they want **Firewall** and **Attack** high, and they have to spend an action switching. Being caught in the wrong configuration is how deckers die.\n\nThe attributes pair with skills in tests: a hacking test is typically **LOG + Cracking**, with the relevant Matrix attribute setting limits and feeding the opposition\'s side.\n\nBetter decks have higher ratings across the board — and cost the sort of **nuyen** that a runner team has to do a job to afford, which is the treadmill the Decker lives on.',
    seeAlso: ['Matrix', 'Decker', 'Technomancer', 'Overwatch Score', 'LOG'],
    aliases: ['asdf', 'attack sleaze data firewall', 'deck attributes', 'firewall', 'sleaze'],
  },
  {
    term: 'Overwatch Score',
    kind: 'mechanic',
    short: 'A counter that rises with every illegal Matrix action and with time. At 40, GOD converges on you.',
    body: '**Overwatch Score (OS)** is the Matrix\'s countdown, and it is the reason Matrix runs are tense rather than leisurely.\n\nIt goes up:\n\n· Every time you take an **illegal Matrix action** — by the number of hits your **opposition** got against you\n· **Automatically over time** — roughly **2d6 every 15 minutes** you remain connected\n· Faster when things go wrong — a **critical glitch** can spike it\n\nAt **Overwatch Score 40**, **convergence** happens. **GOD** — the **Grid Overwatch Division** — finds you, and that is not a fight you win.\n\nThe key properties:\n\n· **You do not know your exact OS.** The GM tracks it. You can spend an action on a test to check it, which costs you time — and time raises it further. Deckers live in genuine uncertainty about how much rope they have left.\n· **It follows you across the Matrix.** Logging off and back on does not reset it cleanly; you need to properly **reboot**, which takes time and drops all your marks and connections.\n· **The passive tick means loitering is fatal.** You cannot sit in a host and think about it.\n\nThis is why a Matrix run has the shape it does: get in, do the thing, get out, before the number you cannot see reaches forty.',
    seeAlso: ['Convergence', 'Matrix', 'Decker', 'Mark', 'Critical Glitch'],
    aliases: ['os', 'overwatch', 'overwatch score', 'god'],
  },
  {
    term: 'Convergence',
    kind: 'mechanic',
    short: 'What happens at Overwatch Score 40: GOD finds you, bricks your deck, and dispatches people to your location.',
    body: '**Convergence** triggers the moment your **Overwatch Score reaches 40**. The **Grid Overwatch Division** — GOD, the joint corporate Matrix policing body — has located you.\n\nWhat happens:\n\n· GOD **launches an attack on your persona** — your deck takes serious **Matrix damage** and is likely **bricked**\n· You take **biofeedback damage** if you are in **VR**, and **dumpshock** when you are forcibly disconnected\n· Your **physical location is traced** — and then real people with real guns are dispatched to it\n· Your **marks** and connections are gone\n\nThe damage is survivable. The trace is what ends runs. A converged Decker has told the corporation exactly where the team is sitting.\n\n**Avoiding it** is the entire discipline of Matrix play:\n\n· **Get in and out fast** — the passive **2d6 per 15 minutes** means loitering alone will converge you\n· **Reboot** to reset OS when you can afford the downtime and the lost marks\n· Minimise **illegal actions**; use legal ones where possible\n· Watch for **critical glitches**, which spike it\n\nGOD is not an enemy you fight. It is a clock. The only counter is being finished before it strikes forty.',
    seeAlso: ['Overwatch Score', 'Matrix', 'Decker', 'Matrix Attributes'],
    aliases: ['god', 'converge', 'grid overwatch', 'dumpshock', 'bricked'],
  },
  {
    term: 'Mark',
    kind: 'term',
    short: 'An access token you place on a device or persona; more marks mean more control. You can hold up to 3.',
    body: 'A **mark** is a piece of access you have planted on a Matrix target — a device, a file, a host, a persona. You need marks to do things to a target, and **more marks mean more control**.\n\nYou can hold up to **3 marks** on any one target.\n\nGetting them:\n\n· **Hack on the Fly** — the quiet way; **LOG + Cracking** with **Sleaze** opposed by their **Willpower + Firewall** (or Intuition + Firewall). Slower, subtler, and it can place marks without anyone noticing.\n· **Brute Force** — the loud way; **LOG + Cracking** with **Attack** opposed by their defence. Faster, and it **alerts** the target.\n\nBoth raise your **Overwatch Score** by the opposition\'s hits, so every mark you take costs you time on the clock.\n\nWhat marks buy you: with the right number of marks you can **control** a device — open the door, turn the camera, unlock the maglock, **brick the guard\'s smartgun**, shut off the alarm. This is the Decker\'s actual contribution to a run: not fighting, but **owning the building**.\n\nMarks are lost when you **reboot**, when the target reboots, and on **convergence** — which is part of why convergence is so ruinous mid-run.',
    seeAlso: ['Matrix', 'Decker', 'Overwatch Score', 'Matrix Attributes', 'Convergence'],
    aliases: ['marks', 'mark a device', 'hack on the fly', 'brute force'],
  },
  {
    term: 'Technomancer',
    kind: 'class',
    short: 'Emerged, not Awakened: they run the Matrix natively with RES, no deck required. Fading is their Drain.',
    body: 'A **technomancer** interacts with the Matrix as a **natural phenomenon**, using the **RES (Resonance)** attribute instead of hardware. A build concept, not a class.\n\nWhat that means:\n\n· **No cyberdeck.** Their **living persona** provides the **Matrix attributes**, derived from **RES** and mental attributes.\n· **Complex forms** instead of programs — the technomancer\'s equivalent of spells, costing **Fading**\n· **RES + Tasking** to **compile, register and command sprites**\n· **Fading** resisted with **WIL + RES**\n\nThe advantages are real: **nothing to confiscate**, nothing to brick, nothing incriminating in your bag, and no upgrade treadmill. They just **are** the deck.\n\nThe costs are also real:\n\n· **Essence loss reduces RES** exactly as it reduces MAG — a technomancer cannot chrome up\n· **Fading** is Stun damage and can go Physical if pushed, so they hurt themselves running\n· They are **hunted**. Corporations regard technomancers as an existential anomaly and study them in ways that do not end well.\n· They are still bound by the **Overwatch Score** clock like everyone else\n\nTechnomancers are the rarest thing at the table and the most alarming thing in the setting: a person who cannot be disarmed of the Matrix.',
    seeAlso: ['RES', 'Fading', 'Sprite', 'Matrix', 'Matrix Attributes', 'ESS'],
    aliases: ['technomancers', 'techno', 'emerged', 'living persona', 'complex form'],
  },
  {
    term: 'Fading',
    kind: 'mechanic',
    short: 'The technomancer\'s Drain: resist with WIL + RES, take the rest as Stun — or Physical if it exceeds RES.',
    body: '**Fading** is to technomancers what **Drain** is to magicians, and it works the same way.\n\nEvery **complex form** you thread, and every **sprite** you compile, has a **Fading Value**. You roll a **Fading resistance test** of **WIL + RES**, each hit reduces it, and you take what is left.\n\n· Unresisted Fading is **Stun damage**\n· **If the Fading Value exceeds your RESONANCE rating, it is PHYSICAL damage instead**\n\nThe consequences chain exactly as they do for a mage. Fading fills your **Stun track**; a full Stun track means **unconscious**; Stun overflow **converts to Physical**. A technomancer who pushes too hard in the middle of a run collapses, in a body that is already lying on the floor because they are in **VR**.\n\nAnd there is no per-day limit here either. A technomancer can thread as many complex forms as they can physically survive — the limiter is their **Willpower**, their **Resonance**, and their Stun track.\n\nThis is the symmetry the designers built: **magic and Resonance both cost you your body**, both refuse to be augmented, and both make the person who has them the most fragile member of a team that keeps getting shot at.',
    seeAlso: ['Technomancer', 'RES', 'Drain', 'Stun Damage', 'Sprite', 'WIL'],
    aliases: ['fading value', 'fade', 'complex form'],
  },
  {
    term: 'Sprite',
    kind: 'term',
    short: 'A Matrix entity compiled by a technomancer — the Resonance answer to a spirit, and it owes you tasks.',
    body: 'A **sprite** is an entity of the Resonance, **compiled** by a technomancer with **RES + Tasking**. It is the Matrix counterpart of a **spirit**, and it works almost identically.\n\n· **Compiling** is an Opposed Test against the sprite\'s **Level** — your **net hits** are the **tasks** it owes you\n· You take **Fading** for the attempt, win or lose\n· Compiling a sprite of **Level higher than your RES** risks **Physical** Fading\n· **Registering** a sprite — a longer process with its own Fading — gives you one you can call repeatedly\n\nThe types map to Matrix jobs: **Courier** sprites carry data, **Crack** sprites break protection, **Data** sprites search and analyse, **Fault** sprites attack, **Machine** sprites handle devices — each with its own powers and its own dice pools derived from its **Level**.\n\nWhat they are for: a sprite is **another actor in the Matrix**. A technomancer with three registered sprites is not one hacker — they are a team, and that parallelism is the technomancer\'s real answer to the Decker\'s better gear.\n\nAnd like spirits, they are **not obedient**. They are Resonance entities with their own nature, they perform their tasks and leave, and a **critically glitched** compiling leaves you with a free, hostile sprite that knows your persona.',
    seeAlso: ['Technomancer', 'RES', 'Fading', 'Matrix', 'Spirit', 'Critical Glitch'],
    aliases: ['sprites', 'compile', 'compiling', 'registering', 'tasks'],
  },

  // ── Rigging ──────────────────────────────────────────────────────────────────────────────
  {
    term: 'Rigger',
    kind: 'class',
    short: 'Drives and fights through drones and vehicles, jumping in via a control rig. A build concept, not a class.',
    body: 'A **Rigger** operates **vehicles and drones**, either remotely or by **jumping in** — projecting their consciousness into the machine so it becomes their body.\n\n· **REA + Piloting** to drive or fly normally\n· A **control rig** (cyberware, so **Essence**) is what lets you **jump in**\n· **Jumped in**, you use the **vehicle\'s** handling and sensors with your own skills, and you get bonuses from the rig\n· You can control a **whole team of drones** at once, switching between them\n\nWhat the Rigger brings to a run:\n\n· **Drones** — surveillance, overwatch, a rotor drone with a gun, an autonomous perimeter\n· **The getaway** — someone has to drive, and doing it jumped-in is meaningfully better than doing it by hand\n· **Expendable bodies** — a drone that gets shot is a bill, not a funeral\n\nThe risks: jumped-in Riggers take **biofeedback** when the drone is damaged, exactly like a hot-sim Decker. Their body is also **elsewhere and unattended** while they are jumped in. And drones can be **hacked** — a Decker on the other side who takes marks on your drone now owns your gun.\n\nDrones run on **Pilot** ratings and **Autosofts** when nobody is jumped in, which makes them competent but stupid.',
    seeAlso: ['Drone', 'REA', 'ESS', 'Matrix', 'Mark'],
    aliases: ['riggers', 'rigging', 'control rig', 'jumped in', 'vehicles'],
  },
  {
    term: 'Drone',
    kind: 'term',
    short: 'A remote machine that runs on Pilot + Autosofts alone, or becomes the Rigger\'s body when they jump in.',
    body: 'A **drone** is a vehicle without a driver in it. They range from a **fly-sized surveillance unit** to a **rotor drone with a machine gun** to a **security walker**.\n\nThree ways to run one:\n\n· **Autonomous** — the drone acts on its own **Pilot** rating plus **Autosofts** (skill software: Targeting, Clearsight, Maneuvering). Competent, tireless, and genuinely stupid.\n· **Remote control** — the Rigger issues commands; the drone still uses Pilot for the fiddly parts.\n· **Jumped in** — the Rigger **is** the drone. Their skills, the drone\'s body, plus **control rig** bonuses. This is dramatically better and dramatically riskier.\n\nDrones have their own **condition monitor** and take **Matrix damage** as well as physical — a Decker can **brick your drone** without ever shooting it.\n\nWhy they matter tactically: a drone gives the team **eyes everywhere**, **a gun that nobody has to stand behind**, and a **casualty that costs nuyen instead of a character**. A rotor drone hovering over a meet is the difference between an ambush and a firefight you win.\n\nAnd the vulnerability that defines them: they are **wireless devices**, so they are **Matrix targets**. Every drone on the field is a thing the other side\'s Decker is looking at.',
    seeAlso: ['Rigger', 'Matrix', 'Mark', 'Condition Monitor'],
    aliases: ['drones', 'autosoft', 'pilot', 'rotor drone'],
  },

  // ── Character build and the world ────────────────────────────────────────────────────────
  {
    term: 'Karma',
    kind: 'mechanic',
    short: 'The only advancement: spend it on skills, attributes, qualities and spells. Costs scale with the new rating.',
    body: '**Karma** is Shadowrun\'s experience currency, and it works **continuously** — there is **no level, no level-up, no hit die, no class feature you unlock**.\n\nThe GM awards Karma after a run for the work, the risks, and the roleplay. You then spend it on whatever you like:\n\n· Raising a **skill** by one point\n· Raising an **attribute** by one point\n· Buying a **specialization** or **expertise**\n· Learning a **spell** or a **complex form**\n· Buying off a **negative quality**, or buying a **positive quality**\n· Raising **MAG** or **RES** — but never above the ceiling your **Essence** permits\n· **Binding** a spirit or **registering** a sprite\n\nThe universal principle: **the cost scales with the new rating you are buying**. Going from 2 to 3 is cheap; going from 5 to 6 is expensive. So a character\'s first improvements come fast and their last ones take a campaign — which naturally plateaus everyone around the same competence band.\n\nThat is also why **breadth beats depth** in Shadowrun. A runner improves faster by buying a second useful skill at 3 than by pushing their best skill from 5 to 6.\n\nKarma is also used at **character creation** in some build methods, and to buy off the flaws you took to afford your chrome.',
    seeAlso: ['Skills', 'Nuyen', 'MAG', 'RES', 'ESS', 'Priority Character Creation'],
    aliases: ['xp', 'experience', 'karma points', 'advancement', 'level up'],
  },
  {
    term: 'Nuyen',
    kind: 'term',
    short: 'The money. It buys gear, cyberware and lifestyle — and it advances your character as surely as Karma does.',
    body: '**Nuyen (¥)** is the currency of the Sixth World, and in Shadowrun money is a **character advancement mechanic**, not just a resource.\n\nWhat it buys:\n\n· **Gear** — guns, armor, decks, drones, vehicles\n· **Cyberware and bioware** — the thing that makes you actually dangerous\n· **Lifestyle** — your monthly rent, which you must pay\n· **Fake SINs** and licences — without which you legally do not exist\n· **Medical care**, **DocWagon** contracts, and **repairs**\n\nThe crucial structural point: **nuyen improves you faster than Karma does**. A runner who buys **Wired Reflexes** has gained more combat capability in one purchase than months of Karma spending would provide. This is why runners take runs, and why the corps can always find someone.\n\nAnd it is why the **Essence** economy is a trap. The fastest route to power costs the one thing you cannot buy back — which is fine for the street samurai and impossible for the mage, who has to advance the slow way, on Karma, while their teammate simply writes a cheque.\n\nGear also has an **Availability** rating and legality. Money alone is not enough; you need a **Fixer** and a **Negotiation** test to get the good things.',
    seeAlso: ['Karma', 'Lifestyle', 'ESS', 'Priority Character Creation'],
    aliases: ['money', 'nuyen', 'cash', 'eddies', 'gear'],
  },
  {
    term: 'Lifestyle',
    kind: 'term',
    short: 'A monthly cost for how you live, from Street (free) to Luxury. You pay it every month or you drop a tier.',
    body: '**Lifestyle** is a recurring monthly bill representing where and how you live — and it is the thing that forces runners to keep taking runs.\n\nThe ladder, from bottom to top:\n\n· **Street** — no cost, no home. Doorways, squats, your car. No safe place to sleep and no address.\n· **Squatter** — a hole with a roof. Barely.\n· **Low** — a coffin motel or a bad flat. Functional.\n· **Middle** — an actual apartment in an actual building. The comfortable default.\n· **High** — real security, real services, a good neighbourhood.\n· **Luxury** — corporate-executive living, and the price tag to match.\n\nYou pay **every month**. Miss it and you drop a tier, with everything that implies.\n\nWhat lifestyle buys mechanically:\n\n· A **place to heal** — recovery intervals and downtime need somewhere to be\n· **Security** — a low lifestyle means people can find you and get in\n· **Access** — a High lifestyle puts you in rooms a Squatter cannot enter\n· A place to keep your **gear** where it will still be there\n\nThe design intent is blunt: your lifestyle is a **clock counting down to your next run**. Live well and you must work more. Live in a coffin and you keep your nuyen — and your fence knows exactly where you sleep.',
    seeAlso: ['Nuyen', 'Healing', 'Priority Character Creation'],
    aliases: ['lifestyles', 'rent', 'squatter', 'middle lifestyle', 'sin'],
  },
  {
    term: 'Metatype',
    kind: 'term',
    short: 'Human, Elf, Dwarf, Ork or Troll — each shifts your attribute maxima and grants a couple of traits.',
    body: 'Metahumanity comes in **five** playable varieties, and the choice mostly moves your **attribute maximums** rather than granting powers.\n\n· **Human** — no physical edge, but **Edge maximum 7** where everyone else caps at 6. That single point is the whole metatype, and it is genuinely good: Humans start every session with the fullest Edge pool in the game.\n· **Elf** — higher **Agility** and notably higher **Charisma** maxima, plus **low-light vision**. The archetypal Face and the archetypal shooter, and the reason "Elf" and "smug" are synonyms in the Sixth World.\n· **Dwarf** — higher **Body**, **Strength** and **Willpower** maxima, **thermographic vision**, and **+2 dice to resist toxins and pathogens**. Slower movement. Tough, stubborn, and hard to poison.\n· **Ork** — substantially higher **Body** and **Strength**, lower **Logic** and **Charisma** maxima, **low-light vision**. Durable and socially penalised, which is exactly the setting\'s point.\n· **Troll** — the extreme: **Body** and **Strength** maxima up around **10**, **+1 Reach** in melee, **natural dermal armor**, **thermographic vision**, and low Logic/Charisma maxima. Also: you do not fit through doors, you pay more for everything custom, and every cop in the city notices you.\n\nMetatype is bought through **priority character creation** — being a Troll costs you a priority slot that a Human gets for free, which is how the game prices that Body 10.',
    seeAlso: ['Priority Character Creation', 'EDG', 'BOD', 'STR', 'CHA'],
    aliases: ['metatypes', 'race', 'species', 'troll', 'elf', 'dwarf', 'ork', 'human'],
  },
  {
    term: 'Priority Character Creation',
    kind: 'mechanic',
    short: 'Assign A–E, each exactly once, across Metatype, Attributes, Magic/Resonance, Skills and Resources.',
    body: 'The classic Shadowrun build method. There are **five categories** and **five priorities (A through E)**, and you assign **each priority exactly once**:\n\n· **Metatype** — a higher priority buys the bigger metatypes and more **special attribute points** (Edge, Magic, Resonance)\n· **Attributes** — the pool of points for BOD/AGI/REA/STR/WIL/LOG/INT/CHA\n· **Magic or Resonance** — a **single shared column**. You take **MAG** or **RES** or **neither** — never both.\n· **Skills** — the pool of skill points\n· **Resources** — starting **nuyen** for gear, chrome and lifestyle\n\nThat structure is the character creation *and* the setting, in one table. It tells you the four things you cannot have at once, and forces you to give one up:\n\n· A **magician** must spend a high priority on Magic, so they cannot also afford Resources — the mage is **poor**\n· A **street samurai** needs **Resources A** for the chrome, so they cannot take Magic at all\n· A **Decker** needs Resources for the deck **and** Skills for Cracking — a permanently squeezed build\n· A **Troll** spends a high priority on Metatype and gives up something else for it\n\nThe alternatives are a **point-buy** and a **Karma-build** method, but Priority is the one that most clearly enforces the game\'s central law: **you cannot be augmented and Awakened**.',
    seeAlso: ['Metatype', 'MAG', 'RES', 'Nuyen', 'Karma', 'ESS'],
    aliases: ['priority table', 'character creation', 'chargen', 'build', 'priorities'],
  },
];
