// GENERATED by scripts/prepare-andrew-photos.mjs — do not edit by hand.
// Re-run `node scripts/prepare-andrew-photos.mjs` after changing the source photos.

export interface AndrewPhoto {
  id: string;
  alt: string;
  role: string;
  /** CSS `object-position` that keeps the subject in frame at ANY crop ratio.
   *  Travels with the photo so no call site can forget it — the bug that shipped
   *  service cards with people's heads cropped off. */
  focal: string;
  width: number;
  height: number;
  orientation: 'landscape' | 'portrait' | 'square';
}

export const ANDREW_PHOTOS: readonly AndrewPhoto[] = [
  {
    "id": "portrait-formal",
    "alt": "Black-and-white portrait of Andrew Ash in a top hat and bow tie",
    "focal": "50% 34%",
    "role": "Primary hero portrait. Dramatic, monochrome, already square.",
    "width": 640,
    "height": 640,
    "orientation": "square"
  },
  {
    "id": "recital-white-tie",
    "alt": "Andrew Ash performing in white tie and tails at a chapel recital",
    "focal": "50% 18%",
    "role": "Classical credibility shot — the one that says \"trained singer\".",
    "width": 1342,
    "height": 2048,
    "orientation": "portrait"
  },
  {
    "id": "recital-expressive",
    "alt": "Andrew Ash mid-performance, hands raised, at a recital",
    "focal": "44% 30%",
    "role": "Motion + expression. Used wide, behind text.",
    "width": 1600,
    "height": 1066,
    "orientation": "landscape"
  },
  {
    "id": "ensemble-choir",
    "alt": "Andrew Ash singing in a vocal ensemble on stage",
    "focal": "14% 38%",
    "role": "Ensemble work. Andrew is far left, hence the west gravity.",
    "width": 1439,
    "height": 1080,
    "orientation": "landscape"
  },
  {
    "id": "stage-duet",
    "alt": "Andrew Ash performing a duet in a stage musical",
    "focal": "48% 24%",
    "role": "Musical theatre lead, in character, mid-scene.",
    "width": 960,
    "height": 640,
    "orientation": "landscape"
  },
  {
    "id": "stage-ensemble-scene",
    "alt": "Andrew Ash on stage with the full company of a musical",
    "focal": "76% 32%",
    "role": "Production scale. Andrew is stage-right.",
    "width": 960,
    "height": 640,
    "orientation": "landscape"
  },
  {
    "id": "stage-period-scene",
    "alt": "Andrew Ash in period costume performing a comic scene",
    "focal": "34% 24%",
    "role": "Comic timing / character range.",
    "width": 684,
    "height": 493,
    "orientation": "landscape"
  },
  {
    "id": "stage-costume",
    "alt": "Andrew Ash in full period costume after a performance, with his parents",
    "focal": "50% 26%",
    "role": "About page only — costume and family, needs a caption. Never a service card.",
    "width": 1229,
    "height": 1638,
    "orientation": "portrait"
  },
  {
    "id": "graduation-presser-hall",
    "alt": "Andrew Ash in cap and gown outside Presser Hall at UMHB",
    "focal": "38% 34%",
    "role": "Education. Presser Hall is the UMHB music building — on the nose.",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape"
  },
  {
    "id": "graduation-umhb",
    "alt": "Andrew Ash in cap and gown beside the UMHB letters on campus",
    "focal": "48% 46%",
    "role": "Wide establishing shot for the About timeline.",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape"
  },
  {
    "id": "event-tuxedo",
    "alt": "Andrew Ash in a tuxedo at a music event",
    "focal": "32% 22%",
    "role": "Formal/professional. Also reads as \"after the show\".",
    "width": 720,
    "height": 960,
    "orientation": "portrait"
  },
  {
    "id": "character-fishbowl",
    "alt": "Andrew Ash in a green-and-purple caped costume with a glass helmet",
    "focal": "50% 12%",
    "role": "Character work — the \"I will commit to a bit\" evidence.",
    "width": 1600,
    "height": 1600,
    "orientation": "square"
  },
  {
    "id": "character-aviator",
    "alt": "Andrew Ash in an aviator costume with goggles and a leather jacket",
    "focal": "46% 10%",
    "role": "Second character-work photo, different genre.",
    "width": 272,
    "height": 517,
    "orientation": "portrait"
  },
  {
    "id": "archive-young",
    "alt": "Andrew Ash as a child, smiling at an outdoor gathering",
    "focal": "48% 24%",
    "role": "The \"it started early\" beat in the About story. Deliberately small.",
    "width": 639,
    "height": 960,
    "orientation": "portrait"
  },
  {
    "id": "personal-formal",
    "alt": "Andrew Ash dressed formally at a family celebration",
    "focal": "50% 12%",
    "role": "Held in the library, unused on the public pages by default.",
    "width": 1365,
    "height": 2048,
    "orientation": "portrait"
  },
  {
    "id": "personal-candid",
    "alt": "Candid photo of Andrew Ash",
    "focal": "50% 34%",
    "role": "Held in the library, unused on the public pages by default.",
    "width": 1538,
    "height": 2048,
    "orientation": "portrait"
  }
] as const;

/** Public URL for a photo. `size` picks the 800px derivative for cards. */
export function photoUrl(id: string, size: 'full' | 'card' = 'full'): string {
  return `/andrew/photos/${id}${size === 'card' ? '-800' : ''}.jpg`;
}

export function photoUrlWebp(id: string, size: 'full' | 'card' = 'full'): string {
  return `/andrew/photos/${id}${size === 'card' ? '-800' : ''}.webp`;
}

export function photoById(id: string): AndrewPhoto | undefined {
  return ANDREW_PHOTOS.find((p) => p.id === id);
}
