// lib/cad/labels/annotation-types.ts — Annotation type definitions
import type { Point2D } from '../types';

export type AnnotationType = 'BEARING_DISTANCE' | 'CURVE_DATA' | 'MONUMENT_LABEL' | 'AREA_LABEL' | 'TEXT' | 'LEADER';

export interface AnnotationBase {
  id: string;
  type: AnnotationType;
  layerId: string;
  visible: boolean;
  locked: boolean;
  linkedFeatureId: string | null;
  linkedSegmentIndex: number | null;
  isManuallyPlaced: boolean;
  isAutoGenerated: boolean;
  priority: number;
}

export interface BearingDistanceDimension extends AnnotationBase {
  type: 'BEARING_DISTANCE';
  priority: 1;
  startPoint: Point2D;
  endPoint: Point2D;
  bearing: number;
  distance: number;
  bearingText: string;
  distanceText: string;
  textPosition: 'ABOVE' | 'BELOW' | 'CENTERED';
  textOffset: number;
  textRotation: 'ALONG_LINE' | 'HORIZONTAL' | 'UPRIGHT';
  bearingAbove: boolean;
  font: string;
  fontSize: number;
  color: string;
  extensionLines: boolean;
  extensionLineLength: number;
}

export interface CurveDataAnnotation extends AnnotationBase {
  type: 'CURVE_DATA';
  priority: 3;
  showRadius: boolean;
  showArcLength: boolean;
  showChordBearing: boolean;
  showChordDistance: boolean;
  showDelta: boolean;
  showTangent: boolean;
  textLines: string[];
  position: 'OUTSIDE_ARC' | 'INSIDE_ARC' | 'CUSTOM';
  customPosition: Point2D | null;
  followCurve: boolean;
  leaderToArc: boolean;
  font: string;
  fontSize: number;
  color: string;
  lineSpacing: number;
}

export interface MonumentLabel extends AnnotationBase {
  type: 'MONUMENT_LABEL';
  priority: 2;
  pointId: string;
  position: Point2D;
  text: string;
  abbreviatedText: string;
  offsetAngle: number;
  offsetDistance: number;
  hasLeader: boolean;
  font: string;
  fontSize: number;
  color: string;
}

export interface AreaAnnotation extends AnnotationBase {
  type: 'AREA_LABEL';
  priority: 4;
  linkedFeatureId: string;
  areaSqFt: number;
  areaAcres: number;
  format: 'SQFT' | 'ACRES' | 'BOTH' | 'LOT_NUMBER';
  text: string;
  lotNumber: string | null;
  blockNumber: string | null;
  position: Point2D;
  font: string;
  fontSize: number;
  color: string;
}

export interface TextAnnotation extends AnnotationBase {
  type: 'TEXT';
  priority: 6;
  position: Point2D;
  text: string;
  multiline: boolean;
  font: string;
  fontSize: number;
  bold: boolean;
  italic: boolean;
  underline: boolean;
  color: string;
  rotation: number;
  alignment: 'LEFT' | 'CENTER' | 'RIGHT';
  verticalAlignment: 'TOP' | 'MIDDLE' | 'BOTTOM';
  backgroundColor: string | null;
  borderVisible: boolean;
  borderColor: string;
  padding: number;
}

export interface LeaderAnnotation extends AnnotationBase {
  type: 'LEADER';
  priority: 7;
  arrowPoint: Point2D;
  textPosition: Point2D;
  vertices: Point2D[];
  text: string;
  arrowStyle: 'CLOSED' | 'OPEN' | 'DOT' | 'TICK' | 'NONE';
  lineWeight: number;
  font: string;
  fontSize: number;
  color: string;
}

export type Annotation = BearingDistanceDimension | CurveDataAnnotation | MonumentLabel | AreaAnnotation | TextAnnotation | LeaderAnnotation;
