// lib/cad/labels/area-label.ts — Area annotation creation
import type { Point2D } from '../types';
import { generateId } from '../types';
import type { AreaAnnotation } from './annotation-types';
import { computeAreaFromPoints2D } from '../geometry/area';

export interface AreaLabelConfig {
  format: 'SQFT' | 'ACRES' | 'BOTH' | 'LOT_NUMBER';
  font: string;
  fontSize: number;
  color: string;
}

export const DEFAULT_AREA_LABEL_CONFIG: AreaLabelConfig = {
  format: 'BOTH',
  font: 'Arial',
  fontSize: 9,
  color: '#000000',
};

/** Compute the centroid of a polygon. */
export function computeCentroid(vertices: Point2D[]): Point2D {
  if (vertices.length === 0) return { x: 0, y: 0 };
  const cx = vertices.reduce((s, v) => s + v.x, 0) / vertices.length;
  const cy = vertices.reduce((s, v) => s + v.y, 0) / vertices.length;
  return { x: cx, y: cy };
}

/** Build area label text. */
export function buildAreaText(
  sqft: number,
  format: AreaLabelConfig['format'],
  lotNumber?: string | null,
  blockNumber?: string | null,
): string {
  const acres = sqft / 43560;
  switch (format) {
    case 'SQFT':
      return `${sqft.toLocaleString('en-US', { maximumFractionDigits: 1 })} Sq. Ft.`;
    case 'ACRES':
      return `${acres.toFixed(4)} Acres`;
    case 'BOTH':
      return `${sqft.toLocaleString('en-US', { maximumFractionDigits: 1 })} Sq. Ft.\n${acres.toFixed(4)} Acres`;
    case 'LOT_NUMBER': {
      const lot = lotNumber ? `LOT ${lotNumber}` : '';
      const blk = blockNumber ? `, BLK ${blockNumber}` : '';
      return `${lot}${blk}\n${acres.toFixed(4)} Acres`;
    }
    default:
      return `${sqft.toFixed(1)} Sq. Ft.`;
  }
}

export function createAreaAnnotation(
  linkedFeatureId: string,
  vertices: Point2D[],
  config: AreaLabelConfig,
  lotNumber?: string | null,
  blockNumber?: string | null,
): AreaAnnotation {
  const area = computeAreaFromPoints2D(vertices);
  const centroid = computeCentroid(vertices);
  const text = buildAreaText(area.squareFeet, config.format, lotNumber, blockNumber);

  return {
    id: generateId(),
    type: 'AREA_LABEL',
    layerId: 'ANNOTATION',
    visible: true,
    locked: false,
    linkedFeatureId,
    linkedSegmentIndex: null,
    isManuallyPlaced: false,
    isAutoGenerated: true,
    priority: 4,
    areaSqFt: area.squareFeet,
    areaAcres: area.acres,
    format: config.format,
    text,
    lotNumber: lotNumber ?? null,
    blockNumber: blockNumber ?? null,
    position: centroid,
    font: config.font,
    fontSize: config.fontSize,
    color: config.color,
  };
}
