// lib/cad/labels/area-label.ts — Area annotation creation
import type { Feature, Point2D } from '../types';
import { generateId } from '../types';
import type { AreaAnnotation } from './annotation-types';
import { computeAreaFromPoints2D, computeFeatureArea } from '../geometry/area';
import { ANNOTATION_LAYER_ID } from '../styles/default-layers';

export interface AreaLabelConfig {
  format: 'SQFT' | 'ACRES' | 'BOTH' | 'LOT_NUMBER';
  font: string;
  fontSize: number;
  color: string;
}

export const DEFAULT_AREA_LABEL_CONFIG: AreaLabelConfig = {
  format: 'BOTH',
  font: 'Arial',
  fontSize: 9,
  color: '#000000',
};

/** Compute the centroid of a polygon. */
export function computeCentroid(vertices: Point2D[]): Point2D {
  if (vertices.length === 0) return { x: 0, y: 0 };
  const cx = vertices.reduce((s, v) => s + v.x, 0) / vertices.length;
  const cy = vertices.reduce((s, v) => s + v.y, 0) / vertices.length;
  return { x: cx, y: cy };
}

/** Build area label text. */
export function buildAreaText(
  sqft: number,
  format: AreaLabelConfig['format'],
  lotNumber?: string | null,
  blockNumber?: string | null,
): string {
  const acres = sqft / 43560;
  switch (format) {
    case 'SQFT':
      return `${sqft.toLocaleString('en-US', { maximumFractionDigits: 1 })} Sq. Ft.`;
    case 'ACRES':
      return `${acres.toFixed(4)} Acres`;
    case 'BOTH':
      return `${sqft.toLocaleString('en-US', { maximumFractionDigits: 1 })} Sq. Ft.\n${acres.toFixed(4)} Acres`;
    case 'LOT_NUMBER': {
      const lot = lotNumber ? `LOT ${lotNumber}` : '';
      const blk = blockNumber ? `, BLK ${blockNumber}` : '';
      return `${lot}${blk}\n${acres.toFixed(4)} Acres`;
    }
    default:
      return `${sqft.toFixed(1)} Sq. Ft.`;
  }
}

export function createAreaAnnotation(
  linkedFeatureId: string,
  vertices: Point2D[],
  config: AreaLabelConfig,
  lotNumber?: string | null,
  blockNumber?: string | null,
): AreaAnnotation {
  const area = computeAreaFromPoints2D(vertices);
  const centroid = computeCentroid(vertices);
  const text = buildAreaText(area.squareFeet, config.format, lotNumber, blockNumber);

  return {
    id: generateId(),
    type: 'AREA_LABEL',
    layerId: ANNOTATION_LAYER_ID,
    visible: true,
    locked: false,
    linkedFeatureId,
    linkedSegmentIndex: null,
    isManuallyPlaced: false,
    isAutoGenerated: true,
    priority: 4,
    areaSqFt: area.squareFeet,
    areaAcres: area.acres,
    format: config.format,
    text,
    lotNumber: lotNumber ?? null,
    blockNumber: blockNumber ?? null,
    position: centroid,
    font: config.font,
    fontSize: config.fontSize,
    color: config.color,
    // Slice 232 — opt-in label background defaults off.
    backgroundColor: null,
    borderVisible: false,
    borderColor: '#000000',
    padding: 2,
  };
}

/** Slice 229 — pick the natural centroid for any closed geometry
 *  (CIRCLE / ELLIPSE center; POLYGON / closed POLYLINE vertex
 *  average). Returns {0, 0} for open geometries that have no
 *  natural centroid — callers should guard via
 *  `computeFeatureArea(feature).squareFeet > 0`. */
export function pickFeatureCentroid(feature: Feature): Point2D {
  const g = feature?.geometry;
  if (!g) return { x: 0, y: 0 };
  switch (g.type) {
    case 'CIRCLE':
      return g.circle ? { ...g.circle.center } : { x: 0, y: 0 };
    case 'ELLIPSE':
      return g.ellipse ? { ...g.ellipse.center } : { x: 0, y: 0 };
    case 'POLYGON':
    case 'POLYLINE':
    case 'MIXED_GEOMETRY':
      return computeCentroid(g.vertices ?? []);
    default:
      return { x: 0, y: 0 };
  }
}

/** Slice 229 — feature-aware factory that produces an
 *  AreaAnnotation for ANY closed shape: POLYGON / CIRCLE / ELLIPSE
 *  / closed POLYLINE / closed MIXED_GEOMETRY. Drives the
 *  "📐 Place area label" action in the PropertyPanel + the
 *  on-canvas render path. Returns null when the feature has no
 *  computable area (open shapes, degenerate radii, etc). */
export function createAreaLabelForFeature(
  feature: Feature,
  config: AreaLabelConfig = DEFAULT_AREA_LABEL_CONFIG,
  lotNumber?: string | null,
  blockNumber?: string | null,
): AreaAnnotation | null {
  const area = computeFeatureArea(feature);
  if (area.squareFeet <= 0) return null;
  const centroid = pickFeatureCentroid(feature);
  const text = buildAreaText(area.squareFeet, config.format, lotNumber, blockNumber);
  return {
    id: generateId(),
    type: 'AREA_LABEL',
    layerId: ANNOTATION_LAYER_ID,
    visible: true,
    locked: false,
    linkedFeatureId: feature.id,
    linkedSegmentIndex: null,
    // Slice 229 — the surveyor explicitly clicked the "Place area
    // label" button, so this label is `isManuallyPlaced: true` and
    // is NOT auto-regenerated by the auto-annotate pipeline.
    isManuallyPlaced: true,
    isAutoGenerated: false,
    priority: 4,
    areaSqFt: area.squareFeet,
    areaAcres: area.acres,
    format: config.format,
    text,
    lotNumber: lotNumber ?? null,
    blockNumber: blockNumber ?? null,
    position: centroid,
    font: config.font,
    fontSize: config.fontSize,
    color: config.color,
    // Slice 232 — opt-in label background defaults off.
    backgroundColor: null,
    borderVisible: false,
    borderColor: '#000000',
    padding: 2,
  };
}
