// lib/cad/labels/bearing-dim.ts — Bearing/distance dimension creation and placement
import type { Point2D } from '../types';
import { generateId } from '../types';
import type { BearingDistanceDimension } from './annotation-types';
import { inverseBearingDistance, formatBearing } from '../geometry/bearing';

export interface BearingDimConfig {
  bearingPrecision: 'SECOND' | 'TENTH_SECOND';
  distancePrecision: number;
  defaultPosition: 'ABOVE' | 'BELOW';
  defaultOffset: number;
  textRotation: 'ALONG_LINE' | 'HORIZONTAL' | 'UPRIGHT';
  bearingAbove: boolean;
  extensionLines: boolean;
  font: string;
  fontSize: number;
  color: string;
}

export const DEFAULT_BEARING_DIM_CONFIG: BearingDimConfig = {
  bearingPrecision: 'SECOND',
  distancePrecision: 2,
  defaultPosition: 'ABOVE',
  defaultOffset: 0.06,
  textRotation: 'ALONG_LINE',
  bearingAbove: true,
  extensionLines: true,
  font: 'Arial',
  fontSize: 7,
  color: '#000000',
};

export function createBearingDimension(
  startPoint: Point2D,
  endPoint: Point2D,
  config: BearingDimConfig,
  linkedFeatureId?: string,
  segmentIndex?: number,
): BearingDistanceDimension {
  const inv = inverseBearingDistance(startPoint, endPoint);
  const bearingText = formatBearing(inv.azimuth, config.bearingPrecision);
  const distanceText = `${inv.distance.toFixed(config.distancePrecision)}'`;

  return {
    id: generateId(),
    type: 'BEARING_DISTANCE',
    layerId: 'ANNOTATION',
    visible: true,
    locked: false,
    linkedFeatureId: linkedFeatureId ?? null,
    linkedSegmentIndex: segmentIndex ?? null,
    isManuallyPlaced: false,
    isAutoGenerated: true,
    priority: 1,
    startPoint,
    endPoint,
    bearing: inv.azimuth,
    distance: inv.distance,
    bearingText,
    distanceText,
    textPosition: config.defaultPosition,
    textOffset: config.defaultOffset,
    textRotation: config.textRotation,
    bearingAbove: config.bearingAbove,
    font: config.font,
    fontSize: config.fontSize,
    color: config.color,
    extensionLines: config.extensionLines,
    extensionLineLength: 0.05,
  };
}

/**
 * Compute text placement for a bearing/distance dimension.
 * Returns world-coordinate text centers and the angle that keeps text readable.
 */
export function computeBearingDimPlacement(
  dim: BearingDistanceDimension,
  drawingScale: number,
): { bearingPos: Point2D; distancePos: Point2D; rotation: number } {
  const dx = dim.endPoint.x - dim.startPoint.x;
  const dy = dim.endPoint.y - dim.startPoint.y;

  // Mid-point of the line
  const mx = (dim.startPoint.x + dim.endPoint.x) / 2;
  const my = (dim.startPoint.y + dim.endPoint.y) / 2;

  // Line angle in radians — keep text readable (not upside-down)
  let rotation = Math.atan2(dy, dx);
  if (rotation > Math.PI / 2 || rotation < -Math.PI / 2) rotation += Math.PI;

  // Perpendicular offset (convert paper inches to world units using scale)
  const perpX = -Math.sin(rotation);
  const perpY = Math.cos(rotation);
  const offsetWorld = dim.textOffset * drawingScale;

  // Bearing above line, distance below (or vice-versa based on config)
  const gapWorld = (dim.fontSize / 72) * drawingScale * 1.4; // rough line height in world units

  const topPos: Point2D = {
    x: mx + perpX * (offsetWorld + gapWorld),
    y: my + perpY * (offsetWorld + gapWorld),
  };
  const bottomPos: Point2D = {
    x: mx + perpX * offsetWorld,
    y: my + perpY * offsetWorld,
  };

  return {
    bearingPos: dim.bearingAbove ? topPos : bottomPos,
    distancePos: dim.bearingAbove ? bottomPos : topPos,
    rotation,
  };
}
