// lib/cad/labels/curve-label.ts — Curve data annotation creation and placement
import type { Point2D, CurveParameters } from '../types';
import { generateId } from '../types';
import type { CurveDataAnnotation } from './annotation-types';
import { formatBearing } from '../geometry/bearing';

export interface CurveDataConfig {
  showRadius: boolean;
  showArcLength: boolean;
  showChordBearing: boolean;
  showChordDistance: boolean;
  showDelta: boolean;
  showTangent: boolean;
  font: string;
  fontSize: number;
  color: string;
  lineSpacing: number;
}

export const DEFAULT_CURVE_DATA_CONFIG: CurveDataConfig = {
  showRadius: true,
  showArcLength: true,
  showChordBearing: true,
  showChordDistance: true,
  showDelta: true,
  showTangent: false,
  font: 'Arial',
  fontSize: 7,
  color: '#000000',
  lineSpacing: 1.2,
};

/** Build the text lines for a curve data annotation from a CurveParameters object. */
export function buildCurveDataLines(params: CurveParameters, config: CurveDataConfig): string[] {
  const lines: string[] = [];
  if (config.showRadius)        lines.push(`R = ${params.R.toFixed(2)}'`);
  if (config.showArcLength)     lines.push(`L = ${params.L.toFixed(2)}'`);
  if (config.showDelta)         lines.push(`Δ = ${((params.delta * 180) / Math.PI).toFixed(4)}°`);
  if (config.showChordBearing)  lines.push(`CB = ${formatBearing(params.CB)}`);
  if (config.showChordDistance) lines.push(`C = ${params.C.toFixed(2)}'`);
  if (config.showTangent)       lines.push(`T = ${params.T.toFixed(2)}'`);
  return lines;
}

export function createCurveDataAnnotation(
  params: CurveParameters,
  linkedFeatureId: string,
  config: CurveDataConfig,
): CurveDataAnnotation {
  const textLines = buildCurveDataLines(params, config);

  return {
    id: generateId(),
    type: 'CURVE_DATA',
    layerId: 'ANNOTATION',
    visible: true,
    locked: false,
    linkedFeatureId,
    linkedSegmentIndex: null,
    isManuallyPlaced: false,
    isAutoGenerated: true,
    priority: 3,
    showRadius: config.showRadius,
    showArcLength: config.showArcLength,
    showChordBearing: config.showChordBearing,
    showChordDistance: config.showChordDistance,
    showDelta: config.showDelta,
    showTangent: config.showTangent,
    textLines,
    position: 'OUTSIDE_ARC',
    customPosition: null,
    followCurve: false,
    leaderToArc: true,
    font: config.font,
    fontSize: config.fontSize,
    color: config.color,
    lineSpacing: config.lineSpacing,
  };
}

/**
 * Compute the placement position for a curve data annotation.
 * Returns a world coordinate for the top-left of the text block.
 */
export function computeCurveLabelPosition(
  params: CurveParameters,
  drawingScale: number,
  position: 'OUTSIDE_ARC' | 'INSIDE_ARC' | 'CUSTOM',
  customPosition?: Point2D,
): Point2D {
  if (position === 'CUSTOM' && customPosition) return customPosition;

  // Place outside the arc: move from center toward mpc, then outward by R + offset
  const offset = 0.2 * drawingScale; // 0.2 paper inches offset from arc
  const fromCenter = params.rp;
  const toMpc = params.mpc;
  const dir = Math.atan2(toMpc.y - fromCenter.y, toMpc.x - fromCenter.x);

  const dist = position === 'OUTSIDE_ARC'
    ? params.R + offset
    : params.R * 0.5;

  return {
    x: fromCenter.x + Math.cos(dir) * dist,
    y: fromCenter.y + Math.sin(dir) * dist,
  };
}
