// lib/cad/labels/monument-label.ts — Monument label creation and placement
import type { SurveyPoint, Point2D } from '../types';
import { generateId } from '../types';
import type { MonumentLabel } from './annotation-types';

export interface MonumentLabelConfig {
  font: string;
  fontSize: number;
  color: string;
  defaultOffset: number;
}

export const DEFAULT_MONUMENT_LABEL_CONFIG: MonumentLabelConfig = {
  font: 'Arial',
  fontSize: 7,
  color: '#000000',
  defaultOffset: 0.15,
};

/**
 * Monument text from code + action. Produces strings like:
 *   "1/2\" IRF", "5/8\" IRS w/Cap", "1/2\" IRS", "Mag Nail Found", "PK Nail Found"
 */
export function getMonumentText(point: SurveyPoint): { full: string; abbreviated: string } {
  const action = point.monumentAction;
  const code = point.resolvedAlphaCode?.toUpperCase() ?? '';

  // Monument size/type from numeric code (rough lookup)
  const numCode = parseInt(point.resolvedNumericCode ?? '0', 10);

  // Action suffix
  const actionSuffix = action === 'FOUND' ? ' Found'
    : action === 'SET' ? '' // set is implied
    : action === 'CALCULATED' ? ' (Calc)'
    : '';

  // Material from category code
  const isBoundaryControl = point.codeDefinition?.category === 'BOUNDARY_CONTROL';

  if (!isBoundaryControl) {
    const desc = point.codeDefinition?.description ?? point.rawCode;
    return { full: desc, abbreviated: desc.substring(0, 12) };
  }

  // Iron rod size
  const rodSize = numCode === 7 ? '5/8"' : numCode === 2 ? '1/2"' : numCode === 4 ? '3/4"' : '1/2"';
  const rodType = action === 'FOUND' ? 'IRF' : 'IRS';
  const hasCap = code.includes('CAP') || (numCode >= 5 && numCode <= 9);
  const capSuffix = hasCap && action !== 'FOUND' ? ' w/Cap' : '';

  const full = `${rodSize} ${rodType}${capSuffix}${actionSuffix}`;
  const abbreviated = `${rodSize} ${rodType}`;
  return { full, abbreviated };
}

export function createMonumentLabel(
  point: SurveyPoint,
  config: MonumentLabelConfig,
  offsetAngle = 45,
): MonumentLabel {
  const { full, abbreviated } = getMonumentText(point);

  return {
    id: generateId(),
    type: 'MONUMENT_LABEL',
    layerId: 'ANNOTATION',
    visible: true,
    locked: false,
    linkedFeatureId: point.featureId || null,
    linkedSegmentIndex: null,
    isManuallyPlaced: false,
    isAutoGenerated: true,
    priority: 2,
    pointId: point.id,
    position: { x: point.easting, y: point.northing },
    text: full,
    abbreviatedText: abbreviated,
    offsetAngle,
    offsetDistance: config.defaultOffset,
    hasLeader: true,
    font: config.font,
    fontSize: config.fontSize,
    color: config.color,
  };
}

/**
 * Compute the label anchor position given the point position, offset angle, and distance.
 */
export function computeMonumentLabelPosition(
  pointPos: Point2D,
  offsetAngle: number,
  offsetDistInches: number,
  drawingScale: number,
): Point2D {
  const angleRad = (offsetAngle * Math.PI) / 180;
  const dist = offsetDistInches * drawingScale;
  return {
    x: pointPos.x + Math.cos(angleRad) * dist,
    y: pointPos.y + Math.sin(angleRad) * dist,
  };
}

/**
 * Pick the best offset angle for a monument label by testing 8 candidates
 * and selecting the one that is farthest from all nearby line segments.
 */
export function pickBestOffsetAngle(
  point: Point2D,
  nearbySegments: { from: Point2D; to: Point2D }[],
): number {
  const candidates = [0, 45, 90, 135, 180, 225, 270, 315];

  let bestAngle = 45;
  let bestMinDist = -Infinity;

  for (const angleDeg of candidates) {
    const angleRad = (angleDeg * Math.PI) / 180;

    // Minimum angular distance from test direction to any segment direction
    let minDist = Infinity;
    for (const seg of nearbySegments) {
      const segAngle = Math.atan2(seg.to.y - seg.from.y, seg.to.x - seg.from.x);
      const diff = Math.abs(angleRad - segAngle) % (2 * Math.PI);
      const angDist = Math.min(diff, 2 * Math.PI - diff);
      minDist = Math.min(minDist, angDist);
    }

    if (nearbySegments.length === 0) minDist = Infinity;
    if (minDist > bestMinDist) {
      bestMinDist = minDist;
      bestAngle = angleDeg;
    }
  }

  return bestAngle;
}
