const {Client}=require('pg');(async()=>{const c=new Client({connectionString:process.env.SUPABASE_DB_URL,ssl:{rejectUnauthorized:false}});await c.connect();
const q=async s=>(await c.query(s)).rows[0].n;
const mods=await q(`select count(*) n from learning_modules where deleted_at is null`);
const les=await q(`select count(*) n from learning_lessons where deleted_at is null`);
const blk=await q(`select count(*) n from lesson_blocks`);
const fc=await q(`select count(*) n from flashcards where deleted_at is null`);
const qb=await q(`select count(*) n from question_bank where deleted_at is null`);
const dyn=await q(`select count(*) n from question_bank where is_dynamic=true`);
const tmpl=await q(`select count(*) n from problem_templates where is_active=true`);
const nmsu=await q(`select count(*) n from learning_modules where acc_course_id='nmsu-sur292'`);
console.log(`GRAND TOTALS (platform): modules=${mods} lessons=${les} blocks=${blk} flashcards=${fc} questions=${qb} (dynamic ${dyn}) templates=${tmpl}; NMSU course modules=${nmsu}`);
await c.end();})().catch(e=>{console.error(e.message);process.exit(1)});
