// lib/dnd/systems/intuitive-games/feats.ts — the Intuitive Games FEAT catalog with full rules text,
// transcribed from intuitivegames.net (General Feats: /feats-general; Combat Feats: /feats-combat — added
// in a later slice). Source-only: every feat here is on the site; nothing is invented (IG buildout rule 2).
// The library page, cross-system search, the provenance classifier, and AI grounding all read this so a
// feat carries its actual prerequisites + effect, not just a name.

export interface IGFeat {
  name: string;
  /** Which page it lives on. */
  category: 'General' | 'Combat';
  /** Sub-grouping within the page (site's own headings). */
  group: 'General' | 'Skill' | 'Special' | 'Ability' | 'Combat' | 'Mythic Stance' | 'Style' | 'Mastery';
  /** Prerequisites exactly as the site states them, or null when none are listed. */
  prerequisites: string | null;
  /** The feat's effect (mechanically faithful to the site). */
  effect: string;
}

// ── General Feats page (/feats-general) — 83 feats across four site headings. ────────────────────────
export const IG_GENERAL_FEATS: IGFeat[] = [
  // Main General Feats
  { name: 'Advanced Magic', category: 'General', group: 'General', prerequisites: 'Training in Spellcraft and having learned a single spell that has an Advanced spell ability', effect: 'Learn an Advanced spell. Each casting requires a DC 20 Will save or you lose an action next turn.' },
  { name: 'Alert', category: 'General', group: 'General', prerequisites: 'Training in Perception', effect: 'You are never considered flat-footed so long as you can see 5 feet of your surroundings.' },
  { name: 'Arcane Heritage', category: 'General', group: 'General', prerequisites: 'Training in Arcane', effect: 'Choose one benefit from the aligned, draconic, elemental, fey, nature, occult, time, or vampiric options, each granting a specific magical ability.' },
  { name: 'Archivist', category: 'General', group: 'General', prerequisites: 'Training in Spellcraft and the ability to cast at least one spell from the Spell List', effect: 'Learn two spells from one school you already know a spell from, excluding Advanced/Expert versions.' },
  { name: 'Aura Mastery', category: 'General', group: 'General', prerequisites: 'Training in Religion', effect: 'Make a Religion check as an action; allies within 30 feet (up to your Wisdom modifier) may use the result on one check type chosen from skills, saves, or attacks with proficient weapons.' },
  { name: 'Basic Redistribution', category: 'General', group: 'General', prerequisites: 'Training in Nature', effect: 'Gain the redistribution ability as a Conduit using items of one material type, dealing damage as a 1st-level Conduit.' },
  { name: 'Bomb Crafter', category: 'General', group: 'General', prerequisites: 'Training in Craft: Bomb', effect: 'Learn two bomb types from the listed options; create a number equal to your Craft skill bonus daily using the appropriate materials.' },
  { name: 'Bully', category: 'General', group: 'General', prerequisites: 'Training in Intimidate', effect: 'As a free action you may add your Strength modifier to an Intimidate check; outside combat this costs one nonlethal damage.' },
  { name: 'Combat Healer', category: 'General', group: 'General', prerequisites: null, effect: 'You never provoke reactions for using abilities that restore hit points, and targets recover an additional 2 hit points when you heal them.' },
  { name: 'Companion Creature', category: 'General', group: 'General', prerequisites: 'Training in Handle Animal', effect: 'Gain a Companion Creature using the Archon class rules; you cannot spend two actions directing it in order to take a third action.' },
  { name: 'Cure Ailment', category: 'General', group: 'General', prerequisites: 'Training in Heal and Spellcraft', effect: 'Three-action activity that removes one condition (Confused, Entangled, Fascinated, Paralyzed, Shaken, or Sickened, magical only) from an adjacent target.' },
  { name: 'Divine Blessing / Divine Curse', category: 'General', group: 'General', prerequisites: 'Training in Religion', effect: 'Two-action activity applying a chosen blessing or curse; blessings affect up to your Wisdom modifier in targets, curses target one creature resisted by a Will save.' },
  { name: 'Eldritch Smith', category: 'General', group: 'General', prerequisites: 'Spellcraft and Craft: Eldritch Jewels', effect: 'Manufacture Eldritch Jewels, requiring a DC 30 Spellcraft check, magical components, and five working days per enchantment.' },
  { name: 'Endurance', category: 'General', group: 'General', prerequisites: null, effect: 'Ignore a number of points of nonlethal damage each day equal to your Constitution modifier.' },
  { name: 'Favored Skills', category: 'General', group: 'General', prerequisites: null, effect: '+2 bonus on rolls with two chosen skills. Can be chosen multiple times for additional skill pairs.' },
  { name: 'Fleet', category: 'General', group: 'General', prerequisites: null, effect: 'Gain 10 additional feet of move speed.' },
  { name: 'Flexible Form', category: 'General', group: 'General', prerequisites: 'Training in Nature and Arcane', effect: 'As a three-action activity, transform into a different humanoid creature, gaining its physical characteristics including size changes.' },
  { name: 'Gifted', category: 'General', group: 'General', prerequisites: null, effect: 'Gain an extra class power.' },
  { name: 'Honorbound', category: 'General', group: 'General', prerequisites: null, effect: 'Choose an honor culture (Dominance, Integrity, Nobility, or Protection) gaining its benefits while you maintain honor; lose the benefits upon dishonor.' },
  { name: 'Improviser', category: 'General', group: 'General', prerequisites: null, effect: 'Use half of the relevant ability modifier on all untrained skill checks.' },
  { name: 'Improved Initiative', category: 'General', group: 'General', prerequisites: null, effect: 'Gain advantage on initiative checks.' },
  { name: 'Keen Magic', category: 'General', group: 'General', prerequisites: 'Training in Arcane, Nature, Religion, or Spellcraft', effect: 'Double the range of your magical abilities and gain a +2 bonus on the associated magic skill checks.' },
  { name: 'Linguist', category: 'General', group: 'General', prerequisites: null, effect: 'Learn one common and one uncommon language.' },
  { name: 'Lucky', category: 'General', group: 'General', prerequisites: null, effect: 'Gain a luck pool equal to your character level; spend a point to add 1d6 to an attack/save/skill check or to assist an ally.' },
  { name: 'Martyr', category: 'General', group: 'General', prerequisites: null, effect: 'If an adjacent ally is about to suffer an effect, spend a reaction making a Will save with advantage; on success you take the effect for them.' },
  { name: 'Meddler', category: 'General', group: 'General', prerequisites: 'Training in Arcane or Religion', effect: 'Reaction when a creature uses Divine Blessing, Aura Mastery, Redistribution, or a spell within 30 feet to counter it with a Religion/Arcane check.' },
  { name: 'Mental Training', category: 'General', group: 'General', prerequisites: null, effect: 'Gain an ability score increase to a mental stat, proficiency with a new tool, and learn a common language.' },
  { name: 'Mystic', category: 'General', group: 'General', prerequisites: 'Proficiency with Religion', effect: 'Learn to cast a single Divination spell using your Religion skill and Wisdom modifier instead of Spellcraft and Intelligence.' },
  { name: 'Necromancy', category: 'General', group: 'General', prerequisites: 'Training in Arcane and Heal', effect: 'Gain the Forbidden Practices ability, raising an undead companion that lasts hours equal to your character level.' },
  { name: 'Poison Master', category: 'General', group: 'General', prerequisites: 'Training in Craft: Poison', effect: 'Create doses equal to your Craft bonus daily; learn two poison types (Inhaled, Contact, Ingested, Injury) with their penalties and onset times.' },
  { name: 'Potion Brewer', category: 'General', group: 'General', prerequisites: 'Training in Craft: Potion', effect: 'Create potions equal to your Craft bonus daily; learn two types (Healing, Restoration, Elemental Resistance, Luck, Temperature Tolerance).' },
  { name: 'Pressure Point Mastery', category: 'General', group: 'General', prerequisites: 'Training in Unarmed Combat', effect: 'Two-action unarmed attack inflicting one condition for a varied duration; the target’s armor adds a bonus to its reflex-save defense.' },
  { name: 'Prodigy', category: 'General', group: 'General', prerequisites: null, effect: 'Gain an extra skill proficiency. Can be chosen multiple times.' },
  { name: 'Quick Caster', category: 'General', group: 'General', prerequisites: null, effect: 'Cast a spell or magical ability using one fewer action; you take 2 nonlethal damage and lose your reaction that round.' },
  { name: 'Redirect Energy', category: 'General', group: 'General', prerequisites: 'Training in Arcane', effect: 'Reaction when hit by an elemental attack: make an opposed Arcane check to redirect the damage as a ranged attack to a target within 30 feet.' },
  { name: 'Sorcery', category: 'General', group: 'General', prerequisites: 'Training in Arcane; you must select this feat at Level 1', effect: 'Choose a bloodline learning two associated spells, using Charisma and Arcane instead of Intelligence and Spellcraft.' },
  { name: 'Terrain Expertise', category: 'General', group: 'General', prerequisites: 'Training in Nature', effect: 'Choose a terrain, gaining half nonlethal damage from its extreme temperature and a +2 bonus on eight listed skills within that terrain.' },
  { name: 'Scarred By Magic', category: 'General', group: 'General', prerequisites: 'Training in Arcane', effect: 'Take 1 nonlethal damage from each harmful magical effect; you constantly detect magic without spending an action.' },
  { name: 'Signature Skills', category: 'General', group: 'General', prerequisites: null, effect: 'Take 10 on two chosen skills, even in combat. Can be chosen multiple times for additional skill pairs.' },
  { name: 'Supportive', category: 'General', group: 'General', prerequisites: null, effect: 'Take multiple support actions per round, each supporting a different character.' },
  { name: 'Touch Of Life', category: 'General', group: 'General', prerequisites: 'Training in Arcane and Religion', effect: 'One action: heal yourself 1d8 + level (1 nonlethal). Two actions: heal a touched creature (1 nonlethal). Three actions: heal a touched creature (no cost).' },
  { name: 'Toughness', category: 'General', group: 'General', prerequisites: null, effect: 'Gain advantage on Fortitude saves against damage and gain 5 extra hit points.' },
  { name: 'Trap Crafter', category: 'General', group: 'General', prerequisites: 'Training in Craft: Traps', effect: 'Learn two trap types from six options with their triggers, setup times, and materials. Can be chosen multiple times.' },
  { name: 'Versatile', category: 'General', group: 'General', prerequisites: null, effect: 'Acquire an extra trait. Can only be selected once.' },
  { name: 'Wondrous Crafter', category: 'General', group: 'General', prerequisites: 'Spellcraft and the Craft skills noted in each section', effect: 'Choose two item types (Magic Items, Rods, Scrolls, Wands) to craft using Eldritch Jewels and an arcane focus.' },
  { name: 'Words of Magic', category: 'General', group: 'General', prerequisites: 'Training in Linguistics and Spellcraft', effect: 'Learn spells equal to your Intelligence modifier, cast using your Linguistics bonus; each requires a DC 10 Linguistics check and a written spell item.' },

  // General Skill Feats (one per skill)
  { name: 'Careful Steps', category: 'General', group: 'Skill', prerequisites: 'Training in Acrobatics', effect: 'You are unaffected by difficult terrain.' },
  { name: 'Deal Finder', category: 'General', group: 'Skill', prerequisites: 'Training in Appraise', effect: 'Use Appraise for bartering instead of Diplomacy, and for hidden-object searches instead of Perception.' },
  { name: 'Psychic Power', category: 'General', group: 'Skill', prerequisites: 'Training in Arcane', effect: 'Learn Create Image, Enchant Creature, and Mindlink using Arcane and Charisma instead of Spellcraft/Intelligence; you cannot learn Advanced/Expert versions.' },
  { name: 'Source of Distraction', category: 'General', group: 'Skill', prerequisites: 'Training in Artistry', effect: 'As an action, make an Artistry check opposed by a Will save to fascinate a creature using metallic or artistic objects.' },
  { name: 'Rehearsed Story', category: 'General', group: 'Skill', prerequisites: 'Training in Bluff', effect: 'Gain advantage on Bluff checks when using an invented alter ego or fall-guy persona.' },
  { name: 'Strong Grip', category: 'General', group: 'Skill', prerequisites: 'Training in Climb', effect: 'Gain or increase a climb speed by 10 feet; gain advantage on defensive rolls against disarm attempts.' },
  { name: 'Multitasking', category: 'General', group: 'Skill', prerequisites: 'Training in any Craft', effect: 'Use two different craft subskills simultaneously on separate projects.' },
  { name: 'Honeyed Tongue', category: 'General', group: 'Skill', prerequisites: 'Training in Diplomacy', effect: 'Three-action Diplomacy check opposed by a Will save to achieve peace in combat for one minute, with listed degrees of success.' },
  { name: 'Tools of the Trade', category: 'General', group: 'Skill', prerequisites: 'Training in Disable Device', effect: 'Use thieves’ tools as a 1d4 piercing proficient weapon using your Disable Device bonus; the tools have the engineered property.' },
  { name: 'Uncanny Dodge', category: 'General', group: 'Skill', prerequisites: 'Training in Escape Artist', effect: 'Use your Escape Artist bonus instead of your Reflex save bonus against melee attacks.' },
  { name: 'Master Flier', category: 'General', group: 'Skill', prerequisites: 'Training in Fly', effect: 'Use your Fly bonus instead of your Reflex save bonus against ranged attacks while flying.' },
  { name: "Nature's Friend", category: 'General', group: 'Skill', prerequisites: 'Training in Handle Animal', effect: 'Three-action Handle Animal check opposed by an animal’s Will save to achieve peace in combat, with listed degrees of success.' },
  { name: 'Natural Medicine', category: 'General', group: 'Skill', prerequisites: 'Training in Heal', effect: 'One hour of dedicated use of honey heals hit points equal to your Heal bonus; one hour with sunflower removes conditions.' },
  { name: 'Show of Force', category: 'General', group: 'Skill', prerequisites: 'Training in Intimidate', effect: 'As an action, intimidate creatures within 20 feet up to your Charisma modifier; this can be used as a single attack instead.' },
  { name: 'Lore Master', category: 'General', group: 'Skill', prerequisites: 'Training in any Lore', effect: 'Make Lore checks on topics related to your trained Craft, Perform, or Profession skills using the relevant Lore subskill bonus.' },
  { name: 'Philologist', category: 'General', group: 'Skill', prerequisites: 'Training in Linguistics', effect: 'Create a new language. Can be chosen multiple times.' },
  { name: 'Cruel Materials', category: 'General', group: 'Skill', prerequisites: 'Training in Nature', effect: 'Manufacture poisons using your Nature bonus instead of Craft: Poison, and gain immunity to all poisons and venoms.' },
  { name: 'One Eye Open', category: 'General', group: 'Skill', prerequisites: 'Training in Perception', effect: 'Take no penalty on Perception checks while asleep.' },
  { name: 'Disruptive Performance', category: 'General', group: 'Skill', prerequisites: 'Training in any Perform skill', effect: 'As an action, make a feint check without a weapon using your highest Perform bonus.' },
  { name: 'Augury', category: 'General', group: 'Skill', prerequisites: 'Training in Religion', effect: 'Meditate to ask the powers one question, choosing aligned-creature detection, clairvoyance, or specific knowledge, with the listed costs.' },
  { name: 'Careful Jockey', category: 'General', group: 'Skill', prerequisites: 'Training in Ride', effect: 'Ride any creature regardless of size so long as its weight is within your carrying capacity.' },
  { name: 'Careful Listener', category: 'General', group: 'Skill', prerequisites: 'Training in Sense Motive', effect: 'Use your Sense Motive bonus in place of your Diplomacy bonus for Diplomacy checks.' },
  { name: 'Quick Fingers', category: 'General', group: 'Skill', prerequisites: 'Training in Sleight of Hand', effect: 'Two-action activity including a stride action with a Sleight of Hand attempt at any point during the movement.' },
  { name: 'Enchanter', category: 'General', group: 'Skill', prerequisites: 'Training in Spellcraft', effect: 'Use Spellcraft to recharge enchanted items/Eldritch Jewels instead of Arcane; take half nonlethal damage on a recharge roll below 20+.' },
  { name: 'Shadow Speed', category: 'General', group: 'Skill', prerequisites: 'Training in Stealth', effect: 'Make Stealth checks while striding instead of only while taking steps.' },
  { name: 'Strong Swimmer', category: 'General', group: 'Skill', prerequisites: 'Training in Swim', effect: 'Gain or increase a swim speed by 10 feet, and hold your breath twice as long as normal.' },

  // Special Feats (proficiency + save feats)
  { name: 'Armor Proficiency', category: 'General', group: 'Special', prerequisites: null, effect: 'Eliminate the penalty on Reflex saves from wearing armor.' },
  { name: 'Boundless Stamina', category: 'General', group: 'Special', prerequisites: null, effect: 'Gain a +2 bonus on Fortitude saves.' },
  { name: 'Daring Quickness', category: 'General', group: 'Special', prerequisites: null, effect: 'Gain a +2 bonus on Reflex saves.' },
  { name: 'Inspiring Insight', category: 'General', group: 'Special', prerequisites: null, effect: 'Gain a +2 bonus on Will saves.' },
  { name: 'Shield Proficiency', category: 'General', group: 'Special', prerequisites: null, effect: 'Eliminate shield penalties; ready a shield as an action for a +2 Reflex bonus for one round; use the shield for its bonus and as a weapon simultaneously.' },
  { name: 'Weapon Training', category: 'General', group: 'Special', prerequisites: null, effect: 'Gain proficiency with any two weapon groups. Can be chosen multiple times for additional weapon-group pairs.' },

  // Ability Score Feats
  { name: 'Strength', category: 'General', group: 'Ability', prerequisites: null, effect: 'Gain an Ability Score Boost to Strength, and reroll one Strength-based skill check daily.' },
  { name: 'Dexterity', category: 'General', group: 'Ability', prerequisites: null, effect: 'Gain an Ability Score Boost to Dexterity, and reroll one Dexterity-based skill check daily.' },
  { name: 'Constitution', category: 'General', group: 'Ability', prerequisites: null, effect: 'Gain an Ability Score Boost to Constitution, and remain conscious one additional turn at 0 HP unless killed.' },
  { name: 'Intelligence', category: 'General', group: 'Ability', prerequisites: null, effect: 'Gain an Ability Score Boost to Intelligence, and reroll one Intelligence-based skill check daily.' },
  { name: 'Wisdom', category: 'General', group: 'Ability', prerequisites: null, effect: 'Gain an Ability Score Boost to Wisdom, and reroll one Wisdom-based skill check daily.' },
];

// ── Combat Feats page (/feats-combat) — 68 feats: main combat feats, 8 Mythic Stances, 5 Styles (each
//    with its moves), and 10 Combat Skill "Mastery" feats. Transcribed verbatim from the site. A few
//    proficiency feats (Armor/Shield Proficiency, Weapon Training) appear on BOTH pages, as on the site. ──
export const IG_COMBAT_FEATS: IGFeat[] = [
  { name: 'Armor Proficiency', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'You become proficient with all types of armor, and no longer take a penalty on reflex saves based on the DR granted by that armor worn.' },
  { name: 'Bodyguard', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'You may spend a reaction giving an adjacent ally a bonus on a reflex save equal to your dexterity modifier. This ability can be activated when an adjacent ally is attacked.' },
  { name: 'Bowstaff', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with a ranged piercing weapon like a bow.', effect: 'Your bow, crossbow, or firearm can also be used as a melee bludgeoning weapon with which you are proficient. You must spend an action to adjust your grip to use it as melee or ranged. The damage is calculated as if it were a one-handed bludgeoning weapon.' },
  { name: 'Bludgeoner', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'When wielding a melee bludgeoning weapon with which you are proficient, you may deal lethal or nonlethal damage with your attacks (declare before the attack). You may also make a sunder attempt as a free action against an accessible item held by a target you hit — once per turn, without provoking reactions.' },
  { name: 'Careful Caster', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'You do not provoke reactions for casting a spell or using a similar ability with foes threatening you.' },
  { name: 'Careful Shot', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'You do not provoke reactions for making a ranged attack with foes threatening you.' },
  { name: 'Cleave', category: 'Combat', group: 'Combat', prerequisites: 'Requires Dexterity 14 or higher.', effect: 'As a 3-action activity, you may attack all adjacent enemies (or all threatened enemies with a reach weapon). You don’t take the MSP when using this feat.' },
  { name: 'Combat Patrol', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Spend 2 actions activating this feat. Upon activation, you may act as though you took a move action. You may take two extra reactions this turn.' },
  { name: 'Combat Reflexes', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Gain an extra reaction.' },
  { name: 'Critical Focus', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with the weapon type chosen.', effect: 'Choose one type of weapon. When wielding weapons from the chosen group with the selected damage type, critical successes can be scored with a total of 15 higher than the opponent instead of 20 higher.' },
  { name: 'Defensive Fighting', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Spend one action (which may also be used to make a strike). Take a penalty on all attack rolls equal to your level for one round, and gain a bonus on all reflex rolls equal to your level for one round.' },
  { name: 'Dodge', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'When attacked, spend a reaction to multiply your dexterity modifier by 2 on the reflex save against that attack.' },
  { name: 'Doubleshot', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with ranged weapons.', effect: 'When attacking with a non-firearm ranged weapon, launch an additional piece of ammunition; resolve as one attack that deals damage twice. All subsequent attacks this turn take the MSP as if you had attacked twice. Once per round.' },
  { name: 'Duelist', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with one-handed piercing weapons.', effect: 'When wielding a one-handed piercing melee weapon in one hand and not using your other hand for anything (no weapons or shield), you gain advantage on one attack roll or reflex save that round.' },
  { name: 'Elemental Mastery', category: 'Combat', group: 'Combat', prerequisites: 'Requires an ability that deals elemental damage.', effect: 'Choose one of the five elemental damage types. When you deal damage of that type, deal an additional two points; when you take damage from that element, reduce it by two.' },
  { name: 'Focused Strike', category: 'Combat', group: 'Combat', prerequisites: 'Requires Int or Wis 14.', effect: 'By spending an additional action when making an attack, you gain advantage on the attack roll. Cannot be applied to a reaction attack or when you have no actions left.' },
  { name: 'Formidable Arms', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with the weapon group chosen.', effect: 'A weapon of the chosen group deals damage as if two size categories larger (1d2, 1d4, 1d6, 1d8, 1d10, 1d12, 1d12+1d4, 1d12+1d6, 1d12+1d8, …; 2d6 scales as 2d6+1d4, 2d6+1d6, …).' },
  { name: 'Guarded Combatant', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with shields.', effect: 'As a two-action activity, guard yourself with your shield to make a step or stride and a strike without provoking reactions from that movement. If you use Defensive Fighting, that strike does not take its attack penalty.' },
  { name: 'Great Weapon Fighting', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'When wielding a proficient melee two-handed or heavy weapon, roll your damage dice twice and use the higher result. You may also make a reposition attempt as a free action after hitting — once per turn, without provoking reactions.' },
  { name: 'Lunge', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Spend an action (which may make an attack) to increase the threatened area of your melee weapons by 5 feet until the start of your next turn; you have disadvantage on reflex saves until then. With Relentless, you may use it against any creature within 10 feet.' },
  { name: 'Mage Hunter', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'When you spend a reaction to attack a target that provoked by casting a spell, using redistribution, or a similar ability, gain one extra reaction this turn. Characters with Careful Caster still provoke reactions from you.' },
  { name: 'Magic Specialization', category: 'Combat', group: 'Combat', prerequisites: 'Requires training in Arcane, Nature, or Religion.', effect: 'Apply to a single Wizard spell, Conduit Power, Divine Blessing connection, or similar ability: any effect that deals damage deals two additional points of the same type.' },
  { name: 'Mounted Archery', category: 'Combat', group: 'Combat', prerequisites: 'Requires training in Ride.', effect: 'You are no longer at disadvantage making ranged attacks while moving on a mount. While mounted, you do not provoke reactions for ranged attacks unless the threatening creature has reach.' },
  { name: 'Mounted Combat', category: 'Combat', group: 'Combat', prerequisites: 'Requires training in Ride.', effect: 'If your mount is about to make a saving throw, spend a reaction to make a Ride check; the mount can use the Ride total or its own saving throw total.' },
  // Mythic Stances (each follows normal stance rules, activated with an action; only one Mythic Stance)
  { name: 'Mythic Stance: Dragon Stance', category: 'Combat', group: 'Mythic Stance', prerequisites: 'Requires no other Mythic Stances.', effect: 'Follows all normal stance rules; activated with an action. Your first successful attack each turn deals an additional 1d10 points of damage.' },
  { name: 'Mythic Stance: Fey Stance', category: 'Combat', group: 'Mythic Stance', prerequisites: 'Requires no other Mythic Stances.', effect: 'Follows all normal stance rules; activated with an action. Your movement speed increases by 10 feet.' },
  { name: 'Mythic Stance: Genie Stance', category: 'Combat', group: 'Mythic Stance', prerequisites: 'Requires no other Mythic Stances.', effect: 'Follows all normal stance rules; activated with an action. When you deal elemental damage, you deal an additional 1d6 points of damage.' },
  { name: 'Mythic Stance: Griffon Stance', category: 'Combat', group: 'Mythic Stance', prerequisites: 'Requires no other Mythic Stances.', effect: 'Follows all normal stance rules; activated with an action. You gain one extra reaction each turn.' },
  { name: 'Mythic Stance: Phoenix Stance', category: 'Combat', group: 'Mythic Stance', prerequisites: 'Requires no other Mythic Stances.', effect: 'Follows all normal stance rules; activated with an action. You do not take nonlethal damage from combat or normal exertion; while active you take 1 point of nonlethal damage every 10 minutes.' },
  { name: 'Mythic Stance: Treant Stance', category: 'Combat', group: 'Mythic Stance', prerequisites: 'Requires no other Mythic Stances.', effect: 'Follows all normal stance rules; activated with an action. If you do not move on your turn, you gain a 1d8 bonus on each attack roll that you make.' },
  { name: 'Mythic Stance: Unicorn Stance', category: 'Combat', group: 'Mythic Stance', prerequisites: 'Requires no other Mythic Stances.', effect: 'Follows all normal stance rules; activated with an action. You gain a 1d10 bonus on saves against spells, redistribution, Divine Blessing, and similar abilities.' },
  { name: 'Mythic Stance: Wyvern Stance', category: 'Combat', group: 'Mythic Stance', prerequisites: 'Requires no other Mythic Stances.', effect: 'Follows all normal stance rules; activated with an action. Whenever you deal bleed damage, you double the amount of bleed damage that you deal.' },
  { name: 'Natural Weapon Mastery', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Grants one of two benefits (take twice for the advanced feature). [Single Natural Weapon]: multiply your strength modifier by 1.5. Advanced: roll damage dice twice and increase the die one step. [Multiple Natural Weapons]: MSP is -1 instead of -2 with natural weapons. Advanced: after three natural-weapon attacks, make an additional natural-weapon attack (MSP as normal).' },
  { name: 'Outflank', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'When you flank a creature, it takes -2 on all reflex saves while flanked by you; penalties stack for each flanking creature with this feat. With Threatening Presence, a wall/barrier opposite the target counts as a flanker.' },
  { name: 'Parry', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Make an opposed attack roll as a reaction instead of a reflex save against a melee attack. With Counterattack + Combat Reflexes, one reaction can Parry and Counterattack the same attack (resolve Parry first).' },
  { name: 'Physical Training', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Gain an ability score increase to one physical stat. Gain proficiency with one weapon group.' },
  { name: 'Polearm Mastery', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'When wielding a proficient reach weapon in both hands, adjust your grip as an action for two extra styles (another action to revert). [Double weapon]: loses reach, gains the double property, deals 1d6 bludgeoning on the off end. [Close weapon]: loses reach, wielded as a regular melee weapon; +2 on attacks vs mounted or higher-elevation creatures.' },
  { name: 'Point Blank Shot', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'You gain a +2 bonus on ranged attacks within 30 feet.' },
  { name: 'Power Attack', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Activate with one action (which may make a single attack). All melee attacks deal extra damage equal to your level for one round; take half your level (rounded down) as a penalty on all melee attacks. If you round down (odd level), a partial success on an attack is treated as a failure.' },
  { name: 'Quickdraw', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Draw a weapon as a free action. Any feats that require a move action to adjust your grip are now a free action.' },
  { name: 'Quick Shot', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with ranged weapons.', effect: 'If you have spent two actions making two ranged attacks, you may make a third attack as a free action. The MSP applies as normal for all attacks.' },
  { name: 'Reflective Shield', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with shields.', effect: 'As a reaction after being targeted by a ranged attack, make an opposed attack roll with your shield to send the attack 10 feet in any direction instead of making a reflex save; you may direct it at a target, whose reflex save must then counter your original attack roll.' },
  { name: 'Relentless', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Use a reaction to both step and strike (the strike may be a trained combat skill), any time a creature steps or strides into a hex adjacent to you. With Lunge, use it against any creature within your Lunge reach.' },
  { name: 'Shield Proficiency', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'You no longer take penalties using shields; spend an action to ready a shield for an additional +2 on Reflex saves for one round. You can use a shield for its reflex bonus and as a weapon at the same time.' },
  { name: 'Smite Foe', category: 'Combat', group: 'Combat', prerequisites: 'Requires training in Arcane.', effect: 'As an action, target one creature within sight; deal additional force damage equal to your Charisma modifier against it for each attack you make while using this ability, until the beginning of your next turn.' },
  { name: 'Stock Striker', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency in at least one kind of firearm.', effect: 'Your firearm can also be used as a proficient melee bludgeoning weapon (an action to adjust the grip); the damage equals a one- or two-handed weapon based on the firearm type.' },
  // Style feats (each grants a "move"; take again for another; usable only with a proficient melee weapon)
  { name: 'Style: Ancient Combat', category: 'Combat', group: 'Style', prerequisites: 'Requires training in Lore.', effect: 'Gain one move (take again for another), usable only with a proficient melee weapon. [Seamless Retribution]: gain the Counterattack reaction — when attacked, spend a reaction to attack the aggressor if within your weapon’s range. [Fast Maneuvers]: gain the Redirect reaction — after avoiding an attack with a reflex save, direct that attack at another character in range using your weapon’s attack bonus. [Death Spiral]: 3-action activity, attack all enemies you threaten with no MSP.' },
  { name: 'Style: Arcane Combat', category: 'Combat', group: 'Style', prerequisites: 'Requires training in Arcane.', effect: 'Gain one move (take again for another), usable only with a proficient melee weapon. [Cursed Wound]: attack; if it damages, the target is shaken for rounds equal to your Charisma modifier. [Incorporeal Nudge]: 2-action Arcane check to pull an adjacent enemy into your reach (they oppose with a reflex save); deal weapon damage on success, they return after. [Spell Slash]: reaction when an opponent in reach begins casting — opposed attack roll vs their Reflex save disrupts the spell and wastes its actions.' },
  { name: 'Style: Spell Combat', category: 'Combat', group: 'Style', prerequisites: 'Requires training in Spellcraft.', effect: 'Gain one move (take again for another), usable only with a proficient melee weapon. [Enchanted Strike]: 2-action single attack at +2; if it hits, add damage equal to your Intelligence modifier. [Targeted Strike]: single-action Disarm or Sunder attempt with advantage. [True Strike]: 3-action attack with double advantage. (MSP applies as normal.)' },
  { name: 'Style: Wild Combat', category: 'Combat', group: 'Style', prerequisites: 'Requires training in Nature.', effect: 'Gain one move (take again for another), usable only with a proficient melee weapon. [Hawk Swoop]: after an acrobatics check avoids a movement-based reaction, make a free attack against the evaded target. [Stinger Swarm]: single-action two attacks vs one target, always -2 damage (MSP normal). [Panther’s Leap]: single-action stride or step and a strike, once per turn (no other stride/step this turn).' },
  { name: 'Style: Zealous Combat', category: 'Combat', group: 'Style', prerequisites: 'Requires training in Religion.', effect: 'Gain one move (take again for another), usable only with a proficient melee weapon. [Delayed Opportunity]: forgo any number of actions to gain that many reactions before your next turn. [Obstruction]: action, Religion check vs an adjacent target’s Will save — success gives disadvantage on their next attack (repeatable, no reactions provoked). [Patient Strike]: your reaction attacks gain advantage (applies to Counterattack/Redirect, not Parry).' },
  { name: 'Sword and Pistol', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with One-Handed Firearms and One-Handed Slashing or Piercing weapons.', effect: 'No off-hand penalties using a OHS/OHP weapon in your dominant hand and a One-Handed Firearm in your off hand; attack adjacent targets with the OHF without provoking; MSP lowered to -1 when using both in a turn. Advanced (take twice): an extra off-hand attack in a round with two primary + one off-hand attack.' },
  { name: 'Threatening Presence', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'You are always considered to be threatening adjacent targets, even without a melee weapon. With Outflank, a wall/barrier opposite the target counts as a flanker.' },
  { name: 'Throw Anything', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Use any item you can easily lift as a thrown weapon without penalty; it counts as an improvised weapon dealing damage appropriate for its size.' },
  { name: 'Two-Weapon Fighting', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'When attacking with multiple weapons, MSP is -1 instead of -2, and you apply your full strength modifier on off-hand attack and damage rolls (firearms still don’t apply strength to damage). Advanced (take twice): one additional attack in a round where you attack with weapons in both hands.' },
  { name: 'Weapon Focus', category: 'Combat', group: 'Combat', prerequisites: 'Requires proficiency with the weapon group chosen.', effect: 'Choose one weapon group; gain +2 on attack rolls using weapons from that group with that damage type. Advanced: take multiple times, each for a new weapon group.' },
  { name: 'Weapon Training', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Gain proficiency with any two weapon groups. Advanced: take multiple times, each granting two more weapon groups.' },
  { name: 'Weapon Specialization', category: 'Combat', group: 'Combat', prerequisites: null, effect: 'Choose one weapon group; gain +2 on attack rolls using weapons from that group with that damage type. Advanced: take multiple times, each for a new weapon group.' },
  // Combat Skill "Mastery" feats
  { name: 'Dirty Trick Mastery', category: 'Combat', group: 'Mastery', prerequisites: null, effect: 'You apply two penalties to any target that you succeed a dirty trick attempt against.' },
  { name: 'Disarm Mastery', category: 'Combat', group: 'Mastery', prerequisites: null, effect: 'Disarmed opponents are flat footed for one round.' },
  { name: 'Feint Mastery', category: 'Combat', group: 'Mastery', prerequisites: null, effect: 'If you succeed your feint attempt, the target becomes flat footed until the end of your next turn.' },
  { name: 'Grapple Mastery', category: 'Combat', group: 'Mastery', prerequisites: null, effect: 'At the beginning of your turn after a successful grapple, you may maintain the grapple using a free action. A skill check is still required.' },
  { name: 'Overrun Mastery', category: 'Combat', group: 'Mastery', prerequisites: null, effect: 'You can overrun any number of targets in your path with a single overrun attempt applied to each in succession.' },
  { name: 'Reposition Mastery', category: 'Combat', group: 'Mastery', prerequisites: null, effect: 'When you successfully reposition an opponent, that creature provokes a reaction from all threatening creatures except for you.' },
  { name: 'Steal Mastery', category: 'Combat', group: 'Mastery', prerequisites: null, effect: 'As a two-action activity, stride and make a steal attempt at any point during your movement; that movement does not provoke a reaction from the target of your steal.' },
  { name: 'Sunder Mastery', category: 'Combat', group: 'Mastery', prerequisites: null, effect: 'Ignore hardness equal to your level when sundering an object. You may use your sunder skill bonus instead of your attack bonus vs a creature with damage reduction from armor, a thick hide, or similar.' },
  { name: 'Trip Mastery', category: 'Combat', group: 'Mastery', prerequisites: null, effect: 'You may make a trip attempt against any target within your reach while making a stride or step. This counts toward and is affected by the MSP.' },
  { name: 'Ultramagic', category: 'Combat', group: 'Mastery', prerequisites: 'Requires training in Arcane, Nature, or Religion.', effect: 'Apply to a single Wizard spell, Conduit Power, Divine Blessing connection, or similar ability: gain advantage on rolls that require an arcane/religion/nature check to succeed (for Redistribution, only checks with a single material known). Advanced: take multiple times, each for a new effect.' },
];

/** Every authored IG feat (General + Combat). */
export function igAllFeats(): IGFeat[] {
  return [...IG_GENERAL_FEATS, ...IG_COMBAT_FEATS];
}
