// lib/dnd/statblocks/tiers.ts — what a creature at each tier actually looks like (N1-1/N1-2).
//
// GENERATED by `npm run derive:tiers -- --write`. Do not hand-edit: re-run it instead, so the numbers stay
// a measurement of the catalogue rather than someone's memory of one.
//
// MEASURED, NOT COPIED. D&D's *Monster Statistics by Challenge Rating* and Pathfinder's *Building
// Creatures* are Dungeon Master's Guide and Monster Core content — neither is in the SRD or the
// ORC-licensed remaster, and embedding either verbatim is the boundary this bestiary has refused all along.
// These come from the 4418 CC-BY/OGL creatures we do hold, which is also the better source for the job: a
// guideline says what a designer aimed at, the corpus says what creatures at that tier ARE.
//
// EACH SERIES IS NON-DECREASING, by isotonic regression (pool adjacent violators). Raw medians wobble on
// small samples — 5e's CR 24 measured lower HP than CR 23 — and a target table that dips would tell a DM a
// harder creature is frailer.

export interface TierRow {
  /** CR for D&D, level for Pathfinder. Fractional CRs are their numeric value (¼ → 0.25). */
  tier: number;
  ac: number;
  hp: number;
  /** Median attack bonus across the tier's creatures. 0 where the tier's creatures carry no to-hit. */
  attack: number;
  /** How many creatures this row was measured from — so a thin tier is visible rather than implied. */
  sample: number;
}

/** Measured from 2827 creatures across 31 tiers of `dnd5e-2014`. */
export const DND5E_TIERS: TierRow[] = [
  { tier: 0, ac: 11, hp: 4, attack: 2, sample: 87 },
  { tier: 0.125, ac: 12, hp: 9, attack: 3, sample: 74 },
  { tier: 0.25, ac: 12, hp: 14, attack: 4, sample: 178 },
  { tier: 0.5, ac: 13, hp: 22, attack: 4, sample: 210 },
  { tier: 1, ac: 13, hp: 34, attack: 4, sample: 203 },
  { tier: 2, ac: 13, hp: 47, attack: 5, sample: 287 },
  { tier: 3, ac: 14, hp: 65, attack: 5, sample: 246 },
  { tier: 4, ac: 14, hp: 81, attack: 5, sample: 202 },
  { tier: 5, ac: 15, hp: 97, attack: 7, sample: 250 },
  { tier: 6, ac: 15, hp: 112, attack: 7, sample: 184 },
  { tier: 7, ac: 15, hp: 126, attack: 7, sample: 136 },
  { tier: 8, ac: 16, hp: 133, attack: 8, sample: 121 },
  { tier: 9, ac: 16, hp: 149, attack: 8, sample: 119 },
  { tier: 10, ac: 17, hp: 153, attack: 9, sample: 85 },
  { tier: 11, ac: 17, hp: 172, attack: 9, sample: 80 },
  { tier: 12, ac: 17, hp: 180, attack: 9, sample: 61 },
  { tier: 13, ac: 17, hp: 185, attack: 10, sample: 52 },
  { tier: 14, ac: 18, hp: 192, attack: 11, sample: 32 },
  { tier: 15, ac: 18, hp: 212, attack: 11, sample: 33 },
  { tier: 16, ac: 19, hp: 232, attack: 12, sample: 35 },
  { tier: 17, ac: 19, hp: 253, attack: 13, sample: 28 },
  { tier: 18, ac: 19, hp: 270, attack: 13, sample: 15 },
  { tier: 19, ac: 19, hp: 275, attack: 13, sample: 18 },
  { tier: 20, ac: 19, hp: 321, attack: 14, sample: 14 },
  { tier: 21, ac: 20, hp: 321, attack: 15, sample: 22 },
  { tier: 22, ac: 21, hp: 426, attack: 15, sample: 12 },
  { tier: 23, ac: 21, hp: 446, attack: 15, sample: 15 },
  { tier: 24, ac: 21, hp: 446, attack: 15, sample: 12 },
  { tier: 25, ac: 21, hp: 446, attack: 17, sample: 7 },
  { tier: 26, ac: 22, hp: 546, attack: 18, sample: 5 },
  { tier: 30, ac: 25, hp: 678, attack: 19, sample: 4 },
];

/** Measured from 1591 creatures across 25 tiers of `pathfinder2e`. */
export const PF2_TIERS: TierRow[] = [
  { tier: -1, ac: 15, hp: 8, attack: 7, sample: 37 },
  { tier: 0, ac: 16, hp: 15, attack: 7, sample: 36 },
  { tier: 1, ac: 16, hp: 20, attack: 8, sample: 153 },
  { tier: 2, ac: 17, hp: 30, attack: 10, sample: 151 },
  { tier: 3, ac: 18, hp: 45, attack: 11, sample: 115 },
  { tier: 4, ac: 21, hp: 60, attack: 13, sample: 109 },
  { tier: 5, ac: 21, hp: 75, attack: 15, sample: 103 },
  { tier: 6, ac: 24, hp: 99, attack: 17, sample: 91 },
  { tier: 7, ac: 25, hp: 115, attack: 18, sample: 99 },
  { tier: 8, ac: 27, hp: 135, attack: 20, sample: 91 },
  { tier: 9, ac: 28, hp: 155, attack: 21, sample: 85 },
  { tier: 10, ac: 30, hp: 175, attack: 23, sample: 81 },
  { tier: 11, ac: 31, hp: 195, attack: 24, sample: 63 },
  { tier: 12, ac: 33, hp: 215, attack: 25, sample: 58 },
  { tier: 13, ac: 34, hp: 245, attack: 27, sample: 58 },
  { tier: 14, ac: 36, hp: 252, attack: 29, sample: 53 },
  { tier: 15, ac: 37, hp: 285, attack: 30, sample: 42 },
  { tier: 16, ac: 39, hp: 295, attack: 32, sample: 33 },
  { tier: 17, ac: 40, hp: 330, attack: 33, sample: 29 },
  { tier: 18, ac: 42, hp: 340, attack: 35, sample: 34 },
  { tier: 19, ac: 43, hp: 370, attack: 36, sample: 23 },
  { tier: 20, ac: 45, hp: 375, attack: 38, sample: 29 },
  { tier: 21, ac: 46, hp: 420, attack: 39, sample: 8 },
  { tier: 22, ac: 47, hp: 485, attack: 40, sample: 5 },
  { tier: 23, ac: 49, hp: 485, attack: 41, sample: 5 },
];
