// lib/cad/delivery/traversepc-bundle.ts
//
// One-click "Traverse PC bundle" — zips every artifact a
// surveyor needs to continue a drawing in Traverse PC:
//
//   * points-pnezd.csv — headerless P,N,E,Z,D coordinate file
//                        (import as ASCII, field order PNEZD)
//   * drawing.dxf      — full linework for DXF import
//   * drawing.xml      — LandXML with true curves (best fidelity;
//                        carries arcs as real radius/rotation
//                        curves rather than faceted chords)
//   * IMPORT-STEPS.txt — short how-to so the file is self-explaining
//
// Giving all three lets the surveyor pick the import path that
// fits their workflow: LandXML for full COGO (points + curves),
// DXF for CAD linework, or the PNEZD file for raw points +
// Field-to-Finish.

import JSZip from 'jszip';

import type { DrawingDocument } from '../types';
import type { AnnotationBase } from '../labels/annotation-types';
import { buildPnezdAscii } from '../persistence/export-csv';
import { exportToDxf } from './dxf-writer';
import { exportToLandXML } from './landxml-writer';

export interface TraversePcBundleInputs {
  doc: DrawingDocument;
  /** Annotations to bake into the DXF as TEXT entities. */
  annotations?: Record<string, AnnotationBase>;
}

export interface TraversePcBundle {
  files: Record<string, string>;
  filename: string;
  pointCount: number;
}

export function buildTraversePcBundle(
  inputs: TraversePcBundleInputs
): TraversePcBundle {
  const { doc, annotations } = inputs;
  const pnezd = buildPnezdAscii(doc);
  const files: Record<string, string> = {
    'points-pnezd.csv': pnezd.text,
    'drawing.dxf': exportToDxf(doc, { annotations }),
    'drawing.xml': exportToLandXML(doc),
    'IMPORT-STEPS.txt': renderSteps(),
  };
  return {
    files,
    filename: `${kebabCase(doc.name) || 'drawing'}-traversepc.zip`,
    pointCount: pnezd.rowCount,
  };
}

export async function downloadTraversePcBundle(
  inputs: TraversePcBundleInputs
): Promise<{ filename: string; byteSize: number; pointCount: number }> {
  if (typeof globalThis.document === 'undefined') {
    throw new Error('downloadTraversePcBundle can only run in the browser.');
  }
  const bundle = buildTraversePcBundle(inputs);
  const zip = new JSZip();
  for (const [name, content] of Object.entries(bundle.files)) {
    zip.file(name, content);
  }
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = Object.assign(globalThis.document.createElement('a'), {
    href: url,
    download: bundle.filename,
  });
  a.click();
  URL.revokeObjectURL(url);
  return {
    filename: bundle.filename,
    byteSize: blob.size,
    pointCount: bundle.pointCount,
  };
}

function renderSteps(): string {
  return [
    'IMPORTING THIS DRAWING INTO TRAVERSE PC',
    '',
    'This bundle contains three interchangeable copies of the drawing.',
    'Pick whichever import path suits your workflow.',
    '',
    'OPTION A — LandXML (best fidelity: points + curves as true arcs)',
    '  1. File > Import > LandXML',
    '  2. Select drawing.xml',
    '  3. Points come in numbered with codes/descriptions; linework',
    '     imports as plan features, with arcs preserved as real curves',
    '     (radius + rotation), not short chord segments.',
    '',
    'OPTION B — DXF (CAD linework)',
    '  1. File > Import > DXF/DWG',
    '  2. Select drawing.dxf',
    '  3. Geometry lands on matching layers at the same coordinates.',
    '',
    'OPTION C — PNEZD ASCII (raw points + Field-to-Finish)',
    '  1. File > Import > ASCII Coordinate File',
    '  2. Select points-pnezd.csv',
    '  3. Field order = PNEZD, Delimiter = Comma, Header rows to skip = 0',
    '     (the file is intentionally headerless).',
    '  4. Optionally run Field-to-Finish to rebuild linework from the',
    '     point codes (the code leads each point description).',
    '',
    'COORDINATE SYSTEM',
    '  All coordinates are NAD83 Texas State Plane Central Zone 4203,',
    '  U.S. Survey Feet (EPSG:2277). Verify one known point after import.',
    '',
    'Generated by STARR Surveying.',
    '',
  ].join('\n');
}

function kebabCase(input: string): string {
  return input
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
