// app/AndrewAsh/contract/[token]/ContractBody.tsx — rendering the agreement.
//
// ── A DELIBERATELY TINY MARKDOWN RENDERER ───────────────────────────────────────────────────────
//
// The contract body is generated by `lib/voice/contracts.ts` from a template WE wrote. It contains
// exactly four constructs — `#` headings, `**bold**`, `---` rules and paragraphs — and nothing else,
// ever. Pulling in a markdown library to render four constructs would mean shipping a parser, and
// then needing an HTML sanitiser behind it, on a page whose entire purpose is to display a legal
// document faithfully.
//
// Rendering by hand also means the output cannot contain anything the renderer does not explicitly
// build. There is no `dangerouslySetInnerHTML` anywhere in this file — every node is a React element,
// so no input can become markup. For a page where the text IS the product, that is the right trade.
//
// If Andrew ever edits a body by hand and types raw HTML, it renders as literal text. That is
// correct: a contract that silently interprets angle brackets is a contract nobody can trust.

interface Props {
  markdown: string;
}

export default function ContractBody({ markdown }: Props): React.ReactElement {
  const blocks = String(markdown ?? '').split(/\n{2,}/);

  return (
    <article className="vaContract">
      {blocks.map((raw, i) => {
        const block = raw.trim();
        if (!block) return null;

        if (block === '---') return <hr key={i} className="vaRule" style={{ margin: '28px 0' }} />;

        const heading = /^(#{1,4})\s+(.*)$/.exec(block);
        if (heading) {
          const level = heading[1].length;
          // The document's own `# Title` is an h2 on the page — the page already has an h1, and two
          // h1s is a heading outline no screen reader can make sense of.
          const Tag = (level === 1 ? 'h2' : level === 2 ? 'h3' : 'h4') as 'h2';
          return (
            <Tag key={i} className={level === 1 ? 'vaContractTitle' : 'vaContractHeading'}>
              {inline(heading[2])}
            </Tag>
          );
        }

        return (
          <p key={i} className="vaContractPara">
            {inline(block)}
          </p>
        );
      })}
    </article>
  );
}

/** `**bold**` only, and newlines preserved as line breaks. */
function inline(text: string): React.ReactNode[] {
  return text.split('\n').flatMap((line, lineIndex, lines) => {
    const parts: React.ReactNode[] = line
      .split(/(\*\*[^*]+\*\*)/g)
      .filter((p) => p !== '')
      .map((part, i) =>
        part.startsWith('**') && part.endsWith('**') ? (
          <strong key={`${lineIndex}-${i}`}>{part.slice(2, -2)}</strong>
        ) : (
          <span key={`${lineIndex}-${i}`}>{part}</span>
        ),
      );
    if (lineIndex < lines.length - 1) parts.push(<br key={`br-${lineIndex}`} />);
    return parts;
  });
}
