// worker/src/exports/rw5-exporter.ts — Phase 11 Module N
// Carlson RW5 survey data export.
// RW5 is a space-delimited text format used by Carlson Survey and SurvCE.
//
// Spec §11.15.1 — Carlson RW5 Export

/**
 * Export reconciled boundary corners as Carlson RW5 format.
 *
 * RW5 Format:
 *   JB,NMprojectName,DTdate,TMtime
 *   MO,AD0,UN2,SF1.00000000,EC0,EO0.0,AU0
 *   SP,PNpointNum,N northing,E easting,ELelev,--description
 */
export function exportToRW5(
  corners: {
    northing: number;
    easting: number;
    elevation?: number;
    description?: string;
  }[],
  projectName: string,
): string {
  const lines: string[] = [];
  const now = new Date();

  // Header — Job info
  lines.push(
    `JB,NM${projectName},DT${now.toLocaleDateString('en-US')},TM${now.toLocaleTimeString('en-US')}`,
  );

  // Mode setup
  // AD0 = no atmospheric correction
  // UN2 = US Survey Feet
  // SF1.00000000 = scale factor 1.0
  // EC0 = no earth curvature correction
  // EO0.0 = no elevation offset
  // AU0 = no auto-increment
  lines.push('MO,AD0,UN2,SF1.00000000,EC0,EO0.0,AU0');

  // Coordinate system note
  lines.push('--NAD83 Texas Central Zone (4203), US Survey Feet');
  lines.push(`--Generated by STARR RECON Pipeline`);
  lines.push(`--${now.toISOString()}`);

  // Points
  for (let i = 0; i < corners.length; i++) {
    const c = corners[i];
    const pn = i + 1;
    const desc = c.description || `BNDRY${pn}`;
    const elev = c.elevation || 0;

    lines.push(
      `SP,PN${pn},N ${c.northing.toFixed(6)},E ${c.easting.toFixed(6)},EL${elev.toFixed(4)},--${desc}`,
    );
  }

  // Close by repeating first point as last (boundary closure)
  if (corners.length > 0) {
    const first = corners[0];
    lines.push(
      `SP,PN${corners.length + 1},N ${first.northing.toFixed(6)},E ${first.easting.toFixed(6)},EL${(first.elevation || 0).toFixed(4)},--CLOSURE`,
    );
  }

  return lines.join('\r\n');
}
