// worker/src/infra/site-health-monitor.ts — Site Health Monitor
// Probes all county CAD portals, clerk systems, and external data sources to
// detect when HTML structure or selectors have changed.  Broadcasts alerts
// via WebSocket and exposes REST endpoints for the admin dashboard.
//
// Core capabilities:
//   1. Periodic health checks (configurable interval, default 30 min)
//   2. Selector validation — checks that expected DOM elements exist
//   3. Per-vendor and per-county health status
//   4. WebSocket notification when a site goes down or selectors drift
//   5. "Check All" endpoint to run every probe at once
//   6. Screenshot capture on failure for diagnostics

import type { Browser, Page } from 'playwright';
import { acquireBrowser } from '../lib/browser-factory.js';
import { getCADConfig, listRegisteredCounties, type CADConfig } from '../services/cad-registry.js';

// ── Types ───────────────────────────────────────────────────────────────────

export type SiteStatus = 'healthy' | 'degraded' | 'down' | 'unchecked';
export type AlertSeverity = 'info' | 'warning' | 'error';

export interface SelectorProbe {
  /** CSS selector to look for */
  selector: string;
  /** Human-readable description */
  label: string;
  /** Is this selector required for the adapter to work? */
  required: boolean;
}

export interface SiteHealthResult {
  /** Site identifier (e.g. "hcad", "bell-bis", "kofile-bell") */
  siteId: string;
  /** Display name */
  name: string;
  /** Vendor type */
  vendor: string;
  /** URL that was probed */
  url: string;
  /** Overall status */
  status: SiteStatus;
  /** When this check ran */
  checkedAt: string;
  /** How long the probe took (ms) */
  latencyMs: number;
  /** Individual selector results */
  selectors: SelectorCheckResult[];
  /** Alerts generated by this check */
  alerts: SiteAlert[];
  /** Screenshot path if captured (only on failure) */
  screenshotPath?: string;
  /** Error message if the probe itself failed */
  error?: string;
}

export interface SelectorCheckResult {
  selector: string;
  label: string;
  required: boolean;
  found: boolean;
  /** Number of elements matched */
  count: number;
}

export interface SiteAlert {
  type: 'selector_missing' | 'selector_changed' | 'site_unreachable' | 'slow_response' | 'cloudflare_blocked';
  severity: AlertSeverity;
  message: string;
  siteId: string;
  timestamp: string;
}

export interface HealthSummary {
  totalSites: number;
  healthy: number;
  degraded: number;
  down: number;
  unchecked: number;
  lastFullCheck: string | null;
  alerts: SiteAlert[];
  sites: SiteHealthResult[];
}

// ── Vendor Probe Definitions ────────────────────────────────────────────────
// Each vendor type has a set of CSS selectors that MUST be present on their
// search page for the adapter to function.  When a selector goes missing,
// the adapter is broken.

const VENDOR_PROBES: Record<string, SelectorProbe[]> = {
  hcad: [
    { selector: 'input#PROPERTYADDRESS, input[value="PROPERTYADDRESS"]', label: 'Address radio button', required: true },
    { selector: 'input#OWNERNAME, input[value="OWNERNAME"]', label: 'Owner radio button', required: true },
    { selector: 'input.inputSearch, input[type="search"].searchTerm', label: 'Search input field', required: true },
    { selector: 'button.btn-primary.buttonFontsize', label: 'Search submit button', required: true },
    { selector: 'input#ACCOUNTNUMBER, input[value="ACCOUNTNUMBER"]', label: 'Account number radio', required: false },
  ],
  tad: [
    { selector: 'select#search-type, select[name="searchType"]', label: 'Search type dropdown', required: true },
    { selector: 'input#query, input[name="query"]', label: 'Search input field', required: true },
    { selector: 'button.btn-tad-light-blue[type="submit"], button[type="submit"]', label: 'Submit button', required: true },
    { selector: 'input#residential[value="R"]', label: 'Residential checkbox', required: false },
    { selector: 'form.property-search-form', label: 'Property search form', required: true },
  ],
  bis: [
    { selector: '#home-page-tabs, .nav-pills', label: 'Search tabs', required: false },
    { selector: 'input#OwnerName, input[name="OwnerName"]', label: 'Owner name field', required: true },
    { selector: 'input#StreetNumber, input[name="StreetNumber"]', label: 'Street number field', required: true },
    { selector: 'input#StreetName, input[name="StreetName"]', label: 'Street name field', required: true },
    { selector: 'input#propertySearchOptions_searchText', label: 'Quick search field (legacy)', required: false },
    { selector: 'select#PropertyType, select[name="PropertyType"]', label: 'Property type dropdown', required: false },
  ],
  trueautomation: [
    { selector: 'input#propertySearchOptions_searchText, input[name*="searchText"]', label: 'Quick search field', required: false },
    { selector: 'input#propertySearchOptions_ownerName, input[name*="ownerName"]', label: 'Owner name field', required: true },
    { selector: 'input#propertySearchOptions_streetNumber, input[name*="streetNumber"]', label: 'Street number field', required: true },
    { selector: 'input#propertySearchOptions_streetName, input[name*="streetName"]', label: 'Street name field', required: true },
    { selector: 'input#propertySearchOptions_search, input[value="Search"]', label: 'Search button', required: true },
  ],
  tyler: [
    { selector: 'input[name*="Address"], input[name*="address"], input#txtAddress', label: 'Address field', required: true },
    { selector: 'input[name*="Owner"], input[name*="owner"], input#txtOwnerName', label: 'Owner name field', required: true },
    { selector: 'button[type="submit"], input[type="submit"], input[value="Search"]', label: 'Submit button', required: true },
  ],
  kofile: [
    { selector: 'input[type="search"], input[type="text"][placeholder*="Search"], input.form-control', label: 'Search input', required: true },
    { selector: 'button[type="submit"], button.btn-primary, a.btn-primary', label: 'Search button', required: true },
  ],
  texasfile: [
    { selector: 'input[name*="search"], input[type="text"]', label: 'Search input', required: true },
    { selector: 'button[type="submit"], input[type="submit"]', label: 'Submit button', required: true },
  ],
};

// ── SiteHealthMonitor ───────────────────────────────────────────────────────

export class SiteHealthMonitor {
  private results: Map<string, SiteHealthResult> = new Map();
  private alerts: SiteAlert[] = [];
  private lastFullCheck: string | null = null;
  private checkInterval: ReturnType<typeof setInterval> | null = null;
  private browser: Browser | null = null;
  /** Callback invoked whenever a health alert is generated */
  private onAlert?: (alert: SiteAlert) => void;
  /** When set, only check sites whose FIPS code is in this set */
  private activeCountyFips: Set<string> | null = null;

  constructor(options?: { onAlert?: (alert: SiteAlert) => void; countyFips?: string[] }) {
    this.onAlert = options?.onAlert;
    if (options?.countyFips?.length) {
      this.activeCountyFips = new Set(options.countyFips);
    }
  }

  /** Restrict health checks to specific counties by FIPS code. */
  setActiveCounties(fips: string[]): void {
    this.activeCountyFips = fips.length > 0 ? new Set(fips) : null;
  }

  // ── Lifecycle ───────────────────────────────────────────────────────────

  /**
   * Start periodic health checks.
   * @param intervalMs — check interval in ms (default: 30 minutes)
   */
  startPeriodicChecks(intervalMs = 30 * 60 * 1000): void {
    if (this.checkInterval) return;
    console.log(`[SiteHealth] Starting periodic checks every ${intervalMs / 60000} min`);
    // Run the first check after a short delay (don't block startup)
    setTimeout(() => this.checkAll().catch(console.error), 10_000);
    this.checkInterval = setInterval(() => {
      this.checkAll().catch(console.error);
    }, intervalMs);
  }

  stopPeriodicChecks(): void {
    if (this.checkInterval) {
      clearInterval(this.checkInterval);
      this.checkInterval = null;
    }
  }

  // ── Check All Sites ────────────────────────────────────────────────────

  /**
   * Run health checks against all registered CAD portals, clerk systems, and
   * external data sources.  Returns a full summary.
   */
  async checkAll(): Promise<HealthSummary> {
    console.log('[SiteHealth] Running full health check...');
    const start = Date.now();

    await this.ensureBrowser();

    // Build the list of sites to check
    const checks = this.buildCheckList();

    // Run checks with concurrency limit (max 3 browsers at once)
    const CONCURRENCY = 3;
    for (let i = 0; i < checks.length; i += CONCURRENCY) {
      const batch = checks.slice(i, i + CONCURRENCY);
      await Promise.all(batch.map(c => this.checkSite(c)));
    }

    await this.destroyBrowser();

    this.lastFullCheck = new Date().toISOString();
    const elapsed = Date.now() - start;
    console.log(`[SiteHealth] Full check complete in ${(elapsed / 1000).toFixed(1)}s — ${checks.length} sites`);

    return this.getSummary();
  }

  /**
   * Check a single site by its siteId.
   */
  async checkOne(siteId: string): Promise<SiteHealthResult | null> {
    const checks = this.buildCheckList();
    const check = checks.find(c => c.siteId === siteId);
    if (!check) return null;

    await this.ensureBrowser();
    await this.checkSite(check);
    await this.destroyBrowser();

    return this.results.get(siteId) ?? null;
  }

  /**
   * Check all sites for a specific vendor.
   */
  async checkVendor(vendor: string): Promise<SiteHealthResult[]> {
    const checks = this.buildCheckList().filter(c => c.vendor === vendor);
    if (checks.length === 0) return [];

    await this.ensureBrowser();
    for (const check of checks) {
      await this.checkSite(check);
    }
    await this.destroyBrowser();

    return checks.map(c => this.results.get(c.siteId)!).filter(Boolean);
  }

  // ── Summary ──────────────────────────────────────────────────────────────

  getSummary(): HealthSummary {
    const sites = Array.from(this.results.values());
    return {
      totalSites: sites.length,
      healthy:   sites.filter(s => s.status === 'healthy').length,
      degraded:  sites.filter(s => s.status === 'degraded').length,
      down:      sites.filter(s => s.status === 'down').length,
      unchecked: sites.filter(s => s.status === 'unchecked').length,
      lastFullCheck: this.lastFullCheck,
      alerts: this.alerts.slice(-100), // last 100 alerts
      sites,
    };
  }

  getAlerts(since?: string): SiteAlert[] {
    if (!since) return this.alerts.slice(-100);
    return this.alerts.filter(a => a.timestamp > since);
  }

  clearAlerts(): void {
    this.alerts = [];
  }

  // ── Private: build check list ─────────────────────────────────────────

  private buildCheckList(): Array<{
    siteId: string;
    name: string;
    vendor: string;
    url: string;
    probes: SelectorProbe[];
  }> {
    const checks: Array<{
      siteId: string;
      name: string;
      vendor: string;
      url: string;
      probes: SelectorProbe[];
    }> = [];

    // CAD sites from registry — filtered to active counties when set
    const counties = listRegisteredCounties();
    const seenUrls = new Set<string>();

    for (const { fips, config } of counties) {
      // Skip counties not in the active set (when a filter is configured)
      if (this.activeCountyFips && !this.activeCountyFips.has(fips)) continue;
      if (seenUrls.has(config.searchUrl)) continue;
      seenUrls.add(config.searchUrl);

      const probes = VENDOR_PROBES[config.vendor] ?? [];
      if (probes.length === 0) continue;

      checks.push({
        siteId: `cad-${fips}-${config.vendor}`,
        name: config.name,
        vendor: config.vendor,
        url: config.searchUrl,
        probes,
      });
    }

    // Clerk systems — only include Bell County clerk when Bell is active (or no filter)
    const includeBell = !this.activeCountyFips || this.activeCountyFips.has('48027');
    if (includeBell) {
      checks.push({
        siteId: 'clerk-kofile-bell',
        name: 'Kofile — Bell County',
        vendor: 'kofile',
        url: 'https://bell.tx.publicsearch.us/',
        probes: VENDOR_PROBES.kofile ?? [],
      });
    }

    // TexasFile is statewide — always include
    checks.push({
      siteId: 'clerk-texasfile',
      name: 'TexasFile (statewide)',
      vendor: 'texasfile',
      url: 'https://www.texasfile.com/',
      probes: VENDOR_PROBES.texasfile ?? [],
    });

    return checks;
  }

  // ── Private: probe a single site ──────────────────────────────────────

  private async checkSite(check: {
    siteId: string;
    name: string;
    vendor: string;
    url: string;
    probes: SelectorProbe[];
  }): Promise<void> {
    const start = Date.now();
    const result: SiteHealthResult = {
      siteId: check.siteId,
      name: check.name,
      vendor: check.vendor,
      url: check.url,
      status: 'unchecked',
      checkedAt: new Date().toISOString(),
      latencyMs: 0,
      selectors: [],
      alerts: [],
    };

    let page: Page | null = null;
    try {
      page = await this.browser!.newPage();

      // Navigate with timeout
      const response = await page.goto(check.url, {
        waitUntil: 'domcontentloaded',
        timeout: 30000,
      });

      // Check for Cloudflare challenge
      const pageContent = await page.content();
      if (pageContent.includes('cf-challenge') || pageContent.includes('Just a moment')) {
        result.status = 'degraded';
        const alert = this.createAlert(
          'cloudflare_blocked',
          'warning',
          `${check.name} is behind Cloudflare challenge page`,
          check.siteId,
        );
        result.alerts.push(alert);
      }

      // Check HTTP status
      if (response && response.status() >= 400) {
        result.status = 'down';
        result.error = `HTTP ${response.status()}`;
        const alert = this.createAlert(
          'site_unreachable',
          'error',
          `${check.name} returned HTTP ${response.status()}`,
          check.siteId,
        );
        result.alerts.push(alert);
      }

      // Wait for page to settle (SPAs need extra time)
      await page.waitForTimeout(2000);

      // Probe each selector
      let requiredMissing = 0;
      let optionalMissing = 0;

      for (const probe of check.probes) {
        const elements = await page.$$(probe.selector);
        const found = elements.length > 0;
        result.selectors.push({
          selector: probe.selector,
          label: probe.label,
          required: probe.required,
          found,
          count: elements.length,
        });

        if (!found) {
          if (probe.required) {
            requiredMissing++;
            const alert = this.createAlert(
              'selector_missing',
              'error',
              `${check.name}: required selector "${probe.label}" not found (${probe.selector})`,
              check.siteId,
            );
            result.alerts.push(alert);
          } else {
            optionalMissing++;
          }
        }
      }

      // Determine overall status
      if (result.status !== 'down') {
        if (requiredMissing > 0) {
          result.status = 'down';
        } else if (optionalMissing > 0 || result.status === 'degraded') {
          result.status = 'degraded';
        } else {
          result.status = 'healthy';
        }
      }

      // Check for slow response
      const latency = Date.now() - start;
      if (latency > 15000) {
        const alert = this.createAlert(
          'slow_response',
          'warning',
          `${check.name} took ${(latency / 1000).toFixed(1)}s to load`,
          check.siteId,
        );
        result.alerts.push(alert);
      }

      // Capture screenshot on failure
      if (result.status === 'down' || result.status === 'degraded') {
        try {
          const screenshotDir = '/tmp/site-health';
          const fs = await import('fs');
          if (!fs.existsSync(screenshotDir)) {
            fs.mkdirSync(screenshotDir, { recursive: true });
          }
          const screenshotPath = `${screenshotDir}/${check.siteId}_${Date.now()}.png`;
          await page.screenshot({ path: screenshotPath, fullPage: true });
          result.screenshotPath = screenshotPath;
        } catch {
          // Screenshot failure is non-fatal
        }
      }

    } catch (err: any) {
      result.status = 'down';
      result.error = err.message;
      const alert = this.createAlert(
        'site_unreachable',
        'error',
        `${check.name} probe failed: ${err.message}`,
        check.siteId,
      );
      result.alerts.push(alert);
    } finally {
      if (page) {
        await page.close().catch(() => {});
      }
    }

    result.latencyMs = Date.now() - start;
    this.results.set(check.siteId, result);

    // Log result
    const icon = result.status === 'healthy' ? '✓' : result.status === 'degraded' ? '⚠' : '✗';
    console.log(
      `[SiteHealth] ${icon} ${check.name} — ${result.status} (${result.latencyMs}ms)`,
    );
  }

  // ── Private: alert creation ───────────────────────────────────────────

  private createAlert(
    type: SiteAlert['type'],
    severity: AlertSeverity,
    message: string,
    siteId: string,
  ): SiteAlert {
    const alert: SiteAlert = {
      type,
      severity,
      message,
      siteId,
      timestamp: new Date().toISOString(),
    };
    this.alerts.push(alert);
    // Keep only last 500 alerts
    if (this.alerts.length > 500) {
      this.alerts = this.alerts.slice(-500);
    }
    // Fire callback
    if (this.onAlert) {
      this.onAlert(alert);
    }
    return alert;
  }

  // ── Private: browser lifecycle ────────────────────────────────────────

  private async ensureBrowser(): Promise<void> {
    if (!this.browser) {
      this.browser = await acquireBrowser({
        launchOptions: {
          headless: true,
          args: ['--no-sandbox', '--disable-setuid-sandbox'],
        },
      });
    }
  }

  private async destroyBrowser(): Promise<void> {
    if (this.browser) {
      await this.browser.close().catch(() => {});
      this.browser = null;
    }
  }
}
