// app/api/voice/checklist/route.ts — ticking off a step in the "Start here" checklists.
//
// Progress lives on the USER row, not in localStorage. The business checklist spans weeks — open a
// bank account, get an EIN, file a DBA with the county, set up quarterly estimated taxes — and a
// per-browser store resets the moment Andrew opens it on his phone instead of his laptop, which is
// exactly the point at which a weeks-long list stops getting used.
//
// ── LAST WRITE WINS, AND THAT IS FINE HERE ──────────────────────────────────────────────────────
//
// The whole map is read, patched and written back. With two accounts that is a lost-update race in
// principle: both tick a box, one write lands second and drops the other's tick. The practical stakes
// are one checkbox needing a second click, and the alternative (a row per item, or a JSONB path
// update) is more machinery than the problem deserves. Naming it here so nobody later mistakes it for
// an oversight.

import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';
import { getVoiceSession } from '@/lib/voice/auth';

export async function POST(request: Request): Promise<NextResponse> {
  const session = getVoiceSession();
  if (!session) return NextResponse.json({ error: 'Not signed in.' }, { status: 401 });

  let body: { key?: string; done?: boolean };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Bad request.' }, { status: 400 });
  }

  const key = String(body.key ?? '').slice(0, 120);
  // The key is a section id plus an index, generated by the page. Constrain the shape so a caller
  // cannot use this endpoint to write arbitrary keys into a JSONB column indefinitely.
  if (!/^[a-z0-9-]+:\d{1,3}$/.test(key)) {
    return NextResponse.json({ error: 'Bad key.' }, { status: 400 });
  }

  const { data: user } = await supabaseAdmin
    .from('va_users')
    .select('checklist_progress')
    .eq('id', session.userId)
    .maybeSingle();

  const progress: Record<string, boolean> =
    user?.checklist_progress && typeof user.checklist_progress === 'object' ? { ...user.checklist_progress } : {};

  if (body.done) progress[key] = true;
  // Unticking DELETES rather than storing false, so the map only ever holds what is done and cannot
  // grow without bound as items are toggled.
  else delete progress[key];

  const { error } = await supabaseAdmin
    .from('va_users')
    .update({ checklist_progress: progress })
    .eq('id', session.userId);

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ ok: true, progress });
}
