-- seeds/000_baseline_tables.sql
--
-- Schema reconstruction for tables that existed ONLY in the live database.
-- GENERATED by scripts/dump-missing-schema.mjs — do not hand-edit; regenerate.
-- Verified column-for-column against production by scripts/verify-baseline-schema.mjs.
--
-- Background: docs/planning/PLATFORM_AUDIT_AND_LAUNCH_QUESTIONS_2026-07-29.md §1.1.
-- 78 tables the app queries every day — including `jobs`, the central business entity —
-- had no CREATE statement anywhere in seeds/. They were only ever ALTERed (seeds
-- 280/304/306/452), so a fresh database could not be built from this repo, there was no
-- way to stand up staging, and every schema change was an undocumented dashboard click.
--
-- Every statement is idempotent, so applying this to the existing production database is
-- a no-op. Guarded by __tests__/schema-coverage.test.ts.
--
-- RUNS FIRST. 29 later seeds (from 001_config.sql onward) ALTER these tables, so they
-- must exist before any of them apply. Foreign keys are NOT here — they point at
-- tables created by later seeds and live in seeds/499_baseline_fks.sql.

-- ── acc_course_enrollments ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.acc_course_enrollments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  course_id text NOT NULL,
  enrolled_by text NOT NULL,
  enrolled_at timestamp with time zone DEFAULT now(),
  CONSTRAINT acc_course_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT acc_course_enrollments_user_email_course_id_key UNIQUE (user_email, course_id)
);

-- ── activity_log ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.activity_log (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  action_type text NOT NULL,
  entity_type text,
  entity_id text,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_log_pkey PRIMARY KEY (id)
);

-- ── admin_discussion_threads ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.admin_discussion_threads (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  title text NOT NULL,
  description text,
  thread_type text DEFAULT 'general'::text NOT NULL,
  escalation_level text DEFAULT 'low'::text NOT NULL,
  page_path text,
  page_title text,
  content_type text,
  content_id uuid,
  status text DEFAULT 'open'::text NOT NULL,
  resolved_at timestamp with time zone,
  resolved_by text,
  resolution_notes text,
  conversation_id uuid,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_discussion_threads_escalation_level_check CHECK ((escalation_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text]))),
  CONSTRAINT admin_discussion_threads_status_check CHECK ((status = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text, 'wont_fix'::text]))),
  CONSTRAINT admin_discussion_threads_thread_type_check CHECK ((thread_type = ANY (ARRAY['factual_error'::text, 'improvement'::text, 'bug'::text, 'content_review'::text, 'compliance'::text, 'general'::text]))),
  CONSTRAINT admin_discussion_threads_pkey PRIMARY KEY (id)
);

-- ── assignments ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.assignments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  title text NOT NULL,
  description text,
  assignment_type text DEFAULT 'task'::text NOT NULL,
  priority text DEFAULT 'normal'::text,
  status text DEFAULT 'pending'::text,
  assigned_to text NOT NULL,
  assigned_by text NOT NULL,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  job_id uuid,
  module_id uuid,
  lesson_id uuid,
  notes text,
  completion_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT assignments_pkey PRIMARY KEY (id)
);

-- ── badges ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.badges (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  badge_key text NOT NULL,
  name text NOT NULL,
  description text,
  icon text DEFAULT '🏆'::text,
  category text NOT NULL,
  xp_reward integer DEFAULT 0,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT badges_category_check CHECK ((category = ANY (ARRAY['certification'::text, 'achievement'::text, 'milestone'::text, 'special'::text]))),
  CONSTRAINT badges_pkey PRIMARY KEY (id),
  CONSTRAINT badges_badge_key_key UNIQUE (badge_key)
);

-- ── balance_transactions ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.balance_transactions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  transaction_type text NOT NULL,
  amount numeric(12,2) NOT NULL,
  balance_before numeric(12,2) NOT NULL,
  balance_after numeric(12,2) NOT NULL,
  description text,
  reference_type text,
  reference_id uuid,
  status text DEFAULT 'completed'::text NOT NULL,
  processed_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT balance_transactions_pkey PRIMARY KEY (id)
);

-- ── credential_bonuses ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.credential_bonuses (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  credential_key text NOT NULL,
  label text NOT NULL,
  bonus_per_hour numeric(10,2) DEFAULT 0 NOT NULL,
  credential_type text DEFAULT 'external'::text,
  description text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credential_bonuses_pkey PRIMARY KEY (id),
  CONSTRAINT credential_bonuses_credential_key_key UNIQUE (credential_key)
);

-- ── credit_thresholds ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.credit_thresholds (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  threshold_name text NOT NULL,
  points_required integer NOT NULL,
  reward_type text NOT NULL,
  raise_amount numeric(10,2) DEFAULT 0,
  bonus_amount numeric(10,2) DEFAULT 0,
  credential_key text,
  description text,
  is_active boolean DEFAULT true,
  is_repeatable boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credit_thresholds_points_required_check CHECK ((points_required > 0)),
  CONSTRAINT credit_thresholds_reward_type_check CHECK ((reward_type = ANY (ARRAY['pay_raise'::text, 'one_time_bonus'::text, 'credential_unlock'::text]))),
  CONSTRAINT credit_thresholds_pkey PRIMARY KEY (id)
);

-- ── curriculum_milestones ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.curriculum_milestones (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  milestone_key text NOT NULL,
  title text NOT NULL,
  description text,
  milestone_type text NOT NULL,
  part_number integer,
  required_modules uuid[] DEFAULT '{}'::uuid[],
  required_count integer DEFAULT 0,
  icon text DEFAULT '🏆'::text,
  color text DEFAULT '#1D3095'::text,
  xp_reward integer DEFAULT 500,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT curriculum_milestones_milestone_type_check CHECK ((milestone_type = ANY (ARRAY['part_complete'::text, 'exam_ready'::text, 'certification'::text, 'special'::text]))),
  CONSTRAINT curriculum_milestones_pkey PRIMARY KEY (id),
  CONSTRAINT curriculum_milestones_milestone_key_key UNIQUE (milestone_key)
);

-- ── daily_time_logs ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.daily_time_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  log_date date NOT NULL,
  work_type text NOT NULL,
  hours numeric(5,2) NOT NULL,
  job_id uuid,
  job_name text,
  description text NOT NULL,
  notes text,
  status text DEFAULT 'pending'::text,
  approved_by text,
  approved_at timestamp with time zone,
  rejection_reason text,
  adjustment_note text,
  adjusted_hours numeric(5,2),
  base_rate numeric(10,2),
  role_bonus numeric(10,2),
  seniority_bonus numeric(10,2),
  credential_bonus numeric(10,2),
  effective_rate numeric(10,2),
  total_pay numeric(10,2),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  activity_tag_ids uuid[],
  CONSTRAINT daily_time_logs_hours_check CHECK (((hours > (0)::numeric) AND (hours <= (24)::numeric))),
  CONSTRAINT daily_time_logs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'disputed'::text, 'adjusted'::text]))),
  CONSTRAINT daily_time_logs_pkey PRIMARY KEY (id)
);

-- ── education_courses ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.education_courses (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  course_name text NOT NULL,
  institution text,
  course_type text NOT NULL,
  semester text,
  cost numeric(10,2) DEFAULT 0 NOT NULL,
  attempt_number integer DEFAULT 1 NOT NULL,
  passed boolean,
  grade text,
  company_pays_percent integer DEFAULT 100,
  company_pays_amount numeric(10,2) DEFAULT 0,
  employee_pays_amount numeric(10,2) DEFAULT 0,
  reimbursement_status text DEFAULT 'pending'::text,
  xp_earned integer DEFAULT 0,
  pay_raise_amount numeric(6,2) DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT education_courses_course_type_check CHECK ((course_type = ANY (ARRAY['college_surveying'::text, 'college_other'::text, 'certification_prep'::text, 'continuing_ed'::text, 'online_course'::text]))),
  CONSTRAINT education_courses_reimbursement_status_check CHECK ((reimbursement_status = ANY (ARRAY['pending'::text, 'approved'::text, 'paid'::text, 'denied'::text]))),
  CONSTRAINT education_courses_pkey PRIMARY KEY (id)
);

-- ── employee_certifications ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_certifications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  certification_type text NOT NULL,
  certification_name text NOT NULL,
  issued_date date,
  expiry_date date,
  license_number text,
  pay_bump_amount numeric(10,2) DEFAULT 0,
  pay_bump_percentage numeric(5,2) DEFAULT 0,
  verified boolean DEFAULT false,
  verified_by text,
  verified_at timestamp with time zone,
  document_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_certifications_pkey PRIMARY KEY (id)
);

-- ── employee_earned_credentials ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_earned_credentials (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  credential_key text NOT NULL,
  earned_date date DEFAULT CURRENT_DATE NOT NULL,
  verified boolean DEFAULT false,
  verified_by text,
  verified_at timestamp with time zone,
  expiry_date date,
  document_url text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  source text,
  CONSTRAINT employee_earned_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT employee_earned_credentials_user_email_credential_key_key UNIQUE (user_email, credential_key)
);

-- ── employee_learning_credits ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_learning_credits (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  credit_value_id uuid,
  entity_type text NOT NULL,
  entity_id uuid,
  entity_label text,
  points_earned integer DEFAULT 0 NOT NULL,
  earned_at timestamp with time zone DEFAULT now(),
  source_type text,
  source_id uuid,
  awarded_by text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_learning_credits_pkey PRIMARY KEY (id)
);

-- ── employee_profile_changes ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_profile_changes (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  change_type text NOT NULL,
  title text NOT NULL,
  description text,
  old_value text,
  new_value text,
  changed_by text NOT NULL,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_profile_changes_change_type_check CHECK ((change_type = ANY (ARRAY['role_change'::text, 'pay_raise'::text, 'credential_added'::text, 'credential_removed'::text, 'bonus_awarded'::text, 'profile_updated'::text, 'tier_change'::text, 'seniority_update'::text, 'note_added'::text, 'status_change'::text]))),
  CONSTRAINT employee_profile_changes_pkey PRIMARY KEY (id)
);

-- ── employee_profiles ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_profiles (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  user_name text,
  job_title text DEFAULT 'survey_technician'::text NOT NULL,
  hourly_rate numeric(10,2) DEFAULT 0 NOT NULL,
  salary_type text DEFAULT 'hourly'::text NOT NULL,
  annual_salary numeric(12,2),
  pay_frequency text DEFAULT 'biweekly'::text NOT NULL,
  hire_date date,
  available_balance numeric(12,2) DEFAULT 0 NOT NULL,
  total_earned numeric(12,2) DEFAULT 0 NOT NULL,
  total_withdrawn numeric(12,2) DEFAULT 0 NOT NULL,
  bank_name text,
  bank_routing_last4 text,
  bank_account_last4 text,
  bank_account_type text DEFAULT 'checking'::text,
  bank_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tier_key text,
  date_of_birth date,
  gender text,
  pronouns text,
  bio text,
  CONSTRAINT employee_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT employee_profiles_user_email_key UNIQUE (user_email)
);

-- ── employee_role_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_role_history (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  old_role text,
  new_role text NOT NULL,
  old_tier text,
  new_tier text,
  reason text NOT NULL,
  effective_date date DEFAULT CURRENT_DATE NOT NULL,
  changed_by text NOT NULL,
  pay_impact numeric(10,2) DEFAULT 0,
  payout_log_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_role_history_pkey PRIMARY KEY (id)
);

-- ── employee_threshold_achievements ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_threshold_achievements (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  threshold_id uuid NOT NULL,
  achieved_at timestamp with time zone DEFAULT now(),
  points_at_achievement integer NOT NULL,
  action_taken text,
  action_by text,
  action_at timestamp with time zone,
  payout_log_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_threshold_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT employee_threshold_achievements_user_email_threshold_id_key UNIQUE (user_email, threshold_id)
);

-- ── equipment_inventory ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.equipment_inventory (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  equipment_type text NOT NULL,
  brand text,
  model text,
  serial_number text,
  purchase_date date,
  last_calibration date,
  next_calibration_due date,
  status text DEFAULT 'available'::text,
  current_job_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  next_available_at timestamp with time zone,
  current_reservation_id uuid,
  item_kind text,
  category text,
  current_status text,
  qr_code_id text,
  acquired_at timestamp with time zone,
  acquired_cost_cents bigint,
  useful_life_months integer,
  placed_in_service_at date,
  last_calibrated_at timestamp with time zone,
  next_calibration_due_at timestamp with time zone,
  warranty_expires_at timestamp with time zone,
  service_contract_vendor text,
  last_serviced_at timestamp with time zone,
  unit text,
  quantity_on_hand integer,
  low_stock_threshold integer,
  last_restocked_at timestamp with time zone,
  vendor text,
  cost_per_unit_cents integer,
  home_location text,
  vehicle_id uuid,
  is_personal boolean DEFAULT false NOT NULL,
  owner_user_id uuid,
  retired_at timestamp with time zone,
  retired_reason text,
  serial_suspect boolean DEFAULT false NOT NULL,
  photo_url text,
  condition text,
  condition_updated_at timestamp with time zone,
  linked_acquisition_receipt_id uuid,
  depreciation_method text DEFAULT 'straight_line'::text NOT NULL,
  disposed_at date,
  disposal_proceeds_cents bigint,
  disposal_kind text,
  tax_year_locked_through integer,
  CONSTRAINT equipment_inventory_condition_chk CHECK (((condition IS NULL) OR (condition = ANY (ARRAY['new'::text, 'good'::text, 'fair'::text, 'poor'::text, 'damaged'::text, 'needs_repair'::text])))),
  CONSTRAINT equipment_inventory_current_status_chk CHECK (((current_status IS NULL) OR (current_status = ANY (ARRAY['available'::text, 'in_use'::text, 'maintenance'::text, 'loaned_out'::text, 'lost'::text, 'retired'::text])))),
  CONSTRAINT equipment_inventory_depreciation_method_chk CHECK ((depreciation_method = ANY (ARRAY['section_179'::text, 'straight_line'::text, 'macrs_5yr'::text, 'macrs_7yr'::text, 'bonus_first_year'::text, 'none'::text]))),
  CONSTRAINT equipment_inventory_disposal_kind_chk CHECK (((disposal_kind IS NULL) OR (disposal_kind = ANY (ARRAY['sold'::text, 'traded'::text, 'scrapped'::text, 'lost'::text, 'stolen'::text, 'donated'::text])))),
  CONSTRAINT equipment_inventory_item_kind_chk CHECK (((item_kind IS NULL) OR (item_kind = ANY (ARRAY['durable'::text, 'consumable'::text, 'kit'::text])))),
  CONSTRAINT equipment_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_inventory_qr_code_id_unique UNIQUE (qr_code_id)
);

-- ── error_reports ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.error_reports (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  error_message text NOT NULL,
  error_stack text,
  error_type text DEFAULT 'unknown'::text NOT NULL,
  error_code text,
  component_name text,
  element_selector text,
  page_url text NOT NULL,
  page_title text,
  route_path text,
  api_endpoint text,
  request_method text,
  request_body jsonb,
  user_email text NOT NULL,
  user_name text,
  user_role text,
  user_notes text,
  user_expected text,
  user_cause_guess text,
  severity text DEFAULT 'medium'::text,
  browser_info text,
  screen_size text,
  viewport_size text,
  connection_type text,
  memory_usage text,
  session_duration_ms integer,
  console_logs jsonb,
  breadcrumbs jsonb,
  status text DEFAULT 'new'::text,
  assigned_to text,
  resolution_notes text,
  resolved_at timestamp with time zone,
  resolved_by text,
  occurred_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT error_reports_pkey PRIMARY KEY (id)
);

-- ── exam_prep_categories ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.exam_prep_categories (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  exam_type text NOT NULL,
  category_name text NOT NULL,
  description text,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exam_prep_categories_exam_type_check CHECK ((exam_type = ANY (ARRAY['SIT'::text, 'RPLS'::text]))),
  CONSTRAINT exam_prep_categories_pkey PRIMARY KEY (id)
);

-- ── fs_mock_exam_attempts ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fs_mock_exam_attempts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  total_questions integer DEFAULT 110 NOT NULL,
  correct_answers integer DEFAULT 0 NOT NULL,
  score_percent numeric(5,2) DEFAULT 0,
  time_spent_minutes integer DEFAULT 0,
  category_scores jsonb DEFAULT '{}'::jsonb,
  passed boolean DEFAULT false,
  completed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fs_mock_exam_attempts_pkey PRIMARY KEY (id)
);

-- ── fs_module_progress ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fs_module_progress (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  module_id uuid NOT NULL,
  best_score integer DEFAULT 0,
  attempts integer DEFAULT 0,
  study_time_minutes integer DEFAULT 0,
  last_studied_at timestamp with time zone,
  completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  best_mock_score integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fs_module_progress_pkey PRIMARY KEY (id),
  CONSTRAINT fs_module_progress_user_email_module_id_key UNIQUE (user_email, module_id)
);

-- ── fs_weak_areas ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fs_weak_areas (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  topic text NOT NULL,
  module_number integer,
  miss_count integer DEFAULT 1,
  last_missed_at timestamp with time zone DEFAULT now(),
  resolved boolean DEFAULT false,
  CONSTRAINT fs_weak_areas_pkey PRIMARY KEY (id),
  CONSTRAINT fs_weak_areas_user_email_topic_key UNIQUE (user_email, topic)
);

-- ── job_checklists ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_checklists (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  stage text NOT NULL,
  item text NOT NULL,
  is_completed boolean DEFAULT false,
  completed_by text,
  completed_at timestamp with time zone,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_checklists_pkey PRIMARY KEY (id)
);

-- ── job_equipment ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_equipment (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  equipment_name text NOT NULL,
  equipment_type text,
  serial_number text,
  checked_out_at timestamp with time zone,
  returned_at timestamp with time zone,
  checked_out_by text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  equipment_inventory_id uuid,
  CONSTRAINT job_equipment_pkey PRIMARY KEY (id)
);

-- ── job_field_data ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_field_data (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  data_type text NOT NULL,
  point_name text,
  northing numeric(15,6),
  easting numeric(15,6),
  elevation numeric(12,6),
  description text,
  raw_data jsonb,
  collected_by text NOT NULL,
  collected_at timestamp with time zone DEFAULT now(),
  instrument text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_field_data_pkey PRIMARY KEY (id)
);

-- ── job_payments ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_payments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  amount numeric(12,2) NOT NULL,
  payment_type text DEFAULT 'payment'::text,
  payment_method text,
  reference_number text,
  notes text,
  paid_at timestamp with time zone DEFAULT now(),
  recorded_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_payments_pkey PRIMARY KEY (id)
);

-- ── job_research ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_research (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  category text NOT NULL,
  title text NOT NULL,
  content text,
  source text,
  reference_number text,
  date_of_record timestamp with time zone,
  file_id uuid,
  added_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_research_pkey PRIMARY KEY (id)
);

-- ── job_stages_history ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_stages_history (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  from_stage text,
  to_stage text NOT NULL,
  changed_by text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_stages_history_pkey PRIMARY KEY (id)
);

-- ── job_tags ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_tags (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  tag text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT job_tags_pkey PRIMARY KEY (id)
);

-- ── job_team ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_team (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  user_email text NOT NULL,
  user_name text,
  role text NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  removed_at timestamp with time zone,
  notes text,
  org_id uuid NOT NULL,
  assigned_from timestamp with time zone,
  assigned_to timestamp with time zone,
  slot_role text,
  state text,
  confirmed_at timestamp with time zone,
  declined_at timestamp with time zone,
  decline_reason text,
  is_crew_lead boolean DEFAULT false NOT NULL,
  is_override boolean DEFAULT false NOT NULL,
  override_reason text,
  CONSTRAINT job_team_override_requires_reason_chk CHECK (((is_override = false) OR ((override_reason IS NOT NULL) AND (length(TRIM(BOTH FROM override_reason)) > 0)))),
  CONSTRAINT job_team_state_chk CHECK (((state IS NULL) OR (state = ANY (ARRAY['proposed'::text, 'confirmed'::text, 'declined'::text, 'cancelled'::text])))),
  CONSTRAINT job_team_window_chk CHECK (((assigned_from IS NULL) OR (assigned_to IS NULL) OR (assigned_to > assigned_from))),
  CONSTRAINT job_team_pkey PRIMARY KEY (id)
);

-- ── job_time_entries ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_time_entries (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  user_email text NOT NULL,
  user_name text,
  work_type text DEFAULT 'general'::text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  duration_minutes integer,
  description text,
  billable boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_time_entries_pkey PRIMARY KEY (id)
);

-- ── jobs ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.jobs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_number text NOT NULL,
  name text NOT NULL,
  description text,
  address text,
  city text,
  state text DEFAULT 'TX'::text,
  zip text,
  county text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  survey_type text DEFAULT 'boundary'::text NOT NULL,
  acreage numeric(12,4),
  lot_number text,
  subdivision text,
  abstract_number text,
  stage text DEFAULT 'quote'::text NOT NULL,
  stage_changed_at timestamp with time zone DEFAULT now(),
  date_received timestamp with time zone DEFAULT now(),
  date_quoted timestamp with time zone,
  date_accepted timestamp with time zone,
  date_started timestamp with time zone,
  date_fieldwork_complete timestamp with time zone,
  date_drawing_complete timestamp with time zone,
  date_legal_complete timestamp with time zone,
  date_delivered timestamp with time zone,
  deadline timestamp with time zone,
  quote_amount numeric(12,2),
  final_amount numeric(12,2),
  amount_paid numeric(12,2) DEFAULT 0,
  payment_status text DEFAULT 'unpaid'::text,
  payment_notes text,
  client_name text,
  client_email text,
  client_phone text,
  client_company text,
  client_address text,
  lead_rpls_email text,
  conversation_id uuid,
  is_priority boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  is_legacy boolean DEFAULT false,
  notes text,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  result text,
  result_set_at timestamp with time zone,
  result_reason text,
  deliverables text,
  deleted_at timestamp with time zone,
  instructions text,
  CONSTRAINT jobs_result_check CHECK (((result IS NULL) OR (result = ANY (ARRAY['won'::text, 'lost'::text, 'abandoned'::text])))),
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_job_number_key UNIQUE (job_number)
);

-- ── learning_assignments ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.learning_assignments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  assigned_to text NOT NULL,
  assigned_by text NOT NULL,
  module_id uuid,
  lesson_id uuid,
  unlock_next boolean DEFAULT false,
  status text DEFAULT 'pending'::text NOT NULL,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learning_assignments_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text]))),
  CONSTRAINT learning_assignments_pkey PRIMARY KEY (id)
);

-- ── learning_credit_values ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.learning_credit_values (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  entity_label text,
  credit_points integer DEFAULT 0 NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learning_credit_values_credit_points_check CHECK ((credit_points >= 0)),
  CONSTRAINT learning_credit_values_entity_type_check CHECK ((entity_type = ANY (ARRAY['module'::text, 'lesson'::text, 'quiz_pass'::text, 'exam_prep_pass'::text, 'flashcard_mastery'::text]))),
  CONSTRAINT learning_credit_values_pkey PRIMARY KEY (id)
);

-- ── learning_lessons ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.learning_lessons (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  module_id uuid NOT NULL,
  title text NOT NULL,
  content text,
  key_takeaways text[] DEFAULT '{}'::text[],
  order_index integer DEFAULT 0 NOT NULL,
  estimated_minutes integer DEFAULT 15,
  resources jsonb DEFAULT '[]'::jsonb,
  videos jsonb DEFAULT '[]'::jsonb,
  tags text[] DEFAULT '{}'::text[],
  status text DEFAULT 'draft'::text,
  xp_reward integer DEFAULT 50,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  difficulty_level text DEFAULT 'beginner'::text,
  version integer DEFAULT 1,
  is_published boolean DEFAULT true,
  review_status text DEFAULT 'approved'::text,
  content_format text DEFAULT 'rich_text'::text,
  prerequisite_lesson_id uuid,
  description text,
  learning_objectives text[] DEFAULT '{}'::text[],
  content_migrated boolean DEFAULT false,
  CONSTRAINT learning_lessons_content_format_check CHECK ((content_format = ANY (ARRAY['rich_text'::text, 'markdown'::text, 'video'::text, 'interactive'::text, 'mixed'::text]))),
  CONSTRAINT learning_lessons_difficulty_level_check CHECK ((difficulty_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text, 'expert'::text]))),
  CONSTRAINT learning_lessons_review_status_check CHECK ((review_status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'approved'::text, 'needs_revision'::text]))),
  CONSTRAINT learning_lessons_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text]))),
  CONSTRAINT learning_lessons_pkey PRIMARY KEY (id)
);

-- ── learning_modules ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.learning_modules (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  title text NOT NULL,
  description text,
  difficulty text DEFAULT 'beginner'::text,
  estimated_hours numeric(4,1) DEFAULT 1.0,
  order_index integer DEFAULT 0 NOT NULL,
  status text DEFAULT 'draft'::text,
  tags text[] DEFAULT '{}'::text[],
  xp_reward integer DEFAULT 200,
  is_fs_required boolean DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  difficulty_level text DEFAULT 'beginner'::text,
  estimated_minutes integer DEFAULT 60,
  version integer DEFAULT 1,
  is_published boolean DEFAULT true,
  published_at timestamp with time zone,
  review_status text DEFAULT 'approved'::text,
  last_reviewed_by text,
  last_reviewed_at timestamp with time zone,
  acc_course_id text,
  is_academic boolean DEFAULT false,
  credential_key text,
  CONSTRAINT learning_modules_difficulty_check CHECK ((difficulty = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text]))),
  CONSTRAINT learning_modules_difficulty_level_check CHECK ((difficulty_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text, 'expert'::text]))),
  CONSTRAINT learning_modules_review_status_check CHECK ((review_status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'approved'::text, 'needs_revision'::text]))),
  CONSTRAINT learning_modules_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text]))),
  CONSTRAINT learning_modules_pkey PRIMARY KEY (id)
);

-- ── learning_topics ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.learning_topics (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lesson_id uuid NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  order_index integer DEFAULT 0 NOT NULL,
  keywords text[] DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learning_topics_pkey PRIMARY KEY (id)
);

-- ── lesson_blocks ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.lesson_blocks (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lesson_id uuid NOT NULL,
  block_type text NOT NULL,
  content jsonb DEFAULT '{}'::jsonb NOT NULL,
  order_index integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lesson_blocks_block_type_check CHECK ((block_type = ANY (ARRAY['text'::text, 'html'::text, 'image'::text, 'video'::text, 'audio'::text, 'slideshow'::text, 'file'::text, 'quiz'::text, 'callout'::text, 'highlight'::text, 'key_takeaways'::text, 'equation'::text, 'divider'::text, 'embed'::text, 'table'::text, 'tabs'::text, 'accordion'::text, 'columns'::text, 'link_reference'::text, 'flashcard'::text, 'popup_article'::text, 'backend_link'::text, 'practice_problem'::text]))),
  CONSTRAINT lesson_blocks_pkey PRIMARY KEY (id)
);

-- ── lesson_required_articles ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.lesson_required_articles (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lesson_id uuid NOT NULL,
  article_id uuid NOT NULL,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lesson_required_articles_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_required_articles_lesson_id_article_id_key UNIQUE (lesson_id, article_id)
);

-- ── lesson_versions ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.lesson_versions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lesson_id uuid NOT NULL,
  version_number integer DEFAULT 1 NOT NULL,
  blocks_snapshot jsonb DEFAULT '[]'::jsonb NOT NULL,
  saved_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lesson_versions_pkey PRIMARY KEY (id)
);

-- ── media_library ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.media_library (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  title text DEFAULT 'Untitled'::text NOT NULL,
  caption text,
  media_type text NOT NULL,
  url text NOT NULL,
  alt_text text,
  link_url text,
  is_clickable boolean DEFAULT false,
  resolution text DEFAULT 'original'::text,
  tags text[] DEFAULT '{}'::text[],
  uploaded_by text NOT NULL,
  source_context text,
  source_id uuid,
  deleted_at timestamp with time zone,
  deleted_by text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT media_library_media_type_check CHECK ((media_type = ANY (ARRAY['image'::text, 'video'::text, 'audio'::text, 'document'::text, 'url'::text]))),
  CONSTRAINT media_library_pkey PRIMARY KEY (id)
);

-- ── messaging_preferences ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.messaging_preferences (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  notifications_enabled boolean DEFAULT true,
  sound_enabled boolean DEFAULT true,
  desktop_notifications boolean DEFAULT true,
  email_notifications boolean DEFAULT false,
  auto_archive_days integer DEFAULT 0,
  theme text DEFAULT 'default'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messaging_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT messaging_preferences_user_email_key UNIQUE (user_email)
);

-- ── module_completions ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.module_completions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  module_type text NOT NULL,
  module_id uuid NOT NULL,
  completed_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  xp_earned integer DEFAULT 0,
  is_current boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT module_completions_pkey PRIMARY KEY (id)
);

-- ── module_xp_config ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.module_xp_config (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  module_type text NOT NULL,
  module_id uuid,
  xp_value integer DEFAULT 500 NOT NULL,
  expiry_months integer DEFAULT 18,
  difficulty_rating integer DEFAULT 3,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  refresh_months integer,
  CONSTRAINT module_xp_config_difficulty_rating_check CHECK (((difficulty_rating >= 1) AND (difficulty_rating <= 5))),
  CONSTRAINT module_xp_config_pkey PRIMARY KEY (id)
);

-- ── pay_advance_requests ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pay_advance_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  amount numeric(10,2) NOT NULL,
  reason text NOT NULL,
  status text DEFAULT 'pending'::text,
  requested_at timestamp with time zone DEFAULT now(),
  reviewed_by text,
  reviewed_at timestamp with time zone,
  denial_reason text,
  pay_date date,
  paid_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pay_advance_requests_amount_check CHECK ((amount > (0)::numeric)),
  CONSTRAINT pay_advance_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text, 'paid'::text, 'cancelled'::text]))),
  CONSTRAINT pay_advance_requests_pkey PRIMARY KEY (id)
);

-- ── pay_raises ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pay_raises (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  previous_rate numeric(10,2) NOT NULL,
  new_rate numeric(10,2) NOT NULL,
  raise_amount numeric(10,2) NOT NULL,
  raise_percentage numeric(5,2),
  reason text,
  effective_date date NOT NULL,
  approved_by text NOT NULL,
  next_review_date date,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pay_raises_pkey PRIMARY KEY (id)
);

-- ── pay_rate_standards ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pay_rate_standards (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_title text NOT NULL,
  min_rate numeric(10,2) NOT NULL,
  max_rate numeric(10,2) NOT NULL,
  default_rate numeric(10,2) NOT NULL,
  description text,
  effective_date date DEFAULT CURRENT_DATE NOT NULL,
  is_current boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pay_rate_standards_pkey PRIMARY KEY (id)
);

-- ── pay_stubs ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pay_stubs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  payroll_run_id uuid,
  user_email text NOT NULL,
  user_name text,
  pay_period_start date NOT NULL,
  pay_period_end date NOT NULL,
  regular_hours numeric(8,2) DEFAULT 0,
  overtime_hours numeric(8,2) DEFAULT 0,
  base_rate numeric(10,2) NOT NULL,
  overtime_rate numeric(10,2),
  role_adjustment numeric(10,2) DEFAULT 0,
  cert_adjustment numeric(10,2) DEFAULT 0,
  effective_rate numeric(10,2) NOT NULL,
  gross_pay numeric(12,2) NOT NULL,
  federal_tax numeric(10,2) DEFAULT 0,
  state_tax numeric(10,2) DEFAULT 0,
  social_security numeric(10,2) DEFAULT 0,
  medicare numeric(10,2) DEFAULT 0,
  other_deductions numeric(10,2) DEFAULT 0,
  deduction_notes text,
  total_deductions numeric(12,2) DEFAULT 0,
  net_pay numeric(12,2) NOT NULL,
  disbursement_method text DEFAULT 'balance'::text,
  disbursement_status text DEFAULT 'pending'::text,
  credited_at timestamp with time zone,
  job_hours jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pay_stubs_pkey PRIMARY KEY (id)
);

-- ── pay_system_config ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pay_system_config (
  key text NOT NULL,
  value numeric(10,2) NOT NULL,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pay_system_config_pkey PRIMARY KEY (key)
);

-- ── payout_log ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payout_log (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  payout_type text NOT NULL,
  amount numeric(10,2) NOT NULL,
  reason text NOT NULL,
  details text,
  old_rate numeric(10,2),
  new_rate numeric(10,2),
  old_role text,
  new_role text,
  source_type text,
  source_id uuid,
  processed_by text,
  processed_at timestamp with time zone DEFAULT now(),
  pay_period_start date,
  pay_period_end date,
  status text DEFAULT 'completed'::text,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT payout_log_payout_type_check CHECK ((payout_type = ANY (ARRAY['weekly_payroll'::text, 'pay_raise'::text, 'bonus'::text, 'advance'::text, 'advance_repayment'::text, 'adjustment'::text, 'credential_bonus'::text, 'education_bonus'::text, 'promotion_raise'::text, 'performance_bonus'::text, 'holiday_bonus'::text, 'referral_bonus'::text, 'retention_bonus'::text, 'spot_bonus'::text, 'completion_bonus'::text]))),
  CONSTRAINT payout_log_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'completed'::text, 'cancelled'::text, 'reversed'::text]))),
  CONSTRAINT payout_log_pkey PRIMARY KEY (id)
);

-- ── payroll_runs ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payroll_runs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  pay_period_start date NOT NULL,
  pay_period_end date NOT NULL,
  run_date timestamp with time zone DEFAULT now(),
  status text DEFAULT 'draft'::text NOT NULL,
  total_gross numeric(12,2) DEFAULT 0,
  total_deductions numeric(12,2) DEFAULT 0,
  total_net numeric(12,2) DEFAULT 0,
  employee_count integer DEFAULT 0,
  processed_by text NOT NULL,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payroll_runs_pkey PRIMARY KEY (id)
);

-- ── practice_sessions ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.practice_sessions (
  id text NOT NULL,
  user_email text NOT NULL,
  problems text,
  config text,
  total_problems integer DEFAULT 0,
  correct_answers integer DEFAULT 0,
  score_percent numeric DEFAULT 0,
  time_spent_seconds integer DEFAULT 0,
  status text DEFAULT 'active'::text,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT practice_sessions_status_check CHECK ((status = ANY (ARRAY['active'::text, 'completed'::text, 'abandoned'::text]))),
  CONSTRAINT practice_sessions_pkey PRIMARY KEY (id)
);

-- ── question_bank ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.question_bank (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  question_text text NOT NULL,
  question_type text DEFAULT 'multiple_choice'::text,
  options jsonb DEFAULT '[]'::jsonb,
  correct_answer text NOT NULL,
  explanation text,
  difficulty text DEFAULT 'medium'::text,
  module_id uuid,
  lesson_id uuid,
  topic_id uuid,
  article_id uuid,
  exam_category text,
  tags text[] DEFAULT '{}'::text[],
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  times_answered integer DEFAULT 0,
  times_correct integer DEFAULT 0,
  report_count integer DEFAULT 0,
  is_published boolean DEFAULT true,
  review_status text DEFAULT 'approved'::text,
  study_references jsonb DEFAULT '[]'::jsonb,
  is_dynamic boolean DEFAULT false,
  template_id uuid,
  tolerance numeric DEFAULT 0.01,
  diagram jsonb,
  CONSTRAINT question_bank_difficulty_check CHECK ((difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text]))),
  CONSTRAINT question_bank_question_type_check CHECK ((question_type = ANY (ARRAY['multiple_choice'::text, 'true_false'::text, 'short_answer'::text, 'fill_blank'::text, 'multi_select'::text, 'ordering'::text, 'drag_label'::text, 'hotspot'::text, 'numeric_input'::text, 'math_template'::text, 'essay'::text]))),
  CONSTRAINT question_bank_review_status_check CHECK ((review_status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'approved'::text, 'needs_revision'::text]))),
  CONSTRAINT question_bank_pkey PRIMARY KEY (id)
);

-- ── quiz_attempt_answers ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quiz_attempt_answers (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  attempt_id uuid NOT NULL,
  question_id uuid NOT NULL,
  user_answer text,
  is_correct boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quiz_attempt_answers_pkey PRIMARY KEY (id)
);

-- ── quiz_attempts ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quiz_attempts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  attempt_type text NOT NULL,
  module_id uuid,
  lesson_id uuid,
  article_id uuid,
  exam_category text,
  total_questions integer DEFAULT 0 NOT NULL,
  correct_answers integer DEFAULT 0 NOT NULL,
  score_percent numeric(5,2) DEFAULT 0,
  time_spent_seconds integer DEFAULT 0,
  completed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid DEFAULT '00000000-0000-0000-0000-000000000001'::uuid NOT NULL,
  CONSTRAINT quiz_attempts_attempt_type_check CHECK ((attempt_type = ANY (ARRAY['lesson_quiz'::text, 'module_test'::text, 'exam_prep'::text, 'article_quiz'::text]))),
  CONSTRAINT quiz_attempts_pkey PRIMARY KEY (id)
);

-- ── recycle_bin ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.recycle_bin (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  original_table text NOT NULL,
  original_id uuid NOT NULL,
  item_title text,
  item_type text,
  item_data jsonb NOT NULL,
  deleted_by text NOT NULL,
  deleted_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '90 days'::interval),
  CONSTRAINT recycle_bin_pkey PRIMARY KEY (id)
);

-- ── registered_users ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.registered_users (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email text NOT NULL,
  password_hash text NOT NULL,
  name text NOT NULL,
  roles text[] DEFAULT ARRAY['employee'::text],
  is_approved boolean DEFAULT true,
  is_banned boolean DEFAULT false,
  banned_at timestamp with time zone,
  banned_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  auth_provider text,
  avatar_url text,
  last_sign_in timestamp with time zone,
  default_org_id uuid,
  equipment_self_checkout boolean DEFAULT false NOT NULL,
  worker_classification text DEFAULT 'unclassified'::text NOT NULL,
  CONSTRAINT registered_users_worker_classification_chk CHECK ((worker_classification = ANY (ARRAY['unclassified'::text, 'w2'::text, 'contractor_1099'::text]))),
  CONSTRAINT registered_users_pkey PRIMARY KEY (id),
  CONSTRAINT registered_users_email_key UNIQUE (email)
);

-- ── rewards_catalog ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.rewards_catalog (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  description text,
  category text NOT NULL,
  xp_cost integer NOT NULL,
  image_url text,
  tier text DEFAULT 'bronze'::text NOT NULL,
  stock_quantity integer DEFAULT '-1'::integer,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  cash_price numeric(8,2) DEFAULT NULL::numeric,
  CONSTRAINT rewards_catalog_category_check CHECK ((category = ANY (ARRAY['apparel'::text, 'gear'::text, 'gift_cards'::text, 'accessories'::text, 'cash_bonus'::text, 'other'::text]))),
  CONSTRAINT rewards_catalog_tier_check CHECK ((tier = ANY (ARRAY['bronze'::text, 'silver'::text, 'gold'::text, 'platinum'::text, 'diamond'::text]))),
  CONSTRAINT rewards_catalog_pkey PRIMARY KEY (id)
);

-- ── rewards_purchases ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.rewards_purchases (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  item_id uuid NOT NULL,
  xp_spent integer NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  fulfilled_by text,
  fulfilled_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rewards_purchases_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'fulfilled'::text, 'cancelled'::text]))),
  CONSTRAINT rewards_purchases_pkey PRIMARY KEY (id)
);

-- ── role_pay_adjustments ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.role_pay_adjustments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  base_title text NOT NULL,
  role_on_job text NOT NULL,
  adjustment_type text DEFAULT 'flat'::text NOT NULL,
  adjustment_amount numeric(10,2) DEFAULT 0 NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT role_pay_adjustments_pkey PRIMARY KEY (id)
);

-- ── role_tiers ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.role_tiers (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  role_key text NOT NULL,
  label text NOT NULL,
  base_bonus numeric(10,2) DEFAULT 0 NOT NULL,
  description text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  max_effective_rate numeric(10,2),
  aliases text[] DEFAULT ARRAY[]::text[],
  icon text,
  CONSTRAINT role_tiers_pkey PRIMARY KEY (id),
  CONSTRAINT role_tiers_role_key_key UNIQUE (role_key)
);

-- ── scheduled_bonuses ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.scheduled_bonuses (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  amount numeric(10,2) NOT NULL,
  bonus_type text DEFAULT 'performance'::text,
  reason text NOT NULL,
  scheduled_date date NOT NULL,
  scheduled_time time without time zone DEFAULT '09:00:00'::time without time zone,
  status text DEFAULT 'scheduled'::text,
  created_by text NOT NULL,
  paid_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scheduled_bonuses_amount_check CHECK ((amount > (0)::numeric)),
  CONSTRAINT scheduled_bonuses_bonus_type_check CHECK ((bonus_type = ANY (ARRAY['performance'::text, 'holiday'::text, 'referral'::text, 'retention'::text, 'spot'::text, 'completion'::text, 'other'::text]))),
  CONSTRAINT scheduled_bonuses_status_check CHECK ((status = ANY (ARRAY['scheduled'::text, 'paid'::text, 'cancelled'::text]))),
  CONSTRAINT scheduled_bonuses_pkey PRIMARY KEY (id)
);

-- ── seniority_brackets ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.seniority_brackets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  min_years integer NOT NULL,
  max_years integer,
  bonus_per_hour numeric(10,2) DEFAULT 0 NOT NULL,
  label text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT seniority_brackets_pkey PRIMARY KEY (id)
);

-- ── user_article_completions ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_article_completions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  article_id uuid NOT NULL,
  completed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_article_completions_pkey PRIMARY KEY (id),
  CONSTRAINT user_article_completions_user_email_article_id_key UNIQUE (user_email, article_id)
);

-- ── user_badges ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_badges (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  badge_id uuid NOT NULL,
  earned_at timestamp with time zone DEFAULT now(),
  awarded_by text,
  CONSTRAINT user_badges_pkey PRIMARY KEY (id),
  CONSTRAINT user_badges_user_email_badge_id_key UNIQUE (user_email, badge_id)
);

-- ── user_lesson_progress ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_lesson_progress (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  module_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  status text DEFAULT 'not_started'::text NOT NULL,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  quiz_unlocked boolean DEFAULT false,
  content_interactions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_lesson_progress_status_check CHECK ((status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text]))),
  CONSTRAINT user_lesson_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_lesson_progress_user_email_lesson_id_key UNIQUE (user_email, lesson_id)
);

-- ── user_milestone_progress ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_milestone_progress (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  milestone_id uuid NOT NULL,
  achieved boolean DEFAULT false,
  achieved_at timestamp with time zone,
  progress_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_milestone_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_milestone_progress_user_email_milestone_id_key UNIQUE (user_email, milestone_id)
);

-- ── user_progress ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_progress (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  module_id uuid,
  lesson_id uuid,
  completed_at timestamp with time zone DEFAULT now(),
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  total_time_minutes integer DEFAULT 0,
  last_activity_at timestamp with time zone,
  CONSTRAINT user_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_progress_user_email_lesson_id_key UNIQUE (user_email, lesson_id)
);

-- ── withdrawal_requests ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.withdrawal_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  amount numeric(12,2) NOT NULL,
  destination text DEFAULT 'bank_account'::text NOT NULL,
  bank_name text,
  bank_account_last4 text,
  status text DEFAULT 'pending'::text NOT NULL,
  requested_at timestamp with time zone DEFAULT now(),
  reviewed_by text,
  reviewed_at timestamp with time zone,
  processed_at timestamp with time zone,
  rejection_reason text,
  transaction_id uuid,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT withdrawal_requests_pkey PRIMARY KEY (id)
);

-- ── work_type_rates ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.work_type_rates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  work_type text NOT NULL,
  label text NOT NULL,
  base_rate numeric(10,2) NOT NULL,
  icon text,
  description text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  max_bonus_cap numeric(10,2),
  bonus_multiplier numeric(4,2) DEFAULT 1.00,
  CONSTRAINT work_type_rates_pkey PRIMARY KEY (id),
  CONSTRAINT work_type_rates_work_type_key UNIQUE (work_type)
);

-- ── xp_balances ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.xp_balances (
  user_email text NOT NULL,
  current_balance integer DEFAULT 0 NOT NULL,
  total_earned integer DEFAULT 0 NOT NULL,
  total_spent integer DEFAULT 0 NOT NULL,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT xp_balances_pkey PRIMARY KEY (user_email)
);

-- ── xp_milestone_achievements ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.xp_milestone_achievements (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  milestone_id uuid NOT NULL,
  achieved_at timestamp with time zone DEFAULT now(),
  CONSTRAINT xp_milestone_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT xp_milestone_achievements_user_email_milestone_id_key UNIQUE (user_email, milestone_id)
);

-- ── xp_pay_milestones ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.xp_pay_milestones (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  xp_threshold integer NOT NULL,
  bonus_per_hour numeric(6,2) NOT NULL,
  label text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT xp_pay_milestones_pkey PRIMARY KEY (id),
  CONSTRAINT xp_pay_milestones_xp_threshold_key UNIQUE (xp_threshold)
);

-- ── xp_transactions ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.xp_transactions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_email text NOT NULL,
  amount integer NOT NULL,
  transaction_type text NOT NULL,
  source_type text,
  source_id text,
  description text NOT NULL,
  balance_after integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT xp_transactions_transaction_type_check CHECK ((transaction_type = ANY (ARRAY['module_complete'::text, 'quiz_pass'::text, 'exam_prep_complete'::text, 'mock_exam_pass'::text, 'credential_earned'::text, 'course_pass'::text, 'badge_earned'::text, 'store_purchase'::text, 'admin_adjustment'::text, 'module_retake'::text]))),
  CONSTRAINT xp_transactions_pkey PRIMARY KEY (id)
);


-- ── Indexes ──────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_ace_user ON public.acc_course_enrollments USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_al_action ON public.activity_log USING btree (action_type);
CREATE INDEX IF NOT EXISTS idx_al_created ON public.activity_log USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_al_entity ON public.activity_log USING btree (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_al_user ON public.activity_log USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_discussion_threads_content ON public.admin_discussion_threads USING btree (content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_discussion_threads_created_by ON public.admin_discussion_threads USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_discussion_threads_escalation ON public.admin_discussion_threads USING btree (escalation_level);
CREATE INDEX IF NOT EXISTS idx_discussion_threads_page ON public.admin_discussion_threads USING btree (page_path);
CREATE INDEX IF NOT EXISTS idx_discussion_threads_status ON public.admin_discussion_threads USING btree (status);
CREATE INDEX IF NOT EXISTS idx_discussion_threads_type ON public.admin_discussion_threads USING btree (thread_type);
CREATE INDEX IF NOT EXISTS idx_assignments_due ON public.assignments USING btree (due_date);
CREATE INDEX IF NOT EXISTS idx_assignments_orgid_org_id ON public.assignments USING btree (org_id) WHERE (org_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_assignments_status ON public.assignments USING btree (status);
CREATE INDEX IF NOT EXISTS idx_assignments_user ON public.assignments USING btree (assigned_to);
CREATE INDEX IF NOT EXISTS idx_balance_tx_email ON public.balance_transactions USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_dtl_date ON public.daily_time_logs USING btree (log_date);
CREATE INDEX IF NOT EXISTS idx_dtl_email ON public.daily_time_logs USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_dtl_email_date ON public.daily_time_logs USING btree (user_email, log_date);
CREATE INDEX IF NOT EXISTS idx_dtl_status ON public.daily_time_logs USING btree (status);
CREATE INDEX IF NOT EXISTS idx_ec_user ON public.education_courses USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_employee_certs_email ON public.employee_certifications USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_eec_email ON public.employee_earned_credentials USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_employee_earned_credentials_verified ON public.employee_earned_credentials USING btree (verified, user_email);
CREATE INDEX IF NOT EXISTS idx_elc_earned ON public.employee_learning_credits USING btree (earned_at);
CREATE INDEX IF NOT EXISTS idx_elc_email ON public.employee_learning_credits USING btree (user_email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_elc_unique ON public.employee_learning_credits USING btree (user_email, entity_type, entity_id, source_id);
CREATE INDEX IF NOT EXISTS idx_epc_email ON public.employee_profile_changes USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_epc_unread ON public.employee_profile_changes USING btree (user_email, is_read);
CREATE INDEX IF NOT EXISTS idx_employee_profiles_email ON public.employee_profiles USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_employee_profiles_tier_key ON public.employee_profiles USING btree (tier_key);
CREATE INDEX IF NOT EXISTS idx_erh_email ON public.employee_role_history USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_eta_email ON public.employee_threshold_achievements USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_equipment_inventory_acq_receipt ON public.equipment_inventory USING btree (linked_acquisition_receipt_id) WHERE (linked_acquisition_receipt_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_equipment_inventory_active ON public.equipment_inventory USING btree (category, name) WHERE (retired_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_equipment_inventory_active_assets ON public.equipment_inventory USING btree (depreciation_method, placed_in_service_at) WHERE ((disposed_at IS NULL) AND (retired_at IS NULL));
CREATE INDEX IF NOT EXISTS idx_equipment_inventory_available ON public.equipment_inventory USING btree (category) WHERE (current_status = 'available'::text);
CREATE INDEX IF NOT EXISTS idx_equipment_inventory_calibration_due ON public.equipment_inventory USING btree (next_calibration_due_at) WHERE ((next_calibration_due_at IS NOT NULL) AND (current_status <> ALL (ARRAY['retired'::text, 'lost'::text])));
CREATE INDEX IF NOT EXISTS idx_equipment_inventory_category ON public.equipment_inventory USING btree (category) WHERE (category IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_equipment_inventory_current_reservation ON public.equipment_inventory USING btree (current_reservation_id) WHERE (current_reservation_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_equipment_inventory_low_stock ON public.equipment_inventory USING btree (quantity_on_hand) WHERE ((item_kind = 'consumable'::text) AND (low_stock_threshold IS NOT NULL) AND (quantity_on_hand <= low_stock_threshold));
CREATE INDEX IF NOT EXISTS idx_equipment_inventory_needs_attention ON public.equipment_inventory USING btree (condition, condition_updated_at DESC) WHERE ((condition IS NOT NULL) AND (condition = ANY (ARRAY['fair'::text, 'poor'::text, 'damaged'::text, 'needs_repair'::text])) AND (retired_at IS NULL));
CREATE INDEX IF NOT EXISTS idx_equipment_status ON public.equipment_inventory USING btree (status);
CREATE INDEX IF NOT EXISTS idx_er_created ON public.error_reports USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_er_severity ON public.error_reports USING btree (severity);
CREATE INDEX IF NOT EXISTS idx_er_status ON public.error_reports USING btree (status);
CREATE INDEX IF NOT EXISTS idx_er_type ON public.error_reports USING btree (error_type);
CREATE INDEX IF NOT EXISTS idx_er_user ON public.error_reports USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_error_reports_orgid_org_id ON public.error_reports USING btree (org_id) WHERE (org_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_job_checklists_job ON public.job_checklists USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_job_equipment_inventory_id ON public.job_equipment USING btree (equipment_inventory_id) WHERE (equipment_inventory_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_job_equipment_job ON public.job_equipment USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_job_equipment_open_assignments ON public.job_equipment USING btree (equipment_inventory_id, job_id) WHERE ((equipment_inventory_id IS NOT NULL) AND (returned_at IS NULL));
CREATE INDEX IF NOT EXISTS idx_job_field_data_job ON public.job_field_data USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_job_field_data_type ON public.job_field_data USING btree (data_type);
CREATE INDEX IF NOT EXISTS idx_job_payments_job ON public.job_payments USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_job_research_category ON public.job_research USING btree (category);
CREATE INDEX IF NOT EXISTS idx_job_research_job ON public.job_research USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_job_stages_history_job ON public.job_stages_history USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_job_tags_job ON public.job_tags USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_job_tags_orgid_org_id ON public.job_tags USING btree (org_id) WHERE (org_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_job_tags_tag ON public.job_tags USING btree (tag);
CREATE UNIQUE INDEX IF NOT EXISTS idx_job_tags_unique ON public.job_tags USING btree (job_id, tag);
CREATE INDEX IF NOT EXISTS idx_job_team_capacity ON public.job_team USING gist (user_email, tstzrange(assigned_from, assigned_to, '[)'::text)) WHERE ((state = ANY (ARRAY['proposed'::text, 'confirmed'::text])) AND (assigned_from IS NOT NULL));
CREATE INDEX IF NOT EXISTS idx_job_team_job ON public.job_team USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_job_team_job_state ON public.job_team USING btree (job_id, state, assigned_from);
CREATE INDEX IF NOT EXISTS idx_job_team_orgid_org_id ON public.job_team USING btree (org_id) WHERE (org_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_job_team_overrides ON public.job_team USING btree (assigned_at DESC) WHERE (is_override = true);
CREATE UNIQUE INDEX IF NOT EXISTS idx_job_team_unique ON public.job_team USING btree (job_id, user_email, role) WHERE (removed_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_job_team_user ON public.job_team USING btree (user_email);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_job_team_crew_lead ON public.job_team USING btree (job_id) WHERE ((is_crew_lead = true) AND (state = ANY (ARRAY['proposed'::text, 'confirmed'::text])));
CREATE INDEX IF NOT EXISTS idx_job_time_job ON public.job_time_entries USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_job_time_user ON public.job_time_entries USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_jobs_created_by ON public.jobs USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_jobs_is_archived ON public.jobs USING btree (is_archived);
CREATE INDEX IF NOT EXISTS idx_jobs_job_number ON public.jobs USING btree (job_number);
CREATE INDEX IF NOT EXISTS idx_jobs_lead_rpls ON public.jobs USING btree (lead_rpls_email);
CREATE INDEX IF NOT EXISTS idx_jobs_orgid_org_id ON public.jobs USING btree (org_id) WHERE (org_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_jobs_result_org ON public.jobs USING btree (org_id, result, result_set_at DESC) WHERE (result IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_jobs_stage ON public.jobs USING btree (stage);
CREATE INDEX IF NOT EXISTS idx_jobs_survey_type ON public.jobs USING btree (survey_type);
CREATE INDEX IF NOT EXISTS jobs_deleted_at_idx ON public.jobs USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_la_assigned_to ON public.learning_assignments USING btree (assigned_to);
CREATE INDEX IF NOT EXISTS idx_la_module ON public.learning_assignments USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_la_status ON public.learning_assignments USING btree (status);
CREATE INDEX IF NOT EXISTS idx_lcv_entity ON public.learning_credit_values USING btree (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_fts_lessons ON public.learning_lessons USING gin (to_tsvector('english'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(content, ''::text))));
CREATE INDEX IF NOT EXISTS idx_lessons_module ON public.learning_lessons USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_fts_modules ON public.learning_modules USING gin (to_tsvector('english'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(description, ''::text))));
CREATE INDEX IF NOT EXISTS learning_modules_credential_key_idx ON public.learning_modules USING btree (credential_key) WHERE (credential_key IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_fts_topics ON public.learning_topics USING gin (to_tsvector('english'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(content, ''::text))));
CREATE INDEX IF NOT EXISTS idx_topics_kw ON public.learning_topics USING gin (keywords);
CREATE INDEX IF NOT EXISTS idx_topics_lesson ON public.learning_topics USING btree (lesson_id);
CREATE INDEX IF NOT EXISTS idx_lb_lesson ON public.lesson_blocks USING btree (lesson_id);
CREATE INDEX IF NOT EXISTS idx_lb_order ON public.lesson_blocks USING btree (lesson_id, order_index);
CREATE INDEX IF NOT EXISTS idx_req_articles_article ON public.lesson_required_articles USING btree (article_id);
CREATE INDEX IF NOT EXISTS idx_req_articles_lesson ON public.lesson_required_articles USING btree (lesson_id);
CREATE INDEX IF NOT EXISTS idx_lv_lesson ON public.lesson_versions USING btree (lesson_id);
CREATE INDEX IF NOT EXISTS idx_ml_deleted ON public.media_library USING btree (deleted_at);
CREATE INDEX IF NOT EXISTS idx_ml_type ON public.media_library USING btree (media_type);
CREATE INDEX IF NOT EXISTS idx_ml_uploaded ON public.media_library USING btree (uploaded_by);
CREATE INDEX IF NOT EXISTS idx_mc_user ON public.module_completions USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_module_completions_orgid_org_id ON public.module_completions USING btree (org_id) WHERE (org_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_par_email ON public.pay_advance_requests USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_par_status ON public.pay_advance_requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_pay_raises_email ON public.pay_raises USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_pay_rate_standards_title ON public.pay_rate_standards USING btree (job_title, is_current);
CREATE INDEX IF NOT EXISTS idx_pay_stubs_email ON public.pay_stubs USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_pay_stubs_run ON public.pay_stubs USING btree (payroll_run_id);
CREATE INDEX IF NOT EXISTS idx_payout_log_orgid_org_id ON public.payout_log USING btree (org_id) WHERE (org_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_pl_date ON public.payout_log USING btree (processed_at);
CREATE INDEX IF NOT EXISTS idx_pl_email ON public.payout_log USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_pl_type ON public.payout_log USING btree (payout_type);
CREATE INDEX IF NOT EXISTS idx_payroll_runs_dates ON public.payroll_runs USING btree (pay_period_start, pay_period_end);
CREATE INDEX IF NOT EXISTS idx_ps_user ON public.practice_sessions USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_q_article ON public.question_bank USING btree (article_id);
CREATE INDEX IF NOT EXISTS idx_q_exam ON public.question_bank USING btree (exam_category);
CREATE INDEX IF NOT EXISTS idx_q_lesson ON public.question_bank USING btree (lesson_id);
CREATE INDEX IF NOT EXISTS idx_q_module ON public.question_bank USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_q_tags ON public.question_bank USING gin (tags);
CREATE INDEX IF NOT EXISTS question_bank_template_id_idx ON public.question_bank USING btree (template_id) WHERE (template_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_qa_email ON public.quiz_attempts USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_orgid_org_id ON public.quiz_attempts USING btree (org_id) WHERE (org_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_rb_deleted_by ON public.recycle_bin USING btree (deleted_by);
CREATE INDEX IF NOT EXISTS idx_rb_table ON public.recycle_bin USING btree (original_table);
CREATE INDEX IF NOT EXISTS idx_rb_type ON public.recycle_bin USING btree (item_type);
CREATE INDEX IF NOT EXISTS idx_registered_users_email ON public.registered_users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_registered_users_self_checkout ON public.registered_users USING btree (email) WHERE (equipment_self_checkout = true);
CREATE INDEX IF NOT EXISTS idx_registered_users_worker_classification ON public.registered_users USING btree (worker_classification);
CREATE INDEX IF NOT EXISTS idx_rp_user ON public.rewards_purchases USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_role_tiers_aliases_gin ON public.role_tiers USING gin (aliases);
CREATE INDEX IF NOT EXISTS idx_sb_date ON public.scheduled_bonuses USING btree (scheduled_date);
CREATE INDEX IF NOT EXISTS idx_sb_email ON public.scheduled_bonuses USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_sb_status ON public.scheduled_bonuses USING btree (status);
CREATE INDEX IF NOT EXISTS idx_article_completions_article ON public.user_article_completions USING btree (article_id);
CREATE INDEX IF NOT EXISTS idx_article_completions_user ON public.user_article_completions USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_ub_user ON public.user_badges USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_ulp_module ON public.user_lesson_progress USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_ulp_status ON public.user_lesson_progress USING btree (user_email, status);
CREATE INDEX IF NOT EXISTS idx_ulp_user ON public.user_lesson_progress USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_up_email ON public.user_progress USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_withdrawal_email ON public.withdrawal_requests USING btree (user_email);
CREATE INDEX IF NOT EXISTS idx_xt_type ON public.xp_transactions USING btree (transaction_type);
CREATE INDEX IF NOT EXISTS idx_xt_user ON public.xp_transactions USING btree (user_email);
