-- 440_fs_prep_photos.sql
-- FS prep — intersperse vetted, open-licensed surveying photos through the
-- module lessons to break up the text. Each image is proportionally scaled
-- (undistorted) and carries a professional caption + attribution credit.
-- Sourced from Wikimedia Commons (Public Domain / CC0 / CC BY / CC BY-SA);
-- see public/lessons/fs/photos/CREDITS.json. Generated by scripts/gen-embed-seed.mjs.
BEGIN;
-- Insert a figure markdown after the p_after-th paragraph of the first
-- section of type p_type in module p_mod. Idempotent (skips if already present).
CREATE OR REPLACE FUNCTION fs_insert_figure(p_mod int, p_type text, p_after int, p_fig text)
RETURNS void AS $fn$
DECLARE arr jsonb; i int; el jsonb; parts text[]; n int; k int;
BEGIN
  SELECT content_sections INTO arr FROM fs_study_modules WHERE module_number = p_mod;
  IF arr IS NULL THEN RETURN; END IF;
  FOR i IN 0 .. jsonb_array_length(arr) - 1 LOOP
    el := arr -> i;
    IF el ->> 'type' = p_type THEN
      IF position(p_fig IN coalesce(el ->> 'content', '')) > 0 THEN RETURN; END IF;
      parts := regexp_split_to_array(el ->> 'content', E'\n\n');
      n := coalesce(array_length(parts, 1), 0);
      k := least(greatest(p_after, 1), n);
      parts := parts[1:k] || ARRAY[p_fig] || parts[k+1:n];
      arr := jsonb_set(arr, ARRAY[i::text, 'content'], to_jsonb(array_to_string(parts, E'\n\n')));
      UPDATE fs_study_modules SET content_sections = arr WHERE module_number = p_mod;
      RETURN;
    END IF;
  END LOOP;
END;
$fn$ LANGUAGE plpgsql;

SELECT fs_insert_figure(1, 'overview', 1, $img$![A historic survey party in the field. Surveying has always paired careful field observation with disciplined measurement and record-keeping — the same foundation the FS exam tests.](/lessons/fs/photos/m1-survey-crew.jpg "Photo: Elias Olcott Beaman / James Fennemore / John… — Public domain, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(2, 'examples', 1, $img$![An automatic (dumpy) level. Differential leveling uses instruments like this to carry an elevation from a known benchmark to new points, one balanced backsight/foresight setup at a time.](/lessons/fs/photos/m2-differential-leveling.jpg "Photo: Gampe — CC BY-SA 4.0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(3, 'concepts', 2, $img$![A surveyor sighting through an optical theodolite. The theodolite measures horizontal and vertical angles — the angular half of every distance-and-angle observation.](/lessons/fs/photos/m3-theodolite.jpg "Photo: Queensland State Archives — Public domain, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(3, 'examples', 1, $img$![A retroreflective prism target. A total station’s EDM fires an infrared beam at the prism and times its return to measure slope distance to the point.](/lessons/fs/photos/m3-prism-pole.jpg "Photo: KJG2007 — Public domain, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(4, 'concepts', 2, $img$![A total station set up over a control point during a traverse. Each setup measures the angle and distance to the next station, and coordinates are propagated by latitudes and departures.](/lessons/fs/photos/m4-total-station-road.jpg "Photo: FBenjr123 — CC BY-SA 4.0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(4, 'examples', 1, $img$![A handheld EDM / data collector. Modern traverse and COGO work is recorded and reduced electronically in the field, but the underlying geometry is exactly what you compute by hand here.](/lessons/fs/photos/m4-data-collector.jpg "Photo: Krzysztof Maria Różański, ( Upior polnocy ) — CC BY 2.5, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(5, 'overview', 1, $img$![A horizontal curve on a highway. Route-surveying geometry — radius R, tangent T, external E, and central angle I — is one of the most heavily tested computation topics.](/lessons/fs/photos/m5-highway-curve.jpg "Photo: formulanone from Huntsville, United States — CC BY-SA 2.0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(5, 'examples', 1, $img$![Earthwork grading on a road project. Cut-and-fill volumes between stations are computed from cross-section end areas by the average-end-area method.](/lessons/fs/photos/m5-earthwork-grading.jpg "Photo: Krzysztof Popławski — CC BY 4.0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(6, 'concepts', 2, $img$![A GPS satellite in orbit. GNSS positioning trilaterates a ground position from simultaneous ranges to multiple satellites in view.](/lessons/fs/photos/m6-gps-constellation.jpg "Photo: NASA — Public domain, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(6, 'examples', 1, $img$![A permanent GNSS reference-station antenna (a CORS). Continuously operating reference stations provide the base observations for RTK and post-processed positioning.](/lessons/fs/photos/m6-cors-antenna.jpg "Photo: Karlbrix — CC BY-SA 4.0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(7, 'overview', 1, $img$![A set boundary monument. Physical monuments are the highest form of evidence for a property corner — they generally control over record distances and bearings.](/lessons/fs/photos/m7-boundary-monument.jpg "Photo: Osumi Akari — CC BY-SA 4.0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(7, 'examples', 1, $img$![A surveyor recovering a corner with a GNSS rover. Locating and honoring the original monuments is the heart of boundary retracement and the PLSS.](/lessons/fs/photos/m7-section-corner.jpg "Photo: Intermountain Region US Forest Service — Public domain, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(8, 'concepts', 2, $img$![An aerial view of the landscape. Photogrammetry turns overlapping aerial and UAV imagery into measurable maps, orthophotos, and elevation models.](/lessons/fs/photos/m8-survey-drone.jpg "Photo: Chensiyuan — CC BY-SA 4.0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(8, 'examples', 1, $img$![A topographic map. Contour lines and mapped features are the end product of the mapping, GIS, and photogrammetry workflow.](/lessons/fs/photos/m8-gis-map.jpg "Photo: Geological Survey (U.S.); Marshall, R.; Tatu… — Public domain, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(9, 'overview', 1, $img$![An NCEES-approved scientific calculator. Fluency with DMS entry, rectangular↔polar conversion, and memory registers is worth real points and minutes on exam day.](/lessons/fs/photos/m9-scientific-calculator.jpg "Photo: Jphill19 — CC BY-SA 4.0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(10, 'concepts', 1, $img$![A surveyor operating a total station. The FS exam pulls from every field and office skill practiced across these modules — this review ties them together.](/lessons/fs/photos/m10-field-survey-scene.jpg "Photo: Photograph: Frank C. Müller , Baden-Baden — CC BY-SA 4.0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(11, 'concepts', 1, $img$![A recorded plat. The plat is the legal drawing that documents a survey and creates the parcels — where professional practice, boundary law, and business meet.](/lessons/fs/photos/m11-plat-map.jpg "Photo: Department of Commerce. Bureau of Public Roa… — Public domain, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(11, 'overview', 1, $img$![A surveyor in high-visibility PPE working near traffic. Professional practice includes job-site safety, OSHA compliance, and the standard of care owed to the public.](/lessons/fs/photos/m11-site-safety.jpg "Photo: Retired electrician — CC0, via Wikimedia Commons")$img$);
SELECT fs_insert_figure(1, 'tips', 1, $img$![A Starr Surveying crew member running a total station in the field — the everyday reality behind the theory you are studying.](/lessons/fs/photos/starr-branded-crew.jpg "Photo: Starr Surveying (field photo)")$img$);
SELECT fs_insert_figure(1, 'examples', 1, $img$![Checking a measurement by hand with a steel tape. Even in the electronic era, a good surveyor verifies distances directly in the field.](/lessons/fs/photos/starr-tape-check.jpg "Photo: Starr Surveying (field photo)")$img$);
SELECT fs_insert_figure(3, 'tips', 1, $img$![Sighting through the total station to turn a precise angle — steady setup, careful pointing, and a check angle are what keep angular error small.](/lessons/fs/photos/starr-total-station-sighting.jpg "Photo: Starr Surveying (field photo)")$img$);
SELECT fs_insert_figure(4, 'tips', 1, $img$![Directing the rod person from an occupied station during a traverse. Clear communication and good station geometry make a clean, checkable traverse.](/lessons/fs/photos/starr-crew-directing.jpg "Photo: Starr Surveying (field photo)")$img$);
SELECT fs_insert_figure(6, 'tips', 1, $img$![A Starr Surveying GNSS rover with data collector. RTK positioning fixes coordinates in seconds — but you still need to understand datums, geoid height, and check shots.](/lessons/fs/photos/starr-gnss-rover.jpg "Photo: Starr Surveying (field photo)")$img$);
SELECT fs_insert_figure(10, 'examples', 1, $img$![A total station set and leveled over a point, ready to observe. Every field problem in this review starts with a correct instrument setup.](/lessons/fs/photos/starr-total-station-setup.jpg "Photo: Starr Surveying (field photo)")$img$);
SELECT fs_insert_figure(10, 'tips', 1, $img$![Operating the instrument on a Starr Surveying job. On exam day, picture the real field task behind each question — it keeps the computations grounded.](/lessons/fs/photos/starr-total-station-operate.jpg "Photo: Starr Surveying (field photo)")$img$);

DROP FUNCTION IF EXISTS fs_insert_figure(int, text, int, text);
COMMIT;
