-- seeds/468_dnd_creatures_canonical.sql — one creature, one entry in the list (N7 / N3-6).
--
-- ── THE DEFECT, MEASURED ─────────────────────────────────────────────────────────────────────────────
--
-- The owner reported the bestiary "showing a bunch of transposed duplicates", and it is exactly right:
--
--     5,025 rows            3,659 distinct creature names
--     Badger, Balor, Behir, Ghoul, Animated Armor — TEN ROWS EACH
--
-- Browsing meant scrolling past the same creature ten times. The Badger's ten break down like this, and
-- the breakdown is the whole design of this view:
--
--     3 rows  dnd5e-2014      SRD 5.1 / Black Flag / Monstrous Menagerie   — three books, three publishers
--     3 rows  dnd5e-2024      "Transposed from …"                          — GENERATED by us
--     3 rows  intuitive-games "Transposed from …"                          — GENERATED by us
--     1 row   pathfinder2e    Pathfinder Bestiary 2                        — a publisher
--
-- So there are two different duplications wearing one coat, and they do not have the same answer.
--
-- ── WHY THE ROWS STAY AND ONLY THE LIST CHANGES ──────────────────────────────────────────────────────
--
-- N3 says a derived row must never overwrite a published one, and that stays right. The fix is NOT fewer
-- rows: it is that the LIST is a list of creatures while the ROWS are storage. A view is precisely that
-- distinction made executable — the table keeps every book's Badger, and the catalogue shows one.
--
-- Nothing is deleted here. That matters beyond caution: 44 of the 600 generated rows carry fetched
-- artwork with its own licence and attribution (seed 467), and deleting rows to tidy a list would throw
-- away work whose provenance we are contractually obliged to keep.
--
-- ── THE 600 GENERATED ROWS ARE NOW REDUNDANT, AND THAT IS CHECKED, NOT ASSUMED ───────────────────────
--
-- `generate-transposed-bestiary.mjs` wrote 600 rows (300 dnd5e-2024, 300 intuitive-games) that carry a
-- source system's numbers into another system's page. N3-3's lens now does that at render time and does it
-- BETTER — derived from the target system's own measured tier table rather than carrying foreign figures.
-- They are a stale cache of a worse conversion.
--
-- They are also provably lossless to hide, which is the only reason this view can rank them last without
-- an argument: **the generated rows contribute ZERO distinct creature names.** 3,659 names across all
-- 5,025 rows; 3,659 names across the 4,425 published rows alone. Every generated row's creature has a
-- published row to represent it, so ranking them last can never make a creature disappear from the
-- catalogue. `__tests__/dnd/bestiary-canonical.test.ts` and `npm run audit:bestiary` both assert it, so an
-- import that broke the property would fail rather than silently drop creatures from the list.
--
-- ── IDENTITY IS THE NAME, DELIBERATELY AND WITH ITS COST STATED ──────────────────────────────────────
--
-- lower(btrim(name)). The plan calls identity "the hard part, and it is not the name" — and the honest
-- position is that name is the best available key here rather than a perfect one:
--
--   * It is the SAME key `loadSiblings` uses for the page's system lens (N3-3). A list that groups one way
--     while the page it opens groups another is worse than either rule alone.
--   * It is exact, never fuzzy. "Badger" must not absorb "Giant Badger", and a prefix or trigram match is
--     precisely how it would.
--   * WHAT IT COSTS: two genuinely different creatures that share a name get merged. Measured, this is
--     narrow — the collisions are overwhelmingly the same creature reprinted (the SRD Badger and the Black
--     Flag Badger ARE the badger) — but "Adult Red Dragon" is printed at two different CRs across books,
--     and this view shows one of them and counts the rest. `row_count` and `systems` are exposed for
--     exactly that reason: the entry can SAY it stands for four rows instead of pretending it is the only
--     one.
--
-- ── UNION FACETS, BECAUSE A DEDUPED LIST BREAKS PER-ROW ONES ─────────────────────────────────────────
--
-- Once one row represents a creature, filtering on that row's `system` would hide the creature from every
-- other system it is published in — the Pathfinder Badger would vanish from the Pathfinder filter because
-- the 5e row won the ranking. So `systems`, `types`, `alignments` and `tags` are UNIONS across all of a
-- creature's rows, and the page filters with array containment.
--
-- Known imprecision, stated rather than papered over: system and type are unioned INDEPENDENTLY, so
-- filtering `pathfinder2e` + `beast` matches a creature that is published in Pathfinder and typed "beast"
-- in its 5e row. It is a real creature in both facets rather than a phantom, and the alternative (a
-- per-system facet key) buys precision nobody has asked for at the cost of a filter nobody can read.

BEGIN;

-- Cheap enough at 5k rows that this is a tripwire rather than a plan, but the grouping key is the thing
-- every query here sorts and partitions on, so it gets an index instead of 5,025 lower() calls per page.
CREATE INDEX IF NOT EXISTS dnd_creatures_identity_idx
  ON public.dnd_creatures ((lower(btrim(name))));

DROP VIEW IF EXISTS public.dnd_creatures_canonical;
DROP MATERIALIZED VIEW IF EXISTS public.dnd_creatures_canonical;

-- ── MATERIALIZED, AND ONLY BECAUSE A PLAIN VIEW WAS MEASURED FIRST ──────────────────────────────────
--
-- This shipped as a plain VIEW, which is the right default — always correct, nothing to refresh. Then the
-- bestiary returned **500 Internal Server Error** on `?system=dnd5e-2014&type=beast`:
--
--       123ms   count(*) over the whole view
--      4064ms   one array filter
--      2317ms   two array filters
--      2276ms   one sorted page of 60
--
-- Postgres cannot index through a window function, so every request re-ran the rank over all 5,025 rows,
-- re-aggregated the lateral unnest, and only then filtered. PostgREST issues the count and the page, and
-- the facets add two more reads — four multi-second scans per page load, past the statement timeout.
--
-- Worth stating because it is the reason a plain view was tried at all: the first, one-filter query is the
-- SLOWEST of the four. A filter that matches more rows costs more, so the catalogue growing makes this
-- worse rather than better, and "it is only 5,000 rows" was exactly the wrong instinct.
--
-- ── WHAT MATERIALIZING COSTS, STATED PLAINLY ────────────────────────────────────────────────────────
--
-- Staleness. The fold is a snapshot, so a creature imported after the last refresh is INVISIBLE in the
-- list while sitting perfectly well in the table — which is this repo's signature defect (content that
-- exists and is unreachable) reintroduced by a performance fix.
--
-- Three things make that acceptable rather than a trap:
--
--   1. The table changes only by a deliberate script run (`import:bestiary`, `import:bestiary:pf2`,
--      `art:creatures`, `generate:bestiary`), never by user action. Those scripts refresh when they finish.
--   2. `refresh_dnd_creatures_canonical()` is one call, so nothing has to remember the statement.
--   3. `npm run audit:bestiary` FAILS HARD on staleness by comparing the snapshot's own `sum(row_count)`
--      against the live table count — an exact check that catches a single added or deleted row, not just
--      a new creature name.
--
-- CONCURRENTLY is available (the unique index below exists for it) so a refresh never blocks readers.

CREATE MATERIALIZED VIEW public.dnd_creatures_canonical AS
WITH agg AS (
  -- Everything a creature is, across every row that spells its name the same way. The lateral unnest
  -- multiplies rows, so every aggregate here is DISTINCT and the row count is over distinct ids.
  SELECT
    lower(btrim(c.name))                                              AS identity,
    count(DISTINCT c.id)                                              AS row_count,
    array_agg(DISTINCT c.system)                                      AS systems,
    array_agg(DISTINCT c.source)                                      AS sources,
    coalesce(array_agg(DISTINCT c.type)      FILTER (WHERE c.type      IS NOT NULL), '{}') AS types,
    coalesce(array_agg(DISTINCT c.alignment) FILTER (WHERE c.alignment IS NOT NULL), '{}') AS alignments,
    coalesce(array_agg(DISTINCT t)           FILTER (WHERE t           IS NOT NULL), '{}') AS all_tags,
    -- Systems the creature is PUBLISHED in, which is not the same list as `systems` and is what the lens
    -- calls a designer's numbers. A creature present in dnd5e-2024 only as a row we generated is not
    -- published in 2024.
    coalesce(array_agg(DISTINCT c.system) FILTER (WHERE c.source NOT LIKE 'Transposed from %'), '{}')
                                                                      AS published_systems
  FROM public.dnd_creatures c
  LEFT JOIN LATERAL unnest(c.tags) AS t ON true
  GROUP BY 1
),
ranked AS (
  SELECT
    c.*,
    row_number() OVER (
      PARTITION BY lower(btrim(c.name))
      ORDER BY
        -- 1. A publisher's row always represents the creature. A row we generated never does while a
        --    published one exists — it is the stale cache described above.
        (c.source LIKE 'Transposed from %'),
        -- 2. The site-wide default edition first, so the entry a reader opens is usually already the
        --    system the lens opens on and needs no derivation at all.
        CASE c.system
          WHEN 'dnd5e-2024'      THEN 0
          WHEN 'dnd5e-2014'      THEN 1
          WHEN 'pathfinder2e'    THEN 2
          WHEN 'intuitive-games' THEN 3
          ELSE 4
        END,
        -- 3. An entry with artwork beats one without: the card that gets shown should be the one that
        --    looks like something. Art is sparse (477 of 5,025), so this decides a lot of ties.
        (c.image_url IS NULL),
        -- 4. Stable, so the catalogue does not reshuffle between page loads.
        c.slug
    ) AS rn
  FROM public.dnd_creatures c
)
SELECT
  r.id, r.slug, r.name, r.system, r.type, r.size, r.alignment, r.cr, r.cr_sort,
  r.statblock, r.description, r.image_url, r.image_licence, r.image_attribution, r.image_source_url,
  r.tags, r.environments, r.source, r.licence, r.attribution, r.source_url, r.variant_eligible,
  lower(btrim(r.name))  AS identity,
  a.row_count,
  a.systems,
  a.published_systems,
  a.sources,
  a.types,
  a.alignments,
  a.all_tags
FROM ranked r
JOIN agg a ON a.identity = lower(btrim(r.name))
WHERE r.rn = 1;

-- ── INDEXES — the entire point of materializing ─────────────────────────────────────────────────────
--
-- UNIQUE on identity first: REFRESH CONCURRENTLY REQUIRES one, and without it every refresh takes an
-- ACCESS EXCLUSIVE lock and the bestiary 500s for the duration of an import. It also re-asserts
-- one-entry-per-creature as a constraint rather than a hope — a ranking bug that produced two rows for a
-- name would fail the refresh instead of silently double-listing.
CREATE UNIQUE INDEX dnd_creatures_canonical_identity_idx
  ON public.dnd_creatures_canonical (identity);

-- GIN for the containment filters. These are the queries that timed out.
CREATE INDEX dnd_creatures_canonical_systems_idx    ON public.dnd_creatures_canonical USING gin (systems);
CREATE INDEX dnd_creatures_canonical_types_idx      ON public.dnd_creatures_canonical USING gin (types);
CREATE INDEX dnd_creatures_canonical_alignments_idx ON public.dnd_creatures_canonical USING gin (alignments);
CREATE INDEX dnd_creatures_canonical_tags_idx       ON public.dnd_creatures_canonical USING gin (all_tags);

-- The list's sort — weakest first, then by name — and the CR band filter, which is a range on cr_sort.
CREATE INDEX dnd_creatures_canonical_order_idx ON public.dnd_creatures_canonical (cr_sort, name);

-- One name for the refresh, so no caller has to remember CONCURRENTLY or the fully-qualified relation.
-- SECURITY DEFINER because the scripts connect as an application role that does not own the view.
CREATE OR REPLACE FUNCTION public.refresh_dnd_creatures_canonical()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.dnd_creatures_canonical;
EXCEPTION
  -- CONCURRENTLY cannot run against a snapshot that has never been populated. Falling back keeps a fresh
  -- database from needing a special first-run step; every later refresh takes the concurrent path.
  WHEN OBJECT_NOT_IN_PREREQUISITE_STATE THEN
    REFRESH MATERIALIZED VIEW public.dnd_creatures_canonical;
END;
$$;

COMMENT ON FUNCTION public.refresh_dnd_creatures_canonical() IS
  'Re-fold dnd_creatures into the canonical one-entry-per-creature snapshot. Call at the end of anything '
  'that writes to dnd_creatures — the bestiary LIST reads the snapshot, so a creature imported without a '
  'refresh is catalogued and unreachable. npm run audit:bestiary fails hard when the two disagree.';

COMMENT ON MATERIALIZED VIEW public.dnd_creatures_canonical IS
  'One row per creature identity (lower(btrim(name))) for the bestiary LIST — N7. The table keeps every '
  'book''s and every generated row; this picks the one that represents the creature (published before '
  'generated, 2024 first, art before none, slug as a stable tiebreak) and unions systems/types/alignments/'
  'tags across all of them so filters do not hide a creature because another system''s row won the '
  'ranking. Read by loadBestiary in lib/dnd/bestiary/query.ts. NOT a deduplication of the data: the '
  'creature PAGE still reads dnd_creatures directly, and the system lens still needs every row.';

GRANT SELECT ON public.dnd_creatures_canonical TO service_role;
GRANT SELECT ON public.dnd_creatures_canonical TO authenticated;
GRANT SELECT ON public.dnd_creatures_canonical TO anon;
GRANT EXECUTE ON FUNCTION public.refresh_dnd_creatures_canonical() TO service_role;

COMMIT;

-- Populate it now, so applying this seed leaves a usable catalogue rather than an empty list that looks
-- like an import failure. Outside the transaction: CONCURRENTLY cannot run inside one.
SELECT public.refresh_dnd_creatures_canonical();

-- PostgREST caches the schema; without this the view is invisible to the client until the next reload and
-- the bestiary would 404 its own query on a freshly-applied database.
NOTIFY pgrst, 'reload schema';

-- ─── Verification ────────────────────────────────────────────────────────────────────────────────────
-- Run after applying:
--
--   SELECT count(*) FROM public.dnd_creatures;             -- expect 5025
--   SELECT count(*) FROM public.dnd_creatures_canonical;   -- expect 3659, one per distinct name
--   SELECT count(DISTINCT lower(btrim(name))) FROM public.dnd_creatures;  -- expect the same 3659
--
--   -- No entry is represented by a row we generated (the zero-distinct-names property above):
--   SELECT count(*) FROM public.dnd_creatures_canonical WHERE source LIKE 'Transposed from %';
--   -- expect 0
--
--   -- The Badger is one entry, standing for ten rows in four systems, published in two of them:
--   SELECT slug, system, row_count, systems, published_systems
--   FROM public.dnd_creatures_canonical WHERE identity = 'badger';
