-- seeds/499_baseline_fks.sql
--
-- Schema reconstruction for tables that existed ONLY in the live database.
-- GENERATED by scripts/dump-missing-schema.mjs — do not hand-edit; regenerate.
-- Verified column-for-column against production by scripts/verify-baseline-schema.mjs.
--
-- Background: docs/planning/PLATFORM_AUDIT_AND_LAUNCH_QUESTIONS_2026-07-29.md §1.1.
-- 78 tables the app queries every day — including `jobs`, the central business entity —
-- had no CREATE statement anywhere in seeds/. They were only ever ALTERed (seeds
-- 280/304/306/452), so a fresh database could not be built from this repo, there was no
-- way to stand up staging, and every schema change was an undocumented dashboard click.
--
-- Every statement is idempotent, so applying this to the existing production database is
-- a no-op. Guarded by __tests__/schema-coverage.test.ts.
--
-- RUNS LAST (before the 500-block). These foreign keys reference tables created across
-- the whole seed range — conversations, organizations, receipts, vehicles, job_files,
-- kb_articles, problem_templates and others — so every one of them must already exist.
--
-- Each ALTER is wrapped so re-running is a no-op. `undefined_table` is NOT swallowed:
-- a missing referenced table means the seed order is genuinely wrong and should fail
-- loudly rather than silently ship a database with no referential integrity.

DO $$ BEGIN
  ALTER TABLE public.admin_discussion_threads ADD CONSTRAINT admin_discussion_threads_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.assignments ADD CONSTRAINT assignments_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.assignments ADD CONSTRAINT assignments_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.employee_earned_credentials ADD CONSTRAINT employee_earned_credentials_credential_key_fkey FOREIGN KEY (credential_key) REFERENCES credential_bonuses(credential_key);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.employee_learning_credits ADD CONSTRAINT employee_learning_credits_credit_value_id_fkey FOREIGN KEY (credit_value_id) REFERENCES learning_credit_values(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.employee_profiles ADD CONSTRAINT employee_profiles_tier_key_fkey FOREIGN KEY (tier_key) REFERENCES role_tiers(role_key) ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.employee_threshold_achievements ADD CONSTRAINT employee_threshold_achievements_threshold_id_fkey FOREIGN KEY (threshold_id) REFERENCES credit_thresholds(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.equipment_inventory ADD CONSTRAINT equipment_inventory_acq_receipt_fk FOREIGN KEY (linked_acquisition_receipt_id) REFERENCES receipts(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.equipment_inventory ADD CONSTRAINT equipment_inventory_current_job_id_fkey FOREIGN KEY (current_job_id) REFERENCES jobs(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.equipment_inventory ADD CONSTRAINT equipment_inventory_current_reservation_fk FOREIGN KEY (current_reservation_id) REFERENCES equipment_reservations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.equipment_inventory ADD CONSTRAINT equipment_inventory_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.error_reports ADD CONSTRAINT error_reports_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.fs_module_progress ADD CONSTRAINT fs_module_progress_module_id_fkey FOREIGN KEY (module_id) REFERENCES fs_study_modules(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_checklists ADD CONSTRAINT job_checklists_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_equipment ADD CONSTRAINT job_equipment_inventory_fk FOREIGN KEY (equipment_inventory_id) REFERENCES equipment_inventory(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_equipment ADD CONSTRAINT job_equipment_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_field_data ADD CONSTRAINT job_field_data_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_payments ADD CONSTRAINT job_payments_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_research ADD CONSTRAINT job_research_file_id_fkey FOREIGN KEY (file_id) REFERENCES job_files(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_research ADD CONSTRAINT job_research_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_stages_history ADD CONSTRAINT job_stages_history_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_tags ADD CONSTRAINT job_tags_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_tags ADD CONSTRAINT job_tags_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_team ADD CONSTRAINT job_team_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_team ADD CONSTRAINT job_team_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.job_time_entries ADD CONSTRAINT job_time_entries_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.jobs ADD CONSTRAINT jobs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.learning_lessons ADD CONSTRAINT learning_lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES learning_modules(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.learning_lessons ADD CONSTRAINT learning_lessons_prerequisite_lesson_id_fkey FOREIGN KEY (prerequisite_lesson_id) REFERENCES learning_lessons(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.learning_modules ADD CONSTRAINT learning_modules_credential_key_fkey FOREIGN KEY (credential_key) REFERENCES credential_bonuses(credential_key) ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.learning_topics ADD CONSTRAINT learning_topics_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES learning_lessons(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.lesson_blocks ADD CONSTRAINT lesson_blocks_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES learning_lessons(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.lesson_required_articles ADD CONSTRAINT lesson_required_articles_article_id_fkey FOREIGN KEY (article_id) REFERENCES kb_articles(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.lesson_required_articles ADD CONSTRAINT lesson_required_articles_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES learning_lessons(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.lesson_versions ADD CONSTRAINT lesson_versions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES learning_lessons(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.module_completions ADD CONSTRAINT module_completions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.pay_stubs ADD CONSTRAINT pay_stubs_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES payroll_runs(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.payout_log ADD CONSTRAINT payout_log_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.question_bank ADD CONSTRAINT question_bank_article_id_fkey FOREIGN KEY (article_id) REFERENCES kb_articles(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.question_bank ADD CONSTRAINT question_bank_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES learning_lessons(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.question_bank ADD CONSTRAINT question_bank_template_id_fkey FOREIGN KEY (template_id) REFERENCES problem_templates(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.question_bank ADD CONSTRAINT question_bank_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES learning_topics(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.quiz_attempt_answers ADD CONSTRAINT quiz_attempt_answers_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES quiz_attempts(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.quiz_attempt_answers ADD CONSTRAINT quiz_attempt_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES question_bank(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.quiz_attempts ADD CONSTRAINT quiz_attempts_article_id_fkey FOREIGN KEY (article_id) REFERENCES kb_articles(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.quiz_attempts ADD CONSTRAINT quiz_attempts_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES learning_lessons(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.quiz_attempts ADD CONSTRAINT quiz_attempts_module_id_fkey FOREIGN KEY (module_id) REFERENCES learning_modules(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.quiz_attempts ADD CONSTRAINT quiz_attempts_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.registered_users ADD CONSTRAINT registered_users_default_org_id_fkey FOREIGN KEY (default_org_id) REFERENCES organizations(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.rewards_purchases ADD CONSTRAINT rewards_purchases_item_id_fkey FOREIGN KEY (item_id) REFERENCES rewards_catalog(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.user_article_completions ADD CONSTRAINT user_article_completions_article_id_fkey FOREIGN KEY (article_id) REFERENCES kb_articles(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.user_badges ADD CONSTRAINT user_badges_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES badges(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.user_milestone_progress ADD CONSTRAINT user_milestone_progress_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES curriculum_milestones(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.user_progress ADD CONSTRAINT user_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES learning_lessons(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.user_progress ADD CONSTRAINT user_progress_module_id_fkey FOREIGN KEY (module_id) REFERENCES learning_modules(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.withdrawal_requests ADD CONSTRAINT withdrawal_requests_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES balance_transactions(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.xp_milestone_achievements ADD CONSTRAINT xp_milestone_achievements_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES xp_pay_milestones(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
