-- seeds/649_file_node_thumbnails.sql — previews for the File Explorer's own documents
--
-- Owner, 2026-09-19: "Please make sure that in our filing system for the jobs we have a way to
-- choose different tiles sizes for each file preview so that we can see a thumbnail of each
-- document/pdf/photo/video easily."
--
-- ── WHY THIS IS A SECOND COPY OF seeds/644, AND NOT A SHARED TABLE ──────────────────────────────
--
-- 644 put `thumb_path`/`thumb_bucket`/`thumb_state`/`thumb_updated_at` on `job_files`, for the file
-- panel beside the property map. The Explorer shows a MOUNT — a view over several source tables —
-- and a job's Files tab is a mount over `job_files`. So the job case this request is actually about
-- is already covered: those rows have previews, generated by whoever last opened the map panel, and
-- the Explorer only ever had to start reading them.
--
-- `file_nodes` — the Explorer's own documents, the ones that are not a mount of anything — had no
-- such column, and that is what this adds.
--
-- A generic `file_previews(source_key, source_id, …)` table was the obvious alternative and was not
-- taken. It would have meant every job file having a preview in two places: the one the map panel
-- generated on `job_files`, and a second one here that nothing else could see. Two rows that are
-- supposed to agree about the same picture is a thing to keep in step forever; reading the column
-- that already exists is not.
--
-- The other mount sources (research documents, receipts, CAD drawings, field media) are left alone
-- deliberately. None of them has a preview column, each would need its own, and none of them is
-- what was asked for. They keep their icons, and a small photograph still shows itself.
--
-- ── WHY THE BROWSER MAKES THEM ──────────────────────────────────────────────────────────────────
--
-- Unchanged from 644, and the reasoning is quoted there in full: a PDF's first page needs a PDF
-- renderer and a video's poster frame needs a video decoder, this deployment has neither, and every
-- browser that opens the Explorer has both. The first browser to look at a file makes the preview
-- and posts it; every browser after that is handed a signed URL.

BEGIN;

ALTER TABLE public.file_nodes
  -- Where the preview lives. Kept beside the document it previews, under a prefix nothing else
  -- writes to — see `thumbStoragePath` in lib/jobs/file-thumbnails.ts.
  ADD COLUMN IF NOT EXISTS thumb_path text,
  ADD COLUMN IF NOT EXISTS thumb_bucket text,
  -- pending    : nobody has tried yet (and the state of every row written before today)
  -- ok         : thumb_path holds a preview
  -- failed     : generation was attempted and did not work — do not keep retrying
  -- unsupported: this kind never gets one (audio, a .dwg, a plain text file)
  ADD COLUMN IF NOT EXISTS thumb_state text NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS thumb_updated_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'file_nodes_thumb_state_check') THEN
    ALTER TABLE public.file_nodes
      ADD CONSTRAINT file_nodes_thumb_state_check
      CHECK (thumb_state IN ('pending', 'ok', 'failed', 'unsupported'));
  END IF;
END $$;

COMMENT ON COLUMN public.file_nodes.thumb_state IS
  'Whether this document has a generated preview: pending (nobody has tried), ok, failed (tried, do not retry), unsupported (never will have one). Previews are made by the first browser to need one — the deployment has no PDF renderer or video decoder — and kept here so the work happens once for everybody. Mirrors job_files; see seeds/649 and seeds/644.';

-- The Explorer's question, asked once per folder: which documents in here still need a preview?
-- `deleted_at` rather than an `is_deleted` boolean — file_nodes soft-deletes with a timestamp, and
-- the convention differs from job_files next door.
CREATE INDEX IF NOT EXISTS idx_file_nodes_thumb_pending
  ON public.file_nodes (parent_id) WHERE thumb_state = 'pending' AND deleted_at IS NULL;

COMMIT;
