// app/admin/equipment/inventory/inventory-styles.ts — the inventory page's inline style objects.
//
// Split out for platform audit item 18: the three unit dialogs and the table below them share this
// object, so it could not stay inside either file. Moved verbatim; item 17's token pay-down is a
// separate pass and is tracked by the hex ratchet.
import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  wrap: { padding: '24px', maxWidth: 1400, margin: '0 auto' },
  header: { marginBottom: 16 },
  h1: { fontSize: 22, fontWeight: 600, margin: '0 0 4px' },
  subtitle: {
    fontSize: 13,
    color: 'var(--color-text-tertiary)',
    margin: 0,
    maxWidth: 760,
    lineHeight: 1.5,
  },
  controls: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-end',
    gap: 12,
    marginBottom: 16,
  },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  fieldLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--color-text-tertiary)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    padding: '8px 10px',
    border: '1px solid #E2E5EB',
    borderRadius: 8,
    fontSize: 13,
    minWidth: 160,
  },
  // admin-ui-alignment-2026-08-14 — a <label> carries globals.css's 10px
  // bottom margin, and on a flex-end row the browser aligns the MARGIN box,
  // so this sat 6.5px above the fields beside it. The 8px bottom padding was
  // an earlier attempt at the same problem from the wrong end.
  checkboxField: {
    display: 'flex',
    alignItems: 'center',
    height: 'var(--input-height)',
    boxSizing: 'border-box',
    marginBottom: 0,
    gap: 6,
    fontSize: 13,
  },
  // admin-ui-alignment-2026-08-14 — these took their height from padding
  // (38.8px and 36.8px) beside the 40px filter fields on the same row.
  refreshBtn: {
    background: 'transparent',
    border: '1px solid #E2E5EB',
    borderRadius: 8,
    height: 'var(--button-height)',
    boxSizing: 'border-box',
    padding: '0 14px',
    cursor: 'pointer',
    fontSize: 13,
  },
  addBtn: {
    background: 'var(--color-brand-navy)',
    color: 'var(--color-text-on-brand)',
    border: 'none',
    borderRadius: 8,
    height: 'var(--button-height)',
    boxSizing: 'border-box',
    padding: '0 14px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
  },
  rowActionBtn: {
    background: 'transparent',
    border: '1px solid #E2E5EB',
    borderRadius: 6,
    padding: '4px 10px',
    cursor: 'pointer',
    fontSize: 12,
    color: 'var(--color-brand-navy)',
    fontWeight: 500,
  },
  rowActionBar: {
    display: 'inline-flex',
    gap: 6,
    justifyContent: 'flex-end',
  },
  bulkBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 14px',
    marginBottom: 12,
    background: 'var(--color-info-bg)',
    border: '1px solid #BFDBFE',
    borderRadius: 8,
    fontSize: 13,
    color: '#1E3A8A',
  },
  bulkLabel: {
    flex: 1,
  },
  thCheckbox: {
    textAlign: 'left',
    padding: '10px 8px 10px 14px',
    background: '#F7F8FA',
    borderBottom: '1px solid #E2E5EB',
    width: 32,
  },
  tdCheckbox: {
    padding: '10px 8px 10px 14px',
    borderBottom: '1px solid #F3F4F6',
    width: 32,
    verticalAlign: 'middle',
  },
  rowActionBtnRetire: {
    background: 'transparent',
    border: '1px solid #FCA5A5',
    borderRadius: 6,
    padding: '4px 10px',
    cursor: 'pointer',
    fontSize: 12,
    color: '#B91C1C',
    fontWeight: 500,
  },
  rowActionBtnRestore: {
    background: 'transparent',
    border: '1px solid #86EFAC',
    borderRadius: 6,
    padding: '4px 10px',
    cursor: 'pointer',
    fontSize: 12,
    color: '#15803D',
    fontWeight: 500,
  },
  submitBtn: {
    background: '#15803D',
    color: 'var(--color-text-on-brand)',
    border: 'none',
    borderRadius: 8,
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
  },
  actionMsgOk: {
    background: '#F0FDF4',
    border: '1px solid #86EFAC',
    color: '#15803D',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    fontSize: 13,
  },
  actionMsgWarn: {
    background: '#FEF3C7',
    border: '1px solid #FCD34D',
    color: '#92400E',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    fontSize: 13,
  },
  modalBackdrop: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15, 23, 42, 0.5)',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingTop: 60,
    zIndex: 1000,
  },
  modal: {
    background: 'var(--color-bg-card)',
    borderRadius: 12,
    width: '100%',
    maxWidth: 720,
    maxHeight: 'calc(100vh - 120px)',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.25)',
    display: 'flex',
    flexDirection: 'column',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 20px',
    borderBottom: '1px solid #E2E5EB',
  },
  modalTitle: { fontSize: 16, fontWeight: 600, margin: 0 },
  modalClose: {
    background: 'transparent',
    border: 'none',
    fontSize: 18,
    cursor: 'pointer',
    color: 'var(--color-text-tertiary)',
    lineHeight: 1,
    padding: 4,
  },
  modalBody: {
    padding: 20,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  modalFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    padding: '12px 20px',
    borderTop: '1px solid #E2E5EB',
    background: '#FAFBFC',
    borderRadius: '0 0 12px 12px',
  },
  modalHint: {
    fontSize: 12,
    color: 'var(--color-text-tertiary)',
    margin: 0,
    fontStyle: 'italic',
  },
  formField: { display: 'flex', flexDirection: 'column', gap: 4 },
  formLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: '#374151',
  },
  formInput: {
    padding: '8px 10px',
    border: '1px solid #E2E5EB',
    borderRadius: 6,
    fontSize: 13,
    fontFamily: 'inherit',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: 12,
  },
  fieldset: {
    border: '1px solid #E2E5EB',
    borderRadius: 8,
    padding: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  radioRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    fontSize: 13,
    cursor: 'pointer',
  },
  summary: {
    fontSize: 13,
    color: 'var(--color-text-tertiary)',
    marginBottom: 12,
  },
  empty: {
    padding: 32,
    textAlign: 'center',
    color: 'var(--color-text-tertiary)',
    background: '#F7F8FA',
    borderRadius: 12,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 13,
    border: '1px solid #E2E5EB',
    borderRadius: 12,
    overflow: 'hidden',
  },
  th: {
    textAlign: 'left',
    padding: '10px 14px',
    color: 'var(--color-text-tertiary)',
    fontWeight: 500,
    background: '#F7F8FA',
    borderBottom: '1px solid #E2E5EB',
  },
  thRight: {
    textAlign: 'right',
    padding: '10px 14px',
    color: 'var(--color-text-tertiary)',
    fontWeight: 500,
    background: '#F7F8FA',
    borderBottom: '1px solid #E2E5EB',
  },
  td: {
    padding: '10px 14px',
    borderBottom: '1px solid #F3F4F6',
    verticalAlign: 'middle',
  },
  tdRight: {
    padding: '10px 14px',
    borderBottom: '1px solid #F3F4F6',
    textAlign: 'right',
    fontVariantNumeric: 'tabular-nums',
  },
  retiredRow: {
    background: '#FAFAFA',
    color: 'var(--color-text-muted)',
  },
  statusPill: {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  photoBlock: {
    border: '1px solid #E2E5EB',
    borderRadius: 8,
    padding: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  photoRow: {
    display: 'flex',
    gap: 12,
    alignItems: 'flex-start',
  },
  photoPreview: {
    width: 96,
    height: 96,
    borderRadius: 8,
    objectFit: 'cover',
    border: '1px solid #E2E5EB',
    background: '#F7F8FA',
    flexShrink: 0,
  },
  photoPlaceholder: {
    width: 96,
    height: 96,
    borderRadius: 8,
    background: '#F7F8FA',
    border: '1px dashed #E2E5EB',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    color: 'var(--color-text-muted)',
    flexShrink: 0,
    textAlign: 'center',
    padding: 8,
  },
  photoControls: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  fileBtn: {
    background: 'var(--color-brand-navy)',
    color: 'var(--color-text-on-brand)',
    border: 'none',
    borderRadius: 6,
    padding: '6px 12px',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 500,
    alignSelf: 'flex-start',
  },
  nameCell: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  nameStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  nameBadges: {
    display: 'flex',
    gap: 4,
    flexWrap: 'wrap',
  },
  thumbnail: {
    width: 36,
    height: 36,
    borderRadius: 6,
    objectFit: 'cover',
    border: '1px solid #E2E5EB',
    background: '#F7F8FA',
    flexShrink: 0,
  },
  thumbnailFallback: {
    width: 36,
    height: 36,
    borderRadius: 6,
    background: '#F7F8FA',
    border: '1px solid #E2E5EB',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 18,
    flexShrink: 0,
  },
  thumbnailEmpty: {
    width: 36,
    height: 36,
    borderRadius: 6,
    background: '#FAFBFC',
    border: '1px dashed #E5E7EB',
    flexShrink: 0,
  },
  personalBadge: {
    marginLeft: 6,
    padding: '2px 6px',
    borderRadius: 4,
    background: '#E0E7FF',
    color: '#4338CA',
    fontSize: 10,
    fontWeight: 600,
  },
  suspectBadge: {
    marginLeft: 6,
    padding: '2px 6px',
    borderRadius: 4,
    background: '#FEE2E2',
    color: '#B91C1C',
    fontSize: 10,
    fontWeight: 600,
  },
  retiredBadge: {
    marginLeft: 6,
    padding: '2px 6px',
    borderRadius: 4,
    background: 'var(--color-bg-subtle)',
    color: 'var(--color-text-tertiary)',
    fontSize: 10,
    fontWeight: 600,
  },
  code: {
    fontFamily: 'Menlo, monospace',
    fontSize: 11,
    background: '#F7F8FA',
    padding: '2px 6px',
    borderRadius: 4,
  },
  muted: { color: 'var(--color-text-muted)' },
  lowStock: { color: '#B45309', fontWeight: 600 },
  note: {
    fontSize: 12,
    color: 'var(--color-text-muted)',
    marginTop: 24,
    fontStyle: 'italic',
  },
};
