// lib/cad/templates/default-templates.ts — Built-in drawing templates
import type { CompanyInfo, DrawingTemplate } from './types';
import { DEFAULT_CERTIFICATION_CONFIG } from './certification';
import { DEFAULT_LEGEND_CONFIG } from './legend';
import { DEFAULT_BORDER_CONFIG } from './sheet-border';
import { getDefaultNotes } from './standard-notes';

export const STARR_COMPANY_INFO: CompanyInfo = {
  name: 'Starr Surveying Company',
  address: '301 E. Central Avenue',
  cityStateZip: 'Belton, TX 76513',
  phone: '(254) 939-1009',
  email: 'info@starrsurveying.com',
  licenseNumber: 'RPLS #5634',
  logo: null,
};

const DEFAULT_TITLE_BLOCK_FIELDS = {
  projectName: '',
  projectSubtitle: '',
  projectAddress: '',
  clientName: '',
  surveyDate: '',
  sheetTitle: 'BOUNDARY SURVEY',
  sheetNumber: '1',
  drawnBy: '',
  checkedBy: '',
  jobNumber: '',
  scaleText: "1\" = 50'",
};

export const STARR_SURVEYING_TEMPLATE: DrawingTemplate = {
  id: 'starr-surveying-default',
  name: 'Starr Surveying — Standard',
  isBuiltIn: true,
  isEditable: false,
  paperSize: 'TABLOID',
  orientation: 'LANDSCAPE',
  margins: { top: 0.5, right: 0.5, bottom: 0.5, left: 0.5 },
  scale: 50,
  titleBlock: {
    position: 'BOTTOM_RIGHT',
    customBounds: null,
    fields: { ...DEFAULT_TITLE_BLOCK_FIELDS },
    showCompanyLogo: false,
    showCompanyInfo: true,
    showLicenseNumber: true,
    showSealPlaceholder: true,
    font: 'Arial',
    borderWeight: 0.5,
    dividerWeight: 0.25,
  },
  northArrow: {
    style: 'SIMPLE',
    position: { x: 14.5, y: 9.5 },
    size: 1.25,
    rotation: 0,
    showMagneticDeclination: false,
    magneticDeclination: 0,
  },
  scaleBar: {
    position: { x: 12.0, y: 9.5 },
    width: 2.0,
    segments: 4,
    units: 'FEET',
    font: 'Arial',
    fontSize: 7,
  },
  legend: {
    ...DEFAULT_LEGEND_CONFIG,
    position: { x: 0.5, y: 0.5 },
  },
  certification: {
    ...DEFAULT_CERTIFICATION_CONFIG,
    firmName: STARR_COMPANY_INFO.name,
    licenseNumber: STARR_COMPANY_INFO.licenseNumber,
    licenseState: 'Texas',
  },
  standardNotes: {
    position: { x: 0.5, y: 4.5 },
    width: 3.5,
    title: 'SURVEY NOTES',
    font: 'Arial',
    fontSize: 8,
    selectedNoteIds: getDefaultNotes().map((n) => n.id),
    customNotes: [],
  },
  border: { ...DEFAULT_BORDER_CONFIG },
  company: STARR_COMPANY_INFO,
};

export const LETTER_TEMPLATE: DrawingTemplate = {
  id: 'letter-portrait-default',
  name: 'Letter — Portrait',
  isBuiltIn: true,
  isEditable: false,
  paperSize: 'LETTER',
  orientation: 'PORTRAIT',
  margins: { top: 0.5, right: 0.5, bottom: 0.5, left: 0.5 },
  scale: 20,
  titleBlock: {
    position: 'BOTTOM_RIGHT',
    customBounds: null,
    fields: { ...DEFAULT_TITLE_BLOCK_FIELDS, scaleText: "1\" = 20'" },
    showCompanyLogo: false,
    showCompanyInfo: true,
    showLicenseNumber: true,
    showSealPlaceholder: true,
    font: 'Arial',
    borderWeight: 0.4,
    dividerWeight: 0.2,
  },
  northArrow: {
    style: 'SIMPLE',
    position: { x: 7.5, y: 10.0 },
    size: 0.75,
    rotation: 0,
    showMagneticDeclination: false,
    magneticDeclination: 0,
  },
  scaleBar: {
    position: { x: 5.5, y: 10.0 },
    width: 1.5,
    segments: 4,
    units: 'FEET',
    font: 'Arial',
    fontSize: 6,
  },
  legend: {
    ...DEFAULT_LEGEND_CONFIG,
    position: { x: 0.5, y: 0.5 },
    fontSize: 7,
  },
  certification: {
    ...DEFAULT_CERTIFICATION_CONFIG,
    position: { x: 0.5, y: 1.0 },
    width: 4.5,
    sealDiameter: 1.5,
  },
  standardNotes: {
    position: { x: 0.5, y: 3.5 },
    width: 3.0,
    title: 'SURVEY NOTES',
    font: 'Arial',
    fontSize: 7,
    selectedNoteIds: getDefaultNotes().map((n) => n.id),
    customNotes: [],
  },
  border: { ...DEFAULT_BORDER_CONFIG },
  company: STARR_COMPANY_INFO,
};

export const ARCH_D_TEMPLATE: DrawingTemplate = {
  id: 'arch-d-landscape-default',
  name: 'Arch D — Landscape',
  isBuiltIn: true,
  isEditable: false,
  paperSize: 'ARCH_D',
  orientation: 'LANDSCAPE',
  margins: { top: 0.75, right: 0.75, bottom: 0.75, left: 0.75 },
  scale: 100,
  titleBlock: {
    position: 'BOTTOM_RIGHT',
    customBounds: null,
    fields: { ...DEFAULT_TITLE_BLOCK_FIELDS, scaleText: "1\" = 100'" },
    showCompanyLogo: false,
    showCompanyInfo: true,
    showLicenseNumber: true,
    showSealPlaceholder: true,
    font: 'Arial',
    borderWeight: 0.6,
    dividerWeight: 0.3,
  },
  northArrow: {
    style: 'COMPASS',
    position: { x: 32.0, y: 22.5 },
    size: 1.5,
    rotation: 0,
    showMagneticDeclination: false,
    magneticDeclination: 0,
  },
  scaleBar: {
    position: { x: 28.0, y: 22.5 },
    width: 3.0,
    segments: 6,
    units: 'FEET',
    font: 'Arial',
    fontSize: 8,
  },
  legend: {
    ...DEFAULT_LEGEND_CONFIG,
    position: { x: 0.75, y: 0.75 },
    columns: 2,
  },
  certification: {
    ...DEFAULT_CERTIFICATION_CONFIG,
    position: { x: 0.75, y: 2.5 },
    width: 7.0,
    sealDiameter: 2.0,
  },
  standardNotes: {
    position: { x: 0.75, y: 6.0 },
    width: 5.0,
    title: 'SURVEY NOTES',
    font: 'Arial',
    fontSize: 9,
    selectedNoteIds: getDefaultNotes().map((n) => n.id),
    customNotes: [],
  },
  border: { ...DEFAULT_BORDER_CONFIG },
  company: STARR_COMPANY_INFO,
};
