-- supabase_seed_acc_content_1341_wk0.sql — Lesson: acc03b00-0000-0000-0000-000000000001
-- Converted from legacy HTML to structured lesson blocks
DELETE FROM lesson_blocks WHERE lesson_id = 'acc03b00-0000-0000-0000-000000000001';
INSERT INTO lesson_blocks (id, lesson_id, block_type, content, order_index, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'acc03b00-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Welcome to SRVY 1341 — Land Surveying</h2><p>Welcome to <strong>SRVY 1341: Land Surveying</strong> at Austin Community College. This course is the core lecture companion to <em>SRVY 1335 (Land Surveying Applications Lab)</em>, and together they form the foundation of your traversing, boundary, and adjustment skills.</p>"}'::jsonb, 0, now(), now()),
  (gen_random_uuid(), 'acc03b00-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Course Description</h3><p>A study of the measurement and determination of boundaries, areas, shapes, and location through traversing techniques. Instruction in a variety of adjustment methods using programmed and non-programmed hand-held calculators and computers. Methods of traversing and adjustment of errors according to prevailing and applicable professional standards and the standards of the Texas Board of Professional Engineers and Land Surveyors.</p>"}'::jsonb, 1, now(), now()),
  (gen_random_uuid(), 'acc03b00-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Prerequisites &amp; Corequisites</h3>"}'::jsonb, 2, now(), now()),
  (gen_random_uuid(), 'acc03b00-0000-0000-0000-000000000001', 'table', '{"headers":["Requirement","Course","Notes"],"rows":[["<strong>Prerequisite</strong>","SRVY 1301 — Introduction to Surveying","Must be completed before enrolling"],["<strong>Corequisite</strong>","SRVY 1335 — Land Surveying Applications (Lab)","Must be taken concurrently"]]}'::jsonb, 3, now(), now()),
  (gen_random_uuid(), 'acc03b00-0000-0000-0000-000000000001', 'text', '{"html":"<h3>What You Will Learn</h3><p>Over the next 16 weeks, you will master the following major topic areas:</p><ul>\n  <li><strong>Distance Measurement &amp; Corrections</strong> — Chain/tape measurement, temperature, tension, and sag corrections; EDM principles</li>\n  <li><strong>Traverse Types &amp; Planning</strong> — Open, closed-loop, and connecting traverses; station selection; accuracy standards</li>\n  <li><strong>Traverse Field Procedures</strong> — Angle measurement, total station operation, field notes, direct &amp; reverse readings</li>\n  <li><strong>Traverse Computations</strong> — Azimuth propagation, latitude &amp; departure calculation, linear error of closure, relative precision</li>\n  <li><strong>Traverse Adjustment</strong> — Compass (Bowditch) rule, transit rule, coordinate adjustment</li>\n  <li><strong>Coordinate Geometry (COGO)</strong> — Inverse computations, intersections, coordinate transformations</li>\n  <li><strong>Area Computation</strong> — Coordinate method, DMD/DPD method, area by coordinates</li>\n  <li><strong>Boundary Surveying</strong> — Retracement principles, deed interpretation, monument hierarchy</li>\n  <li><strong>Professional Standards</strong> — TBPELS rules, ALTA/NSPS standards, accuracy requirements</li>\n</ul>"}'::jsonb, 4, now(), now()),
  (gen_random_uuid(), 'acc03b00-0000-0000-0000-000000000001', 'text', '{"html":"<h3>16-Week Semester Overview</h3>"}'::jsonb, 5, now(), now()),
  (gen_random_uuid(), 'acc03b00-0000-0000-0000-000000000001', 'table', '{"headers":["Week","Topic"],"rows":[["0","Course Introduction (this lesson)"],["1","Distance Measurement — Chaining &amp; Tape Corrections"],["2","Traversing Fundamentals — Types &amp; Planning"],["3","Traverse Field Procedures — Angles &amp; Instruments"],["4","Traverse Computations — Azimuths, Latitudes &amp; Departures"],["5","Error of Closure &amp; Relative Precision"],["6","Traverse Adjustment — Compass Rule"],["7","Traverse Adjustment — Transit Rule &amp; Comparison"],["8","<strong>Midterm Exam</strong>"],["9","Coordinate Geometry — Inverse Computations"],["10","Coordinate Geometry — Intersections"],["11","Area Computation Methods"],["12","Boundary Determination &amp; Retracement"],["13","Subdivision &amp; Legal Descriptions"],["14","Professional Standards &amp; TBPELS Compliance"],["15","Review &amp; Exam Preparation"],["16","<strong>Final Exam</strong>"]]}'::jsonb, 6, now(), now()),
  (gen_random_uuid(), 'acc03b00-0000-0000-0000-000000000001', 'text', '{"html":"<h3>What You Need</h3><ul>\n  <li><strong>Textbook:</strong> <em>Elementary Surveying</em> by Ghilani (or <em>Surveying Fundamentals</em> by Nathanson)</li>\n  <li><strong>Calculator:</strong> Scientific calculator with trigonometric functions (TI-30X or similar)</li>\n  <li><strong>Supplies:</strong> Engineering field notebook, pencils, protractor</li>\n</ul>"}'::jsonb, 7, now(), now()),
  (gen_random_uuid(), 'acc03b00-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Grading Overview</h3><ul>\n  <li>Weekly Quizzes: 20%</li>\n  <li>Homework &amp; Practice Problems: 20%</li>\n  <li>Midterm Exam: 25%</li>\n  <li>Final Exam: 35%</li>\n</ul><p>Review the resources and videos below to get oriented, then click <strong>Continue to Next Lesson</strong> to begin Week 1: Distance Measurement.</p>"}'::jsonb, 8, now(), now());

-- Mark lesson as migrated (original HTML preserved as fallback)
UPDATE learning_lessons SET content_migrated = TRUE WHERE id = 'acc03b00-0000-0000-0000-000000000001';
