-- supabase_seed_acc_content_1335_wk1.sql — Lesson: acc02b01-0000-0000-0000-000000000001
-- Converted from legacy HTML to structured lesson blocks
DELETE FROM lesson_blocks WHERE lesson_id = 'acc02b01-0000-0000-0000-000000000001';
INSERT INTO lesson_blocks (id, lesson_id, block_type, content, order_index, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Welcome to the Surveying Lab</h2><p>SRVY 1335 is a <strong>hands-on lab course</strong> where you learn by doing. Every week you will handle precision instruments, work outdoors in central Texas weather, and produce field notes that could stand up in a court of law. Before you touch a single piece of equipment, you need to understand three things: how to keep yourself and others <strong>safe</strong>, what each piece of <strong>equipment</strong> does, and how to <strong>record</strong> your work properly.</p><p>This first lab session covers all three. Take these topics seriously — safety violations can cause injury, equipment damage can cost thousands of dollars, and poor field notes can invalidate an entire survey.</p>"}'::jsonb, 0, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Part 1: Lab and Field Safety</h2>"}'::jsonb, 1, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>General Safety Principles</h3><p>Surveying is outdoor work performed near traffic, on uneven terrain, and often in extreme heat. The most important safety principle is <strong>situational awareness</strong> — always know what is around you.</p><ul>\n<li><strong>Never turn your back on traffic.</strong> When working near roads, always face oncoming traffic. Use a spotter if you must focus on the instrument.</li>\n<li><strong>Wear appropriate clothing.</strong> Closed-toe shoes (preferably boots), long pants, and a hat are mandatory for fieldwork. High-visibility vests are required when working near any roadway.</li>\n<li><strong>Stay hydrated.</strong> Central Texas summers regularly exceed 100°F. Drink water <em>before</em> you feel thirsty. Know the signs of heat exhaustion: heavy sweating, weakness, cold/pale/clammy skin, nausea, fainting.</li>\n<li><strong>Watch for wildlife.</strong> Fire ants, copperheads, rattlesnakes, and thorny brush are common in the Austin area. Look before you step, especially around tall grass, rock piles, and brush.</li>\n<li><strong>Never look at the sun through any optical instrument.</strong> Levels, theodolites, and total stations can focus sunlight directly into your eye, causing instant and permanent retinal damage.</li>\n</ul>"}'::jsonb, 2, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Equipment Safety</h3><ul>\n<li><strong>Carry tripods vertically</strong> with the legs together and pointed down. Never carry a tripod over your shoulder pointed forward — you could strike someone.</li>\n<li><strong>Never leave an instrument unattended on a tripod.</strong> Wind, people, or animals can knock it over. A dropped total station can cost $15,000–$40,000 to replace.</li>\n<li><strong>Use lens caps</strong> when the instrument is not in active use. Scratched lenses degrade measurement accuracy.</li>\n<li><strong>Tighten all clamps gently but firmly.</strong> Over-tightening damages threads and tangent screws. Under-tightening allows the instrument to drift.</li>\n<li><strong>Level rods and prism poles</strong> should be carried vertically, not horizontally, when moving through the field.</li>\n</ul>"}'::jsonb, 3, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>ACC Lab-Specific Rules</h3><ol>\n<li>All equipment must be <strong>checked out</strong> by the team leader and <strong>checked in</strong> by the same person at the end of each lab session.</li>\n<li>Report any equipment damage <strong>immediately</strong> — do not attempt to repair instruments yourself.</li>\n<li>No food or drinks near instruments or in the equipment storage room.</li>\n<li>Field vehicles must have a designated driver who has completed the ACC defensive driving orientation.</li>\n<li>First aid kits are located in the lab storage room and in each field vehicle. Know their location.</li>\n</ol>"}'::jsonb, 4, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Part 2: Surveying Equipment Overview</h2><p>This section introduces the major categories of surveying equipment you will use throughout the semester. You do not need to master every instrument today — you will learn each one in depth during the labs that use it. Today is about recognition and basic handling.</p>"}'::jsonb, 5, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Levels</h3><p>A <strong>level</strong> establishes a horizontal line of sight for measuring differences in elevation. There are two main types you will encounter:</p>"}'::jsonb, 6, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'table', '{"headers":["Type","Description","Typical Accuracy"],"rows":[["<strong>Automatic (compensating) level</strong>","Uses a pendulum compensator to maintain a level line of sight after rough leveling. The standard instrument for differential leveling.","±1–2 mm per km"],["<strong>Digital level</strong>","Reads a bar-coded rod electronically and records data digitally. Eliminates reading errors.","±0.3–1.0 mm per km"]]}'::jsonb, 7, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<p>Both require a <strong>tripod</strong> for mounting and a <strong>leveling rod</strong> (graduated staff) as the target.</p>"}'::jsonb, 8, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Total Stations</h3><p>A <strong>total station</strong> combines an electronic theodolite (for measuring horizontal and vertical angles) with an EDM (Electronic Distance Measurement device). It is the workhorse of modern surveying, used for traversing, boundary surveys, construction layout, and topographic mapping.</p><p>Key components:</p><ul>\n<li><strong>Telescope</strong> — optical tube with crosshairs for precise aiming</li>\n<li><strong>Horizontal circle</strong> — electronic encoder measuring horizontal angles</li>\n<li><strong>Vertical circle</strong> — electronic encoder measuring zenith (vertical) angles</li>\n<li><strong>EDM</strong> — infrared or laser distance measurement</li>\n<li><strong>Display and keyboard</strong> — for entering data and reading measurements</li>\n<li><strong>Tribrach</strong> — the leveling mount that attaches to the tripod</li>\n</ul><p>Total station accuracy classes are defined by the standard deviation of a single angle measurement — for example, a \"5-second\" instrument has a stated angle accuracy of ±5″.</p>"}'::jsonb, 9, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Theodolites</h3><p>A <strong>theodolite</strong> measures horizontal and vertical angles but does <em>not</em> include an EDM. Modern total stations have largely replaced standalone theodolites, but you may encounter them for specific tasks (such as precise angle work) or in contexts where distance is measured separately by tape or GNSS.</p>"}'::jsonb, 10, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Distance Measurement Equipment</h3>"}'::jsonb, 11, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'table', '{"headers":["Equipment","Description","When Used"],"rows":[["<strong>Steel tape (30 m / 100 ft)</strong>","Graduated metal tape for direct distance measurement","Short distances, boundary corners, construction layout"],["<strong>EDM (in total station)</strong>","Electronic distance measurement using infrared beam reflected from a prism","All traverse and control distances"],["<strong>Prism and prism pole</strong>","Glass retroreflector mounted on an adjustable-height pole — the EDM target","Used with total station for all electronic distance measurement"]]}'::jsonb, 12, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Leveling Rods</h3><p>A <strong>leveling rod</strong> (or level staff) is a graduated pole used as the target for leveling measurements. Standard rods are graduated in meters/centimeters or feet/hundredths of a foot. The rod must be held <strong>perfectly vertical</strong> — even a small tilt introduces error. Rod levels (circular bubble vials) are attached to the rod to help maintain plumb.</p>"}'::jsonb, 13, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Tripods</h3><p>All precision instruments (levels, total stations, theodolites) mount on a <strong>tripod</strong>. Surveying tripods have:</p><ul>\n<li><strong>Adjustable legs</strong> with both extension and spread adjustment</li>\n<li><strong>Metal or fiberglass legs</strong> (wood is traditional but heavier)</li>\n<li><strong>A flat head</strong> with a 5/8″-11 threaded center bolt for attaching the tribrach or instrument directly</li>\n<li><strong>Pointed feet</strong> for pushing into soft ground</li>\n</ul>"}'::jsonb, 14, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Tribrachs</h3><p>A <strong>tribrach</strong> is the leveling adapter between the tripod and the instrument. It contains:</p><ul>\n<li>Three <strong>leveling screws</strong> (foot screws) for precise leveling</li>\n<li>A <strong>circular bubble</strong> (bull''s-eye) for rough leveling</li>\n<li>An <strong>optical plummet</strong> (or laser plummet) for centering over a ground mark</li>\n<li>A <strong>locking ring</strong> that accepts the instrument or prism adapter</li>\n</ul>"}'::jsonb, 15, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Auxiliary Equipment</h3><ul>\n<li><strong>Plumb bob</strong> — weighted cone on a string for vertical alignment over a point (backup to optical plummet)</li>\n<li><strong>Range poles</strong> — bright red-and-white striped poles for sighting targets at a distance</li>\n<li><strong>Chaining pins</strong> — steel stakes used to mark tape endpoints during taping</li>\n<li><strong>Flagging tape</strong> — brightly colored plastic ribbon for marking points</li>\n<li><strong>Field book and pencils</strong> — for recording measurements (more on this below)</li>\n<li><strong>Hammer, lath, nails</strong> — for setting temporary points</li>\n</ul>"}'::jsonb, 16, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Part 3: The Surveying Field Book</h2><p>The <strong>field book</strong> is the legal record of your survey observations. It is not a scratch pad — it is a <em>permanent document</em> that may be subpoenaed in court years or decades after the survey was performed. Every measurement, sketch, and note you record must follow professional standards.</p>"}'::jsonb, 17, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Field Book Format</h3><p>Standard surveying field books have a specific layout:</p><ul>\n<li><strong>Left page:</strong> Tabular data — station names, angles, distances, rod readings, HI, HR</li>\n<li><strong>Right page:</strong> Sketches — plan view of the site, showing station locations, traverse lines, reference objects, north arrow, and descriptive notes</li>\n</ul>"}'::jsonb, 18, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Required Information on Every Page</h3>"}'::jsonb, 19, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'table', '{"headers":["Item","Purpose"],"rows":[["Date","Establishes when the work was performed"],["Weather conditions","Temperature, wind, visibility affect measurement accuracy"],["Crew members and roles","Establishes who performed and checked the work"],["Project name / location","Ties the data to a specific job"],["Equipment used (ID numbers)","Allows tracing calibration records"],["Page number","Maintains data sequence"]]}'::jsonb, 20, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>The Rules of Field Note Recording</h3><ol>\n<li><strong>Use pencil only</strong> (HB or 2H) — ink smears in rain and humidity.</li>\n<li><strong>Record measurements at the time of observation.</strong> Never rely on memory or scraps of paper.</li>\n<li><strong>Never erase.</strong> If you make an error, draw a single horizontal line through the incorrect value so it remains legible, write the correct value adjacent to it, and initial the correction.</li>\n<li><strong>Write legibly.</strong> If others cannot read your notes, the data is useless.</li>\n<li><strong>Include sketches.</strong> A plan-view sketch of the site with labeled stations, traverse lines, and reference features is essential for anyone using the data later.</li>\n<li><strong>Note unusual conditions</strong> — passing traffic that may have disturbed a setup, strong wind, heat shimmer, anything that might affect data quality.</li>\n<li><strong>Check your work.</strong> Before leaving a station, review all recorded values for completeness and reasonableness.</li>\n</ol>"}'::jsonb, 21, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Electronic Data Collection</h3><p>Many modern total stations connect to an electronic <strong>data collector</strong> (handheld computer) that records measurements automatically. While this reduces recording errors, you must still:</p><ul>\n<li>Verify the data collector settings (units, coordinate system, atmospheric corrections)</li>\n<li>Confirm point naming conventions before starting</li>\n<li>Back up data at the end of every session</li>\n<li>Maintain a paper field book as a backup record with sketches and notes that the data collector cannot capture</li>\n</ul>"}'::jsonb, 22, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Part 4: Equipment Check-Out Procedures</h2><p>Proper equipment handling begins and ends with the check-out process:</p>"}'::jsonb, 23, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Checking Out Equipment</h3><ol>\n<li>Sign the equipment log with your name, date, course section, and the serial numbers of all items checked out.</li>\n<li><strong>Inspect each item</strong> before accepting it:\n  <ul>\n  <li>Tripod: legs extend and lock properly, feet are attached, head bolt is present</li>\n  <li>Total station / level: lens is clean, display powers on, battery is charged</li>\n  <li>Rod: sections extend and lock, graduations are readable, rod level bubble is intact</li>\n  <li>Prism: glass is uncracked, prism constant label is visible, pole clamp works</li>\n  </ul>\n</li>\n<li>Report any pre-existing damage to the instructor before leaving the storage room.</li>\n</ol>"}'::jsonb, 24, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Returning Equipment</h3><ol>\n<li>Clean all equipment — wipe down instruments with a soft cloth, remove dirt from tripod feet and rod base.</li>\n<li>Return each item to its designated storage location (case, shelf, rack).</li>\n<li>Sign the equipment back in on the log.</li>\n<li>Report any damage or issues discovered during the lab session.</li>\n<li>Ensure all batteries are placed on chargers if needed.</li>\n</ol>"}'::jsonb, 25, now(), now()),
  (gen_random_uuid(), 'acc02b01-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Looking Ahead</h2><p>Next week you will put this knowledge to work in your first hands-on lab: <strong>differential leveling</strong>. You will set up an automatic level, read a leveling rod, and run a simple level circuit to determine elevation differences between points. Bring your field book prepared with a fresh page, your pencil, and a hat — we will be outside.</p>"}'::jsonb, 26, now(), now());

-- Mark lesson as migrated (original HTML preserved as fallback)
UPDATE learning_lessons SET content_migrated = TRUE WHERE id = 'acc02b01-0000-0000-0000-000000000001';
