-- supabase_seed_acc_content_1341_wk1.sql — Lesson: acc03b01-0000-0000-0000-000000000001
-- Converted from legacy HTML to structured lesson blocks
DELETE FROM lesson_blocks WHERE lesson_id = 'acc03b01-0000-0000-0000-000000000001';
INSERT INTO lesson_blocks (id, lesson_id, block_type, content, order_index, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Week 1: Distance Measurement — Chaining &amp; Tape Corrections</h2><p>Accurate distance measurement is the foundation of every survey. Before electronic distance measurement (EDM) became standard, all distances were measured with <strong>steel chains</strong> or <strong>steel tapes</strong> — and even today, tape measurement remains a critical skill tested on licensing exams and used in short-range field checks.</p><p>A steel surveying tape is typically 100 feet or 30 meters long. It is manufactured to be exactly that length under <strong>standard conditions</strong>: a temperature of <strong>68°F (20°C)</strong>, a pull of <strong>10 to 20 pounds</strong> (depending on the tape), and full support along its length (no sag). When field conditions differ from these standards, the tape physically changes length, and the surveyor must apply <strong>corrections</strong> to obtain the true distance.</p>"}'::jsonb, 0, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Measuring with a Chain/Tape — Proper Procedure</h3><p>The fundamental rules of chain measurement have not changed in centuries:</p><ol>\n  <li><strong>Apply Proper Tension:</strong> The tape must be pulled with the correct amount of force — typically <strong>20 to 25 pounds</strong> of tension (or whatever the tape was standardized at). Too little tension leaves slack; too much stretches the tape beyond its calibrated length. A spring balance (tension handle) should be used to ensure consistent pull.</li>\n\n  <li><strong>Always Measure Distances Twice:</strong> Every distance is measured once <strong>forward</strong> and once <strong>back</strong> to catch mistakes. The two measurements should agree within the required tolerance. This is the surveyor''s equivalent of <em>\"measure twice, cut once.\"</em> If forward and back measurements disagree beyond tolerance, the measurement must be repeated until they do.</li>\n\n  <li><strong>Align the Tape:</strong> The tape must be held on line between the two points. Range poles or plumb bobs are used to keep the tape aligned over the correct ground points.</li>\n\n  <li><strong>Read and Record Correctly:</strong> Read the tape at the correct graduation. Call out and independently record each reading. Transposed digits and misread graduations are the most common blunders in taping.</li>\n\n  <li><strong>Keep the Tape Level (or Apply Slope Correction):</strong> If the tape is held level, horizontal distance is measured directly. If the terrain is sloped, either break the chain into level segments (''breaking chain'') or measure the slope distance and reduce it to horizontal using the slope angle or elevation difference.</li>\n</ol>"}'::jsonb, 1, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Why Corrections Are Necessary</h3><p>A steel tape is a <strong>physical object</strong> — it expands and contracts with temperature, stretches under tension, and curves under its own weight. These are <strong>systematic errors</strong>: they always push the measurement in the same direction for the same conditions, and they can be mathematically corrected once the conditions are known.</p><p>The three primary chain corrections are:</p><ul>\n  <li><strong>Temperature Correction (C<sub>t</sub>)</strong> — accounts for thermal expansion/contraction</li>\n  <li><strong>Tension/Pull Correction (C<sub>p</sub>)</strong> — accounts for stretching beyond the standard pull</li>\n  <li><strong>Sag Correction (C<sub>s</sub>)</strong> — accounts for the tape hanging in a catenary curve</li>\n</ul>"}'::jsonb, 2, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Temperature Correction</h3><p>Steel expands when heated and contracts when cooled. The coefficient of thermal expansion for steel is approximately <strong>0.00000645 per °F</strong> (6.45 × 10<sup>−6</sup> /°F). Standard tapes are manufactured at <strong>68°F</strong>.</p>"}'::jsonb, 3, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'callout', '{"type":"formula","text":"<strong>C<sub>t</sub> = 0.00000645 × (T<sub>F</sub> − 68) × L</strong>"}'::jsonb, 4, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<p>Where:</p><ul>\n  <li><strong>C<sub>t</sub></strong> = correction in feet due to temperature</li>\n  <li><strong>T<sub>F</sub></strong> = field temperature in °F</li>\n  <li><strong>L</strong> = measured distance in feet</li>\n  <li><strong>68°F</strong> = standard temperature at which the tape was calibrated</li>\n</ul><h4>Sign Convention</h4><ul>\n  <li><strong>Above 68°F:</strong> The tape is longer than standard → it spans more ground per graduation → readings are <strong>too short</strong> → correction is <strong>positive</strong> (add to measured distance)</li>\n  <li><strong>Below 68°F:</strong> The tape is shorter than standard → it spans less ground → readings are <strong>too long</strong> → correction is <strong>negative</strong> (subtract from measured distance)</li>\n</ul><h4>Example 1 — Hot Day</h4><p>Observed distance: <strong>357.22 ft</strong>, Field temperature: <strong>88°F</strong></p><p>C<sub>t</sub> = 0.00000645 × (88 − 68) × 357.22 = 0.00000645 × 20 × 357.22 = <strong>+0.046 ft</strong></p><p>Corrected distance = 357.22 + 0.046 = <strong>357.27 ft</strong></p><h4>Example 2 — Cold Day</h4><p>Observed distance: <strong>357.22 ft</strong>, Field temperature: <strong>48°F</strong></p><p>C<sub>t</sub> = 0.00000645 × (48 − 68) × 357.22 = 0.00000645 × (−20) × 357.22 = <strong>−0.046 ft</strong></p><p>Corrected distance = 357.22 + (−0.046) = <strong>357.17 ft</strong></p><p>Notice how the same tape, the same distance, but a 40°F temperature difference produces a total spread of 0.10 ft (about 1.2 inches). On a 1,000-foot traverse, this would be even larger. <strong>Temperature correction is never optional on precision work.</strong></p>"}'::jsonb, 5, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Tension (Pull) Correction</h3><p>If you pull the tape harder than the standard tension, it stretches; if you pull lighter, it sags more. The tension correction accounts for the elastic deformation of the tape:</p>"}'::jsonb, 6, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'callout', '{"type":"formula","text":"<strong>C<sub>p</sub> = (P − P<sub>s</sub>) × L / (A × E)</strong>"}'::jsonb, 7, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<p>Where:</p><ul>\n  <li><strong>C<sub>p</sub></strong> = correction in feet due to tension</li>\n  <li><strong>P</strong> = applied tension in pounds</li>\n  <li><strong>P<sub>s</sub></strong> = standard tension (from tape specifications) in pounds</li>\n  <li><strong>L</strong> = measured distance in feet</li>\n  <li><strong>A</strong> = cross-sectional area of the tape in square inches</li>\n  <li><strong>E</strong> = modulus of elasticity of steel ≈ 29,000,000 psi (29 × 10<sup>6</sup> psi)</li>\n</ul><h4>Sign Convention</h4><ul>\n  <li><strong>P &gt; P<sub>s</sub>:</strong> Over-pulling stretches the tape → correction is <strong>positive</strong></li>\n  <li><strong>P &lt; P<sub>s</sub>:</strong> Under-pulling means tape is too short → correction is <strong>negative</strong></li>\n</ul><h4>Example — Tension Correction</h4><p>Standard tension P<sub>s</sub> = 10 lbs, Applied tension P = 25 lbs, Distance L = 500 ft, Cross-section A = 0.005 in², E = 29,000,000 psi</p><p>C<sub>p</sub> = (25 − 10) × 500 / (0.005 × 29,000,000) = 7,500 / 145,000 = <strong>+0.052 ft</strong></p>"}'::jsonb, 8, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Sag Correction</h3><p>When a tape is suspended between two supports (not lying on the ground), gravity pulls the middle downward into a <strong>catenary curve</strong>. The chord distance (straight line between endpoints) is always shorter than the tape reading. Sag correction is <strong>always negative</strong>.</p>"}'::jsonb, 9, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'callout', '{"type":"formula","text":"<strong>C<sub>s</sub> = −w² × L³ / (24 × P²)</strong>"}'::jsonb, 10, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<p>Where:</p><ul>\n  <li><strong>C<sub>s</sub></strong> = sag correction in feet (always negative)</li>\n  <li><strong>w</strong> = weight of tape per foot (lbs/ft)</li>\n  <li><strong>L</strong> = unsupported length in feet</li>\n  <li><strong>P</strong> = applied tension in pounds</li>\n</ul><h4>Why Sag Is Always Negative</h4><p>The tape sags into an arc. The arc is longer than the straight-line (chord) distance between the endpoints. Since the tape reading reflects the arc length, but you need the chord length, you must subtract the sag amount. Increasing tension reduces sag — there is a specific tension called the <strong>normal tension</strong> at which the sag correction exactly cancels the tension correction.</p><h4>Example — Sag Correction</h4><p>Tape weight w = 0.015 lbs/ft, Span L = 100 ft (unsupported), Tension P = 20 lbs</p><p>C<sub>s</sub> = −(0.015)² × (100)³ / (24 × (20)²) = −0.000225 × 1,000,000 / 9,600 = <strong>−0.023 ft</strong></p>"}'::jsonb, 11, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Applying All Corrections Together</h3><p>When field conditions require multiple corrections, simply add them all to the observed distance:</p>"}'::jsonb, 12, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'callout', '{"type":"formula","text":"<strong>D<sub>corrected</sub> = D<sub>measured</sub> + C<sub>t</sub> + C<sub>p</sub> + C<sub>s</sub></strong>"}'::jsonb, 13, now(), now()),
  (gen_random_uuid(), 'acc03b01-0000-0000-0000-000000000001', 'text', '{"html":"<p>Each correction has its own sign (positive or negative). Compute each one separately, then sum. <strong>Always show your work</strong> — on licensing exams and in professional practice, a clearly documented correction sheet protects you from errors and challenges.</p><h4>Combined Example</h4><p>A surveyor measures 500.00 ft on a day when T = 95°F, using a 25-lb pull on a tape standardized at P<sub>s</sub> = 10 lbs, A = 0.005 in², w = 0.015 lbs/ft, fully supported (no sag).</p><ul>\n  <li>C<sub>t</sub> = 0.00000645 × (95 − 68) × 500 = 0.00000645 × 27 × 500 = +0.087 ft</li>\n  <li>C<sub>p</sub> = (25 − 10) × 500 / (0.005 × 29,000,000) = +0.052 ft</li>\n  <li>C<sub>s</sub> = 0 (tape fully supported on ground)</li>\n  <li><strong>D<sub>corrected</sub> = 500.00 + 0.087 + 0.052 + 0 = 500.14 ft</strong></li>\n</ul><p>The true distance is about 1.7 inches longer than measured. On a multi-thousand-foot traverse, these corrections accumulate and become critical for meeting accuracy standards.</p>"}'::jsonb, 14, now(), now());

-- Mark lesson as migrated (original HTML preserved as fallback)
UPDATE learning_lessons SET content_migrated = TRUE WHERE id = 'acc03b01-0000-0000-0000-000000000001';
