-- supabase_seed_acc_content_1335_wk4.sql — Lesson: acc02b04-0000-0000-0000-000000000001
-- Converted from legacy HTML to structured lesson blocks
DELETE FROM lesson_blocks WHERE lesson_id = 'acc02b04-0000-0000-0000-000000000001';
INSERT INTO lesson_blocks (id, lesson_id, block_type, content, order_index, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Mastering Angular Measurement</h2><p>Last week you measured angles with a total station — pressing a button and reading a number from the display. This week you learn the <em>theory and technique</em> behind those numbers. You will work with a theodolite (or use the total station in angle-only mode), practice multiple methods of turning angles, and learn precision techniques like the <strong>repetition method</strong> and <strong>closing the horizon</strong> that have been cornerstones of surveying for over a century.</p><p>Understanding these methods deeply matters for two reasons: (1) the Texas RPLS licensing exam tests angular measurement theory extensively, and (2) when you encounter discrepancies in the field, you need to know <em>why</em> an angle might be wrong, not just that it is.</p>"}'::jsonb, 0, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Theodolite vs. Total Station</h2><p>A <strong>theodolite</strong> is an instrument designed specifically for measuring horizontal and vertical angles. A <strong>total station</strong> adds an EDM to a theodolite. For angle measurement, they are functionally identical — the same circles, clamps, tangent screws, and reading systems.</p>"}'::jsonb, 1, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'table', '{"headers":["Feature","Theodolite","Total Station"],"rows":[["Horizontal angles","Yes","Yes"],["Vertical/zenith angles","Yes","Yes"],["Electronic distance (EDM)","<strong>No</strong>","Yes"],["Data storage","Manual (field book)","Internal or data collector"],["Typical use today","Precise angle work, teaching","All surveying tasks"],["Circle reading","Optical micrometer or electronic","Electronic encoder"]]}'::jsonb, 2, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<p>In this lab, the techniques you learn apply equally to both instruments. Whether the circle is read through an optical micrometer or from an LCD display, the angular measurement methods are the same.</p>"}'::jsonb, 3, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Reading the Circles</h2>"}'::jsonb, 4, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>The Horizontal Circle</h3><p>The horizontal circle measures angles in the horizontal plane. It is graduated from 0° to 360° and reads clockwise when viewed from above. When you turn the instrument to the right (clockwise), the reading increases.</p>"}'::jsonb, 5, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>The Vertical Circle</h3><p>The vertical circle measures the tilt of the telescope. Most modern instruments display the <strong>zenith angle</strong>:</p><ul>\n<li><strong>0°</strong> = telescope pointing straight up</li>\n<li><strong>90°</strong> = telescope horizontal</li>\n<li><strong>180°</strong> = telescope pointing straight down</li>\n</ul><p>Some older instruments use a <strong>vertical angle</strong> convention where 0° = horizontal, positive = upward, negative = downward. Always confirm which convention your instrument uses before recording data.</p>"}'::jsonb, 6, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Optical Micrometer Reading (Older Theodolites)</h3><p>Older theodolites use an <strong>optical micrometer</strong> viewed through a small eyepiece near the main telescope. You see two images of the circle graduation, and turn a micrometer knob until the images align. The micrometer scale then displays the minutes and seconds. This skill is less common today but may appear on licensing exams and in some field situations.</p>"}'::jsonb, 7, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Methods of Measuring Horizontal Angles</h2>"}'::jsonb, 8, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Method 1: Angle to the Right (Direction Method)</h3><p>This is the most common method for modern surveying. All angles are measured <strong>clockwise</strong> from the backsight to the foresight.</p><ol>\n<li>Sight the <strong>backsight</strong> and set the horizontal circle to 0°00′00″ (or a known azimuth).</li>\n<li>Release the horizontal clamp and turn <strong>clockwise</strong> to the foresight.</li>\n<li>Lock the clamp and use the tangent screw for precise pointing.</li>\n<li>Read the horizontal circle. This is the <strong>angle to the right</strong>.</li>\n</ol><p><strong>Advantages:</strong> Unambiguous (always clockwise), directly converts to azimuths, standard for traverse work.</p>"}'::jsonb, 9, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Method 2: Deflection Angles</h3><p>A <strong>deflection angle</strong> is the angle from the prolongation of the incoming line to the outgoing line. It measures how far the new direction <em>deflects</em> from straight ahead.</p><ol>\n<li>Sight the <strong>backsight</strong> with the telescope <strong>inverted</strong> (plunged). This puts you looking along the prolongation of the backsight line — i.e., \"straight ahead.\"</li>\n<li>Rotate to the <strong>foresight</strong> in the normal (direct) position.</li>\n<li>Read the angle. If you turned clockwise, it is a <strong>right deflection (R)</strong>. If counterclockwise, it is a <strong>left deflection (L)</strong>.</li>\n</ol><p><strong>Check:</strong> For a closed traverse, the algebraic sum of deflection angles = 360° (counting right as positive and left as negative).</p><p><strong>Use:</strong> Primarily for route surveys (highways, railroads, pipelines) where you follow a linear corridor.</p>"}'::jsonb, 10, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Method 3: Interior Angles</h3><p><strong>Interior angles</strong> are measured inside the closed polygon of a traverse.</p><ol>\n<li>At each station, sight the <strong>backsight</strong>.</li>\n<li>Turn to the <strong>foresight</strong>, measuring the angle on the <em>interior</em> side of the traverse.</li>\n</ol><p><strong>Check:</strong> Sum of interior angles = (n − 2) × 180° for an n-sided polygon.</p><p><strong>Use:</strong> Standard for closed loop (property) traverses.</p>"}'::jsonb, 11, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Closing the Horizon</h2><p><strong>Closing the horizon</strong> is a powerful check on angular measurements at a station where you measure angles to three or more targets. The procedure:</p><ol>\n<li>Set 0° on the first target (A)</li>\n<li>Turn clockwise to target B and read the angle (e.g., 73°15′22″)</li>\n<li>Turn clockwise to target C and read the angle (e.g., 192°41′08″)</li>\n<li>Turn clockwise <strong>back to target A</strong> — the reading should be <strong>360°00′00″</strong> (or very close to it)</li>\n</ol><p>The difference between 360° and the final reading is the <strong>horizon closure error</strong>. It should be within the instrument''s accuracy. If you measure n angles around the full circle, the closure check is:</p><p style=\"text-align:center;\"><strong>Sum of all measured angles around the horizon = 360°00′00″</strong></p><p>This check catches blunders in individual angles. If the closure is outside tolerance, one or more angles must be re-measured.</p>"}'::jsonb, 12, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Example</h3>"}'::jsonb, 13, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'table', '{"headers":["Target","Circle Reading","Angle"],"rows":[["A (start)","0°00′00″","—"],["B","73°15′22″","73°15′22″"],["C","192°41′08″","119°25′46″"],["A (close)","360°00′06″","167°18′58″"],["<strong>Sum of angles:</strong>","<strong>360°00′06″</strong>"]]}'::jsonb, 14, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<p>Horizon closure error = 6″ — well within the tolerance of a 5″ instrument.</p>"}'::jsonb, 15, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>The Repetition Method</h2><p>The <strong>repetition method</strong> (also called the method of repetitions) improves angular precision by measuring the same angle multiple times and <em>accumulating</em> the readings on the circle without resetting to zero. The accumulated total is then divided by the number of repetitions to get the mean angle.</p>"}'::jsonb, 16, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Why It Works</h3><p>Each individual reading has a random pointing error. By accumulating n repetitions and dividing by n, the random errors tend to cancel, and the mean angle is more precise than any single reading by a factor of approximately √n.</p>"}'::jsonb, 17, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Procedure (6 repetitions)</h3><p><strong>First set (3 Direct / Face Left):</strong></p><ol>\n<li>Sight the backsight and set the circle to 0°00′00″. Record the initial reading (R₁ = 0°00′00″).</li>\n<li>Turn clockwise to the foresight and read the angle (e.g., 87°14′20″). Do NOT reset the circle.</li>\n<li>Release the <strong>lower clamp</strong> (which controls the circle) and turn the instrument back to the backsight without changing the circle reading.</li>\n<li>Lock the lower clamp, sight the backsight with the tangent screw.</li>\n<li>Release the <strong>upper clamp</strong> (which turns the telescope relative to the circle) and turn to the foresight again. The reading is now the accumulated value of approximately 2 × 87°14′20″ = 174°28′40″.</li>\n<li>Repeat one more time to get 3 repetitions. The accumulated reading should be approximately 3 × 87°14′20″ = 261°43′00″.</li>\n</ol><p><strong>Second set (3 Reverse / Face Right):</strong></p><ol>\n<li>Plunge the telescope (transit to Face Right).</li>\n<li>Continue accumulating 3 more repetitions in the reverse position, starting from the last Face Left reading.</li>\n<li>After 6 total repetitions, read the final accumulated circle value (e.g., 523°26′06″ — this has gone past 360°, so the actual accumulated value is 523°26′06″).</li>\n</ol><p><strong>Compute the mean:</strong></p><p style=\"text-align:center;\"><strong>Mean angle = Accumulated reading / number of repetitions = 523°26′06″ / 6 = 87°14′21″</strong></p><p>Note: If the accumulated reading passes through 360°, you must add 360° (or 720°, etc.) before dividing. The number of full turns is known from the number of repetitions and the approximate angle.</p>"}'::jsonb, 18, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Practical Notes</h3><ul>\n<li>The minimum number of repetitions is usually <strong>2 D + 2 R = 4 total</strong> for boundary surveys.</li>\n<li>For higher accuracy, use <strong>3 D + 3 R = 6 total</strong> or more.</li>\n<li>The D&R split eliminates systematic instrument errors (collimation, trunnion axis tilt).</li>\n<li>Record the initial and final accumulated readings in your field book. Also record intermediate readings for error checking.</li>\n</ul>"}'::jsonb, 19, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Comparing the Methods</h2>"}'::jsonb, 20, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'table', '{"headers":["Method","Precision Improvement","Eliminates Systematic Errors?","Use Case"],"rows":[["Single D&R","None (just one measurement)","Yes (collimation, trunnion, VCI)","Routine work"],["Repetition (n reps)","~√n improvement","Yes (if D&R included)","Higher precision needed"],["Direction method (multiple sets)","~√n improvement","Yes (if D&R + circle advance)","Highest precision control surveys"]]}'::jsonb, 21, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Sources of Angular Error</h2><p>Understanding error sources helps you diagnose problems in the field:</p>"}'::jsonb, 22, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Systematic Errors (Eliminated by D&R)</h3><ul>\n<li><strong>Collimation error:</strong> The line of sight is not perpendicular to the trunnion axis. Effect: angles read consistently too large or too small in one face.</li>\n<li><strong>Trunnion axis tilt:</strong> The horizontal axis is not truly horizontal. Effect: errors in horizontal angles, especially at steep zenith angles.</li>\n<li><strong>Vertical circle index error:</strong> The zero of the vertical circle is offset. Effect: zenith angles are consistently off in one face.</li>\n</ul>"}'::jsonb, 23, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Random Errors (Reduced by Repetition)</h3><ul>\n<li><strong>Pointing error:</strong> Inability to aim at exactly the same point every time. Affected by magnification, target size, atmospheric conditions, and observer skill.</li>\n<li><strong>Reading error:</strong> For optical micrometers, imprecision in aligning the micrometer images. For electronic instruments, typically ±1 least count.</li>\n<li><strong>Centering error:</strong> The instrument or target is not exactly over the station mark. Produces angular error proportional to offset/distance.</li>\n</ul>"}'::jsonb, 24, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Blunders</h3><ul>\n<li>Sighting the wrong target</li>\n<li>Reading the wrong circle (horizontal vs. vertical)</li>\n<li>Transposing digits when recording</li>\n<li>Not properly locking clamps before using tangent screws</li>\n</ul>"}'::jsonb, 25, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Recording Angular Measurements</h2><p>For each angle measured, your field book should contain:</p>"}'::jsonb, 26, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'table', '{"headers":["Item","Example"],"rows":[["Station occupied","STA B"],["Backsight station","STA A"],["Foresight station","STA C"],["Method used","3D + 3R repetitions"],["Initial circle reading","0°00′00″"],["Accumulated reading after n reps","523°26′06″"],["Number of repetitions","6"],["Mean angle","87°14′21″"],["Horizon closure (if applicable)","+6″"]]}'::jsonb, 27, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Today''s Lab Exercise</h2><p>You will practice three exercises:</p><ol>\n<li><strong>Angles to the right:</strong> Measure angles from a setup to 4 targets using single D&R.</li>\n<li><strong>Closing the horizon:</strong> Sum the individual angles between consecutive targets around the full circle and verify the sum equals 360°.</li>\n<li><strong>Repetition method:</strong> Measure one angle using 3D + 3R (6 repetitions) and compare the mean to your single D&R value.</li>\n</ol>"}'::jsonb, 28, now(), now()),
  (gen_random_uuid(), 'acc02b04-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Looking Ahead</h2><p>Next week you begin <strong>differential leveling</strong> — using an automatic level and leveling rod to precisely determine elevation differences between points. Angular measurement gives you the horizontal framework; leveling gives you the vertical dimension.</p>"}'::jsonb, 29, now(), now());

-- Mark lesson as migrated (original HTML preserved as fallback)
UPDATE learning_lessons SET content_migrated = TRUE WHERE id = 'acc02b04-0000-0000-0000-000000000001';
