-- supabase_seed_acc_content_1335_wk3.sql — Lesson: acc02b03-0000-0000-0000-000000000001
-- Converted from legacy HTML to structured lesson blocks
DELETE FROM lesson_blocks WHERE lesson_id = 'acc02b03-0000-0000-0000-000000000001';
INSERT INTO lesson_blocks (id, lesson_id, block_type, content, order_index, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>The Total Station: Your Most Important Tool</h2><p>Last week you used the total station''s EDM to measure distances. This week you learn to operate the <em>entire</em> instrument — setting up precisely over a point, orienting to a backsight, and measuring angles and distances simultaneously. The total station is the instrument you will use more than any other in your surveying career, so the skills you develop this week are ones you will repeat thousands of times.</p><p>By the end of today''s lab you should be able to set up a total station, orient it to a backsight azimuth, and measure a complete round of horizontal angles, zenith angles, and slope distances to multiple targets — recording everything properly in your field book.</p>"}'::jsonb, 0, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Total Station Components Review</h2><p>Before operating the instrument, make sure you can identify every part:</p>"}'::jsonb, 1, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Optical and Mechanical Components</h3>"}'::jsonb, 2, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'table', '{"headers":["Component","Function"],"rows":[["<strong>Telescope</strong>","Magnifying optical tube with crosshairs (reticle) for precise aiming. Typically 26–30× magnification."],["<strong>Objective lens</strong>","Front lens of the telescope — gathers light. Keep the lens cap on when not in use."],["<strong>Eyepiece</strong>","Rear lens with a focus ring. Adjust the eyepiece first to sharpen the crosshairs, then use the main focus knob to focus on the target."],["<strong>Crosshairs (reticle)</strong>","Fine lines (vertical and horizontal) etched on glass inside the telescope. The intersection defines the line of sight."],["<strong>Sighting device</strong>","A notch-and-post sight or red-dot finder on top of the telescope for rough aiming before looking through the eyepiece."],["<strong>Horizontal clamp and tangent screw</strong>","The clamp locks the horizontal rotation; the tangent screw provides fine adjustment. Release the clamp to swing freely, lock it near the target, then use the tangent screw for precise pointing."],["<strong>Vertical clamp and tangent screw</strong>","Same function for vertical (tilting) motion of the telescope."],["<strong>Tribrach</strong>","Leveling base with three foot screws, circular bubble, optical/laser plummet, and locking ring."]]}'::jsonb, 3, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Electronic Components</h3>"}'::jsonb, 4, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'table', '{"headers":["Component","Function"],"rows":[["<strong>Horizontal circle encoder</strong>","Measures horizontal angles electronically (replaces the old glass circle and micrometer)"],["<strong>Vertical circle encoder</strong>","Measures zenith (vertical) angles electronically"],["<strong>EDM transmitter/receiver</strong>","Infrared distance measurement unit, coaxial with the telescope"],["<strong>Dual-axis compensator</strong>","Electronic tilt sensor that corrects angles for small leveling errors (typically ±3′ range)"],["<strong>Display panel</strong>","LCD screen showing angles, distances, coordinates, and menu options"],["<strong>Keyboard</strong>","For entering data (station name, HI, HR, atmospheric corrections) and navigating menus"],["<strong>Battery</strong>","Rechargeable; typical runtime 6–10 hours depending on EDM usage"],["<strong>Data port</strong>","Connection for external data collector or computer download"]]}'::jsonb, 5, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Setting Up Over a Point: The Complete Procedure</h2><p>You practiced a basic setup last week. This week you will refine it and learn to achieve <strong>sub-millimeter centering</strong> — critical for short sightlines where centering error dominates.</p>"}'::jsonb, 6, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Phase 1: Tripod Placement</h3><ol>\n<li>Stand behind the tripod and look down through the center hole in the tripod head. Position the tripod so the center hole is approximately over the ground mark.</li>\n<li>Spread the legs wide enough for stability (roughly shoulder width apart) with the head at a comfortable height.</li>\n<li>Push <strong>each leg firmly</strong> into the ground. On hard surfaces, use rubber leg tips or a tripod pad.</li>\n<li>The tripod head should be <strong>roughly level</strong> — within a few degrees. If one leg is much higher than the others, adjust leg lengths now rather than fighting the leveling screws later.</li>\n</ol>"}'::jsonb, 7, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Phase 2: Instrument Mounting and Rough Leveling</h3><ol>\n<li>Thread the tribrach onto the tripod center bolt and tighten snugly.</li>\n<li>Place the total station on the tribrach and engage the locking ring with a firm quarter-turn.</li>\n<li>Center the <strong>circular (bull''s-eye) bubble</strong> by adjusting the tripod legs. Turn the leg extension clamps to raise or lower individual legs. Do not use the leveling screws yet.</li>\n</ol>"}'::jsonb, 8, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Phase 3: Centering with the Optical Plummet</h3><ol>\n<li>Look through the <strong>optical plummet</strong> eyepiece (located on the side or bottom of the tribrach). Focus the plummet crosshair and then focus on the ground mark.</li>\n<li>Loosen the tribrach center clamp and <strong>slide the instrument</strong> on the tripod head until the plummet crosshair is exactly on the ground mark.</li>\n<li>Re-tighten the center clamp.</li>\n</ol><p><strong>Laser plummet alternative:</strong> Many modern tribrachs have a laser plummet that projects a red dot downward. Center the dot on the ground mark. Laser plummets are easier to use in bright sunlight where the optical plummet image may be dim.</p>"}'::jsonb, 9, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Phase 4: Fine Leveling</h3><ol>\n<li>Rotate the instrument so the <strong>plate bubble</strong> (tubular bubble) is <strong>parallel</strong> to the line between two of the three leveling screws.</li>\n<li>Turn those two screws <strong>simultaneously in opposite directions</strong>. The bubble moves in the direction of your left thumb. Center the bubble.</li>\n<li>Rotate the instrument <strong>90°</strong>. Center the bubble using the <strong>third screw only</strong>.</li>\n<li>Rotate back and check. Repeat until the bubble stays centered in <strong>all orientations</strong>.</li>\n</ol>"}'::jsonb, 10, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Phase 5: Iterate Centering and Leveling</h3><p>Fine leveling often shifts the instrument slightly off the ground mark. Check the optical plummet — if the crosshair has moved off the mark, loosen the center clamp, re-center, re-tighten, and re-level. <strong>Repeat</strong> until the instrument is simultaneously level and centered. This typically takes 2–3 iterations.</p>"}'::jsonb, 11, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Phase 6: Measure HI</h3><p>Measure the <strong>Height of Instrument (HI)</strong> — the vertical distance from the ground mark to the trunnion axis (the horizontal rotation axis of the telescope). Use a steel tape or the graduated HI mark on the instrument/tribrach. Record the HI immediately in your field book.</p>"}'::jsonb, 12, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Focusing the Telescope</h2><p>Proper focus is essential for accurate pointing. There are <strong>two separate focus adjustments</strong>:</p><ol>\n<li><strong>Eyepiece focus (crosshair focus):</strong> Point the telescope at a light background (like the sky — NOT the sun). Turn the eyepiece ring until the crosshairs are sharp and black. This focuses your eye on the reticle plane. Do this <em>once</em> at the beginning of the session; it should not change unless a different person uses the instrument.</li>\n<li><strong>Main focus (target focus):</strong> Point at the target and turn the focus knob on the side of the telescope until the target image is sharp. You must refocus for each new target at a different distance.</li>\n</ol>"}'::jsonb, 13, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Eliminating Parallax</h3><p><strong>Parallax</strong> is the apparent movement of the crosshairs against the target image when you move your eye slightly side to side at the eyepiece. It occurs when the target image and the crosshairs are not in the same focal plane. To eliminate parallax:</p><ol>\n<li>Focus the eyepiece on the crosshairs (step 1 above)</li>\n<li>Focus the main knob on the target (step 2)</li>\n<li>Move your eye slightly at the eyepiece — if the crosshairs appear to shift against the target, re-adjust the main focus until the shift disappears</li>\n</ol><p>Parallax causes pointing errors. Always check for it before taking critical measurements.</p>"}'::jsonb, 14, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Orienting to a Backsight</h2><p>Before measuring angles, you must <strong>orient</strong> the total station — that is, tell it what direction it is pointing. This is done by sighting a <strong>backsight</strong> (a point with a known direction from your station) and setting the horizontal circle accordingly.</p>"}'::jsonb, 15, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Method 1: Zero the Circle on the Backsight</h3><ol>\n<li>Sight the backsight prism precisely (using the tangent screws)</li>\n<li>Press the <strong>\"0 SET\"</strong> or <strong>\"OSET\"</strong> button on the total station. This sets the horizontal circle to 0°00′00″ while pointing at the backsight.</li>\n<li>All subsequent horizontal readings are angles measured clockwise from the backsight direction.</li>\n</ol>"}'::jsonb, 16, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Method 2: Set a Known Azimuth</h3><ol>\n<li>Sight the backsight prism precisely</li>\n<li>Enter the <strong>known azimuth</strong> of the line from your station to the backsight (e.g., 227°15′30″) as the horizontal circle reading</li>\n<li>Now all horizontal readings are true azimuths, not just angles from the backsight</li>\n</ol><p>Method 2 is preferred for traverse work because it gives you azimuths directly, eliminating a computation step. Method 1 is simpler and common for construction layout where you measure angles from a reference line.</p>"}'::jsonb, 17, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Verifying Orientation</h3><p>After orienting, swing to a <strong>second known point</strong> (if available) and check that the displayed angle or azimuth matches the expected value. This confirms that your orientation is correct. If it does not match, recheck your backsight identification and the azimuth you entered.</p>"}'::jsonb, 18, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Measuring Angles and Distances</h2>"}'::jsonb, 19, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Measuring a Horizontal Angle</h3><ol>\n<li><strong>Sight the backsight</strong> and zero the circle (or set the known azimuth).</li>\n<li><strong>Release the horizontal clamp</strong> and swing the telescope clockwise toward the foresight target.</li>\n<li><strong>Lock the horizontal clamp</strong> when the target is near the crosshairs.</li>\n<li><strong>Use the horizontal tangent screw</strong> for precise pointing — center the vertical crosshair on the prism.</li>\n<li><strong>Read the horizontal angle</strong> from the display. This is the angle clockwise from the backsight (or the azimuth if you set one).</li>\n</ol>"}'::jsonb, 20, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Measuring a Vertical (Zenith) Angle</h3><ol>\n<li>With the horizontal angle set, adjust the <strong>vertical clamp and tangent screw</strong> to center the horizontal crosshair on the target (usually the center of the prism).</li>\n<li>Read the <strong>zenith angle</strong> from the display. Zenith = 0° is straight up; 90° is horizontal; >90° means looking downhill.</li>\n</ol>"}'::jsonb, 21, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Measuring the Distance</h3><ol>\n<li>With both horizontal and vertical angles set on the target, press <strong>\"MEAS\"</strong> or <strong>\"DIST\"</strong>.</li>\n<li>The EDM fires and returns slope distance (SD), horizontal distance (HD), and vertical difference (VD).</li>\n<li>Record all three values.</li>\n</ol>"}'::jsonb, 22, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>One Button Does It All</h3><p>Many total stations have an <strong>\"ALL\"</strong> button that simultaneously records the horizontal angle, zenith angle, and EDM distance in one shot, storing everything in the data collector. This is the most efficient method when connected to an electronic data collector.</p>"}'::jsonb, 23, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Measuring Multiple Targets from One Setup</h2><p>In practice, you often measure angles and distances to several targets from a single instrument setup — all the foresight stations visible from your position, plus sideshots to features like building corners, fences, trees, or utility poles.</p>"}'::jsonb, 24, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Procedure</h3><ol>\n<li>Orient to the backsight (zero or set azimuth)</li>\n<li>Swing to <strong>Target 1</strong>, measure angle + distance, record</li>\n<li>Swing to <strong>Target 2</strong>, measure angle + distance, record</li>\n<li>Continue for all targets</li>\n<li>Swing <strong>back to the backsight</strong> and re-read the horizontal angle. It should still read 0°00′00″ (or your set azimuth). If it has drifted, the instrument may have been bumped — you must re-orient and re-measure.</li>\n</ol><p>This <strong>closing check</strong> on the backsight is critical. It confirms that the instrument''s orientation was stable throughout all your measurements.</p>"}'::jsonb, 25, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>The Importance of Face Left / Face Right (D&R)</h2><p>For traverse angles and any measurement that requires high accuracy, you should measure in <strong>both face positions</strong> (Direct and Reverse). You learned the theory in SRVY 1341; today you practice it hands-on:</p><ol>\n<li><strong>Face Left (Direct):</strong> Measure the angle to each target with the vertical circle on the left side of the telescope. Record all readings.</li>\n<li><strong>Plunge the telescope</strong> (rotate it 180° vertically) and rotate 180° horizontally.</li>\n<li><strong>Face Right (Reverse):</strong> Re-measure the angle to each target. The Face Right horizontal reading should differ from Face Left by approximately 180°.</li>\n<li><strong>Compute the mean:</strong> (Face Left + (Face Right − 180°)) / 2 for each angle.</li>\n</ol><p>This eliminates collimation error, trunnion axis tilt, and vertical circle index error — the three systematic instrumental errors.</p>"}'::jsonb, 26, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Configuring Instrument Settings</h2><p>Before starting measurements, verify these settings in the total station''s menu:</p>"}'::jsonb, 27, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'table', '{"headers":["Setting","What to Check","Why"],"rows":[["Distance units","Meters or US Survey Feet","Must match your project units. Mixing units is a common blunder."],["Angle units","Degrees-Minutes-Seconds (DMS) vs. decimal degrees vs. gons","DMS is standard for US surveying"],["Zenith vs. vertical angle","Zenith (0° up) vs. vertical (0° horizontal)","Affects slope-to-horizontal conversion; US standard is zenith"],["EDM mode","Standard (prism), reflectorless, or tracking","Must match your target type"],["Prism constant","0, −30, or other value","Must match the prism being used"],["Atmospheric corrections","Temperature and pressure","Enter actual values measured at the instrument"],["Compensator","On/off, single-axis or dual-axis","Should be ON for normal work"]]}'::jsonb, 28, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Recording Your Measurements</h2><p>For each setup (occupied station), your field book should contain:</p>"}'::jsonb, 29, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'table', '{"headers":["Item","Example"],"rows":[["Station occupied","STA 2"],["HI","1.487 m"],["Backsight station","STA 1"],["Backsight azimuth (if set)","47°15′30″"]]}'::jsonb, 30, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<p>For each target measured:</p>"}'::jsonb, 31, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'table', '{"headers":["Item","Example"],"rows":[["Target station","STA 3"],["HR (prism height)","1.800 m"],["HA — Face Left","92°17′34″"],["HA — Face Right","272°17′40″"],["HA — Mean","92°17′37″"],["ZA — Face Left","89°42′15″"],["ZA — Face Right","270°17′49″"],["ZA — Mean","89°42′13″"],["SD (mean of 3+)","187.342 m"],["HD (computed)","187.340 m"]]}'::jsonb, 32, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Today''s Lab Exercise</h2><p>You will set up the total station at a designated control point on campus, orient to a backsight, and measure angles and distances to at least <strong>four targets</strong>. You will measure each target in <strong>both Face Left and Face Right</strong>, compute the mean angles, and verify that the D&R discrepancies are within the instrument''s stated accuracy. Finally, you will close on the backsight to verify that the orientation was stable throughout.</p>"}'::jsonb, 33, now(), now()),
  (gen_random_uuid(), 'acc02b03-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Looking Ahead</h2><p>Next week you apply these total station skills to <strong>differential leveling</strong> — determining precise elevation differences between points using an automatic level and leveling rod. While the total station can compute elevations from zenith angles and distances, dedicated leveling instruments achieve much higher vertical accuracy for benchmark-to-benchmark work.</p>"}'::jsonb, 34, now(), now());

-- Mark lesson as migrated (original HTML preserved as fallback)
UPDATE learning_lessons SET content_migrated = TRUE WHERE id = 'acc02b03-0000-0000-0000-000000000001';
