-- supabase_seed_acc_content_1335_wk5.sql — Lesson: acc02b05-0000-0000-0000-000000000001
-- Converted from legacy HTML to structured lesson blocks
DELETE FROM lesson_blocks WHERE lesson_id = 'acc02b05-0000-0000-0000-000000000001';
INSERT INTO lesson_blocks (id, lesson_id, block_type, content, order_index, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Putting Angular Measurement into Practice</h2><p>Last week you learned the theory of angular measurement — angles to the right, deflection angles, interior angles, closing the horizon, and the repetition method. This week you take those methods into the field and execute them on a real multi-station figure. By the end of today, you will have measured a complete set of horizontal angles, computed angular closure, and evaluated whether your fieldwork meets accuracy standards.</p><p>This lab is the first exercise where you combine <strong>all</strong> of the skills from the previous weeks: instrument setup, orientation, angle turning, D&R measurement, field note recording, and quality control. The goal is not just to get numbers — it is to get <em>good</em> numbers and to <em>prove</em> that they are good by computing closure.</p>"}'::jsonb, 0, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Today''s Field Setup</h2><p>The instructor has established a <strong>multi-station figure</strong> on campus — typically a closed polygon with 4 to 6 stations marked by hubs and tacks or concrete monuments. You will occupy each station, measure the interior angle (or angle to the right) using the repetition method, and record everything in your field book.</p>"}'::jsonb, 1, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Crew Organization</h3><p>Each crew should have:</p><ul>\n<li><strong>Instrument operator:</strong> Sets up the total station, levels, centers, measures angles</li>\n<li><strong>Rod person(s):</strong> Holds the prism pole plumb over the backsight and foresight stations</li>\n<li><strong>Recorder:</strong> Records all readings in the field book, computes running checks</li>\n</ul><p>Rotate roles so every crew member gets time on the instrument. The recorder role is just as critical as the operator — a recording blunder wastes the operator''s careful measurement.</p>"}'::jsonb, 2, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Measurement Procedure at Each Station</h2><p>At every station in the figure, follow this procedure:</p>"}'::jsonb, 3, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Step 1: Set Up</h3><ol>\n<li>Place the tripod over the station mark, mount the tribrach and total station</li>\n<li>Rough-level with the circular bubble, center with the optical plummet</li>\n<li>Fine-level with the plate bubble and leveling screws</li>\n<li>Iterate centering and leveling until both are satisfied</li>\n<li>Measure and record HI</li>\n</ol>"}'::jsonb, 4, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Step 2: Orient and Measure — 2D + 2R Repetitions</h3><p>For this lab, you will measure each angle using <strong>2 Direct + 2 Reverse = 4 repetitions</strong>:</p><h4>Direct (Face Left) — 2 repetitions</h4><ol>\n<li>Sight the <strong>backsight</strong>. Set the circle to 0°00′00″. Record the initial reading.</li>\n<li>Turn clockwise to the <strong>foresight</strong>. Read and record the angle (e.g., 92°17′34″).</li>\n<li>Release the <strong>lower clamp</strong>, swing back to the backsight <em>without</em> changing the circle reading.</li>\n<li>Lock the lower clamp, fine-point on the backsight with the lower tangent screw.</li>\n<li>Release the <strong>upper clamp</strong>, turn to the foresight again. The circle now accumulates: approximately 2 × 92°17′34″ = 184°35′08″. Record this accumulated reading.</li>\n</ol><h4>Reverse (Face Right) — 2 repetitions</h4><ol>\n<li><strong>Plunge the telescope</strong> (transit to Face Right).</li>\n<li>Continue accumulating: return to backsight via lower clamp, turn to foresight via upper clamp. Two more repetitions.</li>\n<li>After 4 total repetitions, read the final accumulated value (e.g., 369°10′12″).</li>\n</ol><h4>Compute the Mean</h4><ol>\n<li>The circle has passed 360° once (since 4 × 92° ≈ 369°). True accumulated = 369°10′12″ (no need to add 360° since the accumulated ≈ 369° and expected ≈ 369°). Wait — 4 × 92°17′34″ = 369°10′16″. The display reads 369°10′12″, so the accumulated value is 369°10′12″.</li>\n<li>Mean angle = 369°10′12″ / 4 = 92°17′33″</li>\n</ol><p>Record the initial reading, intermediate readings (optional but recommended), final accumulated reading, number of repetitions, and computed mean.</p>"}'::jsonb, 5, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Step 3: Record and Move</h3><ol>\n<li>Record all data in the field book (see recording format below)</li>\n<li>Pack up the instrument and move to the next station</li>\n<li>The rod persons move their poles to the new backsight and foresight positions</li>\n</ol>"}'::jsonb, 6, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Angular Closure Computation</h2><p>After measuring angles at all stations, compute the angular closure <strong>in the field</strong> before leaving the site:</p>"}'::jsonb, 7, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h3>For Interior Angles</h3><p style=\"text-align:center; font-size:1.1em;\"><strong>Expected sum = (n − 2) × 180°</strong></p><p style=\"text-align:center;\"><strong>Angular misclosure = Measured sum − Expected sum</strong></p>"}'::jsonb, 8, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Allowable Misclosure</h3><p style=\"text-align:center;\"><strong>Allowable = K × √n</strong></p><p>where K depends on the accuracy standard and n is the number of angles.</p><p>For this lab exercise with a 5″ total station at third-order Class I (K = 5″):</p>"}'::jsonb, 9, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'table', '{"headers":["Stations (n)","Expected Sum","Allowable Misclosure"],"rows":[["4","360°","5″ × √4 = 10″"],["5","540°","5″ × √5 = 11.2″"],["6","720°","5″ × √6 = 12.2″"]]}'::jsonb, 10, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<p>If your misclosure exceeds the allowable value, you must <strong>re-measure</strong> before leaving the field. Start with the angle measured under the worst conditions (longest sightlines, most wind, poorest visibility).</p>"}'::jsonb, 11, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Field Note Format for This Lab</h2><p>Your field book should contain the following for each station:</p>"}'::jsonb, 12, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Left Page (Data)</h3>"}'::jsonb, 13, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'table', '{"headers":["Item","Example"],"rows":[["Station occupied","STA B"],["HI","1.523 m"],["Backsight","STA A"],["Foresight","STA C"],["Method","2D + 2R"],["Initial circle reading","0°00′00″"],["After 1st D rep","92°17′34″"],["After 2nd D rep","184°35′10″"],["After 1st R rep","276°52′42″"],["After 2nd R rep (final)","369°10′12″"],["Number of reps","4"],["Mean angle","92°17′33″"]]}'::jsonb, 14, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h3>Right Page (Sketch)</h3><p>Draw a plan-view sketch of the entire figure showing:</p><ul>\n<li>All station locations (labeled)</li>\n<li>Traverse lines connecting stations</li>\n<li>North arrow</li>\n<li>Approximate angle values at each station</li>\n<li>Reference features (buildings, roads, trees) for context</li>\n</ul>"}'::jsonb, 15, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Quality Control Checklist</h2><p>Before leaving <strong>each station</strong>, verify:</p><ul>\n<li>☐ D&R discrepancy is within instrument specification (the difference between Face Left and Face Right accumulated values, normalized, should be small)</li>\n<li>☐ All intermediate readings are recorded</li>\n<li>☐ Station ID, backsight, and foresight are correct</li>\n<li>☐ HI is recorded</li>\n</ul><p>Before leaving the <strong>field site</strong>:</p><ul>\n<li>☐ Angles at all stations are measured</li>\n<li>☐ Running sum of angles is computed</li>\n<li>☐ Angular misclosure is computed and within tolerance</li>\n<li>☐ If misclosure exceeds tolerance, suspect angle(s) have been re-measured</li>\n<li>☐ Sketch is complete</li>\n</ul>"}'::jsonb, 16, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Common Mistakes in This Lab</h2>"}'::jsonb, 17, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'table', '{"headers":["Mistake","Consequence","Prevention"],"rows":[["Forgetting to use the lower clamp when returning to backsight","Circle resets — accumulated value is lost","Practice the lower-clamp/upper-clamp sequence before starting"],["Not plunging the telescope between D and R sets","Systematic errors not cancelled","Physically verify the vertical circle reads >180° in Face Right"],["Moving the prism pole before all measurements from a station are complete","Inconsistent backsight/foresight positions","Communicate clearly with rod person; finish all reps before signaling \"move\""],["Recording the wrong accumulated reading","Mean angle is wrong","Have the recorder read back the value to the instrument operator"],["Not computing angular closure before leaving the field","Discovering a blown angle back at the office, requiring a return trip","Compute the running sum as you go; check closure at the last station"]]}'::jsonb, 18, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h2>After the Lab: Computation</h2><p>Back at the desk (or in the field if time permits), complete the following computations:</p><ol>\n<li><strong>Tabulate all mean angles</strong> from each station</li>\n<li><strong>Sum the angles</strong> and compute the misclosure against (n − 2) × 180°</li>\n<li><strong>Check the allowable misclosure</strong> for your accuracy standard</li>\n<li><strong>If within tolerance:</strong> distribute the misclosure equally to balance the angles (this prepares them for azimuth computation in a future lab)</li>\n<li><strong>Report:</strong> tabulated raw and balanced angles, misclosure, allowable, and pass/fail evaluation</li>\n</ol>"}'::jsonb, 19, now(), now()),
  (gen_random_uuid(), 'acc02b05-0000-0000-0000-000000000001', 'text', '{"html":"<h2>Looking Ahead</h2><p>Next week you combine angle measurement with distance measurement for a complete <strong>traverse</strong> — measuring both angles and distances at every station of a closed figure. This week''s angle skills feed directly into that exercise. The better your angle technique, the better your traverse will close.</p>"}'::jsonb, 20, now(), now());

-- Mark lesson as migrated (original HTML preserved as fallback)
UPDATE learning_lessons SET content_migrated = TRUE WHERE id = 'acc02b05-0000-0000-0000-000000000001';
