// __tests__/cad/labels/bearing-dim.test.ts — Unit tests for bearing/distance dimension
import { describe, it, expect } from 'vitest';
import {
  createBearingDimension,
  computeBearingDimPlacement,
  DEFAULT_BEARING_DIM_CONFIG,
} from '@/lib/cad/labels/bearing-dim';
import type { BearingDimConfig } from '@/lib/cad/labels/bearing-dim';

const cfg: BearingDimConfig = { ...DEFAULT_BEARING_DIM_CONFIG };

describe('createBearingDimension', () => {
  it('has type BEARING_DISTANCE', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    expect(dim.type).toBe('BEARING_DISTANCE');
  });

  it('has priority 1', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    expect(dim.priority).toBe(1);
  });

  it('computes correct distance for a due-East line of 100 ft', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    expect(dim.distance).toBeCloseTo(100, 3);
  });

  it('distanceText shows correct value with 2 decimal places', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    expect(dim.distanceText).toBe("100.00'");
  });

  it('bearingText contains "90" and "E" for a due-East line (azimuth=90)', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    // Due East = azimuth 90 = quadrant S90°E or N90°E depending on convention
    expect(dim.bearingText).toMatch(/90/);
    expect(dim.bearingText).toMatch(/E/);
  });

  it('bearing azimuth is 0 for a due-North line', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 0, y: 100 }, cfg);
    expect(dim.bearing).toBeCloseTo(0, 3);
  });

  it('links to provided featureId and segmentIndex', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 50, y: 50 }, cfg, 'feat-1', 3);
    expect(dim.linkedFeatureId).toBe('feat-1');
    expect(dim.linkedSegmentIndex).toBe(3);
  });

  it('isAutoGenerated is true; isManuallyPlaced is false', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    expect(dim.isAutoGenerated).toBe(true);
    expect(dim.isManuallyPlaced).toBe(false);
  });

  it('layerId defaults to ANNOTATION', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    expect(dim.layerId).toBe('ANNOTATION');
  });

  it('extensionLineLength is 0.05 (paper inches)', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    expect(dim.extensionLineLength).toBeCloseTo(0.05, 5);
  });

  it('uses custom distancePrecision', () => {
    const custom: BearingDimConfig = { ...cfg, distancePrecision: 4 };
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, custom);
    expect(dim.distanceText).toBe("100.0000'");
  });
});

describe('computeBearingDimPlacement', () => {
  it('returns finite bearingPos and distancePos', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    const placement = computeBearingDimPlacement(dim, 50);
    expect(isFinite(placement.bearingPos.x)).toBe(true);
    expect(isFinite(placement.bearingPos.y)).toBe(true);
    expect(isFinite(placement.distancePos.x)).toBe(true);
    expect(isFinite(placement.distancePos.y)).toBe(true);
  });

  it('rotation is 0 for a horizontal line (angle=0°)', () => {
    const dim = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, cfg);
    const placement = computeBearingDimPlacement(dim, 50);
    // atan2(0,100) = 0, which is not > π/2, so stays 0
    expect(placement.rotation).toBeCloseTo(0, 5);
  });

  it('rotation stays readable — result is a finite number', () => {
    // A westward line: atan2(0,-100) = π. The function should add π to get 2π (or 0).
    // The key property is that the result is finite and wraps correctly.
    const dim = createBearingDimension({ x: 100, y: 0 }, { x: 0, y: 0 }, cfg);
    const placement = computeBearingDimPlacement(dim, 50);
    expect(isFinite(placement.rotation)).toBe(true);
  });

  it('bearing position is above midpoint when bearingAbove=true', () => {
    const dimAbove = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, { ...cfg, bearingAbove: true });
    const placementAbove = computeBearingDimPlacement(dimAbove, 50);
    // For a horizontal line going right, perpendicular is "up" (positive y)
    // So bearingPos.y > distancePos.y when bearingAbove=true
    expect(placementAbove.bearingPos.y).toBeGreaterThan(placementAbove.distancePos.y);
  });

  it('positions swap when bearingAbove=false', () => {
    const dimBelow = createBearingDimension({ x: 0, y: 0 }, { x: 100, y: 0 }, { ...cfg, bearingAbove: false });
    const placement = computeBearingDimPlacement(dimBelow, 50);
    expect(placement.bearingPos.y).toBeLessThan(placement.distancePos.y);
  });
});
