// __tests__/cad/labels/create-area-label-for-feature.test.ts
//
// Slice 229 of cad-area-calculation-multi-unit-2026-05-29.md. Locks
// the feature-aware AreaAnnotation factory + the centroid picker so
// every closed shape can drop a moveable area label. Also locks the
// source-level wiring of the PropertyPanel "📐 Place area label"
// button + the canvas render path that draws stored AREA_LABEL
// annotations.

import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import {
  createAreaLabelForFeature,
  pickFeatureCentroid,
  DEFAULT_AREA_LABEL_CONFIG,
} from '@/lib/cad/labels/area-label';
import type { Feature } from '@/lib/cad/types';

function feat<T extends Feature['geometry']>(geom: T): Feature {
  return {
    id: 'F1',
    type: geom.type,
    geometry: geom as Feature['geometry'],
    layerId: 'L',
    style: { color: '#000', lineWeight: 1, opacity: 1 } as Feature['style'],
    properties: {},
  };
}

describe('pickFeatureCentroid — picks the natural centroid for any closed geometry', () => {
  it('returns the CIRCLE center', () => {
    const c = pickFeatureCentroid(feat({
      type: 'CIRCLE', circle: { center: { x: 12, y: 34 }, radius: 5 },
    }));
    expect(c).toEqual({ x: 12, y: 34 });
  });

  it('returns the ELLIPSE center', () => {
    const c = pickFeatureCentroid(feat({
      type: 'ELLIPSE',
      ellipse: { center: { x: 7, y: 8 }, radiusX: 4, radiusY: 2, rotation: 0 },
    }));
    expect(c).toEqual({ x: 7, y: 8 });
  });

  it('returns the vertex average for POLYGON', () => {
    const c = pickFeatureCentroid(feat({
      type: 'POLYGON',
      vertices: [
        { x: 0, y: 0 }, { x: 4, y: 0 },
        { x: 4, y: 4 }, { x: 0, y: 4 },
      ],
    }));
    expect(c.x).toBeCloseTo(2, 6);
    expect(c.y).toBeCloseTo(2, 6);
  });

  it('returns the vertex average for POLYLINE (closed or open)', () => {
    const c = pickFeatureCentroid(feat({
      type: 'POLYLINE',
      vertices: [{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 10, y: 5 }, { x: 0, y: 5 }],
    }));
    expect(c.x).toBe(5);
    expect(c.y).toBeCloseTo(2.5, 6);
  });

  it('returns {0,0} for LINE / POINT and other open / centroid-less geometries', () => {
    expect(pickFeatureCentroid(feat({
      type: 'LINE',
      start: { x: 0, y: 0 }, end: { x: 10, y: 10 },
    }))).toEqual({ x: 0, y: 0 });
    expect(pickFeatureCentroid(feat({
      type: 'POINT', point: { x: 5, y: 5 },
    }))).toEqual({ x: 0, y: 0 });
  });
});

describe('createAreaLabelForFeature — closed shapes produce a valid AreaAnnotation', () => {
  it('returns null for an open shape (LINE)', () => {
    expect(
      createAreaLabelForFeature(feat({
        type: 'LINE',
        start: { x: 0, y: 0 }, end: { x: 10, y: 10 },
      })),
    ).toBeNull();
  });

  it('returns null for a degenerate CIRCLE (radius 0)', () => {
    expect(
      createAreaLabelForFeature(feat({
        type: 'CIRCLE', circle: { center: { x: 0, y: 0 }, radius: 0 },
      })),
    ).toBeNull();
  });

  it('POLYGON: area, position, and isManuallyPlaced flag set correctly', () => {
    const ann = createAreaLabelForFeature(feat({
      type: 'POLYGON',
      vertices: [
        { x: 0, y: 0 }, { x: 100, y: 0 },
        { x: 100, y: 100 }, { x: 0, y: 100 },
      ],
    }));
    expect(ann).not.toBeNull();
    expect(ann!.type).toBe('AREA_LABEL');
    expect(ann!.linkedFeatureId).toBe('F1');
    expect(ann!.areaSqFt).toBe(10_000);
    expect(ann!.areaAcres).toBeCloseTo(10_000 / 43560, 6);
    expect(ann!.position.x).toBeCloseTo(50, 6);
    expect(ann!.position.y).toBeCloseTo(50, 6);
    // Slice 229 — user clicked the button so the label is manually
    // placed and is NOT auto-regenerated by the auto-annotate pipe.
    expect(ann!.isManuallyPlaced).toBe(true);
    expect(ann!.isAutoGenerated).toBe(false);
    expect(ann!.visible).toBe(true);
  });

  it('CIRCLE: area = π·r² + position at the circle center', () => {
    const ann = createAreaLabelForFeature(feat({
      type: 'CIRCLE', circle: { center: { x: 3, y: 4 }, radius: 10 },
    }));
    expect(ann).not.toBeNull();
    expect(ann!.areaSqFt).toBeCloseTo(Math.PI * 100, 6);
    expect(ann!.position).toEqual({ x: 3, y: 4 });
  });

  it('ELLIPSE: area = π·a·b + position at the ellipse center', () => {
    const ann = createAreaLabelForFeature(feat({
      type: 'ELLIPSE',
      ellipse: { center: { x: 1, y: 2 }, radiusX: 8, radiusY: 5, rotation: 0 },
    }));
    expect(ann).not.toBeNull();
    expect(ann!.areaSqFt).toBeCloseTo(Math.PI * 40, 6);
    expect(ann!.position).toEqual({ x: 1, y: 2 });
  });

  it('closed POLYLINE: returns a label using the shoelace area', () => {
    const closed = [
      { x: 0, y: 0 }, { x: 10, y: 0 },
      { x: 10, y: 10 }, { x: 0, y: 10 },
      { x: 0, y: 0 },
    ];
    const ann = createAreaLabelForFeature(feat({ type: 'POLYLINE', vertices: closed }));
    expect(ann).not.toBeNull();
    expect(ann!.areaSqFt).toBe(100);
  });

  it('honors the supplied config (font / fontSize / color / format)', () => {
    const ann = createAreaLabelForFeature(
      feat({ type: 'CIRCLE', circle: { center: { x: 0, y: 0 }, radius: 5 } }),
      { format: 'ACRES', font: 'Helvetica', fontSize: 12, color: '#ff0000' },
    );
    expect(ann!.font).toBe('Helvetica');
    expect(ann!.fontSize).toBe(12);
    expect(ann!.color).toBe('#ff0000');
    expect(ann!.format).toBe('ACRES');
  });

  it('uses DEFAULT_AREA_LABEL_CONFIG when no config is supplied', () => {
    const ann = createAreaLabelForFeature(feat({
      type: 'CIRCLE', circle: { center: { x: 0, y: 0 }, radius: 5 },
    }));
    expect(ann!.font).toBe(DEFAULT_AREA_LABEL_CONFIG.font);
    expect(ann!.fontSize).toBe(DEFAULT_AREA_LABEL_CONFIG.fontSize);
    expect(ann!.color).toBe(DEFAULT_AREA_LABEL_CONFIG.color);
  });
});

describe('Slice 229 — PropertyPanel wiring', () => {
  const SRC = fs.readFileSync(
    path.join(__dirname, '..', '..', '..', 'app', 'admin', 'cad', 'components', 'PropertyPanel.tsx'),
    'utf8',
  );

  it('imports createAreaLabelForFeature + the annotation store', () => {
    expect(SRC).toContain("import { createAreaLabelForFeature } from '@/lib/cad/labels/area-label';");
    expect(SRC).toContain("import { useAnnotationStore } from '@/lib/cad/store/annotation-store';");
  });

  it('renders the Place area label button (gated by the same area > 0 guard as the readout)', () => {
    expect(SRC).toContain('data-testid="property-panel-place-area-label"');
    expect(SRC).toContain('📐 Place area label on canvas');
  });

  it('the button click calls createAreaLabelForFeature(feature) + addAnnotation when non-null', () => {
    expect(SRC).toMatch(/const ann = createAreaLabelForFeature\(feature\);/);
    expect(SRC).toMatch(/if \(ann\) useAnnotationStore\.getState\(\)\.addAnnotation\(ann\);/);
  });
});

describe('Slice 229 — CanvasViewport render path', () => {
  const SRC = fs.readFileSync(
    path.join(__dirname, '..', '..', '..', 'app', 'admin', 'cad', 'components', 'CanvasViewport.tsx'),
    'utf8',
  );

  it('imports the annotation store', () => {
    expect(SRC).toMatch(/useAnnotationStore,/);
  });

  it('adds an areaLabelTexts Map onto the Pixi state', () => {
    expect(SRC).toMatch(/areaLabelTexts: Map<string, import\('pixi\.js'\)\.Text>/);
    expect(SRC).toMatch(/areaLabelTexts: new Map\(\)/);
  });

  it('defines renderAreaAnnotations + invokes it from the per-frame pipeline', () => {
    expect(SRC).toMatch(/function renderAreaAnnotations\(\) \{/);
    // Sandwiched between renderLabels and renderTextFeatures so it
    // sits on the labelLayer with the other labels.
    expect(SRC).toMatch(/renderLabels\(\);\s*\n\s*\/\/ Slice 229[\s\S]*?renderAreaAnnotations\(\);\s*\n\s*renderTextFeatures\(\);/);
  });

  it('renderAreaAnnotations GCs Pixi text objects whose annotations were removed', () => {
    // Locks the alive-id sweep so a future refactor can't drop the
    // cleanup and start leaking Pixi Text objects.
    expect(SRC).toMatch(/if \(!aliveIds\.has\(id\)\) \{/);
    expect(SRC).toMatch(/pixi\.areaLabelTexts\.delete\(id\);/);
  });

  it('renderAreaAnnotations only draws annotations whose type === AREA_LABEL + visible !== false', () => {
    expect(SRC).toMatch(/if \(!ann \|\| ann\.type !== 'AREA_LABEL'\) continue;/);
    expect(SRC).toMatch(/if \(ann\.visible === false\) continue;/);
  });
});
