// __tests__/cad/labels/label-optimizer.test.ts — Unit tests for label optimizer
import { describe, it, expect } from 'vitest';
import { optimizeLabels, DEFAULT_LABEL_OPT_CONFIG } from '@/lib/cad/labels/label-optimizer';
import type { LabelOptConfig } from '@/lib/cad/labels/label-optimizer';
import type { AnnotationBase, BearingDistanceDimension } from '@/lib/cad/labels/annotation-types';

// ── Helpers ──────────────────────────────────────────────────────────────────

let _idCount = 0;
function nextId() { return `ann-${++_idCount}`; }

function mkBDAnnotation(
  id: string,
  x1: number, y1: number,
  x2: number, y2: number,
  manuallyPlaced = false,
): BearingDistanceDimension {
  return {
    id,
    type: 'BEARING_DISTANCE',
    layerId: 'ANNOTATION',
    visible: true,
    locked: false,
    linkedFeatureId: null,
    linkedSegmentIndex: null,
    isManuallyPlaced: manuallyPlaced,
    isAutoGenerated: !manuallyPlaced,
    priority: 1,
    startPoint: { x: x1, y: y1 },
    endPoint: { x: x2, y: y2 },
    bearing: 90,
    distance: Math.hypot(x2 - x1, y2 - y1),
    bearingText: "N 90°00'00\" E",
    distanceText: "100.00'",
    textPosition: 'ABOVE',
    textOffset: 0.06,
    textRotation: 'ALONG_LINE',
    bearingAbove: true,
    font: 'Arial',
    fontSize: 7,
    color: '#000000',
    extensionLines: true,
    extensionLineLength: 0.05,
  };
}

function mkTextAnnotation(id: string, x: number, y: number): AnnotationBase {
  return {
    id,
    type: 'TEXT',
    layerId: 'ANNOTATION',
    visible: true,
    locked: false,
    linkedFeatureId: null,
    linkedSegmentIndex: null,
    isManuallyPlaced: false,
    isAutoGenerated: true,
    priority: 6,
  } as AnnotationBase;
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe('optimizeLabels — basic contract', () => {
  const quickCfg: LabelOptConfig = { ...DEFAULT_LABEL_OPT_CONFIG, maxIterations: 10 };

  it('returns a placement for every annotation', () => {
    const annotations = [
      mkBDAnnotation('a1', 0, 0, 100, 0),
      mkBDAnnotation('a2', 0, 50, 100, 50),
    ];
    const result = optimizeLabels(annotations, 50, quickCfg);
    for (const a of annotations) {
      expect(result.placements.has(a.id)).toBe(true);
    }
  });

  it('placements map size matches annotation count', () => {
    const n = 5;
    const annotations = Array.from({ length: n }, (_, i) =>
      mkBDAnnotation(`a${i}`, i * 200, 0, i * 200 + 100, 0),
    );
    const result = optimizeLabels(annotations, 50, quickCfg);
    expect(result.placements.size).toBe(n);
  });

  it('returns 0 collisions for annotations that are far apart', () => {
    // Place annotations 500 units apart — should not collide
    const annotations = [
      mkBDAnnotation('far1', 0, 0, 100, 0),
      mkBDAnnotation('far2', 5000, 0, 5100, 0),
    ];
    const result = optimizeLabels(annotations, 50, quickCfg);
    expect(result.collisionsRemaining).toBe(0);
  });

  it('each placement has a valid strategy string', () => {
    const validStrategies = ['ORIGINAL', 'FLIPPED', 'SLID', 'LEADER_ADDED', 'SHRUNK', 'STACKED', 'ABBREVIATED', 'FLAGGED_MANUAL'];
    const annotations = [mkBDAnnotation('a1', 0, 0, 100, 0)];
    const result = optimizeLabels(annotations, 50, quickCfg);
    const p = result.placements.get('a1')!;
    expect(validStrategies).toContain(p.strategy);
  });

  it('manually placed annotations keep ORIGINAL strategy', () => {
    const manual = mkBDAnnotation('m1', 0, 0, 100, 0, true);
    const nearby  = mkBDAnnotation('a2', 0, 0, 100, 0, false);
    const result = optimizeLabels([manual, nearby], 50, quickCfg);
    expect(result.placements.get('m1')!.strategy).toBe('ORIGINAL');
  });

  it('flaggedForManual is an array', () => {
    const annotations = [mkBDAnnotation('a1', 0, 0, 100, 0)];
    const result = optimizeLabels(annotations, 50, quickCfg);
    expect(Array.isArray(result.flaggedForManual)).toBe(true);
  });

  it('each placement has offsetX and offsetY as numbers', () => {
    const annotations = [mkBDAnnotation('a1', 0, 0, 100, 0)];
    const result = optimizeLabels(annotations, 50, quickCfg);
    const p = result.placements.get('a1')!;
    expect(typeof p.offsetX).toBe('number');
    expect(typeof p.offsetY).toBe('number');
    expect(isFinite(p.offsetX)).toBe(true);
    expect(isFinite(p.offsetY)).toBe(true);
  });

  it('empty annotations returns 0 collisions', () => {
    const result = optimizeLabels([], 50, quickCfg);
    expect(result.collisionsRemaining).toBe(0);
    expect(result.placements.size).toBe(0);
    expect(result.flaggedForManual).toHaveLength(0);
  });

  it('collisionsResolved is non-negative', () => {
    const annotations = [
      mkBDAnnotation('a1', 0, 0, 100, 0),
      mkBDAnnotation('a2', 0, 0, 100, 0),
    ];
    const result = optimizeLabels(annotations, 50, quickCfg);
    expect(result.collisionsResolved).toBeGreaterThanOrEqual(0);
  });
});

describe('optimizeLabels — collision resolution', () => {
  it('resolves at least some overlapping labels after 500 iterations', () => {
    const cfg: LabelOptConfig = { ...DEFAULT_LABEL_OPT_CONFIG, maxIterations: 500 };
    // Two identical annotations at the same position — guaranteed collision
    const annotations = [
      mkBDAnnotation('a1', 0, 0, 100, 0),
      mkBDAnnotation('a2', 0, 0, 100, 0), // exactly same position
    ];
    const result = optimizeLabels(annotations, 50, cfg);
    // After 500 iterations we expect at least 1 resolved
    expect(result.collisionsResolved).toBeGreaterThanOrEqual(1);
  });
});
