// __tests__/schema-coverage.test.ts — every table the code queries must have a schema in the repo.
//
// WHY THIS EXISTS. On 2026-07-29 an audit found 78 tables that the app queried every day with no
// CREATE statement anywhere in `seeds/` — including `jobs`, the central business entity, which was
// only ever ALTERed (seeds 280/304/306/452). The practical effect: there was exactly one database
// (production), no staging could be built, a fresh clone could not stand the app up, and every
// schema change to those tables was an undocumented click in the Supabase dashboard.
//
// `seeds/500_baseline_reconstruct.sql` closed that gap (generated by
// scripts/dump-missing-schema.mjs, verified column-for-column against production by
// scripts/verify-baseline-schema.mjs). This test keeps it closed: query a table, define a table.
//
// It also catches the inverse bug the same audit surfaced — code querying a table that does not
// exist ANYWHERE, not in seeds and not in production. Three research routes did exactly that, and
// because they destructure `{ data }` and drop `error`, the features silently returned nothing
// instead of failing loudly. Those are listed in KNOWN_PHANTOM_TABLES below so this test documents
// them rather than pretending they're fine.
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const CODE_DIRS = ['app', 'lib', 'worker', 'server'];

/** Tables referenced in code that exist in neither seeds/ nor production. These are BUGS — the
 *  callers silently swallow the error and degrade to an empty result. Listed here so the guard
 *  stays green while the reality stays visible. Delete an entry when the table is created or the
 *  dead call site is removed; do NOT add to this list to make a failure go away. */
const KNOWN_PHANTOM_TABLES = new Set([
  // app/api/admin/research/[projectId]/full-extract/route.ts:104 — artifacts always load as []
  'research_artifacts',
  // deep-lot-analysis/route.ts:463 + verify-lot/route.ts:380 — Phase 4 cross-validation never runs
  'research_extracted_data_points',
]);

/** `.from('x')` inside a test fixture is a Buffer, not a table. Two-char names aren't tables. */
const isPlausibleTableName = (t: string) => t.length >= 3 && !/^(x|hello|test)$/.test(t);

function walk(dir: string, acc: string[] = []): string[] {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (['node_modules', '.next', '.git', '__tests__'].includes(e.name)) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, acc);
    else if (/\.(ts|tsx)$/.test(e.name) && !/\.test\.tsx?$/.test(e.name)) acc.push(p);
  }
  return acc;
}

/** Every distinct table name passed to a supabase `.from('…')` call in application code. */
export function tablesQueriedInCode(): Map<string, string[]> {
  const files = CODE_DIRS.filter((d) => fs.existsSync(path.join(ROOT, d))).flatMap((d) =>
    walk(path.join(ROOT, d)),
  );
  const found = new Map<string, string[]>();
  for (const file of files) {
    const src = fs.readFileSync(file, 'utf8');
    for (const m of src.matchAll(/\.from\(\s*['"`]([a-z_0-9]+)['"`]\s*\)/g)) {
      const table = m[1];
      if (!isPlausibleTableName(table)) continue;
      const rel = path.relative(ROOT, file).replace(/\\/g, '/');
      if (!found.has(table)) found.set(table, []);
      const sites = found.get(table)!;
      if (!sites.includes(rel)) sites.push(rel);
    }
  }
  return found;
}

/** Every table/view given a CREATE statement anywhere in seeds/. */
export function tablesDefinedInSeeds(): Set<string> {
  const dir = path.join(ROOT, 'seeds');
  const defined = new Set<string>();
  const re =
    /CREATE\s+(?:TABLE|(?:MATERIALIZED\s+)?VIEW|OR\s+REPLACE\s+VIEW)\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:public\.)?"?([a-z_0-9]+)"?/gi;
  for (const f of fs.readdirSync(dir).filter((x) => x.endsWith('.sql'))) {
    const src = fs.readFileSync(path.join(dir, f), 'utf8');
    for (const m of src.matchAll(re)) defined.add(m[1].toLowerCase());
  }
  return defined;
}

describe('the scanner itself', () => {
  it('finds a .from() call and ignores short Buffer-ish fixtures', () => {
    const defined = tablesDefinedInSeeds();
    // The reconstruction file must be present and must carry the central entity.
    expect(defined.has('jobs'), 'seeds/ no longer defines `jobs` — did 500_baseline_reconstruct.sql get deleted?')
      .toBe(true);
  });

  it('the seeds directory defines a substantial schema (a broken regex would silently pass)', () => {
    expect(tablesDefinedInSeeds().size).toBeGreaterThan(150);
  });

  it('the code scanner finds a substantial number of tables', () => {
    expect(tablesQueriedInCode().size).toBeGreaterThan(150);
  });
});

describe('SCHEMA COVERAGE', () => {
  it('every table the code queries has a CREATE statement in seeds/', () => {
    const queried = tablesQueriedInCode();
    const defined = tablesDefinedInSeeds();

    const undefinedTables = [...queried.keys()]
      .filter((t) => !defined.has(t))
      .filter((t) => !KNOWN_PHANTOM_TABLES.has(t))
      .sort();

    const detail = undefinedTables
      .map((t) => `  ${t}\n      queried in: ${queried.get(t)!.slice(0, 3).join(', ')}`)
      .join('\n');

    expect(
      undefinedTables,
      undefinedTables.length
        ? `These tables are queried by application code but have no CREATE statement in seeds/.\n` +
            `A table that exists only in the live database means: no staging environment, no\n` +
            `reproducible build, and no schema history. Add it to seeds/ (see\n` +
            `scripts/dump-missing-schema.mjs) rather than creating it in the dashboard.\n\n${detail}\n`
        : '',
    ).toEqual([]);
  });

  it('the phantom-table list has not grown', () => {
    // Pinning the size stops a future failure being "fixed" by appending to the allowlist.
    expect(
      KNOWN_PHANTOM_TABLES.size,
      'KNOWN_PHANTOM_TABLES is an inventory of bugs, not an escape hatch. Fix the table or the ' +
        'call site instead of adding to it.',
    ).toBeLessThanOrEqual(2);
  });

  it('every phantom table is still genuinely referenced (delete stale entries)', () => {
    const queried = tablesQueriedInCode();
    const stale = [...KNOWN_PHANTOM_TABLES].filter((t) => !queried.has(t));
    expect(
      stale,
      `These are listed as known-phantom but nothing queries them any more — remove them from ` +
        `KNOWN_PHANTOM_TABLES: ${stale.join(', ')}`,
    ).toEqual([]);
  });
});
