// app/admin/equipment/maintenance/[id]/maintenance-styles.ts — the detail page's inline styles.
//
// Split out for platform audit item 18: the read view and the four write dialogs both use it, so it
// could not stay in either. Moved verbatim.

import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  wrap: { padding: '24px', maxWidth: 960, margin: '0 auto' },
  backLink: {
    display: 'inline-block',
    marginBottom: 12,
    fontSize: 13,
    color: 'var(--color-brand-navy)',
    textDecoration: 'none',
    fontWeight: 500,
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 24,
    paddingBottom: 16,
    borderBottom: '1px solid #E2E5EB',
  },
  h1: { fontSize: 24, fontWeight: 600, margin: '0 0 8px' },
  h2: {
    fontSize: 14,
    fontWeight: 600,
    margin: '0 0 12px',
    color: '#374151',
    display: 'flex',
    alignItems: 'baseline',
    gap: 6,
  },
  h2Hint: { fontSize: 11, color: 'var(--color-text-muted)', fontWeight: 400 },
  headerBadges: { display: 'flex', gap: 8, marginBottom: 8, flexWrap: 'wrap' as const },
  qaFailedBadge: {
    padding: '4px 10px',
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 600,
    background: '#FEE2E2',
    color: '#7F1D1D',
  },
  qaPassedBadge: {
    padding: '4px 10px',
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 600,
    background: '#DCFCE7',
    color: '#166534',
  },
  summaryLine: {
    fontSize: 14,
    color: '#374151',
    margin: 0,
    fontStyle: 'italic' as const,
  },
  editStub: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  editBtn: {
    padding: '8px 14px',
    border: '1px solid var(--color-brand-navy)',
    background: 'var(--color-bg-card)',
    color: 'var(--color-brand-navy)',
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
  },
  disabledBtn: {
    padding: '6px 12px',
    border: '1px dashed #E2E5EB',
    background: '#FAFBFC',
    color: 'var(--color-text-muted)',
    borderRadius: 6,
    fontSize: 12,
    cursor: 'not-allowed',
  },
  section: {
    marginBottom: 24,
    background: 'var(--color-bg-card)',
    border: '1px solid #E2E5EB',
    borderRadius: 12,
    padding: 16,
  },
  docsHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  detailRow: {
    display: 'grid',
    gridTemplateColumns: '160px 1fr',
    gap: 12,
    padding: '6px 0',
    fontSize: 13,
    alignItems: 'baseline',
  },
  rowLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--color-text-tertiary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  rowValue: { color: '#111827', wordBreak: 'break-word' as const },
  link: { color: 'var(--color-brand-navy)', textDecoration: 'none', fontWeight: 500 },
  linkedReceiptRow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
  },
  linkBtn: {
    background: 'transparent',
    border: '1px solid var(--color-brand-navy)',
    color: 'var(--color-brand-navy)',
    padding: '4px 10px',
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 500,
    cursor: 'pointer',
  },
  muted: { color: 'var(--color-text-muted)' },
  notes: {
    fontSize: 13,
    color: '#374151',
    whiteSpace: 'pre-wrap' as const,
    background: '#FAFBFC',
    padding: 12,
    borderRadius: 6,
    border: '1px solid #F1F2F4',
  },
  code: {
    fontFamily: 'Menlo, monospace',
    fontSize: 11,
    background: 'var(--color-bg-subtle)',
    padding: '1px 6px',
    borderRadius: 4,
  },
  table: { width: '100%', borderCollapse: 'collapse' as const, fontSize: 13 },
  th: {
    textAlign: 'left' as const,
    padding: '8px 10px',
    background: 'var(--color-bg-app)',
    borderBottom: '1px solid #E2E5EB',
    fontSize: 11,
    color: 'var(--color-text-tertiary)',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  thRight: {
    textAlign: 'right' as const,
    padding: '8px 10px',
    background: 'var(--color-bg-app)',
    borderBottom: '1px solid #E2E5EB',
    fontSize: 11,
    color: 'var(--color-text-tertiary)',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  td: { padding: '8px 10px', borderBottom: '1px solid #F1F2F4' },
  tdRight: {
    padding: '8px 10px',
    borderBottom: '1px solid #F1F2F4',
    textAlign: 'right' as const,
  },
  tdMuted: {
    padding: '8px 10px',
    borderBottom: '1px solid #F1F2F4',
    fontSize: 12,
    color: 'var(--color-text-tertiary)',
  },
  empty: {
    padding: 32,
    textAlign: 'center' as const,
    color: 'var(--color-text-tertiary)',
    fontSize: 13,
    background: 'var(--color-bg-card)',
    border: '1px solid #E2E5EB',
    borderRadius: 12,
    margin: 24,
  },
  actionMsg: {
    marginTop: 12,
    padding: '10px 14px',
    background: '#DCFCE7',
    border: '1px solid #86EFAC',
    color: '#166534',
    borderRadius: 8,
    fontSize: 13,
  },
};
